import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { extract } from "./human-counts.mjs";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET,OPTIONS","Cache-Control":"no-store, max-age=0","Content-Type":"application/json"};
const EVENT=/(bhotekoshi|bhote\s*koshi|rasuwa|trishuli|भोटेकोशी|भोटेकोसी|रसुवा|त्रिशूली|त्रिशुली)/i;
const CORR=/(correction|corrected|revised|revision|सच्याइएको|संशोधित)/i;
const AUTHORITY=/(NDRRMA|National Disaster Risk Reduction|राष्ट्रिय विपद् जोखिम न्यूनीकरण|नेपाल प्रहरी|सशस्त्र प्रहरी|प्राधिकरण)/i;
function strip(s:string){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/,/g,'').replace(/\s+/g,' ').trim()}
function isoFromHtml(h:string){for(const re of [/article:published_time[^>]+content=["']([^"']+)/i,/datePublished["']?\s*[:=]\s*["']([^"']+)/i,/<time[^>]+datetime=["']([^"']+)/i]){const m=h.match(re);if(m){const d=new Date(m[1]);if(Number.isFinite(+d))return d.toISOString()}}return null}
function onlineKhabarTime(h:string){const t=strip(h).replace(/[०-९]/g,d=>'०१२३४५६७८९'.indexOf(d)),m=t.match(/2083\s+भदौ\s+(\d{1,2})\s+गते\s+(\d{1,2}):(\d{2})/);if(!m)return null;const day=Number(m[1]),hour=Number(m[2]),minute=Number(m[3]),d=new Date(Date.UTC(2026,7,16+day,hour-5,minute-45));return day>=1&&day<=32&&hour<24&&minute<60?d.toISOString():null}
function relevant(title:string,text:string){return EVENT.test(title)&&/(flood|बाढी)/i.test(title+' '+text)}
async function fetchText(url:string,ms=9000){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 (compatible; FloodSafeNepal/3.1)","Cache-Control":"no-cache"},signal:c.signal,redirect:'follow'});if(!r.ok)throw new Error(String(r.status));return await r.text()}finally{clearTimeout(to)}}
type Cand={value:number,time:string,source:string,url:string,correction:boolean,minimum?:boolean};
function choose(old:Cand|undefined,c:Cand,kind:string){if(!old)return c;const ot=+new Date(old.time),ct=+new Date(c.time);if(c.value<old.value&&!c.correction){if(kind!=='missing')return old;if(c.value<old.value*.65)return old;}return ct>ot?c:old}
async function inspect(best:Record<string,Cand>,url:string,source:string,requireAuthority=false){try{const h=await fetchText(url),title=strip((h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||''),text=strip((h.match(/<article[^>]*>([\s\S]*?)<\/article>/i)||h.match(/<main[^>]*>([\s\S]*?)<\/main>/i)||['',h])[1]),joined=title+' '+text;if(!relevant(title,text)||requireAuthority&&!AUTHORITY.test(joined))return;const time=isoFromHtml(h)||onlineKhabarTime(h);if(!time)return;const correction=CORR.test(joined);for(const kind of ['death','missing','rescued'] as const){const v=extract(joined,kind);if(v!==null)best[kind]=choose(best[kind],{value:v,time,source,url,correction,minimum:kind==='missing'&&/(more than|over|भन्दा बढी)/i.test(joined)},kind)}}catch(e){console.log('inspect failed',source,url,String(e))}}
async function radioLinks(){try{const h=await fetchText('https://radionepalonline.com/en/'),out:string[]=[];for(const m of h.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){try{const u=new URL(m[1],'https://radionepalonline.com/en/'),title=strip(m[2]);if(!u.hostname.endsWith('radionepalonline.com')||!EVENT.test(title))continue;if(!out.includes(u.href))out.push(u.href)}catch{}if(out.length>=18)break}return out}catch{return[]}}
async function onlineKhabarLinks(){const out=['https://www.onlinekhabar.com/2026/09/2009006/rasuwa-flood-death-toll-reaches-1114'];try{const h=await fetchText('https://www.onlinekhabar.com/trend/bhotekoshi-flood');for(const m of h.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){try{const u=new URL(m[1],'https://www.onlinekhabar.com/'),title=strip(m[2]);if(u.hostname!=='www.onlinekhabar.com'||!EVENT.test(title)||!/\/20\d\d\//.test(u.pathname))continue;if(!out.includes(u.href))out.push(u.href)}catch{}if(out.length>=18)break}}catch(e){console.log('OnlineKhabar listing failed',String(e))}return out}
async function refresh(current:any){const best:Record<string,Cand>={};const seed=(kind:string,value:any,source:any,url:any,time:any)=>{if(value!==null&&value!==undefined&&Number.isFinite(Number(value))&&time)best[kind]={value:Number(value),source:String(source||''),url:String(url||''),time:new Date(time).toISOString(),correction:false,minimum:kind==='missing'&&Boolean(current?.raw?.missing_is_minimum)}};seed('death',current?.deaths,current?.deaths_source,current?.deaths_url,current?.deaths_observed_at);seed('missing',current?.missing,current?.missing_source,current?.missing_url,current?.missing_observed_at);seed('rescued',current?.rescued,current?.rescued_source,current?.rescued_url,current?.rescued_observed_at);
 await inspect(best,'https://radionepalonline.com/en/2026/08/31/435175.html','Radio Nepal / NDRRMA');
 const links=await radioLinks();for(let i=0;i<Math.min(links.length,12);i+=4)await Promise.all(links.slice(i,i+4).map(u=>inspect(best,u,'Radio Nepal / NDRRMA')));
 const okLinks=await onlineKhabarLinks();for(let i=0;i<Math.min(okLinks.length,15);i+=3)await Promise.all(okLinks.slice(i,i+3).map(u=>inspect(best,u,'NDRRMA via OnlineKhabar',true)));
 try{const r=await fetch('https://www.ronbpost.com/wp-json/wp/v2/posts?per_page=40&_fields=date_gmt,modified_gmt,link,title,excerpt,content',{headers:{'User-Agent':'FloodSafeNepal/3.1'},signal:AbortSignal.timeout(9000)});if(r.ok){const j=await r.json();if(Array.isArray(j))for(const p of j){const title=strip(p?.title?.rendered||''),body=strip((p?.content?.rendered||'')+' '+(p?.excerpt?.rendered||''));if(!relevant(title,body))continue;let raw=p.date_gmt;if(!raw)continue;if(raw&&!/[zZ]|[+-]\d\d:\d\d$/.test(raw))raw+='Z';const time=raw&&Number.isFinite(+new Date(raw))?new Date(raw).toISOString():null;if(!time)continue;for(const kind of ['death','missing','rescued'] as const){const v=extract(title+' '+body,kind);if(v!==null)best[kind]=choose(best[kind],{value:v,time,source:'RONB',url:p.link||'',correction:CORR.test(title+' '+body),minimum:kind==='missing'&&/(more than|over)/i.test(title+' '+body)},kind)}}}}catch(e){console.log('RONB failed',String(e))}
 const d=best.death,m=best.missing,s=best.rescued,payload={id:1,event:'Bhotekoshi flash flood',event_ne:'भोटेकोशी आकस्मिक बाढी',deaths:d?.value??current?.deaths??null,deaths_source:d?.source??current?.deaths_source??null,deaths_url:d?.url??current?.deaths_url??null,deaths_observed_at:d?.time??current?.deaths_observed_at??null,missing:m?.value??current?.missing??null,missing_source:m?.source??current?.missing_source??null,missing_url:m?.url??current?.missing_url??null,missing_observed_at:m?.time??current?.missing_observed_at??null,rescued:s?.value??current?.rescued??null,rescued_source:s?.source??current?.rescued_source??null,rescued_url:s?.url??current?.rescued_url??null,rescued_observed_at:s?.time??current?.rescued_observed_at??null,checked_at:new Date().toISOString(),raw:{sources:['NDRRMA via OnlineKhabar','NDRRMA via Radio Nepal','RONB','Nepal Police supporting links'],missing_is_minimum:Boolean(m?.minimum),policy:'Newest explicit event-wide authority-attributed total wins. Nepali thousand/lakh totals are parsed only when attached to deaths, missing or rescued outcomes; subgroup counts and BS years cannot become totals.'}};const {error}=await db.from('floodsafe_human_status').upsert(payload,{onConflict:'id'});if(error)throw error;return payload}
function shape(x:any){return {event:x?.event,event_ne:x?.event_ne,recovered_bodies:x?.deaths,recovered_source:x?.deaths_source,recovered_source_url:x?.deaths_url,recovered_update_time:x?.deaths_observed_at,recovered_update_iso:x?.deaths_observed_at,missing_minimum:x?.missing,missing_is_minimum:Boolean(x?.raw?.missing_is_minimum),missing_source:x?.missing_source,missing_source_url:x?.missing_url,missing_update_time:x?.missing_observed_at,rescued_alive:x?.rescued,rescued_source:x?.rescued_source,rescued_source_url:x?.rescued_url,rescued_update_time:x?.rescued_observed_at,status:'source_reported',last_checked_utc:x?.checked_at,sync_sources:['NDRRMA','OnlineKhabar','Radio Nepal','RONB','Nepal Police supporting']}}
let pending:Promise<any>|null=null;
function background(row:any){if(pending)return;pending=refresh(row).catch(e=>console.error('human-status refresh failed',String(e))).finally(()=>{pending=null});EdgeRuntime.waitUntil(pending)}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});try{const {data:row}=await db.from('floodsafe_human_status').select('*').eq('id',1).maybeSingle(),force=new URL(req.url).searchParams.get('force')==='1',age=row?.checked_at?Date.now()-+new Date(row.checked_at):Infinity,out=row||await refresh({});if(row&&(force||age>45000))background(row);return new Response(JSON.stringify(shape(out)),{headers:CORS})}catch(e){return new Response(JSON.stringify({error:String(e),status:'error'}),{status:500,headers:CORS})}});
