from pathlib import Path
import re

UI=Path('floodsafe-android-app/app/src/main/java/io/github/pujan1234hub/floodsafe/app/NativeFullActivity.java')
GRADLE=Path('floodsafe-android-app/app/build.gradle')
s=UI.read_text(encoding='utf-8')
g=GRADLE.read_text(encoding='utf-8')

if 'import java.net.URLEncoder;' not in s:
    s=s.replace('import java.net.URL;\n','import java.net.URL;\nimport java.net.URLEncoder;\n',1)

pattern=r'    private void showSathiDialog\(String initial\)\{.*?    private void consumeSathiIntent\(Intent i\)\{'
replacement=r'''    private void showSathiDialog(String initial){
        LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(8),dp(18),0);
        TextView transcript=text(t("नमस्ते 🙂 म SATHI हुँ। नेपालका ठाउँको मौसम, नदी/स्टेशन, warning/danger, nearby risk, notification वा app ले के गर्छ भनेर जे सोध्नुस् — उपलब्ध live app data हेरेर जवाफ दिन्छु।","Hi 🙂 I'm SATHI. Ask me about weather in a Nepal place, rivers/stations, warnings/danger, nearby risk, notifications, or what the app does — I'll answer from the live data available in FloodSafe."),14,false,Color.rgb(30,52,72));
        transcript.setPadding(dp(12),dp(12),dp(12),dp(12));transcript.setBackground(round(Color.rgb(248,252,254),16,Color.rgb(200,223,234),1));
        ScrollView chatScroll=new ScrollView(this);chatScroll.setFillViewport(true);chatScroll.addView(transcript);box.addView(chatScroll,lp(-1,dp(250),0,0,0,dp(10)));
        EditText input=new EditText(this);input.setHint(t("जस्तै: झापाको तापक्रम कति छ? काठमाडौंमा आज पानी पर्छ?","For example: What's the temperature in Jhapa? Will it rain in Kathmandu today?"));input.setTextSize(14);input.setMinLines(2);input.setMaxLines(4);input.setSingleLine(false);input.setPadding(dp(12),dp(10),dp(12),dp(10));input.setBackground(round(Color.rgb(248,252,254),16,Color.rgb(200,223,234),1));box.addView(input,lp(-1,-2,0,0,0,dp(8)));
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);
        Button ask=button(t("➤ सोध्नुहोस्","➤ Ask")),mic=button(t("🎙️ आवाज","🎙️ Voice"));actions.addView(ask,new LinearLayout.LayoutParams(0,dp(52),1f));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(0,dp(52),1f);mp.setMargins(dp(6),0,0,0);actions.addView(mic,mp);box.addView(actions);
        AlertDialog d=new AlertDialog.Builder(this).setTitle("🤖 SATHI").setView(box).setNegativeButton(t("बन्द","Close"),null).create();
        Runnable submit=()->{String q=input.getText().toString().trim();if(q.isEmpty())return;input.setText("");askSathi(transcript,chatScroll,q);};
        ask.setOnClickListener(v->submit.run());mic.setOnClickListener(v->startVoice(transcript,chatScroll));d.show();
        if(initial!=null&&!initial.trim().isEmpty()){transcript.setText("");askSathi(transcript,chatScroll,initial.trim());}
    } // V0911_SATHI_LIVE_DATA_CHAT

    private void appendSathiUser(TextView out,ScrollView chatScroll,String q){
        String before=String.valueOf(out.getText()).trim();String turn=t("तपाईं","You")+": "+q;
        out.setText(before.isEmpty()?turn:before+"\n\n"+turn);if(chatScroll!=null)chatScroll.post(()->chatScroll.fullScroll(View.FOCUS_DOWN));
    }
    private void appendSathiAnswer(TextView out,ScrollView chatScroll,String a){
        String before=String.valueOf(out.getText()).trim();String turn="SATHI: "+a;
        out.setText(before.isEmpty()?turn:before+"\n\n"+turn);if(chatScroll!=null)chatScroll.post(()->chatScroll.fullScroll(View.FOCUS_DOWN));
    }
    private void askSathi(TextView out,ScrollView chatScroll,String q){
        appendSathiUser(out,chatScroll,q);
        String local=answerSathiLocal(q);
        if(local!=null){appendSathiAnswer(out,chatScroll,local);speak(local);return;}
        appendSathiAnswer(out,chatScroll,t("एकछिन, live data हेर्दैछु…","One moment, I'm checking the live data…"));
        final String marker=t("एकछिन, live data हेर्दैछु…","One moment, I'm checking the live data…");
        io.execute(()->{String a;try{a=answerSathiNetwork(q);}catch(Exception e){a=t("अहिले online data लिन सकिनँ। Internet check गरेर फेरि सोध्नुस्; river safety data भने app मा उपलब्ध भएअनुसार चलिरहन्छ।","I couldn't fetch the online data right now. Check your internet and ask again; river safety data in the app continues to work from the available feed.");}final String ans=a;main.post(()->{String text=String.valueOf(out.getText());String suffix="SATHI: "+marker;int at=text.lastIndexOf(suffix);if(at>=0)out.setText(text.substring(0,at)+"SATHI: "+ans+text.substring(at+suffix.length()));else appendSathiAnswer(out,chatScroll,ans);if(chatScroll!=null)chatScroll.post(()->chatScroll.fullScroll(View.FOCUS_DOWN));speak(ans);});});
    }

    private void startVoice(TextView out,ScrollView chatScroll){
        if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}
        if(!SpeechRecognizer.isRecognitionAvailable(this)){appendSathiAnswer(out,chatScroll,t("यो फोनमा voice recognition उपलब्ध छैन। तल लेखेर सोध्नुस्।","Voice recognition isn't available on this phone. Please type your question below."));return;}
        if(speech!=null)try{speech.destroy();}catch(Exception ignored){}
        speech=SpeechRecognizer.createSpeechRecognizer(this);speech.setRecognitionListener(new RecognitionListener(){
            public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float x){}public void onBufferReceived(byte[]b){}public void onEndOfSpeech(){}
            public void onError(int e){appendSathiAnswer(out,chatScroll,t("आवाज स्पष्ट बुझिनँ। फेरि भन्नुस् वा लेखेर सोध्नुस्।","I couldn't understand the voice clearly. Please try again or type it."));}
            public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle b){}
            public void onResults(Bundle b){ArrayList<String> r=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);String q=r==null||r.isEmpty()?"":r.get(0).trim();if(q.isEmpty())appendSathiAnswer(out,chatScroll,t("प्रश्न सुनिनँ। फेरि प्रयास गर्नुस्।","I didn't catch a question. Please try again."));else askSathi(out,chatScroll,q);}
        });
        speech.startListening(new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM).putExtra(RecognizerIntent.EXTRA_LANGUAGE,english?"en-GB":"ne-NP").putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,5));
    }

    private String answerSathiLocal(String q){
        String x=q==null?"":q.toLowerCase(Locale.ROOT).trim();if(x.isEmpty())return t("म यहाँ छु 🙂 जे जान्न चाहनुहुन्छ सोध्नुस्।","I'm here 🙂 Ask whatever you want to know about FloodSafe's data.");
        if(x.contains("thank")||x.contains("धन्यवाद")||x.contains("dhany"))return t("स्वागत छ 🙂 अरू पनि सोध्नुस्।","You're welcome 🙂 Ask me anything else.");
        if(x.matches(".*\\b(hi|hello|hey|namaste|namaskar)\\b.*")||x.contains("नमस्ते")||x.contains("नमस्कार"))return t("नमस्ते 🙂 म SATHI हुँ। मौसम, नदी, स्टेशन, warning/danger, notification वा app का feature बारे सोध्नुस्।","Hi 🙂 I'm SATHI. Ask about weather, rivers, stations, warnings/danger, notifications, or app features.");
        if(isAppFeatureQuestion(x))return sathiAppFeatures();
        if(x.contains("notification")||x.contains("सूचना")||x.contains("push")||x.contains("alert kasari")||x.contains("चेतावनी कसरी"))return t("FloodSafe मा दुई प्रकारको मुख्य background notification छन्: तपाईंको location नजिक verified Warning/Danger भए emergency river alert, र weather/rain update। Monitoring on, notification permission र location permission आवश्यक हुन्छ।","FloodSafe has two main background notification paths: an emergency river alert when a verified Warning/Danger affects the river near your location, and weather/rain updates. Monitoring, notification permission, and location permission need to be enabled.");
        if(x.contains("location")||x.contains("gps")||x.contains("म कहाँ")||x.contains("ma kaha")){if(Double.isFinite(lat)&&Double.isFinite(lon))return t("GPS active छ। Nearby station र local river-risk notification का लागि यही current location प्रयोग भइरहेको छ।","GPS is active. FloodSafe is using your current location for nearby stations and local river-risk notifications.");return t("अहिले GPS location उपलब्ध छैन। Location permission र GPS on गरेपछि nearby data र local alerts काम गर्छन्।","GPS location isn't available right now. Turn on GPS and location permission for nearby data and local alerts.");}
        if(isWeatherQuestion(x))return null;
        String river=answerRiverOrStationQuestion(q);if(river!=null)return river;
        if(x.contains("status")||x.contains("app thik")||x.contains("app ठीक"))return t("App चलिरहेको छ। BIPAD river set foreground मा refresh हुन्छ, stale reading लाई live threat मानिँदैन, र language switch गर्दा map/location restart हुँदैन।","The app is running. The BIPAD river set refreshes in the foreground, stale readings are not treated as live threats, and language switching doesn't restart the map/location.");
        return t("यो प्रश्न app को safety/weather/river data सँग सम्बन्धित भए ठाउँ, नदी वा station को नामसहित सोध्नुस्। जस्तै ‘Jhapa को temperature?’, ‘Kathmandu मा आज पानी पर्छ?’, ‘Koshi को अवस्था?’ वा ‘app ले के काम गर्छ?’","If this is about the app's safety, weather, or river data, include the place, river, or station name. For example: ‘Jhapa temperature?’, ‘Will it rain in Kathmandu today?’, ‘Koshi status?’, or ‘What does this app do?’");
    } // V0911_SATHI_BILINGUAL_LOCAL_KNOWLEDGE

    private boolean isAppFeatureQuestion(String x){return x.contains("app le k")||x.contains("appले के")||x.contains("के काम")||x.contains("what does")||x.contains("what can")||x.contains("feature")||x.contains("function")||x.contains("काम गर्छ");}
    private String sathiAppFeatures(){return t("FloodSafe Nepal ले official BIPAD river stations र water-level status देखाउँछ; district अनुसार station detail, native river map/flow/status colour, GPS nearby station, verified local Warning/Danger alert, rain/weather update र storm/rain map effect दिन्छ। SATHI बाट ठाउँको मौसम, नदी/स्टेशनको अवस्था र app status सोध्न सकिन्छ। Stale river data लाई live खतरा मानिँदैन।","FloodSafe Nepal shows official BIPAD river stations and water-level status; district station details, a native river map with flow/status colours, GPS-based nearby stations, verified local Warning/Danger alerts, weather/rain updates, and storm/rain map effects. SATHI can answer place weather, river/station status, and app-status questions. Stale river data is not treated as a live threat.");}
    private boolean isWeatherQuestion(String x){return x.contains("weather")||x.contains("मौसम")||x.contains("mausam")||x.contains("rain")||x.contains("वर्षा")||x.contains("pani")||x.contains("पानी")||x.contains("temperature")||x.contains("temp")||x.contains("तापक्रम")||x.contains("garmi")||x.contains("chiso")||x.contains("आज")||x.contains("aaja")||x.contains("tomorrow")||x.contains("भोलि");}

    private String answerRiverOrStationQuestion(String q){
        String x=q.toLowerCase(Locale.ROOT);boolean riverIntent=x.contains("river")||x.contains("नदी")||x.contains("nadi")||x.contains("खोला")||x.contains("khola")||x.contains("flood")||x.contains("बाढी")||x.contains("badhi")||x.contains("warning")||x.contains("danger")||x.contains("alert")||x.contains("station")||x.contains("स्टेशन")||x.contains("koshi")||x.contains("gandaki")||x.contains("karnali");if(!riverIntent)return null;
        String district=findDistrictMention(q);if(!district.isEmpty())return sathiDistrictRiverSummary(district);
        List<RiverStation> matched=new ArrayList<>();String[] tokens=x.replaceAll("[^a-z0-9\\p{L}]+"," ").trim().split("\\s+");
        synchronized(stations){for(RiverStation s:stations){String hay=((s.name==null?"":s.name)+" "+(s.riverName==null?"":s.riverName)).toLowerCase(Locale.ROOT);boolean hit=false;for(String tok:tokens){if(tok.length()<4||isSathiStopToken(tok))continue;if(hay.contains(tok)){hit=true;break;}}if(hit)matched.add(s);}}
        if(!matched.isEmpty()){matched.sort(Comparator.comparingInt((RiverStation a)->a.fresh?0:1).thenComparingInt(a->a.rank));StringBuilder b=new StringBuilder();int n=Math.min(4,matched.size());for(int i=0;i<n;i++){RiverStation s=matched.get(i);if(i>0)b.append("; ");b.append(s.name);if(Double.isFinite(s.level))b.append(" ").append(String.format(Locale.US,"%.2f m",s.level));b.append(" (").append(s.fresh?s.stage:t("पुरानो","stale")).append(")");}return t("मिलेका official station/river detail: ","Matched official station/river details: ")+b.toString();}
        int d=0,w=0,a=0,f=0,total=0;synchronized(stations){for(RiverStation s:stations){total++;if(!s.fresh)continue;f++;if("danger".equals(s.stage))d++;else if("warning".equals(s.stage))w++;else if("alert".equals(s.stage))a++;}}
        return t("अहिले official set मा "+total+" station छन्; fresh "+f+" मध्ये Danger "+d+", Warning "+w+", Alert "+a+" छन्। कुनै खास नदी/जिल्लाको नाम दिए म त्यही detail निकाल्छु।","The official set currently has "+total+" stations; among "+f+" fresh readings there are "+d+" Danger, "+w+" Warning and "+a+" Alert. Give me a river or district name and I'll narrow it down.");
    }
    private boolean isSathiStopToken(String s){return s.equals("river")||s.equals("nadi")||s.equals("khola")||s.equals("station")||s.equals("status")||s.equals("warning")||s.equals("danger")||s.equals("alert")||s.equals("what")||s.equals("today")||s.equals("aaja")||s.equals("pani")||s.equals("mausam")||s.equals("flood");}
    private String findDistrictMention(String q){String x=q.toLowerCase(Locale.ROOT);for(String name:v0909AllDistrictNames())if(!name.isEmpty()&&x.contains(name.toLowerCase(Locale.ROOT)))return name;String[][] aliases={{"झापा","Jhapa"},{"काठमाडौं","Kathmandu"},{"काठमाण्डौ","Kathmandu"},{"ललितपुर","Lalitpur"},{"भक्तपुर","Bhaktapur"},{"चितवन","Chitwan"},{"कास्की","Kaski"},{"मोरङ","Morang"},{"सुनसरी","Sunsari"},{"इलाम","Ilam"},{"ताप्लेजुङ","Taplejung"},{"संखुवासभा","Sankhuwasabha"},{"सुरखेत","Surkhet"},{"सुर्खेत","Surkhet"},{"तनहुँ","Tanahun"},{"स्याङ्जा","Syangja"},{"उदयपुर","Udayapur"},{"धनकुटा","Dhankuta"},{"मुस्ताङ","Mustang"},{"सोलुखुम्बु","Solukhumbu"}};for(String[] a:aliases)if(x.contains(a[0]))return a[1];return "";}
    private String sathiDistrictRiverSummary(String district){List<RiverStation> rows=new ArrayList<>();synchronized(stations){for(RiverStation s:stations)if(s.district!=null&&s.district.equalsIgnoreCase(district))rows.add(s);}if(rows.isEmpty())return t(district+" जिल्लामा अहिले BIPAD River Watch को station row देखिएको छैन।",district+" currently has no BIPAD River Watch station row in the app.");int d=0,w=0,a=0,f=0;rows.sort(Comparator.comparingInt((RiverStation r)->r.fresh?0:1).thenComparingInt(r->r.rank));StringBuilder detail=new StringBuilder();for(int i=0;i<rows.size();i++){RiverStation s=rows.get(i);if(s.fresh){f++;if("danger".equals(s.stage))d++;else if("warning".equals(s.stage))w++;else if("alert".equals(s.stage))a++;}if(i<4){if(detail.length()>0)detail.append("; ");detail.append(s.name);if(Double.isFinite(s.level))detail.append(" ").append(String.format(Locale.US,"%.2f m",s.level));detail.append(" (").append(s.fresh?s.stage:t("पुरानो","stale")).append(")");}}return t(district+" मा "+rows.size()+" official river station छन्। Fresh "+f+"; Danger "+d+", Warning "+w+", Alert "+a+"। मुख्य detail: ",district+" has "+rows.size()+" official river stations. Fresh "+f+"; Danger "+d+", Warning "+w+", Alert "+a+". Details: ")+detail;}

    private String answerSathiNetwork(String q)throws Exception{if(isWeatherQuestion(q.toLowerCase(Locale.ROOT)))return sathiWeatherAnswer(q);String local=answerSathiLocal(q);return local==null?t("अहिले उत्तर निकाल्न सकिनँ।","I couldn't produce an answer right now."):local;}
    private static final class SathiPlace{final String name;final double lat,lon;SathiPlace(String n,double a,double o){name=n;lat=a;lon=o;}}
    private String sathiWeatherAnswer(String q)throws Exception{
        String hint=extractWeatherPlace(q);SathiPlace p=null;if(!hint.isEmpty())p=geocodeSathiPlace(hint);if(p==null&&Double.isFinite(lat)&&Double.isFinite(lon))p=new SathiPlace(t("तपाईंको location","your location"),lat,lon);if(p==null)return t("कुन ठाउँको मौसम चाहिएको हो नामसहित सोध्नुस् — जस्तै ‘Jhapa को तापक्रम?’ वा ‘Kathmandu मा आज पानी पर्छ?’","Tell me the place name — for example, ‘Jhapa temperature?’ or ‘Will it rain in Kathmandu today?’");
        String u="https://api.open-meteo.com/v1/forecast?latitude="+p.lat+"&longitude="+p.lon+"&current=temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,rain,showers,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max&forecast_days=2&timezone=auto";JSONObject root=sathiFetchJson(u);JSONObject c=root.optJSONObject("current");JSONObject d=root.optJSONObject("daily");double temp=c==null?Double.NaN:c.optDouble("temperature_2m",Double.NaN),feel=c==null?Double.NaN:c.optDouble("apparent_temperature",Double.NaN),precip=c==null?0d:Math.max(c.optDouble("precipitation",0d),Math.max(c.optDouble("rain",0d),c.optDouble("showers",0d))),wind=c==null?Double.NaN:c.optDouble("wind_speed_10m",Double.NaN);int code=c==null?-1:c.optInt("weather_code",-1);double max=dayDouble(d,"temperature_2m_max",0),min=dayDouble(d,"temperature_2m_min",0),sum=dayDouble(d,"precipitation_sum",0);int prob=(int)Math.round(dayDouble(d,"precipitation_probability_max",0));String cond=sathiWeatherCondition(code);String rainNow=precip>=0.1?t("अहिले पानी परिरहेको छ","it's raining now"):t("अहिले उल्लेख्य वर्षा छैन","there is no significant rain right now");String today=(prob>=50||sum>=0.5)?t("आज पानी पर्ने सम्भावना छ","rain is likely today"):t("आज उल्लेख्य वर्षाको सम्भावना कम छ","significant rain looks unlikely today");StringBuilder b=new StringBuilder();b.append(p.name).append(english?": ":" मा ");if(Double.isFinite(temp))b.append(t("अहिले ","currently ")).append(Math.round(temp)).append("°C");if(Double.isFinite(feel))b.append(t(" (महसुस "," (feels ")).append(Math.round(feel)).append("°C)");b.append(" • ").append(cond).append(" • ").append(rainNow).append(" • ").append(today).append(t(" — वर्षा सम्भावना "," — rain chance ")).append(prob).append("%, ").append(String.format(Locale.US,"%.1f",sum)).append(" mm");if(Double.isFinite(min)&&Double.isFinite(max))b.append(t(" • आज "," • today ")).append(Math.round(min)).append("–").append(Math.round(max)).append("°C");if(Double.isFinite(wind))b.append(t(" • हावा "," • wind ")).append(Math.round(wind)).append(" km/h");return b.toString();
    } // V0911_SATHI_PLACE_WEATHER
    private double dayDouble(JSONObject daily,String key,int i){if(daily==null)return Double.NaN;JSONArray a=daily.optJSONArray(key);return a==null?Double.NaN:a.optDouble(i,Double.NaN);}
    private String sathiWeatherCondition(int c){if(c==0)return t("सफा","clear");if(c<=3)return t("बादल/आंशिक बादल","cloudy/partly cloudy");if(c==45||c==48)return t("कुहिरो","foggy");if(c>=95)return t("चट्याङ/आँधीको अवस्था","thunderstorm conditions");if(c>=80)return t("वर्षा/झरी","showers");if(c>=61)return t("वर्षा","rain");if(c>=51)return t("फुहार","drizzle");return t("मौसम code "+c,"weather code "+c);}
    private String extractWeatherPlace(String q){String district=findDistrictMention(q);if(!district.isEmpty())return district;String x=q.replaceAll("[?.,!;:]"," ").trim();String low=x.toLowerCase(Locale.ROOT);String[][] alias={{"पोखरा","Pokhara"},{"विराटनगर","Biratnagar"},{"धरान","Dharan"},{"जनकपुर","Janakpur"},{"बुटवल","Butwal"},{"नेपालगञ्ज","Nepalgunj"},{"हेटौडा","Hetauda"},{"हेटौँडा","Hetauda"}};for(String[] a:alias)if(low.contains(a[0]))return a[1];String[] toks=x.split("\\s+");for(String tok:toks){String clean=tok.replaceAll("[^a-zA-Z\\p{L}]","");String l=clean.toLowerCase(Locale.ROOT);if(clean.length()<3||isWeatherStop(l))continue;if(clean.endsWith("मा")&&clean.length()>4)clean=clean.substring(0,clean.length()-2);if(clean.endsWith("को")&&clean.length()>4)clean=clean.substring(0,clean.length()-2);return clean;}return "";}
    private boolean isWeatherStop(String s){String z=s.toLowerCase(Locale.ROOT);return z.equals("will")||z.equals("rain")||z.equals("weather")||z.equals("today")||z.equals("tomorrow")||z.equals("temperature")||z.equals("what")||z.equals("whats")||z.equals("aaja")||z.equals("bholi")||z.equals("pani")||z.equals("parxa")||z.equals("parcha")||z.equals("mausam")||z.equals("tapkram")||z.equals("kati")||z.equals("आज")||z.equals("भोलि")||z.equals("पानी")||z.equals("पर्छ")||z.equals("मौसम")||z.equals("तापक्रम")||z.equals("कति")||z.equals("छ");}
    private SathiPlace geocodeSathiPlace(String name)throws Exception{String u="https://geocoding-api.open-meteo.com/v1/search?name="+URLEncoder.encode(name,"UTF-8")+"&count=10&language=en&format=json";JSONObject root=sathiFetchJson(u);JSONArray r=root.optJSONArray("results");if(r==null||r.length()==0)return null;JSONObject first=null;for(int i=0;i<r.length();i++){JSONObject o=r.optJSONObject(i);if(o==null)continue;if(first==null)first=o;String cc=o.optString("country_code","");if("NP".equalsIgnoreCase(cc)){first=o;break;}}if(first==null)return null;double a=first.optDouble("latitude",Double.NaN),o=first.optDouble("longitude",Double.NaN);if(!Double.isFinite(a)||!Double.isFinite(o))return null;String label=first.optString("name",name);String admin=first.optString("admin1","");if(!admin.isEmpty()&&!label.equalsIgnoreCase(admin))label+=" ("+admin+")";return new SathiPlace(label,a,o);}
    private JSONObject sathiFetchJson(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(15000);c.setUseCaches(false);c.setRequestProperty("Accept","application/json");c.setRequestProperty("Cache-Control","no-cache");int code=c.getResponseCode();if(code!=200){c.disconnect();throw new IllegalStateException("HTTP "+code);}StringBuilder b=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null)b.append(line);}finally{c.disconnect();}return new JSONObject(b.toString());}

    private void consumeSathiIntent(Intent i){'''

s2,n=re.subn(pattern,lambda m:replacement,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'SATHI v0910 block anchor expected once, got {n}')
s=s2
for marker in ['V0911_SATHI_LIVE_DATA_CHAT','V0911_SATHI_BILINGUAL_LOCAL_KNOWLEDGE','V0911_SATHI_PLACE_WEATHER']:
    if marker not in s: raise SystemExit('missing '+marker)
if 'android.webkit.WebView' in s: raise SystemExit('WebView introduced')

if "versionName '0.9.10-sathi-chat-map-labels'" not in g: raise SystemExit('v0910 version anchor missing')
g=g.replace("versionCode 24","versionCode 25",1) if "versionCode 24" in g else g
g=g.replace("versionName '0.9.10-sathi-chat-map-labels'","versionName '0.9.11-sathi-live-all-data-alert-safe'",1)
UI.write_text(s,encoding='utf-8');GRADLE.write_text(g,encoding='utf-8')
print('V0911_SATHI_LIVE_DATA_OK')
