from pathlib import Path
root=Path(__file__).resolve().parent
p=root/'app/src/main/java/io/github/pujan1234hub/floodsafe/app/NativeFullActivity.java'
a=p.read_text(encoding='utf-8')
if 'import android.widget.EditText;' not in a:a=a.replace('import android.widget.Button;','import android.widget.Button;\nimport android.widget.EditText;',1)
s=a.find('    private void showSathiDialog(String initial)');e=a.find('    private void consumeSathiIntent(',s)
if s<0 or e<0:raise SystemExit('SATHI anchors')
new=r'''    private void showSathiDialog(String initial){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(8),dp(18),0);TextView answer=text(t("जिल्ला, नदी/खोला, status, rainfall, temperature वा weather सोध्नुहोस्।","Ask any district, river/khola, status, rainfall, temperature or weather question."),14,false,Color.rgb(30,52,72));box.addView(answer);EditText input=new EditText(this);input.setHint(t("उदाहरण: Kathmandu मा Dhobi Khola status?","Example: Dhobi Khola status in Kathmandu?"));box.addView(input);Button ask=button(t("🤖 सोध्नुहोस्","🤖 Ask"));box.addView(ask,lp(-1,dp(50),0,dp(8),0,0));Button mic=button(t("🎙️ माइकबाट सोध्नुहोस्","🎙️ Ask by voice"));box.addView(mic,lp(-1,dp(50),0,dp(7),0,0));AlertDialog d=new AlertDialog.Builder(this).setTitle("🤖 SATHI • LIVE DATA").setView(box).setNegativeButton(t("बन्द","Close"),null).create();ask.setOnClickListener(v->{String q=input.getText().toString().trim();if(!q.isEmpty())answerSathiAsync(q,answer,false);});mic.setOnClickListener(v->startVoice(answer));d.show();if(initial!=null&&!initial.trim().isEmpty()){input.setText(initial);answerSathiAsync(initial.trim(),answer,false);}}
    private void startVoice(TextView out){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){out.setText(t("यो फोनमा voice recognition उपलब्ध छैन।","Voice recognition is unavailable."));return;}if(speech!=null)try{speech.destroy();}catch(Exception ignored){}speech=SpeechRecognizer.createSpeechRecognizer(this);speech.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){out.setText(t("🎙 सुन्दैछु…","🎙 Listening…"));}public void onBeginningOfSpeech(){}public void onRmsChanged(float x){}public void onBufferReceived(byte[]b){}public void onEndOfSpeech(){}public void onError(int x){out.setText(t("आवाज बुझिएन।","Could not understand."));}public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle b){}public void onResults(Bundle b){ArrayList<String> r=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);String q=r==null||r.isEmpty()?"":r.get(0);answerSathiAsync(q,out,true);}});speech.startListening(new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM).putExtra(RecognizerIntent.EXTRA_LANGUAGE,english?"en-GB":"ne-NP").putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,5));}
    private void answerSathiAsync(String q,TextView out,boolean voice){final String z=q==null?"":q.trim();if(z.isEmpty())return;out.setText(t("🔎 live data जाँच्दैछु…","🔎 Checking live data…"));io.execute(()->{String ans;try{ans=v848SathiAnswer(z);}catch(Exception ex){ans=t("Live data अहिले पढ्न सकिनँ। फेरि प्रयास गर्नुहोस्।","Could not read live data right now. Try again.");}final String f=ans;runOnUiThread(()->{out.setText("तपाईं: "+z+"\n\nSATHI: "+f);if(voice)speak(f);});});}
    private String v848SathiAnswer(String q)throws Exception{String x=q.toLowerCase(Locale.ROOT),district=v848FindDistrict(q);RiverStation st=v848BestStation(q);boolean weather=x.contains("weather")||x.contains("मौसम")||x.contains("temperature")||x.contains("temp")||x.contains("तापक्रम")||x.contains("rainfall")||x.contains("rain")||x.contains("वर्षा");if(st!=null&&(x.contains("river")||x.contains("khola")||x.contains("नदी")||x.contains("खोला")||x.contains("status")||x.contains("level")||x.contains("स्थिति")||x.contains("सतह"))){StringBuilder b=new StringBuilder(st.name);if(!st.district.isEmpty())b.append(" • ").append(st.district);if(st.fresh){b.append("\n").append(stageName(st.stage));if(Double.isFinite(st.level))b.append(String.format(Locale.US," • %.2f m",st.level));b.append("\nOfficial time: ").append(v848Time(st.at));}else b.append(t("\nअहिले current official reading छैन।","\nNo current official reading right now."));if(Double.isFinite(st.warning))b.append(String.format(Locale.US,"\nWarning %.2f m",st.warning));if(Double.isFinite(st.danger))b.append(String.format(Locale.US," • Danger %.2f m",st.danger));return b.toString();}if(weather){double[] pt=v848Point(district);if(pt==null)return t("जिल्ला वा स्थानको नामसहित सोध्नुहोस्।","Ask with a district or place name.");return v848Weather(district,pt[0],pt[1]);}if(!district.isEmpty())return v848DistrictStatus(district);if(x.contains("river")||x.contains("khola")||x.contains("नदी")||x.contains("खोला")||x.contains("flood")||x.contains("बाढी")){List<RiverStation> z; synchronized(stations){z=new ArrayList<>(stations);}int live=0,d=0,w=0,al=0;for(RiverStation r:z){if(r.fresh)live++;if("danger".equals(r.stage))d++;else if("warning".equals(r.stage))w++;else if("alert".equals(r.stage))al++;}return t("Official station "+z.size()+", अहिले current "+live+"। Danger "+d+", Warning "+w+", Alert "+al+"। जिल्ला वा खोला नाम सोध्नुहोस्।","Official stations "+z.size()+", current now "+live+". Danger "+d+", Warning "+w+", Alert "+al+". Ask a district or river name.");}return t("जिल्ला, नदी/खोला, water level/status, rainfall, temperature वा weather सोध्नुहोस्।","Ask a district, river/khola, water level/status, rainfall, temperature or weather.");}
    private RiverStation v848BestStation(String q){String k=v848Key(q);RiverStation best=null;int bs=0;synchronized(stations){for(RiverStation r:stations){String n=v848Key(r.name);int sc=0;for(String t:r.name.toLowerCase(Locale.ROOT).split("[^a-z0-9]+"))if(t.length()>2&&q.toLowerCase(Locale.ROOT).contains(t))sc++;if(k.contains(n)&&n.length()>4)sc+=4;if(sc>bs||(sc==bs&&best!=null&&r.fresh&&!best.fresh)){bs=sc;best=r;}}}return bs>=2?best:null;}
    private String v848FindDistrict(String q){String k=v848Key(q);java.util.TreeSet<String> n=new java.util.TreeSet<>(String.CASE_INSENSITIVE_ORDER);synchronized(stations){for(RiverStation r:stations)if(r.district!=null&&!r.district.isEmpty())n.add(r.district);}for(String d:n){String z=v848Key(d);if(!z.isEmpty()&&k.contains(z))return d;}return "";}
    private String v848DistrictStatus(String d){List<RiverStation> z=new ArrayList<>();synchronized(stations){for(RiverStation r:stations)if(d.equalsIgnoreCase(r.district))z.add(r);}z.sort(Comparator.comparingInt((RiverStation r)->r.rank).thenComparing(r->r.name,String.CASE_INSENSITIVE_ORDER));int live=0,da=0,wa=0,al=0;StringBuilder b=new StringBuilder(d+": ");for(RiverStation r:z){if(r.fresh)live++;if("danger".equals(r.stage))da++;else if("warning".equals(r.stage))wa++;else if("alert".equals(r.stage))al++;}b.append(z.size()).append(" official • ").append(live).append(" current • 🔴 ").append(da).append(" 🟠 ").append(wa).append(" 🟡 ").append(al);for(int i=0;i<Math.min(6,z.size());i++){RiverStation r=z.get(i);b.append("\n• ").append(r.name).append(" — ").append(r.fresh?stageName(r.stage):t("current छैन","no current"));if(r.fresh&&Double.isFinite(r.level))b.append(String.format(Locale.US," %.2f m",r.level));}return b.toString();}
    private double[] v848Point(String d){if(d!=null&&!d.isEmpty()){double a=0,o=0;int n=0;synchronized(stations){for(RiverStation r:stations)if(d.equalsIgnoreCase(r.district)){a+=r.lat;o+=r.lon;n++;}}if(n>0)return new double[]{a/n,o/n};}if(isNepal(lat,lon))return new double[]{lat,lon};return null;}
    private String v848Weather(String d,double la,double lo)throws Exception{String u=String.format(Locale.US,"https://api.open-meteo.com/v1/forecast?latitude=%.6f&longitude=%.6f&current=temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m&timezone=Asia%%2FKathmandu",la,lo);JSONObject j=getJson(u),c=j.getJSONObject("current");double te=c.optDouble("temperature_2m",Double.NaN),pr=c.optDouble("precipitation",Double.NaN),hu=c.optDouble("relative_humidity_2m",Double.NaN),wi=c.optDouble("wind_speed_10m",Double.NaN);StringBuilder b=new StringBuilder(d==null||d.isEmpty()?t("हालको स्थान","Current location"):d);if(Double.isFinite(te))b.append(String.format(Locale.US,"\n🌡 %.1f°C",te));if(Double.isFinite(pr))b.append(String.format(Locale.US," • 🌧 %.1f mm",pr));if(Double.isFinite(hu))b.append(String.format(Locale.US," • humidity %.0f%%",hu));if(Double.isFinite(wi))b.append(String.format(Locale.US," • wind %.0f km/h",wi));RainStation rr=v848NearestRain(la,lo);if(rr!=null){b.append("\nBIPAD/DHM rain: ").append(rr.name);if(Double.isFinite(rr.rainfall))b.append(String.format(Locale.US," • 1h %.1f mm",rr.rainfall));if(Double.isFinite(rr.rain3))b.append(String.format(Locale.US," • 3h %.1f",rr.rain3));if(Double.isFinite(rr.rain6))b.append(String.format(Locale.US," • 6h %.1f",rr.rain6));if(Double.isFinite(rr.rain24))b.append(String.format(Locale.US," • 24h %.1f",rr.rain24));b.append(rr.fresh?" • LATEST":" • STALE/UNKNOWN");}return b.toString();}
    private RainStation v848NearestRain(double la,double lo){RainStation b=null;double bd=Double.MAX_VALUE;synchronized(rainStations){for(RainStation r:rainStations){double d=v848Km(la,lo,r.lat,r.lon);if(d<bd){bd=d;b=r;}}}return b;}
    private static double v848Km(double a,double o,double b,double p){double R=6371,d1=Math.toRadians(b-a),d2=Math.toRadians(p-o),q=Math.sin(d1/2)*Math.sin(d1/2)+Math.cos(Math.toRadians(a))*Math.cos(Math.toRadians(b))*Math.sin(d2/2)*Math.sin(d2/2);return 2*R*Math.asin(Math.sqrt(q));}
    private String v848Time(long tm){if(tm<=0)return t("अज्ञात","unknown");try{return ZonedDateTime.ofInstant(Instant.ofEpochMilli(tm),ZoneId.of("Asia/Kathmandu")).format(DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm:ss 'NPT'",Locale.ENGLISH));}catch(Exception e){return "unknown";}}

'''
a=a[:s]+new+a[e:]
for x in ['answerSathiAsync','v848SathiAnswer','v848Weather','v848DistrictStatus']:
 if x not in a:raise SystemExit('missing '+x)
p.write_text(a,encoding='utf-8')
print('v0.8.48 advanced SATHI PASS')
