from pathlib import Path
import re

ROOT=Path('floodsafe-android-app')
UI=ROOT/'app/src/main/java/io/github/pujan1234hub/floodsafe/app/NativeFullActivity.java'
GRADLE=ROOT/'app/build.gradle'
s=UI.read_text(encoding='utf-8')
g=GRADLE.read_text(encoding='utf-8')

def once(text,old,new,label):
    n=text.count(old)
    if n!=1: raise SystemExit(f'{label}: expected 1, got {n}')
    return text.replace(old,new,1)

# Version from verified v0.9.15 generated base.
g=once(g,'versionCode 32','versionCode 33','versionCode')
g=once(g,"versionName '0.9.15-current-weather-icons'","versionName '0.9.16-sathi-knowledge'",'versionName')

# Keep a rotating knowledge tip and refresh no-news fallback every 10 minutes.
s=once(s,'    private String currentWeather="";\n    private boolean showAllStations=false;', '''    private String currentWeather="";
    private boolean showAllStations=false;
    private int knowledgeTipIndex=-1;
    private final Runnable newsKnowledgeTick=new Runnable(){@Override public void run(){refreshNews();main.postDelayed(this,10L*60L*1000L);}}; // V0916_KNOWLEDGE_ROTATION
''','knowledge fields')
s=once(s,'        main.post(clockTick);','        main.post(clockTick);\n        main.postDelayed(newsKnowledgeTick,10L*60L*1000L);','knowledge timer')

# Current local weather string used by SATHI must contain actual condition + temperature, not only Rain/No rain.
s=once(s,'current=temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m&hourly=precipitation_probability,precipitation',
       'current=temperature_2m,relative_humidity_2m,precipitation,cloud_cover,weather_code,wind_speed_10m&hourly=precipitation_probability,precipitation',
       'weather current fields')
old='double te=c.optDouble("temperature_2m",Double.NaN),pr=c.optDouble("precipitation",0),hu=c.optDouble("relative_humidity_2m",Double.NaN),wi=c.optDouble("wind_speed_10m",Double.NaN);String ws=pr>=.5?t("अहिले वर्षा भइरहेको छ","Rain now"):t("अहिले वर्षा छैन","No rain now");String timing=rainTiming(j);currentWeather=ws;'
new='double te=c.optDouble("temperature_2m",Double.NaN),pr=c.optDouble("precipitation",0),cl=c.optDouble("cloud_cover",0),hu=c.optDouble("relative_humidity_2m",Double.NaN),wi=c.optDouble("wind_speed_10m",Double.NaN);int wc=c.optInt("weather_code",-1);String ws=pr>=.1?t("अहिले वर्षा भइरहेको छ","Rain now"):t("अहिले वर्षा छैन","No rain now");String timing=rainTiming(j);String cond=weatherCodeLabel(wc);currentWeather=t(cond+", तापक्रम "+(Double.isFinite(te)?Math.round(te)+"°C":"उपलब्ध छैन")+", वर्षा "+String.format(Locale.US,"%.1f",pr)+" mm, बादल "+Math.round(cl)+"%"+(Double.isFinite(hu)?", आर्द्रता "+Math.round(hu)+"%":"")+(Double.isFinite(wi)?", हावा "+Math.round(wi)+" km/h":"")+"।",cond+", "+(Double.isFinite(te)?Math.round(te)+"°C":"temperature unavailable")+", rain "+String.format(Locale.US,"%.1f",pr)+" mm, cloud "+Math.round(cl)+"%"+(Double.isFinite(hu)?", humidity "+Math.round(hu)+"%":"")+(Double.isFinite(wi)?", wind "+Math.round(wi)+" km/h":"")+".");'
s=once(s,old,new,'currentWeather detail')

# Conversational patch submit hooks: district weather is fetched asynchronously at the requested district centre.
old_submit='Runnable submit=()->{String q=input.getText().toString().trim();if(q.isEmpty())return;String a=answerSathi(q);appendSathiTurn(transcript,chatScroll,q,a);input.setText("");speak(a);};'
new_submit='Runnable submit=()->{String q=input.getText().toString().trim();if(q.isEmpty())return;input.setText("");submitSathiQuestion(transcript,chatScroll,q);};'
s=once(s,old_submit,new_submit,'typed SATHI submit')
old_voice='String a=answerSathi(q);appendSathiTurn(out,chatScroll,q,a);speak(a);'
# Only replace the onResults occurrence left by v0.9.10.
s=once(s,old_voice,'submitSathiQuestion(out,chatScroll,q);','voice SATHI submit')

# Add helpers immediately before answerSathi generated by v0.9.10.
anchor='    private String answerSathi(String q){'
if anchor not in s: raise SystemExit('answerSathi anchor missing')
helpers=r'''    // V0916_SATHI_DISTRICT_WEATHER — district-specific answers use live current weather at the district geometry centre.
    private void submitSathiQuestion(TextView out,ScrollView chatScroll,String q){
        if(isWeatherQuestion(q)){
            io.execute(()->{
                String a=null;
                try{a=districtWeatherAnswer(q);}catch(Exception ignored){}
                final String answer=(a==null||a.isEmpty())?answerSathi(q):a;
                runOnUiThread(()->{appendSathiTurn(out,chatScroll,q,answer);speak(answer);});
            });
        }else{String a=answerSathi(q);appendSathiTurn(out,chatScroll,q,a);speak(a);}
    }

    private boolean isWeatherQuestion(String q){String x=q==null?"":q.toLowerCase(Locale.ROOT);return x.contains("weather")||x.contains("mausam")||x.contains("मौसम")||x.contains("rain")||x.contains("pani")||x.contains("पानी")||x.contains("वर्षा")||x.contains("temperature")||x.contains("temp")||x.contains("garmi")||x.contains("chiso")||x.contains("cloud")||x.contains("बादल")||x.contains("तापक्रम")||x.contains("aaja")||x.contains("आज");}

    private String districtWeatherAnswer(String q)throws Exception{
        JSONObject root=assetJson("floodsafe-nepal/v24/nepal-districts.geojson");JSONArray fs=root.optJSONArray("features");if(fs==null)return null;String low=q==null?"":q.toLowerCase(Locale.ROOT);JSONObject hit=null;String name="";
        for(int i=0;i<fs.length();i++){JSONObject f=fs.optJSONObject(i);if(f==null)continue;String n=f.optJSONObject("properties")==null?"":f.optJSONObject("properties").optString("nameEn","").trim();if(n.isEmpty())continue;String key=n.toLowerCase(Locale.ROOT);if(low.matches(".*(^|[^a-z])"+java.util.regex.Pattern.quote(key)+"([^a-z]|$).*")||low.contains(key)){hit=f;name=n;break;}}
        if(hit==null)return null;JSONObject geo=hit.optJSONObject("geometry");if(geo==null)return null;double[] b={Double.POSITIVE_INFINITY,Double.NEGATIVE_INFINITY,Double.POSITIVE_INFINITY,Double.NEGATIVE_INFINITY};scanGeoBounds(geo.optJSONArray("coordinates"),b);if(!Double.isFinite(b[0])||!Double.isFinite(b[1])||!Double.isFinite(b[2])||!Double.isFinite(b[3]))return null;double a=(b[0]+b[1])/2d,o=(b[2]+b[3])/2d;
        String u=String.format(Locale.US,"https://api.open-meteo.com/v1/forecast?latitude=%.5f&longitude=%.5f&current=temperature_2m,relative_humidity_2m,precipitation,cloud_cover,weather_code,wind_speed_10m&timezone=Asia%%2FKathmandu",a,o);JSONObject c=getJson(u).optJSONObject("current");if(c==null)return null;double te=c.optDouble("temperature_2m",Double.NaN),pr=c.optDouble("precipitation",0),cl=c.optDouble("cloud_cover",0),hu=c.optDouble("relative_humidity_2m",Double.NaN),wi=c.optDouble("wind_speed_10m",Double.NaN);int wc=c.optInt("weather_code",-1);String cond=weatherCodeLabel(wc);boolean tempOnly=low.contains("temperature")||low.contains("temp")||low.contains("तापक्रम")||low.contains("garmi")||low.contains("chiso");
        if(tempOnly)return t(name+" को तापक्रम "+(Double.isFinite(te)?Math.round(te)+"°C":"उपलब्ध छैन")+" छ · "+cond+"।",name+" temperature is "+(Double.isFinite(te)?Math.round(te)+"°C":"unavailable")+" · "+cond+".");
        return t(name+": "+cond+", तापक्रम "+(Double.isFinite(te)?Math.round(te)+"°C":"उपलब्ध छैन")+", वर्षा "+String.format(Locale.US,"%.1f",pr)+" mm, बादल "+Math.round(cl)+"%"+(Double.isFinite(hu)?", आर्द्रता "+Math.round(hu)+"%":"")+(Double.isFinite(wi)?", हावा "+Math.round(wi)+" km/h":"")+"।",name+": "+cond+", "+(Double.isFinite(te)?Math.round(te)+"°C":"temperature unavailable")+", rain "+String.format(Locale.US,"%.1f",pr)+" mm, cloud "+Math.round(cl)+"%"+(Double.isFinite(hu)?", humidity "+Math.round(hu)+"%":"")+(Double.isFinite(wi)?", wind "+Math.round(wi)+" km/h":"")+".");
    }
    private void scanGeoBounds(JSONArray a,double[] b){if(a==null)return;if(a.length()>=2&&a.opt(0) instanceof Number&&a.opt(1) instanceof Number){double o=a.optDouble(0,Double.NaN),la=a.optDouble(1,Double.NaN);if(Double.isFinite(la)&&Double.isFinite(o)){b[0]=Math.min(b[0],la);b[1]=Math.max(b[1],la);b[2]=Math.min(b[2],o);b[3]=Math.max(b[3],o);}return;}for(int i=0;i<a.length();i++){Object x=a.opt(i);if(x instanceof JSONArray)scanGeoBounds((JSONArray)x,b);}}
    private String weatherCodeLabel(int c){if(c==0)return t("खुला आकाश","Clear");if(c==1)return t("मुख्यतः खुला","Mostly clear");if(c==2)return t("आंशिक बादल","Partly cloudy");if(c==3)return t("बादल","Overcast");if(c==45||c==48)return t("कुहिरो","Fog");if(c>=51&&c<=57)return t("झरी","Drizzle");if(c>=61&&c<=67)return t("वर्षा","Rain");if(c>=71&&c<=77)return t("हिमपात","Snow");if(c>=80&&c<=82)return t("वर्षा shower","Rain showers");if(c>=95&&c<=99)return t("मेघगर्जन","Thunderstorm");return t("मौसम","Weather");}

'''
s=s.replace(anchor,helpers+anchor,1)

# Add gyan/fact handling before generic weather branch in the conversational answer.
needle='        boolean weatherQ=x.contains("weather")'
if needle not in s: raise SystemExit('weatherQ anchor missing')
s=s.replace(needle,'        if(x.contains("ज्ञान")||x.contains("gyan")||x.contains("fact")||x.contains("tip")){if(knowledgeTipIndex<0)selectKnowledgeTip();return knowledgeText(knowledgeTipIndex);}\n\n'+needle,1)

# Replace empty 30-minute news result with rotating knowledge fallback.
pat=re.compile(r'private void renderNews\(List<NewsItem> out\)\{newsList\.removeAllViews\(\);if\(out\.isEmpty\(\)\)\{newsList\.addView\(empty\(t\("नयाँ live समाचार भेटिएन।","No fresh live stories found\."\)\)\);return;\}')
m=pat.search(s)
if not m: raise SystemExit('renderNews empty branch missing')
s=s[:m.start()]+m.group(0).replace('newsList.addView(empty(t("नयाँ live समाचार भेटिएन।","No fresh live stories found.")));return;','renderKnowledgeFallback(true);return;')+s[m.end():]

# Knowledge helpers before privacy dialog.
privacy='    private void showPrivacy(){'
if privacy not in s: raise SystemExit('privacy anchor missing')
knowledge=r'''    // V0916_KNOWLEDGE_FALLBACK — when no verified <=30-minute news exists, show a non-repeating safety fact.
    private static final String[] KNOW_NE={
        "बाढीको पानी देख्दा गहिराइ अनुमान गरेर पार गर्ने प्रयास नगर्नुहोस्; सुरक्षित अग्लो ठाउँतिर जानुहोस्।",
        "नदीको पानी अचानक धमिलो हुनु, बहाव तीव्र बढ्नु वा ठूला काठ/ढुङ्गा बग्नु माथिल्लो क्षेत्रमा बाढी आएको संकेत हुन सक्छ।",
        "Warning वा Danger देखिएको नदी किनारमा फोटो वा भिडियो लिन जानु जोखिमपूर्ण हुन्छ।",
        "पहिरो सम्भावित ठाउँमा जमिनमा नयाँ चिरा, ढल्किएको रुख वा असामान्य पानीको बहाव देखिए सुरक्षित ठाउँमा सर्नुहोस्।",
        "बाढीको बेला विद्युत् पोल, खुलेको तार र पानी जमेको सडकबाट टाढा रहनुहोस्।",
        "राति नदीको अवस्था आँखाले मात्र अनुमान गर्न कठिन हुन्छ; official gauge र चेतावनीलाई प्राथमिकता दिनुहोस्।",
        "नदीको सतह घट्न थाले पनि upstream वर्षा जारी छ भने पुनः बढ्न सक्छ; official update हेर्दै रहनुहोस्।",
        "बाढीपछि घर फर्कँदा भित्तामा चिरा, कमजोर जग वा विद्युत् जोखिम जाँच नगरी प्रवेश नगर्नुहोस्।",
        "आपतकालीन झोलामा पानी, आवश्यक औषधि, टर्च, power bank र महत्वपूर्ण कागजातको सुरक्षित प्रतिलिपि राख्नु उपयोगी हुन्छ।",
        "पुलमाथि पानी बगिरहेको छ भने सवारी वा पैदल पार नगर्नुहोस्; वैकल्पिक सुरक्षित मार्ग रोज्नुहोस्।",
        "एक station सामान्य भए पनि अर्को upstream station Warning मा हुन सक्छ; सम्बन्धित नदीका धेरै official reading हेर्नुहोस्।",
        "पुरानो/stale river reading लाई live सुरक्षित अवस्था मान्न हुँदैन; नयाँ official observation पर्खनुहोस्।"
    };
    private static final String[] KNOW_EN={
        "Do not try to cross floodwater by guessing its depth; move toward safer higher ground.",
        "A sudden rise, muddy flow, or large debris in a river can signal flooding upstream.",
        "Do not approach a river in Warning or Danger just to take photos or videos.",
        "New ground cracks, leaning trees, or unusual water flow can be warning signs of slope movement.",
        "During floods, stay away from power poles, exposed wires and waterlogged roads.",
        "River conditions are hard to judge visually at night; prioritise official gauges and warnings.",
        "A river can rise again even after falling if heavy rain continues upstream.",
        "After flooding, check structural and electrical safety before entering a damaged building.",
        "A basic emergency bag can include water, essential medicines, a torch, power bank and copies of key documents.",
        "Never cross a bridge or road when floodwater is flowing over it; use a safer alternative route.",
        "One station may be normal while an upstream station is in Warning; check multiple official readings on the same river.",
        "Do not treat a stale river reading as proof that conditions are currently safe."
    };
    private int selectKnowledgeTip(){SharedPreferences p=getSharedPreferences(PREFS,MODE_PRIVATE);int last=p.getInt("knowledge_last",-1);String raw=p.getString("knowledge_used","");java.util.HashSet<Integer> used=new java.util.HashSet<>();if(raw!=null&&!raw.isEmpty())for(String x:raw.split(","))try{used.add(Integer.parseInt(x));}catch(Exception ignored){}if(used.size()>=KNOW_NE.length-1){used.clear();if(last>=0)used.add(last);}java.util.ArrayList<Integer> choices=new java.util.ArrayList<>();for(int i=0;i<KNOW_NE.length;i++)if(i!=last&&!used.contains(i))choices.add(i);knowledgeTipIndex=choices.isEmpty()?(last+1+KNOW_NE.length)%KNOW_NE.length:choices.get(new java.util.Random().nextInt(choices.size()));used.add(knowledgeTipIndex);StringBuilder b=new StringBuilder();for(Integer i:used){if(b.length()>0)b.append(',');b.append(i);}p.edit().putInt("knowledge_last",knowledgeTipIndex).putString("knowledge_used",b.toString()).apply();return knowledgeTipIndex;}
    private String knowledgeText(int i){if(i<0||i>=KNOW_NE.length)i=0;return english?KNOW_EN[i]:KNOW_NE[i];}
    private void renderKnowledgeFallback(boolean rotate){newsList.removeAllViews();if(rotate||knowledgeTipIndex<0)selectKnowledgeTip();newsList.setTag("knowledge");newsTitle.setText(t("💡 ज्ञानको कुरा","💡 Safety knowledge"));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(12),dp(12),dp(12));c.setBackground(round(Color.rgb(248,252,254),17,Color.rgb(216,234,243),1));c.addView(text(t("आजको उपयोगी कुरा","Useful safety fact"),15,true,Color.rgb(16,39,70)));c.addView(text(knowledgeText(knowledgeTipIndex),13,false,Color.rgb(88,117,138)));newsList.addView(c);}

'''
s=s.replace(privacy,knowledge+privacy,1)

# Fresh news must reset the knowledge tag/title; language toggle preserves the current tip without rotating it.
needle='private void renderNews(List<NewsItem> out){newsList.removeAllViews();'
if needle not in s: raise SystemExit('renderNews start missing')
s=s.replace(needle,'private void renderNews(List<NewsItem> out){newsList.removeAllViews();newsList.setTag(null);newsTitle.setText(t("📰 नेपालका पछिल्ला समाचार","📰 Latest Nepal news"));',1)
old_lang='privacySub.setText(t("Location, microphone र alert data कसरी प्रयोग हुन्छ हेर्नुहोस्।","See how location, microphone and alert data are used."));updateOutsideNotice();}'
new_lang='privacySub.setText(t("Location, microphone र alert data कसरी प्रयोग हुन्छ हेर्नुहोस्।","See how location, microphone and alert data are used."));if(newsList!=null&&"knowledge".equals(newsList.getTag()))renderKnowledgeFallback(false);updateOutsideNotice();}'
s=once(s,old_lang,new_lang,'knowledge language refresh')

assert 'V0916_KNOWLEDGE_ROTATION' in s
assert 'V0916_SATHI_DISTRICT_WEATHER' in s
assert 'V0916_KNOWLEDGE_FALLBACK' in s
assert 'districtWeatherAnswer' in s
assert 'current=temperature_2m,relative_humidity_2m,precipitation,cloud_cover,weather_code,wind_speed_10m' in s
assert 'versionCode 33' in g
assert "versionName '0.9.16-sathi-knowledge'" in g
UI.write_text(s,encoding='utf-8')
GRADLE.write_text(g,encoding='utf-8')
print('V0916_SATHI_KNOWLEDGE_PATCHED')
