(()=>{
  const boot=()=>{
    if(document.documentElement.dataset.motionReady==='3') return;
    document.documentElement.dataset.motionReady='3';
    document.body.classList.add('portfolio-v3');

    const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
    const fine=matchMedia('(pointer:fine)').matches;
    const q=(s,r=document)=>r.querySelector(s);
    const qa=(s,r=document)=>[...r.querySelectorAll(s)];

    const style=document.createElement('style');
    style.id='portfolio-motion-v3-style';
    style.textContent=`
      :root{--pv3-blue:#3157d5;--pv3-coral:#e9694d;--pv3-green:#16866a;--pv3-violet:#7057d8;--pv3-teal:#129da0;--pv3-sky:#2d87c8;--pv3-paper:#f2eee6;--pv3-card:#fffdf8;--pv3-ink:#17191d;--pv3-muted:#646b75;--pv3-line:#d2c9bc;--pv3-mono:"SFMono-Regular",Consolas,"Liberation Mono",Menlo,monospace}
      html{scroll-padding-top:92px}body.portfolio-v3{overflow-x:hidden;background:radial-gradient(circle at 8% 4%,rgba(49,87,213,.08),transparent 24rem),radial-gradient(circle at 92% 10%,rgba(233,105,77,.07),transparent 22rem),linear-gradient(rgba(23,25,29,.022) 1px,transparent 1px),linear-gradient(90deg,rgba(23,25,29,.022) 1px,transparent 1px),var(--pv3-paper);background-size:auto,auto,28px 28px,28px 28px,auto}
      body.portfolio-v3:before{content:"";position:fixed;inset:0;pointer-events:none;z-index:120;opacity:.12;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.32'/%3E%3C/svg%3E");mix-blend-mode:multiply}
      .motion-progress{position:fixed;top:0;left:0;width:100%;height:3px;transform:scaleX(0);transform-origin:left center;background:linear-gradient(90deg,var(--pv3-blue),var(--pv3-violet),var(--pv3-coral));z-index:200;pointer-events:none;box-shadow:0 1px 14px rgba(49,87,213,.25)}
      body.portfolio-v3 .nav{top:12px;width:min(1220px,calc(100% - 24px));margin:12px auto 0;border:1px solid rgba(23,25,29,.14);border-radius:20px;background:rgba(250,247,240,.86);box-shadow:0 14px 42px rgba(23,25,29,.08),inset 0 1px 0 rgba(255,255,255,.72);backdrop-filter:blur(18px) saturate(1.15);overflow:visible}
      body.portfolio-v3 .navin{min-height:62px;padding:0 14px}.identity{gap:10px}.mark{position:relative;overflow:hidden;box-shadow:0 0 0 1px rgba(255,255,255,.14) inset,0 6px 16px rgba(23,25,29,.12)}.mark:after{content:"";position:absolute;inset:-50%;background:linear-gradient(115deg,transparent 38%,rgba(255,255,255,.35) 48%,transparent 58%);translate:-70% 0;animation:markSweep 6s ease-in-out infinite}@keyframes markSweep{0%,68%,100%{translate:-70% 0}78%{translate:70% 0}}
      .navlinks{gap:14px}.navlinks a{padding:6px 0;transition:color .2s ease}.navlinks a:after{height:2px;bottom:1px;background:var(--pv3-blue)}.navlinks a.motion-active{color:var(--pv3-ink);font-weight:800}.navlinks a.motion-active:after{right:0}.open-note{background:#f1d66f;box-shadow:2px 3px 0 rgba(23,25,29,.08)}
      body.portfolio-v3 .hero{position:relative;isolation:isolate;overflow:hidden;padding:96px 0 68px}.hero>.wrap{position:relative;z-index:3}.hero-grid{grid-template-columns:minmax(0,1.15fr) minmax(330px,.85fr);gap:54px;align-items:start}.hero:after{content:"";position:absolute;inset:0;z-index:1;pointer-events:none;background:linear-gradient(90deg,rgba(242,238,230,.97) 0%,rgba(242,238,230,.87) 43%,rgba(242,238,230,.55) 70%,rgba(242,238,230,.82) 100%)}
      .cs-network{position:absolute;inset:0;width:100%;height:100%;z-index:0;opacity:.66;pointer-events:none;mix-blend-mode:multiply}.hero .kicker{display:inline-flex;align-items:center;gap:9px;padding:7px 10px;border:1px solid rgba(49,87,213,.22);border-radius:999px;background:rgba(255,253,248,.72);box-shadow:0 8px 24px rgba(49,87,213,.06);animation:fadeUp .6s .03s both}.hero .kicker:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--pv3-blue);box-shadow:0 0 0 5px rgba(49,87,213,.09)}
      h1{font-size:clamp(3.85rem,7.6vw,7rem);line-height:.86;text-wrap:balance}.hero h1{animation:heroIn .85s .08s cubic-bezier(.2,.78,.18,1) both}.hero h1 em{position:relative;text-decoration-thickness:.07em;text-decoration-color:rgba(49,87,213,.17);text-underline-offset:.08em}.hero-copy{font-size:1.08rem;max-width:730px;animation:fadeUp .7s .2s both}.hero-actions{animation:fadeUp .7s .3s both}.btn{min-height:44px;position:relative;overflow:hidden;isolation:isolate;transition:translate .2s ease,box-shadow .2s ease,background .2s ease,color .2s ease}.btn:before{content:"";position:absolute;inset:-2px;z-index:-1;background:linear-gradient(110deg,transparent 35%,rgba(255,255,255,.35) 48%,transparent 62%);translate:-130% 0;transition:translate .55s ease}.btn:hover:before{translate:130% 0}.btn:hover{translate:0 -3px;box-shadow:0 12px 24px rgba(23,25,29,.10)}.btn:active{translate:0 0}
      @keyframes heroIn{from{opacity:0;translate:0 28px;filter:blur(5px)}to{opacity:1;translate:0 0;filter:blur(0)}}@keyframes fadeUp{from{opacity:0;translate:0 16px}to{opacity:1;translate:0 0}}
      .hero-aside{animation:asideIn .9s .18s cubic-bezier(.2,.78,.18,1) both;padding:12px;border:1px solid rgba(23,25,29,.12);border-radius:26px;background:rgba(255,253,248,.60);box-shadow:0 20px 55px rgba(23,25,29,.07);backdrop-filter:blur(8px)}@keyframes asideIn{from{opacity:0;translate:30px 6px;rotate:1deg}to{opacity:1;translate:0 0;rotate:0deg}}
      .board-title{margin:0;padding:6px 5px 13px}.ticket{--ticket-accent:var(--pv3-blue);margin-top:9px;border:1px solid rgba(23,25,29,.16)!important;border-radius:17px!important;box-shadow:none!important;transform:none!important;background:rgba(255,255,255,.84)!important;overflow:hidden;transition:translate .25s ease,box-shadow .25s ease,border-color .25s ease;animation:none!important}.ticket:before{content:"";position:absolute;left:0;top:10px;bottom:10px;width:3px;border-radius:0 4px 4px 0;background:var(--ticket-accent)}.ticket:nth-of-type(3n+1){--ticket-accent:var(--pv3-coral)}.ticket:nth-of-type(3n+2){--ticket-accent:var(--pv3-blue)}.ticket:nth-of-type(3n){--ticket-accent:var(--pv3-green)}.ticket:hover{translate:5px 0;box-shadow:0 10px 24px rgba(23,25,29,.08)!important;border-color:rgba(49,87,213,.32)!important}.ticket h3{font-size:1rem}.ticket p{margin-top:6px}.tag{font-family:var(--pv3-mono);letter-spacing:.035em;background:#f8f6f1}
      .hero-system{margin-top:28px;border:1px solid #202631;border-radius:18px;background:#10151c;color:#dfe8f5;overflow:hidden;box-shadow:0 18px 46px rgba(17,21,27,.16),6px 7px 0 rgba(23,25,29,.08);font-family:var(--pv3-mono);animation:terminalIn .82s .38s cubic-bezier(.2,.78,.18,1) both}@keyframes terminalIn{from{opacity:0;translate:0 14px;clip-path:inset(0 100% 0 0)}to{opacity:1;translate:0 0;clip-path:inset(0 0 0 0)}}
      .hero-system-head{height:38px;display:flex;align-items:center;justify-content:space-between;padding:0 13px;border-bottom:1px solid rgba(255,255,255,.09);background:#171e27;color:#8e9aac;font-size:.67rem;letter-spacing:.08em;text-transform:uppercase}.sys-dots{display:flex;gap:6px}.sys-dots i{width:7px;height:7px;border-radius:50%;background:#e9694d}.sys-dots i:nth-child(2){background:#f2d46e}.sys-dots i:nth-child(3){background:#58c69c}.hero-system-body{padding:15px 16px 16px;min-height:128px;font-size:.76rem;line-height:1.72}.sys-line{display:flex;gap:9px;align-items:flex-start;min-height:1.72em}.sys-prompt{color:#7791ff}.sys-ok{color:#69d9ac}.sys-muted{color:#8390a1}.sys-cursor{width:7px;height:1em;background:#dfe8f5;display:inline-block;vertical-align:-.12em;animation:blink 1s steps(1) infinite}@keyframes blink{50%{opacity:0}}
      .hero-system-foot{padding:8px 16px;border-top:1px solid rgba(255,255,255,.08);display:flex;gap:16px;flex-wrap:wrap;color:#758396;font-size:.64rem}.hero-system-foot b{color:#b7c6d9;font-weight:600}
      .rule-band{margin-top:0;background:rgba(255,253,248,.45);backdrop-filter:blur(5px)}.rule-item{transition:background .22s ease,translate .22s ease}.rule-item:hover{background:rgba(255,255,255,.5);translate:0 -2px}.rule-item strong:before{content:"// ";color:var(--pv3-blue);font-family:var(--pv3-mono);font-weight:700}
      .cs-stack{border-bottom:1px solid var(--pv3-line);overflow:hidden;background:rgba(255,253,248,.35);position:relative}.cs-stack:before,.cs-stack:after{content:"";position:absolute;top:0;bottom:0;width:84px;z-index:3;pointer-events:none}.cs-stack:before{left:0;background:linear-gradient(90deg,var(--pv3-paper),transparent)}.cs-stack:after{right:0;background:linear-gradient(270deg,var(--pv3-paper),transparent)}.cs-stack-track{display:flex;width:max-content;animation:marquee 28s linear infinite}.cs-stack-item{white-space:nowrap;padding:12px 22px;border-right:1px solid var(--pv3-line);font:700 .69rem/1 var(--pv3-mono);letter-spacing:.08em;text-transform:uppercase;color:#59616d}.cs-stack-item b{color:var(--pv3-blue);margin-right:8px}@keyframes marquee{to{translate:-50% 0}}
      section{position:relative}.section-head{margin-bottom:28px}.section-number{color:#a9a091;transition:color .28s ease,translate .28s ease}.section-head:hover .section-number{color:var(--pv3-coral);translate:4px -2px}.section-title h2{text-wrap:balance}.section-title p{font-size:1rem}.cs-pipeline{display:flex;align-items:center;gap:10px;overflow:auto;scrollbar-width:none;padding:13px 0 16px;margin:-6px 0 28px;border-bottom:1px dashed #bdb4a6;font-family:var(--pv3-mono)}.cs-pipeline::-webkit-scrollbar{display:none}.cs-node{display:flex;align-items:center;gap:8px;white-space:nowrap;font-size:.69rem;letter-spacing:.075em;text-transform:uppercase}.cs-node i{width:9px;height:9px;border:1px solid var(--pv3-ink);background:var(--pv3-paper)}.cs-node.active i{background:var(--pv3-blue);box-shadow:0 0 0 4px rgba(49,87,213,.09)}.cs-arrow{color:#93897c;animation:arrow 1.7s ease-in-out infinite}@keyframes arrow{0%,100%{opacity:.35;translate:-2px 0}50%{opacity:1;translate:2px 0}}
      body.portfolio-v3 .project{--project-accent:var(--pv3-blue);position:relative;margin:0 0 24px;padding:28px;border:1px solid rgba(23,25,29,.14);border-radius:28px;background:linear-gradient(145deg,rgba(255,253,248,.93),rgba(255,255,255,.70));box-shadow:0 16px 48px rgba(23,25,29,.055);overflow:hidden;transition:translate .28s ease,box-shadow .28s ease,border-color .28s ease}.project:before{content:"";position:absolute;left:0;top:0;bottom:0;width:5px;background:linear-gradient(180deg,var(--project-accent),color-mix(in srgb,var(--project-accent) 35%,transparent));opacity:.9}.project:after{content:"";position:absolute;width:230px;height:230px;border-radius:50%;right:-90px;top:-120px;background:radial-gradient(circle,color-mix(in srgb,var(--project-accent) 15%,transparent),transparent 68%);pointer-events:none}.project:hover{translate:0 -5px;box-shadow:0 24px 68px rgba(23,25,29,.085);border-color:color-mix(in srgb,var(--project-accent) 38%,#d1c9bd)}
      #teamtracker{--project-accent:var(--pv3-blue)}#fixcheck{--project-accent:var(--pv3-violet)}#datemate{--project-accent:var(--pv3-teal)}#floodsafe{--project-accent:var(--pv3-sky)}#lifeos{--project-accent:var(--pv3-green)}#sathi-ai{--project-accent:var(--pv3-coral)}
      .project-side{min-height:320px}.project-index{font-family:var(--pv3-mono);font-size:.72rem;text-transform:uppercase;letter-spacing:.08em;color:#80786f}.project-side h3{font-size:2.2rem;transition:color .22s ease,translate .22s ease}.project:hover .project-side h3{color:var(--project-accent);translate:4px 0}.project-status{border:1px solid rgba(23,25,29,.12);border-radius:999px;background:rgba(255,255,255,.64);padding:7px 9px;width:max-content;max-width:100%}.dot{animation:pulse 2.1s ease-in-out infinite}@keyframes pulse{50%{box-shadow:0 0 0 6px rgba(31,158,116,.10)}}
      .project-main{gap:26px}.project-copy>p{font-size:.98rem;line-height:1.7}.bullets{gap:8px}.bullet{grid-template-columns:27px 1fr;gap:9px;padding:8px 0;border-bottom:1px solid rgba(23,25,29,.07)}.bullet:last-child{border-bottom:0}.bullet i{font:700 .66rem/1.7 var(--pv3-mono);color:var(--project-accent)}
      .cs-project-meta{display:flex;flex-wrap:wrap;gap:7px;margin-top:18px}.cs-chip{font:700 .62rem/1 var(--pv3-mono);letter-spacing:.04em;padding:6px 8px;border:1px solid color-mix(in srgb,var(--project-accent) 25%,#cfc7bb);border-radius:999px;background:rgba(255,255,255,.72);color:#59616b}.cs-chip:before{content:"<";color:var(--project-accent)}.cs-chip:after{content:"/>";color:var(--project-accent)}
      .side-links a{position:relative;border:0;padding:7px 0;font-size:.81rem}.side-links a:after{content:"";position:absolute;left:0;right:100%;bottom:2px;height:1px;background:var(--project-accent);transition:right .22s ease}.side-links a:hover{color:var(--project-accent)}.side-links a:hover:after{right:0}
      .preview,.sathi-preview{border-radius:21px!important;border:1px solid rgba(23,25,29,.16)!important;box-shadow:0 12px 30px rgba(23,25,29,.07)!important;overflow:hidden;transform:perspective(1050px) rotateX(var(--tilt-x,0deg)) rotateY(var(--tilt-y,0deg));transform-style:preserve-3d;transition:transform .18s ease,box-shadow .28s ease,translate .28s ease;will-change:transform}.project:hover .preview,.project:hover .sathi-preview{translate:0 -3px;box-shadow:0 18px 42px rgba(23,25,29,.10)!important}.windowbar{padding:4px 4px 11px}.ui-box{border-radius:14px}.map{border-radius:10px;overflow:hidden}.phone{border-radius:29px;box-shadow:0 12px 22px rgba(23,25,29,.08)}.phone-screen{border-radius:19px}.big-action{transition:scale .2s ease,filter .2s ease}.preview:hover .big-action{scale:1.015}.cs-preview-label{position:absolute;right:12px;bottom:10px;z-index:4;border:1px solid rgba(23,25,29,.12);border-radius:999px;background:rgba(255,253,248,.86);backdrop-filter:blur(8px);padding:5px 7px;font:700 .56rem/1 var(--pv3-mono);letter-spacing:.07em;text-transform:uppercase;color:#6b737e;pointer-events:none}
      .screens{margin-top:18px}.screens-head{border-top:1px solid rgba(23,25,29,.12);padding-top:20px}.shot-grid{gap:16px}.shot-card{border-radius:18px;overflow:hidden;border-color:rgba(23,25,29,.14);box-shadow:0 10px 28px rgba(23,25,29,.055);transition:translate .24s ease,box-shadow .24s ease,border-color .24s ease}.shot-card:hover{translate:0 -5px;transform:none;box-shadow:0 18px 36px rgba(23,25,29,.09);border-color:color-mix(in srgb,var(--project-accent) 30%,#cbc2b6)}.shot-card img{border-radius:11px;background:#eef2f4}.shot-card figcaption{padding:9px 4px 3px}
      .note-grid{gap:16px}.note-big{border-radius:28px;background:linear-gradient(135deg,#253f9d,#3157d5 55%,#5b6edb);box-shadow:0 18px 46px rgba(49,87,213,.15);position:relative;overflow:hidden}.note-big:after{content:"";position:absolute;width:180px;height:180px;border-radius:50%;right:-60px;top:-70px;border:1px solid rgba(255,255,255,.18);box-shadow:0 0 0 34px rgba(255,255,255,.035),0 0 0 68px rgba(255,255,255,.025)}.note-small{border-radius:18px;box-shadow:0 10px 26px rgba(23,25,29,.045)}
      .about-grid{border-top:0;padding-top:0;gap:20px}.about-card{border-radius:22px;transform:none;box-shadow:0 14px 34px rgba(23,25,29,.07);transition:translate .25s ease,rotate .25s ease,box-shadow .25s ease}.about-card:hover{translate:0 -4px;rotate:-.25deg;box-shadow:0 20px 42px rgba(23,25,29,.09)}.about-copy{background:rgba(255,253,248,.52);border:1px solid rgba(23,25,29,.10);border-radius:22px;padding:24px}
      footer{padding-top:84px}.foot{border-top:1px solid rgba(23,25,29,.18);padding:22px 4px 0}
      .motion-reveal{opacity:0;translate:0 24px;filter:blur(3px);transition:opacity .72s cubic-bezier(.2,.72,.2,1),translate .72s cubic-bezier(.2,.72,.2,1),filter .72s ease}.motion-reveal.is-visible{opacity:1;translate:0 0;filter:blur(0)}.motion-reveal[data-delay="1"]{transition-delay:.05s}.motion-reveal[data-delay="2"]{transition-delay:.10s}.motion-reveal[data-delay="3"]{transition-delay:.15s}.motion-reveal[data-delay="4"]{transition-delay:.20s}
      .project-rail{position:fixed;right:14px;top:50%;translate:0 -50%;z-index:80;display:flex;flex-direction:column;gap:7px;padding:8px;border:1px solid rgba(23,25,29,.12);border-radius:999px;background:rgba(250,247,240,.78);backdrop-filter:blur(12px);box-shadow:0 12px 34px rgba(23,25,29,.07)}.project-rail a{position:relative;width:10px;height:10px;border-radius:50%;background:#aaa398;transition:scale .2s ease,background .2s ease}.project-rail a.active{background:var(--rail-accent,var(--pv3-blue));scale:1.35}.project-rail a span{position:absolute;right:18px;top:50%;translate:6px -50%;opacity:0;pointer-events:none;white-space:nowrap;padding:5px 8px;border-radius:8px;background:#17191d;color:#fff;font:700 .62rem/1 var(--pv3-mono);transition:.2s}.project-rail a:hover span{opacity:1;translate:0 -50%}
      .motion-orb{position:fixed;z-index:-1;width:320px;height:320px;border-radius:50%;pointer-events:none;opacity:.10;filter:blur(12px);background:radial-gradient(circle,rgba(49,87,213,.45),rgba(233,105,77,.12) 48%,transparent 70%);translate:-50% -50%;left:50%;top:30%}.scroll-cue{display:inline-flex;align-items:center;gap:8px;margin-top:16px;color:#6d746f;font:700 .65rem/1 var(--pv3-mono);letter-spacing:.08em;text-transform:uppercase}.scroll-cue i{width:26px;height:1px;background:#8c8478;position:relative;overflow:hidden}.scroll-cue i:after{content:"";position:absolute;inset:0;background:var(--pv3-blue);translate:-100% 0;animation:cue 1.9s ease-in-out infinite}@keyframes cue{50%,100%{translate:100% 0}}
      @media(max-width:1180px){.project-rail{display:none}.hero-grid{gap:36px}.navlinks{gap:10px;font-size:.82rem}}
      @media(max-width:950px){body.portfolio-v3 .nav{top:6px;margin-top:6px;border-radius:16px}.hero-grid{grid-template-columns:1fr}.hero-aside{max-width:none}.project{grid-template-columns:1fr!important}.project-side{min-height:auto}.project-main{grid-template-columns:1fr}.cs-network{opacity:.40}.hero:after{background:rgba(242,238,230,.82)}.shot-grid.flood{grid-template-columns:repeat(2,minmax(0,1fr))}}
      @media(max-width:700px){body.portfolio-v3 .hero{padding:64px 0 48px}h1{font-size:clamp(3.25rem,16vw,4.4rem)}.hero-aside{padding:9px;border-radius:20px}.ticket{border-radius:14px!important}.hero-system{border-radius:14px}.hero-system-body{font-size:.69rem;min-height:116px}.hero-system-foot{display:none}.project{padding:20px!important;border-radius:22px!important}.project-side h3{font-size:2rem}.preview,.sathi-preview{transform:none!important;border-radius:17px!important}.motion-orb{display:none}.motion-reveal{translate:0 15px}.cs-stack-item{padding:11px 16px}.shot-grid,.shot-grid.flood{grid-template-columns:1fr}.shot-card.poster{grid-column:auto}.about-copy{padding:19px}.scroll-cue{display:none}}
      @media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}.motion-reveal{opacity:1!important;translate:0 0!important;filter:none!important}.cs-network,.motion-orb,.motion-progress{display:none!important}.preview,.sathi-preview{transform:none!important}.cs-stack-track{animation:none!important}}
    `;
    document.head.appendChild(style);

    const progress=document.createElement('div');progress.className='motion-progress';progress.setAttribute('aria-hidden','true');document.body.appendChild(progress);
    const setProgress=()=>{const d=document.documentElement;const max=Math.max(1,d.scrollHeight-innerHeight);progress.style.transform=`scaleX(${Math.min(1,Math.max(0,scrollY/max))})`};setProgress();addEventListener('scroll',setProgress,{passive:true});addEventListener('resize',setProgress,{passive:true});

    const hero=q('.hero');
    if(hero && !q('.cs-network',hero)){
      const canvas=document.createElement('canvas');canvas.className='cs-network';canvas.setAttribute('aria-hidden','true');hero.prepend(canvas);
      if(!reduce){const ctx=canvas.getContext('2d');let w=1,h=1,dpr=1,raf=0,t=0,running=true;const nodes=[[.04,.20],[.12,.70],[.24,.42],[.35,.78],[.47,.19],[.57,.52],[.68,.16],[.77,.70],[.90,.34],[.88,.82],[.38,.10],[.62,.88],[.96,.60]];const edges=[[0,2],[1,2],[2,3],[2,4],[2,5],[4,5],[4,6],[5,7],[5,11],[6,8],[7,8],[7,9],[8,12],[3,11],[10,4],[6,10]];const resize=()=>{const r=hero.getBoundingClientRect();dpr=Math.min(2,devicePixelRatio||1);w=Math.max(1,r.width);h=Math.max(1,r.height);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)};const draw=()=>{if(!running)return;t+=.007;ctx.clearRect(0,0,w,h);edges.forEach((e,i)=>{const a=nodes[e[0]],b=nodes[e[1]],ax=a[0]*w,ay=a[1]*h,bx=b[0]*w,by=b[1]*h;ctx.strokeStyle=i%4===0?'rgba(49,87,213,.28)':'rgba(23,25,29,.12)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke();const p=(t+i*.071)%1,px=ax+(bx-ax)*p,py=ay+(by-ay)*p;ctx.fillStyle=i%3===0?'rgba(49,87,213,.78)':'rgba(233,105,77,.55)';ctx.beginPath();ctx.arc(px,py,2.15,0,Math.PI*2);ctx.fill()});nodes.forEach((n,i)=>{const x=n[0]*w,y=n[1]*h;ctx.fillStyle=i%5===0?'#3157d5':'rgba(255,253,248,.95)';ctx.strokeStyle='rgba(23,25,29,.38)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,i%5===0?4.2:3.1,0,Math.PI*2);ctx.fill();ctx.stroke()});raf=requestAnimationFrame(draw)};resize();draw();addEventListener('resize',resize,{passive:true});document.addEventListener('visibilitychange',()=>{running=!document.hidden;if(running){cancelAnimationFrame(raf);draw()}else cancelAnimationFrame(raf)})}
    }

    const actions=q('.hero-actions');
    if(actions && !q('.hero-system')){const term=document.createElement('div');term.className='hero-system';term.innerHTML=`<div class="hero-system-head"><span class="sys-dots"><i></i><i></i><i></i></span><span>pujan@portfolio / build</span><span>live</span></div><div class="hero-system-body"><div class="sys-line"><span class="sys-prompt">$</span><span id="pv3-command"></span><span class="sys-cursor"></span></div><div id="pv3-output"></div></div><div class="hero-system-foot"><span><b>01</b> problem</span><span><b>02</b> system</span><span><b>03</b> interface</span><span><b>04</b> test</span><span><b>05</b> refine</span></div>`;actions.insertAdjacentElement('afterend',term);const sequences=[['portfolio.inspect --projects','6 curated builds · product-first · hands-on iteration'],['system.check --focus','clear workflows · useful feedback · reliable updates'],['build.next --mode=practical','turn real friction into a testable software flow']];let si=0,ci=0,to=0;const command=q('#pv3-command'),out=q('#pv3-output');const run=()=>{if(!command||!out)return;const [cmd,res]=sequences[si];command.textContent=cmd.slice(0,ci++);if(ci<=cmd.length){to=setTimeout(run,28);return}out.innerHTML=`<div class="sys-line"><span class="sys-ok">✓</span><span>${res}</span></div><div class="sys-line"><span class="sys-muted">→</span><span class="sys-muted">ready for the next useful version</span></div>`;to=setTimeout(()=>{si=(si+1)%sequences.length;ci=0;command.textContent='';out.textContent='';run()},2600)};if(reduce){command.textContent=sequences[0][0];out.innerHTML=`<div class="sys-line"><span class="sys-ok">✓</span><span>${sequences[0][1]}</span></div>`}else run();addEventListener('pagehide',()=>clearTimeout(to),{once:true});const cue=document.createElement('div');cue.className='scroll-cue';cue.innerHTML='<i></i><span>scroll to selected work</span>';term.insertAdjacentElement('afterend',cue)}

    const rule=q('.rule-band');if(rule && !q('.cs-stack')){const stack=document.createElement('div');stack.className='cs-stack';const items=['JavaScript','Android','Java','GitHub Actions','API integration','Responsive UI','Realtime UX','Testing','System design','Accessibility'];const row=items.map((x,i)=>`<span class="cs-stack-item"><b>${String(i+1).padStart(2,'0')}</b>${x}</span>`).join('');stack.innerHTML=`<div class="cs-stack-track">${row}${row}</div>`;rule.insertAdjacentElement('afterend',stack)}
    const work=q('#work .wrap');if(work && !q('.cs-pipeline',work)){const head=q('.section-head',work);const pipe=document.createElement('div');pipe.className='cs-pipeline';pipe.innerHTML='<span class="cs-node active"><i></i>Problem</span><span class="cs-arrow">→</span><span class="cs-node"><i></i>System</span><span class="cs-arrow">→</span><span class="cs-node"><i></i>Interface</span><span class="cs-arrow">→</span><span class="cs-node"><i></i>Test</span><span class="cs-arrow">→</span><span class="cs-node"><i></i>Refine</span>';if(head)head.insertAdjacentElement('afterend',pipe);else work.prepend(pipe)}

    const projectTags={teamtracker:['workflow','realtime','responsive'],fixcheck:['network','diagnostics','web'],datemate:['android','camera','reminders'],floodsafe:['map','river-data','alerts'],lifeos:['finance','automation','dashboard'],'sathi-ai':['assistant','background','prototype']};
    const labels={teamtracker:'TEAM / FLOW',fixcheck:'NETWORK / DIAG',datemate:'ANDROID / EXPIRY',floodsafe:'NEPAL / SAFETY',lifeos:'FINANCE / SYSTEM','sathi-ai':'COMPANION / PROTOTYPE'};
    const enhanceProjects=()=>{qa('.project').forEach((p,pi)=>{if(!p.dataset.motionEnhanced){p.dataset.motionEnhanced='1';p.classList.add('motion-reveal');p.dataset.delay=String(pi%3);const copy=q('.project-copy',p);if(copy&&!q('.cs-project-meta',copy)){const m=document.createElement('div');m.className='cs-project-meta';(projectTags[p.id]||['build','test','refine']).forEach(t=>{const s=document.createElement('span');s.className='cs-chip';s.textContent=t;m.appendChild(s)});copy.appendChild(m)}const prev=q('.preview,.sathi-preview',p);if(prev&&!q('.cs-preview-label',prev)){const l=document.createElement('span');l.className='cs-preview-label';l.textContent=labels[p.id]||'PRODUCT / BUILD';prev.appendChild(l)}}})};enhanceProjects();

    const cleanupPresentation=()=>{const workNumber=q('#work .section-number');if(workNumber)workNumber.textContent=String(qa('#work .project').length||6).padStart(2,'0');const lifeAction=qa('.hero-actions a').find(a=>(a.getAttribute('href')||'')==='#lifeos' && /DateMate/i.test(a.textContent||''));if(lifeAction)lifeAction.setAttribute('href','#datemate');const flood=q('#floodsafe');if(flood){const bullet=qa('.bullet span',flood).find(x=>/Human-impact|मानवीय प्रभाव/i.test(x.textContent||''));if(bullet)bullet.textContent=/मानवीय/.test(bullet.textContent||'')?'विपद् स्थिति, स्थानीय सतर्कता र नेपाल समाचार एउटै सुरक्षा अनुभवमा।':'Disaster status, local alerts and Nepal news in the same safety experience.';qa('.shot-card',flood).forEach(card=>{const img=q('img',card);if(img && /floodsafe-human\.svg/i.test(img.getAttribute('src')||''))card.style.display='none'});const sh=q('.screens-head span',flood);if(sh)sh.textContent=/स्क्रिन/.test(sh.textContent||'')?'FloodSafe Nepal का ५ स्क्रिन':'5 FloodSafe Nepal screens'}const heroCopy=q('.hero-copy');if(heroCopy && /^Five real projects/i.test((heroCopy.textContent||'').trim()))heroCopy.textContent='Six real projects are currently in the portfolio: Team Tracker, FixCheck, DateMate, FloodSafe Nepal, LifeOS AI and SATHI AI. Each one is shown at its real current stage, from working products to active prototypes.';if(heroCopy && /^पोर्टफोलियोमा अहिले पाँच वास्तविक/i.test((heroCopy.textContent||'').trim()))heroCopy.textContent='पोर्टफोलियोमा अहिले छ वटा वास्तविक प्रोजेक्ट छन्: Team Tracker, FixCheck, DateMate, FloodSafe Nepal, LifeOS AI र SATHI AI। हरेक प्रोजेक्टलाई यसको वास्तविक हालको अवस्थामै देखाइएको छ।'};

    let revealObserver=null;const observeReveal=()=>{if(reduce){qa('.motion-reveal').forEach(el=>el.classList.add('is-visible'));return}if(!revealObserver)revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');revealObserver.unobserve(e.target)}}),{threshold:.11,rootMargin:'0px 0px -5% 0px'});qa('.section-head,.note-grid,.about-grid,.screens,.motion-reveal').forEach((el,i)=>{if(!el.classList.contains('motion-reveal')){el.classList.add('motion-reveal');el.dataset.delay=String(i%3)}if(!el.classList.contains('is-visible'))revealObserver.observe(el)})};observeReveal();

    if(fine&&!reduce){qa('.preview,.sathi-preview').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.setProperty('--tilt-y',`${x*4.2}deg`);el.style.setProperty('--tilt-x',`${y*-3.2}deg`)});el.addEventListener('pointerleave',()=>{el.style.setProperty('--tilt-y','0deg');el.style.setProperty('--tilt-x','0deg')})});const orb=document.createElement('div');orb.className='motion-orb';orb.setAttribute('aria-hidden','true');document.body.appendChild(orb);let ox=innerWidth/2,oy=innerHeight*.3,tx=ox,ty=oy,oraf=0;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY},{passive:true});const move=()=>{ox+=(tx-ox)*.08;oy+=(ty-oy)*.08;orb.style.left=ox+'px';orb.style.top=oy+'px';oraf=requestAnimationFrame(move)};move();addEventListener('pagehide',()=>cancelAnimationFrame(oraf),{once:true})}

    let rail=q('.project-rail');const syncRail=()=>{const projects=qa('#work .project');if(!projects.length)return;if(!rail){rail=document.createElement('nav');rail.className='project-rail';rail.setAttribute('aria-label','Project quick navigation');document.body.appendChild(rail)}const key=projects.map(p=>p.id).join('|');if(rail.dataset.key===key)return;rail.dataset.key=key;rail.innerHTML='';projects.forEach((p,i)=>{const a=document.createElement('a');a.href='#'+p.id;a.style.setProperty('--rail-accent',getComputedStyle(p).getPropertyValue('--project-accent')||'#3157d5');const name=q('.project-side h3',p)?.textContent?.trim()||`Project ${i+1}`;a.innerHTML=`<span>${String(i+1).padStart(2,'0')} · ${name}</span>`;rail.appendChild(a)})};syncRail();
    let activeObserver=null;const observeActive=()=>{if(activeObserver)activeObserver.disconnect();const projects=qa('#work .project');activeObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(!e.isIntersecting)return;const id=e.target.id;qa('.project-rail a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));qa('.navlinks a').forEach(a=>a.classList.toggle('motion-active',a.getAttribute('href')==='#'+id))})},{threshold:.35,rootMargin:'-15% 0px -45%'});projects.forEach(p=>activeObserver.observe(p))};observeActive();

    cleanupPresentation();setTimeout(()=>{enhanceProjects();cleanupPresentation();syncRail();observeReveal();observeActive()},0);setTimeout(()=>{enhanceProjects();cleanupPresentation();syncRail();observeReveal();observeActive()},180);
    const mo=new MutationObserver(()=>{enhanceProjects();cleanupPresentation();syncRail();observeReveal();observeActive()});const workRoot=q('#work');if(workRoot)mo.observe(workRoot,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('.lang-switch'))setTimeout(()=>{cleanupPresentation();syncRail()},0)});
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();