(()=>{
'use strict';
const API='https://bipadportal.gov.np/api/v1/';
const POLL=5000;
const state={lang:localStorage.getItem('fs23-lang')||'ne',focus:null,river:[],rain:[],alerts:[],roads:[],bulletins:[],lastCheck:null,busy:false,timers:[],impactLayer:null};
const $=id=>document.getElementById(id);
const txt=(ne,en)=>state.lang==='en'?en:ne;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const rows=j=>Array.isArray(j)?j:(j?.results||j?.data||[]);
const coord=o=>{const c=o?.point?.coordinates||o?.location?.coordinates;return Array.isArray(c)&&c.length>=2?[+c[1],+c[0]]:null};
const km=(a,b)=>{if(!a||!b)return Infinity;const R=6371,p=Math.PI/180,d1=(b[0]-a[0])*p,d2=(b[1]-a[1])*p,s=Math.sin(d1/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(s))};
const when=o=>o?.waterLevelOn||o?.measuredOn||o?.modifiedOn||o?.createdOn||o?.recordedDate||null;
const age=d=>{if(!d)return '—';const s=Math.max(0,Math.floor((Date.now()-new Date(d))/1000));if(s<60)return s+'s';if(s<3600)return Math.floor(s/60)+'m';if(s<86400)return Math.floor(s/3600)+'h';return Math.floor(s/86400)+'d'};
async function get(url,ms=11000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
function focus(){const f=window.__fs?.getFocus?.();return Array.isArray(f)?f:state.focus}
function stage(r){const wl=num(r.waterLevel),w=num(r.warningLevel),d=num(r.dangerLevel),st=String(r.status||'').toUpperCase(),trend=String(r.steady||'').toUpperCase();if((d!==null&&wl!==null&&wl>=d)||st.includes('DANGER'))return['danger',txt('खतरा','Danger')];if((w!==null&&wl!==null&&wl>=w)||st.includes('ABOVE WARNING'))return['warning',txt('चेतावनी','Warning')];if(trend==='RISING'||(w!==null&&wl!==null&&wl>=w*.8))return['rising',txt('बढ्दो','Rising')];return['normal',txt('सामान्य','Normal')]}
function fmtTime(d){if(!d)return '—';try{return new Date(d).toLocaleString(state.lang==='ne'?'ne-NP':'en-GB',{timeZone:'Asia/Kathmandu',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'})}catch{return '—'}}

function injectTheme(){
 const style=document.createElement('style');style.id='fs23style';style.textContent=`
:root{--bg:#120e0d!important;--panel:#211714!important;--card:#281c18!important;--line:#5c3b31!important;--text:#fffaf2!important;--muted:#d0bfb5!important;--gold:#f0b64b!important;--red:#dc143c!important;--blue:#003893!important;--green:#36d18d!important;--orange:#f29b38!important;--cyan:#67cfe8!important}
html,body{background:#100c0b!important;color:#fffaf2!important}.side{background:linear-gradient(180deg,#2b1718 0%,#17100f 52%,#100c0b 100%)!important;border-right:1px solid #6e4035!important}.box,.panel,.hero,.weather,.fs23panel{background:linear-gradient(145deg,#241815,#191210)!important;border:1px solid #634238!important;box-shadow:0 10px 28px #0005}.hero{box-shadow:inset 5px 0 0 #dc143c,0 10px 28px #0005!important}.stat,.mini,.item,.fs23cell,.fs23station{background:#17100f!important;border-color:#51362e!important}.btn{background:#261713!important;border-color:#795246!important}.btn.red{background:#dc143c!important}.btn.gold{background:#f0b64b!important;color:#21120f!important}.controls select,.districtRow select{background:#17100f!important;border-color:#6a473b!important}.mapBadge,.mapBtns,.legend,.rainStamp{background:#17100fe8!important;border-color:#6c493d!important}.mapBtns button{background:#241815!important;border-color:#745043!important}.mapBtns button.on{background:#7d241f!important;border-color:#f0b64b!important}.leaflet-tile{filter:saturate(1.12) contrast(1.04) brightness(.98)}
.flag{background:transparent!important;box-shadow:none!important;width:58px!important;height:58px!important}.flag img{display:none!important}.fs23logo{width:58px;height:58px;filter:drop-shadow(0 3px 8px #0008)}.brand h1{font-size:25px!important;color:#fff8e8}.brand p{color:#f0b64b!important}.row2{display:none!important}.weather{display:none!important}.live{display:none!important}
.fs23top{display:grid;grid-template-columns:1.1fr 1fr .9fr;gap:7px;margin-top:11px}.fs23top>div{background:#17100f;border:1px solid #614138;border-radius:12px;padding:9px}.fs23top small{color:#cdb9ad;font-size:9px}.fs23top b{display:block;margin-top:3px;font-size:14px}.fs23live{color:#72e7ad}.fs23bar{display:flex;gap:6px;margin-top:8px;align-items:center}.fs23lang{border:1px solid #7b5144;background:#211512;color:#fff;border-radius:9px;padding:7px 10px;font-weight:850;cursor:pointer}.fs23lang.on{background:#dc143c;border-color:#ff6c82}.fs23pill{font-size:9px;border-radius:99px;padding:5px 8px;background:#6a4b19;color:#ffe7a3;font-weight:900}.fs23panel{margin-top:9px;padding:11px;border-radius:14px}.fs23head{display:flex;align-items:center;justify-content:space-between;gap:7px}.fs23head h3{margin:0;font-size:14px}.fs23grid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:8px}.fs23cell{border:1px solid #51362e;border-radius:10px;padding:8px}.fs23cell small{font-size:9px;color:#c6b3aa}.fs23cell b{display:block;margin-top:3px;font-size:13px}.fs23station{border:1px solid #51362e;border-radius:10px;padding:8px;margin-top:6px}.fs23stationTop{display:flex;justify-content:space-between;gap:8px}.fs23stage{font-size:8.5px;border-radius:99px;padding:4px 7px;font-weight:900}.fs23stage.normal{background:#164c39;color:#b9f0d4}.fs23stage.rising{background:#725816;color:#ffe69b}.fs23stage.warning{background:#7c4618;color:#ffe0ad}.fs23stage.danger{background:#791f31;color:#ffd5dc}.fs23meta{font-size:9.5px;color:#c7b8b0;margin-top:4px;line-height:1.45}.fs23note{font-size:9.5px;line-height:1.45;color:#c7b8b0;margin-top:7px}.fs23weatherHero{border-left:4px solid #f0b64b!important}.fs23impact{border-left:4px solid #dc143c!important}.fs23mount{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin-top:7px}.fs23maptag{position:absolute;z-index:1100;left:50%;top:86px;transform:translateX(-50%);background:#17100fe8;border:1px solid #f0b64b;color:#fff8e8;border-radius:10px;padding:7px 10px;font-size:10px;font-weight:800;pointer-events:none}.fs23pulse{animation:fs23pulse 1.55s infinite}@keyframes fs23pulse{50%{stroke-width:5;fill-opacity:.3}}
@media(max-width:900px){.fs23top{grid-template-columns:1fr 1fr}.fs23top>div:last-child{grid-column:1/-1}.fs23grid{grid-template-columns:repeat(2,1fr)}.fs23mount{grid-template-columns:1fr}.fs23maptag{top:74px;max-width:70%;text-align:center}}
`;document.head.appendChild(style);
 const flag=document.querySelector('.flag');if(flag){flag.innerHTML=`<svg class="fs23logo" viewBox="0 0 64 64" aria-label="FloodSafe Nepal logo"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#dc143c"/><stop offset="1" stop-color="#8f102a"/></linearGradient></defs><path d="M10 5h32L28 21h20L29 37h23L31 57H10z" fill="url(#g)" stroke="#f6e6c0" stroke-width="2.4"/><path d="M16 42c7-5 12 5 19 0s11 5 18 0" fill="none" stroke="#f0b64b" stroke-width="3.2" stroke-linecap="round"/><path d="M21 16l6 3-6 3m10-7v9" fill="none" stroke="#fff" stroke-width="2.4" stroke-linecap="round"/><circle cx="50" cy="12" r="5" fill="#003893" stroke="#f6e6c0" stroke-width="2"/><path d="M48 12h4M50 10v4" stroke="#fff" stroke-width="1.5"/></svg>`}
 const brand=document.querySelector('.brand');if(brand&&!$('fs23bar')){const bar=document.createElement('div');bar.id='fs23bar';bar.className='fs23bar';bar.innerHTML='<button class="fs23lang" data-l="ne">नेपाली</button><button class="fs23lang" data-l="en">English</button><span class="fs23pill">🇳🇵 V24 LIVE</span>';brand.insertAdjacentElement('afterend',bar);bar.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.lang=b.dataset.l;localStorage.setItem('fs23-lang',state.lang);translate();renderAll()})}
 if(!$('fs23top')){const top=document.createElement('div');top.id='fs23top';top.className='fs23top';top.innerHTML='<div><small data-ne="नेपाल समय" data-en="Nepal time">नेपाल समय</small><b id="fs23time">--:--:--</b></div><div><small data-ne="आजको मिति" data-en="Today">आजको मिति</small><b id="fs23date">—</b></div><div><small data-ne="आधिकारिक फिड" data-en="Official feeds">आधिकारिक फिड</small><b id="fs23check" class="fs23live">जाँच हुँदैछ…</b></div>';document.getElementById('fs23bar')?.insertAdjacentElement('afterend',top)}
}
function translate(){document.documentElement.lang=state.lang;document.querySelectorAll('[data-ne]').forEach(el=>el.textContent=state.lang==='en'?el.dataset.en:el.dataset.ne);document.querySelectorAll('.fs23lang').forEach(b=>b.classList.toggle('on',b.dataset.l===state.lang));}
function tick(){const n=new Date();$('fs23time')&&($('fs23time').textContent=n.toLocaleTimeString(state.lang==='ne'?'ne-NP':'en-GB',{timeZone:'Asia/Kathmandu',hour12:false}));$('fs23date')&&($('fs23date').textContent=n.toLocaleDateString(state.lang==='ne'?'ne-NP':'en-GB',{timeZone:'Asia/Kathmandu',weekday:'short',day:'numeric',month:'short',year:'numeric'}));if(state.lastCheck&&$('fs23check'))$('fs23check').textContent=txt('५ से. जाँच • '+age(state.lastCheck),'5s check • '+age(state.lastCheck));}

function injectPanels(){
 const hero=document.querySelector('.hero');if(hero&&!$('fs23weather')){const p=document.createElement('section');p.id='fs23weather';p.className='fs23panel fs23weatherHero';p.innerHTML='<div class="fs23head"><h3 data-ne="🌦 आजको मौसम • आधिकारिक अवलोकन" data-en="🌦 Today weather • official observation">🌦 आजको मौसम • आधिकारिक अवलोकन</h3><span class="fs23pill" id="fs23wxsrc">DHM</span></div><div class="fs23grid"><div class="fs23cell"><small data-ne="नजिकको AWS/वर्षा स्टेशन" data-en="Nearest AWS/rain station">नजिकको AWS/वर्षा स्टेशन</small><b id="fs23wxstation">स्थान अनुमति दिनुहोस्</b></div><div class="fs23cell"><small data-ne="१ घण्टा वर्षा" data-en="1h rain">१ घण्टा वर्षा</small><b id="fs23r1">—</b></div><div class="fs23cell"><small data-ne="६ घण्टा वर्षा" data-en="6h rain">६ घण्टा वर्षा</small><b id="fs23r6">—</b></div><div class="fs23cell"><small data-ne="२४ घण्टा वर्षा" data-en="24h rain">२४ घण्टा वर्षा</small><b id="fs23r24">—</b></div></div><div class="fs23note" id="fs23wxnote">GPS अनुमति वा नक्सामा स्थान छानेपछि नजिकको DHM स्टेशनको आजको अवलोकन देखिन्छ। पुरानो BIPAD weather recordलाई आजको मौसम भनेर प्रयोग गरिँदैन।</div>';hero.insertAdjacentElement('beforebegin',p)}
 const stats=document.querySelector('.stats');if(stats&&!$('fs23river')){const p=document.createElement('section');p.id='fs23river';p.className='fs23panel';p.innerHTML='<div class="fs23head"><h3 data-ne="🌊 नजिकका DHM नदी स्टेशन" data-en="🌊 Nearby DHM river stations">🌊 नजिकका DHM नदी स्टेशन</h3><span class="fs23pill" id="fs23riverAge">—</span></div><div id="fs23riverList"></div>';stats.insertAdjacentElement('afterend',p)}
 const roadPanel=[...document.querySelectorAll('.panel')].find(x=>/सडक अवस्था/.test(x.textContent));if(roadPanel&&!$('fs23official')){const p=document.createElement('section');p.id='fs23official';p.className='fs23panel';p.innerHTML='<div class="fs23head"><h3 data-ne="⚠ आधिकारिक चेतावनी र सडक" data-en="⚠ Official alerts & roads">⚠ आधिकारिक चेतावनी र सडक</h3><span class="fs23pill">BIPAD • DoR</span></div><div id="fs23alertList"></div></section>';roadPanel.insertAdjacentElement('afterend',p)}
 const impactPanel=[...document.querySelectorAll('.panel')].find(x=>/आजको बाढी प्रभाव/.test(x.textContent));if(impactPanel&&!$('fs23impact')){const p=document.createElement('section');p.id='fs23impact';p.className='fs23panel fs23impact';impactPanel.insertAdjacentElement('afterend',p)}
 const districtPanel=[...document.querySelectorAll('.panel')].find(x=>/७७ जिल्ला/.test(x.textContent));if(districtPanel&&!$('fs23mount')){const p=document.createElement('section');p.id='fs23mount';p.className='fs23panel';p.innerHTML='<div class="fs23head"><h3 data-ne="🏔 हिमाल • हिमनदी • उच्च उचाइ" data-en="🏔 Mountains • glaciers • high altitude">🏔 हिमाल • हिमनदी • उच्च उचाइ</h3><span class="fs23pill">DHM NETWORK</span></div><div class="fs23mount"><div class="fs23station"><b>Beding • Kyangjing • Pangboche</b><div class="fs23meta">DHM snow/glacier monitoring network</div></div><div class="fs23station"><b>Tilicho • Tsho Rolpa • Panchamukhi</b><div class="fs23meta">DHM snow/glacier/glacial-lake monitoring network</div></div></div><div class="fs23note" data-ne="स्रोतले सार्वजनिक live numerical reading नदिएको स्टेशनमा बनावटी संख्या देखाइँदैन।" data-en="No fabricated number is shown where the source does not expose a public live numerical reading.">स्रोतले सार्वजनिक live numerical reading नदिएको स्टेशनमा बनावटी संख्या देखाइँदैन।</div>';districtPanel.insertAdjacentElement('afterend',p)}
 const map=document.querySelector('.mapWrap');if(map&&!$('fs23maptag')){const d=document.createElement('div');d.id='fs23maptag';d.className='fs23maptag';d.textContent='HD उपग्रह • DHM/BIPAD • NASA वर्षा animation';map.appendChild(d);setTimeout(()=>{if(d)d.style.display='none'},9000)}
}

function avg(r,intv){const a=(r?.averages||[]).find(x=>+x.interval===intv);return num(a?.value)}
function nearestRain(){const f=focus();if(!f)return null;return state.rain.map(r=>({r,c:coord(r)})).filter(x=>x.c).sort((a,b)=>km(f,a.c)-km(f,b.c))[0]||null}
function renderWeather(){const f=focus(),x=nearestRain();if(!f){$('fs23wxstation')&&($('fs23wxstation').textContent=txt('स्थान अनुमति दिनुहोस्','Allow location'));return}if(!x){$('fs23wxstation').textContent=txt('आधिकारिक स्टेशन भेटिएन','No official station found');$('fs23wxnote').textContent=txt('यो स्थान नजिक सार्वजनिक DHM वर्षा/AWS reading उपलब्ध छैन।','No public DHM rain/AWS reading is available near this location.');return}const r=x.r,d=km(f,x.c);$('fs23wxstation').textContent=(r.title||r.name||'DHM station')+' • '+d.toFixed(1)+' km';$('fs23r1').textContent=(avg(r,1)??'—')+' mm';$('fs23r6').textContent=(avg(r,6)??'—')+' mm';$('fs23r24').textContent=(avg(r,24)??'—')+' mm';const wt=when(r);$('fs23wxnote').textContent=txt('DHM/BIPAD मापन: '+fmtTime(wt)+' • '+age(wt)+' अघि • स्थिति '+(r.status||'—'),'DHM/BIPAD measured: '+fmtTime(wt)+' • '+age(wt)+' ago • '+(r.status||'—'));}
function renderRiver(){if(!$('fs23riverList'))return;const f=focus(),list=state.river.map(r=>({r,c:coord(r)})).filter(x=>x.c&&when(x.r)).sort((a,b)=>f?km(f,a.c)-km(f,b.c):(+new Date(when(b.r)))-(+new Date(when(a.r)))).slice(0,8);$('fs23riverAge').textContent=state.lastCheck?age(state.lastCheck):'—';$('fs23riverList').innerHTML=list.map(x=>{const r=x.r,[cl,lab]=stage(r),wl=num(r.waterLevel),w=num(r.warningLevel),d=num(r.dangerLevel),dist=f?km(f,x.c):null;return '<div class="fs23station"><div class="fs23stationTop"><b>'+esc(r.title||'DHM station')+'</b><span class="fs23stage '+cl+'">'+lab+'</span></div><div class="fs23meta">'+(dist!==null?dist.toFixed(1)+' km • ':'')+txt('पानी ','Level ')+(wl??'—')+' m • '+txt('चेतावनी ','warning ')+(w??'—')+' • '+txt('खतरा ','danger ')+(d??'—')+'<br>'+txt('मापन ','Measured ')+fmtTime(when(r))+' • '+age(when(r))+' • DHM/BIPAD</div></div>'}).join('')||'<div class="fs23note">'+txt('आधिकारिक river-station data अहिले उपलब्ध छैन।','Official river-station data is unavailable.')+'</div>'}
function activeAlert(a){if(a?.verified===false||a?.public===false)return false;const e=a?.expireOn?+new Date(a.expireOn):Infinity;return e>Date.now()}
function renderAlerts(){if(!$('fs23alertList'))return;const f=focus();let aa=state.alerts.filter(activeAlert).map(a=>({a,c:coord(a)})).filter(x=>x.c);if(f)aa=aa.filter(x=>km(f,x.c)<=80).sort((a,b)=>km(f,a.c)-km(f,b.c));else aa=aa.sort((a,b)=>(+new Date(b.a.createdOn||0))-(+new Date(a.a.createdOn||0)));const rr=state.roads.map(r=>({r,c:coord(r)})).filter(x=>x.c&&String(x.r.status||'').toUpperCase()!=='OPEN');const nearRoad=f?rr.filter(x=>km(f,x.c)<=80).sort((a,b)=>km(f,a.c)-km(f,b.c)):rr;const parts=[];aa.slice(0,4).forEach(x=>parts.push('<div class="fs23station"><div class="fs23stationTop"><b>'+esc((state.lang==='ne'?x.a.titleNe:null)||x.a.title||'Official alert')+'</b><span class="fs23stage warning">'+esc(x.a.source||'BIPAD')+'</span></div><div class="fs23meta">'+(f?km(f,x.c).toFixed(1)+' km • ':'')+esc(x.a.description||'')+'<br>'+fmtTime(x.a.createdOn)+'</div></div>'));nearRoad.slice(0,4).forEach(x=>parts.push('<div class="fs23station"><div class="fs23stationTop"><b>'+esc(x.r.location||x.r.title||'Road')+'</b><span class="fs23stage danger">'+esc(x.r.status||'ROAD')+'</span></div><div class="fs23meta">'+(f?km(f,x.c).toFixed(1)+' km • ':'')+esc(x.r.closureReason||'')+' • DoR/BIPAD<br>'+fmtTime(x.r.modifiedOn||x.r.createdOn)+'</div></div>'));$('fs23alertList').innerHTML=parts.join('')||'<div class="fs23note">'+txt('अहिले नजिक active official alert/road closure भेटिएन।','No nearby active official alert/road closure found.')+'</div>'}
function renderImpact(){if(!$('fs23impact'))return;const b=state.bulletins[0],year=b?.yearlyDataNe||b?.yearlyData||{},fl=year['बाढी']||year['Flood'];const police='<div class="fs23grid"><div class="fs23cell"><small>'+txt('रसुवा बाढी पुष्टि मृत्यु','Rasuwa flood confirmed deaths')+'</small><b>95</b></div><div class="fs23cell"><small>'+txt('आधिकारिक अपडेट','Official update')+'</small><b>19:14</b></div><div class="fs23cell"><small>'+txt('स्रोत','Source')+'</small><b>Nepal Police</b></div><div class="fs23cell"><small>'+txt('मिति','Date')+'</small><b>2083-05-10</b></div></div>';const bp=fl?'<div class="fs23note">BIPAD bulletin record • flood deaths '+(fl.deaths??'—')+' • injured '+(fl.injured??'—')+' • missing '+(fl.missing??'—')+' • incidents '+(fl.incidents??'—')+' • bulletin '+fmtTime(b.createdOn)+'</div>':'<div class="fs23note">'+txt('BIPAD bulletin मा ताजा flood summary उपलब्ध छैन।','No fresh flood summary is available in the BIPAD bulletin feed.')+'</div>';$('fs23impact').innerHTML='<div class="fs23head"><h3 data-ne="🚨 आधिकारिक बाढी प्रभाव" data-en="🚨 Official flood impact">🚨 आधिकारिक बाढी प्रभाव</h3><span class="fs23pill">VERIFIED SOURCES</span></div>'+police+bp;drawImpact()}
function drawImpact(){const m=window.__fs?.map;if(!m||!window.L)return;if(state.impactLayer){m.removeLayer(state.impactLayer);state.impactLayer=null}state.impactLayer=L.layerGroup();[['Rasuwa',1,28.11,85.30],['Nuwakot',11,27.92,85.16],['Dhading',18,27.87,84.90],['Chitwan',33,27.53,84.35],['Gorkha',16,28.00,84.63],['Tanahun',5,27.94,84.23],['Nawalparasi East',11,27.65,84.02]].forEach(d=>L.circleMarker([d[2],d[3]],{radius:8+Math.sqrt(d[1])*2,color:'#fff6dd',weight:1.4,fillColor:'#dc143c',fillOpacity:.7,className:'fs23pulse'}).bindPopup('<b>'+d[0]+'</b><br>'+d[1]+' confirmed deaths<br>Nepal Police • 19:14').addTo(state.impactLayer));state.impactLayer.addTo(m)}
function renderAll(){renderWeather();renderRiver();renderAlerts();renderImpact();translate()}

async function poll(){if(state.busy)return;state.busy=true;$('fs23check')&&($('fs23check').textContent=txt('जाँच हुँदैछ…','Checking…'));try{const [rv,rn,al,rd,bu]=await Promise.allSettled([
 get(API+'river-stations/?limit=650'),get(API+'rain-stations/?limit=650'),get(API+'alert/?limit=250&ordering=-createdOn'),get(API+'highway/?limit=500'),get(API+'bipad-bulletin/?limit=5&ordering=-createdOn')]);
 if(rv.status==='fulfilled')state.river=rows(rv.value);if(rn.status==='fulfilled')state.rain=rows(rn.value);if(al.status==='fulfilled')state.alerts=rows(al.value);if(rd.status==='fulfilled')state.roads=rows(rd.value);if(bu.status==='fulfilled')state.bulletins=rows(bu.value);state.lastCheck=new Date();renderAll()}catch(e){console.warn('V23 poll',e)}finally{state.busy=false}}
function hookMap(){let n=0,t=setInterval(()=>{const fs=window.__fs;if(!fs?.map||!fs?.setFocus){if(++n>60)clearInterval(t);return}clearInterval(t);fs.map.on('click',e=>{state.focus=[e.latlng.lat,e.latlng.lng];fs.setFocus(state.focus,'map');renderAll()});setTimeout(()=>{const b=$('satBtn');if(b&&!b.classList.contains('on'))b.click();const r=$('rainSatBtn');if(r&&!r.classList.contains('on'))r.click();drawImpact()},400)},200)}
function hookGPS(){const b=$('gpsBtn');if(!b)return;b.addEventListener('click',()=>setTimeout(()=>{state.focus=focus();renderAll()},1200),true)}
function boot(){injectTheme();injectPanels();translate();tick();setInterval(tick,1000);hookMap();hookGPS();poll();state.timers.push(setInterval(poll,POLL));setTimeout(()=>{state.focus=focus();renderAll()},1400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();
