(()=>{
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  let serviceLast=null,serviceBusy=false,speedBusy=false;
  function q(s){return document.querySelector(s)}
  function connectionLabel(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection,t=c&&c.type;if(t==='wifi')return'Wi‑Fi';if(t==='cellular')return'Mobile data';if(t==='ethernet')return'Ethernet';return'Current connection'}
  function setCheckRow(key,label){const t=q('#t-'+key);if(t){const row=t.closest('.check');const b=row&&row.querySelector('b');if(b)b.textContent=label}}
  function ensureUi(){
    document.title='FixCheck — Service Response';
    const brand=document.querySelector('.brand small,.brandText small');if(brand)brand.textContent='Check the service, not just the internet';
    const h1=document.querySelector('h1');if(h1)h1.textContent='Which service feels slow?';
    const intro=h1&&h1.nextElementSibling;if(intro&&intro.tagName==='P')intro.textContent='Pick a service. FixCheck sends its own HTTPS probes to that selected domain and compares the result with the FixCheck web server.';
    if(!q('#serviceProbeNote')&&intro){const n=document.createElement('div');n.id='serviceProbeNote';n.className='card';n.style.cssText='margin:10px 0;font-size:11px;color:#8da5a1';n.textContent='Service timings are FixCheck-generated HTTPS probe requests to the selected domain. They are not private Facebook/YouTube app traffic and they are not an Mbps bandwidth test.';intro.insertAdjacentElement('afterend',n)}
    setCheckRow('device','Device connection');setCheckRow('internet','Selected service DNS');setCheckRow('dns','Selected service HTTPS probes');setCheckRow('target','FixCheck server response');
    const qRow=q('#t-quality')?.closest('.check');if(qRow)qRow.style.display='none';const sRow=q('#t-speed')?.closest('.check');if(sRow)sRow.style.display='none';
    const statusbar=document.querySelector('.statusbar')||q('#online')?.parentElement;if(statusbar&&!q('#fixcheckServerPill')){const p=document.createElement('div');p.id='fixcheckServerPill';p.className='pill';p.innerHTML='FixCheck server · <strong id="fixcheckServerTop">not tested</strong>';statusbar.appendChild(p)}
    const result=q('#result');if(result&&!q('#serviceV6Metrics'))result.innerHTML='<div class="dash"><div class="card score"><div class="ring" id="ring"><div><strong id="score">--</strong><small>/100</small></div></div><b id="grade">Service quality</b></div><div class="card metrics" id="serviceV6Metrics"><div class="metric"><small id="mService">SERVICE MEDIAN</small><b id="serviceMed">--</b></div><div class="metric"><small>SERVICE JITTER</small><b id="serviceJit">--</b></div><div class="metric"><small>PROBE SUCCESS</small><b id="serviceRel">--</b></div><div class="metric"><small>FASTEST RESPONSE</small><b id="serviceMin">--</b></div><div class="metric"><small>SLOWEST RESPONSE</small><b id="serviceMax">--</b></div><div class="metric"><small>DNS LOOKUP</small><b id="dnsMs">--</b></div></div></div><div class="card" style="margin-top:10px"><b id="serviceCompareTitle">Selected service vs FixCheck server</b><div class="metrics" style="margin-top:8px"><div class="metric"><small>FIXCHECK SERVER MEDIAN</small><b id="serverMed">--</b></div><div class="metric"><small>FIXCHECK SERVER JITTER</small><b id="serverJit">--</b></div><div class="metric"><small>FIXCHECK SERVER SUCCESS</small><b id="serverRel">--</b></div></div></div><div class="card verdict"><small class="muted">FIXCHECK VERDICT</small><h2 id="vtitle">—</h2><p id="vtext"></p><div class="rowbtns"><button id="copy">Copy report</button><button id="again">Run again</button></div></div>';
    const history=document.querySelector('.history');if(history&&!q('#serviceSpeedBox')){const box=document.createElement('section');box.id='serviceSpeedBox';box.className='card';box.style.marginTop='10px';box.innerHTML='<div style="display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap"><div><b>Optional connection speed test</b><div class="muted" style="font-size:10px;margin-top:4px">Your current Wi‑Fi/mobile/ethernet estimate only — never the selected service speed.</div></div><div><strong id="serviceSpeedValue" style="font-size:22px;margin-right:10px">--</strong><button class="mini" id="serviceSpeedBtn">Run speed test</button></div></div>';history.parentNode.insertBefore(box,history);q('#serviceSpeedBtn').onclick=runConnectionSpeed}
    const hb=history&&history.querySelector('b');if(hb)hb.textContent='Recent service checks';
    wireButtons();updateRunLabel();renderServiceHistory();
  }
  function validTarget(){try{return target()}catch{return null}}
  function updateRunLabel(){const t=validTarget(),b=q('#run');if(b&&!serviceBusy)b.textContent='● RUN '+(t?t.name.toUpperCase():'SERVICE')+' CHECK'}
  function summary(vals,total){const a=vals.filter(Number.isFinite).sort((x,y)=>x-y),success=a.length,rel=Math.round(success/total*100);if(!a.length)return{median:null,min:null,max:null,jitter:null,success,total,rel};const i=Math.floor(a.length/2),median=a.length%2?a[i]:Math.round((a[i-1]+a[i])/2);let jitter=null;if(a.length>1){const ds=[];for(let j=1;j<a.length;j++)ds.push(Math.abs(a[j]-a[j-1]));jitter=Math.round(ds.reduce((x,y)=>x+y,0)/ds.length)}return{median,min:a[0],max:a[a.length-1],jitter,success,total,rel}}
  async function probes(url,count=6,noCors=true){const vals=[];for(let i=0;i<count;i++){const r=await probe(url,5000,noCors);if(r.ok)vals.push(r.ms);if(i<count-1)await sleep(150)}return summary(vals,count)}
  function serviceScore(s,dnsOk){if(!dnsOk||!s.success)return null;let x=100;if(s.rel<100)x-=Math.min(45,(100-s.rel)*1.5);const m=s.median??9999,j=s.jitter??9999;if(m>1000)x-=40;else if(m>600)x-=28;else if(m>350)x-=18;else if(m>200)x-=10;else if(m>120)x-=5;if(j>300)x-=30;else if(j>150)x-=20;else if(j>80)x-=12;else if(j>40)x-=6;return Math.max(0,Math.round(x))}
  function saveHistory(x){let h=[];try{h=JSON.parse(localStorage.getItem('fixcheck-service-history')||'[]')}catch{}h.unshift(x);localStorage.setItem('fixcheck-service-history',JSON.stringify(h.slice(0,10)));renderServiceHistory()}
  function renderServiceHistory(){const e=q('#history');if(!e)return;let h=[];try{h=JSON.parse(localStorage.getItem('fixcheck-service-history')||'[]')}catch{}e.innerHTML=h.length?'':'<p class="muted">No service checks yet.</p>';h.forEach(x=>{const d=document.createElement('div');d.className='hist';d.innerHTML='<span><b>'+x.target+'</b><br><small class="muted">'+x.when+' · median '+(x.serviceMedian??'--')+' ms</small></span><strong>'+(x.score==null?'--':x.score+'/100')+'</strong>';e.appendChild(d)})}
  async function runService(){if(serviceBusy)return;const tg=validTarget();if(!tg){const hint=q('#hint');if(hint){hint.textContent='Not a valid public website. Use something like bbc.co.uk or example.com.';hint.className='hint bad'}toast('Invalid website — test not started');return}serviceBusy=true;running=true;const b=q('#run');b.disabled=true;b.textContent='CHECKING '+tg.name.toUpperCase()+'…';q('#result')?.classList.add('hide');status('device',navigator.onLine?'pass':'fail',navigator.onLine?connectionLabel()+' is online':'Device reports offline');['internet','dns','target'].forEach(k=>status(k,'','Waiting'));if(!navigator.onLine){status('internet','warn','Skipped while offline');status('dns','warn','Skipped while offline');status('target','fail','FixCheck server unreachable while offline');finishService();return}
    status('internet','','Resolving '+tg.host+'…');const d=await dns(tg.host);status('internet',d.ok?'pass':'fail',d.ok?tg.host+' resolved · '+d.ms+' ms DoH':d.nx?tg.host+' does not exist':'DNS could not be confirmed');
    let svc=summary([],6);if(d.ok){status('dns','','Sending 6 HTTPS probes to '+tg.name+'…');svc=await probes(tg.url,6,true);status('dns',svc.rel>=80?'pass':svc.rel>0?'warn':'fail',svc.success+'/'+svc.total+' probes · median '+(svc.median??'--')+' ms · jitter '+(svc.jitter??'--')+' ms')}else status('dns','fail','Not tested — selected service DNS did not resolve');
    status('target','','Measuring device → FixCheck server…');const srv=await probes('./ping.txt',6,false);status('target',srv.rel>=80?'pass':srv.rel>0?'warn':'fail',srv.success+'/'+srv.total+' server probes · median '+(srv.median??'--')+' ms · jitter '+(srv.jitter??'--')+' ms');const top=q('#fixcheckServerTop');if(top)top.textContent=srv.median==null?'unavailable':srv.median+' ms median';
    const sc=serviceScore(svc,d.ok),good=sc!=null&&sc>=75,mid=sc!=null&&sc>=55;q('#score').textContent=sc==null?'--':sc;q('#grade').textContent=sc==null?'Service not rated':(sc>=90?'Excellent':sc>=75?'Good':sc>=55?'Fair':'Poor')+' '+tg.name+' response';q('#ring').style.background='conic-gradient('+(sc==null?'var(--amber)':good?'var(--green)':mid?'var(--amber)':'var(--red)')+' '+((sc??0)*3.6)+'deg,#173033 0)';q('#mService').textContent=tg.name.toUpperCase()+' MEDIAN';q('#serviceMed').textContent=svc.median==null?'--':svc.median+' ms';q('#serviceJit').textContent=svc.jitter==null?'--':svc.jitter+' ms';q('#serviceRel').textContent=svc.rel+'%';q('#serviceMin').textContent=svc.min==null?'--':svc.min+' ms';q('#serviceMax').textContent=svc.max==null?'--':svc.max+' ms';q('#dnsMs').textContent=d.ms==null?'--':d.ms+' ms';q('#serviceCompareTitle').textContent=tg.name+' vs FixCheck server';q('#serverMed').textContent=srv.median==null?'--':srv.median+' ms';q('#serverJit').textContent=srv.jitter==null?'--':srv.jitter+' ms';q('#serverRel').textContent=srv.rel+'%';
    let title,text;if(!d.ok){title=tg.name+' could not be resolved';text='No '+tg.name+' timing was claimed because its DNS did not resolve.'}else if(!svc.success){title=tg.name+' was not confirmed';text='DNS resolved, but none of FixCheck’s HTTPS probes to '+tg.name+' completed. This is not a general internet speed result.'}else{const gap=svc.median!=null&&srv.median!=null?svc.median-srv.median:null;title=tg.name+' response measured';text='FixCheck sent '+svc.total+' HTTPS probes directly to '+tg.name+'. Median '+svc.median+' ms, jitter '+svc.jitter+' ms, success '+svc.rel+'%.'+(gap==null?'':' FixCheck server median '+srv.median+' ms ('+(gap>=0?'+':'')+gap+' ms difference).')}
    q('#vtitle').textContent=title;q('#vtext').textContent=text;serviceLast={target:tg.name,score:sc,dnsMs:d.ms,serviceMedian:svc.median,serviceJitter:svc.jitter,serviceRel:svc.rel,serverMedian:srv.median,serverJitter:srv.jitter,serverRel:srv.rel,when:new Date().toLocaleString()};saveHistory(serviceLast);q('#result').classList.remove('hide');tone(sc!=null&&sc>=75?780:420,.1);finishService()}
  function finishService(){serviceBusy=false;running=false;const b=q('#run');b.disabled=false;updateRunLabel()}
  async function runConnectionSpeed(){if(speedBusy)return;speedBusy=true;const b=q('#serviceSpeedBtn'),v=q('#serviceSpeedValue');b.disabled=true;b.textContent='Testing…';v.textContent='…';const bytes=2000000,t=performance.now();let mbps=null;try{const r=await fetch('https://speed.cloudflare.com/__down?bytes='+bytes+'&x='+Date.now(),{cache:'no-store'});if(!r.ok)throw 0;const a=await r.arrayBuffer(),sec=(performance.now()-t)/1000;mbps=Math.round((a.byteLength*8/sec/1e6)*10)/10}catch{}v.textContent=mbps==null?'Unavailable':mbps+' Mbps';b.textContent='Run again';b.disabled=false;speedBusy=false}
  function serviceReport(){if(!serviceLast)return'';return`FixCheck service report\nTarget: ${serviceLast.target}\nService score: ${serviceLast.score??'Not rated'}\nDNS: ${serviceLast.dnsMs??'--'} ms\nService median: ${serviceLast.serviceMedian??'--'} ms\nService jitter: ${serviceLast.serviceJitter??'--'} ms\nService success: ${serviceLast.serviceRel}%\nFixCheck server median: ${serviceLast.serverMedian??'--'} ms\nFixCheck server jitter: ${serviceLast.serverJitter??'--'} ms\nFixCheck server success: ${serviceLast.serverRel}%`}
  function wireButtons(){const runBtn=q('#run'),again=q('#again'),copy=q('#copy');if(runBtn)runBtn.onclick=runService;if(again)again.onclick=runService;if(copy)copy.onclick=async()=>{if(!serviceLast)return toast('Run a service check first');try{await navigator.clipboard.writeText(serviceReport());toast('Report copied')}catch{toast('Copy unavailable')}}}
  document.addEventListener('click',e=>{if(e.target.closest('.svc'))setTimeout(updateRunLabel,0)});q('#serviceTab')?.addEventListener('click',()=>setTimeout(updateRunLabel,0));q('#siteTab')?.addEventListener('click',()=>setTimeout(updateRunLabel,0));q('#url')?.addEventListener('input',()=>setTimeout(updateRunLabel,0));
  window.run=runService;try{run=runService}catch{}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureUi);else ensureUi();
})();