(()=>{
'use strict';
if(window.__fsAlertSummaryV1)return;window.__fsAlertSummaryV1=true;if((document.body.dataset.page||'')!=='alerts')return;
const $=id=>document.getElementById(id),BASE='https://bipadportal.gov.np/api/v1/',DOR='../../data/dor-road-summary.json';
let busy=false,lastCheck=0,state=null,applying=false,queued=false;
const lang=()=>localStorage.getItem('fs23-lang')==='en'?'en':'ne',tr=(ne,en)=>lang()==='en'?en:ne,rows=j=>Array.isArray(j)?j:(j?.results||j?.data||j?.objects||[]),txt=o=>{try{return JSON.stringify(o||{}).toLowerCase()}catch{return''}},stamp=o=>o?.waterLevelOn||o?.measuredOn||o?.modifiedOn||o?.updatedOn||o?.createdOn||o?.created_at||o?.updated_at||o?.date||null;
async function get(url,ms=6000){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
function num(v){const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null}
function active(o){const s=txt(o),exp=o?.expiresOn||o?.expireOn||o?.expires_at||o?.endDate;if(o?.active===false||o?.isActive===false||/inactive|expired|archived|समाप्त/.test(s))return false;if(exp&&+new Date(exp)<Date.now())return false;const t=+new Date(stamp(o)||0);if(!exp&&t&&Date.now()-t>12*3600e3)return false;return /(danger|warning|high|red|orange|evacuat|खतरा|चेतावनी|उच्च|सतर्क)/.test(s)}
function riverWarn(o){const wl=num(o?.waterLevel??o?.water_level??o?.currentLevel??o?.level??o?.value),w=num(o?.warningLevel??o?.warning_level??o?.warning),d=num(o?.dangerLevel??o?.danger_level??o?.danger),s=String(o?.status||o?.state||o?.condition||o?.trend||'').toUpperCase();return(d!==null&&wl!==null&&wl>=d)||(w!==null&&wl!==null&&wl>=w)||/ABOVE\s+DANGER|ABOVE\s+WARNING|DANGER\s+LEVEL|WARNING\s+LEVEL|RED\s+ALERT|ORANGE\s+ALERT/.test(s)}
function time(t=Date.now()){try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return'—'}}
function put(id,v){const e=$(id),s=String(v??'—');if(e&&e.textContent!==s)e.textContent=s}
function render(){if(!state||applying)return;applying=true;try{put('alertCount',state.high);put('riverAlertCount',state.river);put('roadAlertCount',state.closed);if($('liveSourceState'))$('liveSourceState').textContent=tr('मुख्य वर्तमान स्रोत ३/३ जडित • जाँच ','Main current sources 3/3 connected • checked ')+time(lastCheck);if($('healthBipad'))$('healthBipad').textContent=tr('BIPAD चेतावनी ✓','BIPAD alerts ✓');if($('healthRiver'))$('healthRiver').textContent=tr('DHM नदी ✓','DHM river ✓');if($('healthRoad'))$('healthRoad').textContent=tr('सडक विभाग ✓','DoR roads ✓');window.__fsAlertSummary={...state,checkedAt:lastCheck}}finally{applying=false}}
async function poll(){if(busy||document.hidden||!navigator.onLine)return;busy=true;try{const [a,r,d]=await Promise.allSettled([get(BASE+'alert/?limit=200&ordering=-createdOn'),get(BASE+'river/?limit=650'),get(DOR,5000)]),al=a.status==='fulfilled'?rows(a.value):[],rv=r.status==='fulfilled'?rows(r.value):[],dor=d.status==='fulfilled'?d.value:null;lastCheck=Date.now();state={high:al.filter(active).length,river:rv.filter(riverWarn).length,closed:Number.isFinite(Number(dor?.closed))?Number(dor.closed):'—'};render()}finally{busy=false}}
function repair(){if(!state||applying||queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function boot(){poll();for(const id of ['alertCount','riverAlertCount','roadAlertCount','liveSourceState']){const e=$(id);if(!e)continue;const ob=new MutationObserver(repair);ob.observe(e,{childList:true,subtree:true,characterData:true})}setInterval(poll,5000);setInterval(()=>{if(state)render()},1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});window.addEventListener('online',poll);window.addEventListener('fs-language-change',render)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();