(()=>{
'use strict';
if(window.__fsAlertsOwnerV1)return;window.__fsAlertsOwnerV1=true;
if((document.body.dataset.page||'')!=='alerts')return;
const $=id=>document.getElementById(id),BASE='https://bipadportal.gov.np/api/v1/',DOR='../../data/dor-road-summary.json',KCHA='https://kchakhabar.com/api/v1/today.json?limit=100';
const URLS={alerts:BASE+'alert/?limit=200&ordering=-createdOn',river:BASE+'river/?limit=650',road:BASE+'highway/?limit=500'};
const DISTRICTS=[['Taplejung','ताप्लेजुङ'],['Panchthar','पाँचथर'],['Ilam','इलाम'],['Jhapa','झापा'],['Morang','मोरङ'],['Sunsari','सुनसरी'],['Dhankuta','धनकुटा'],['Terhathum','तेह्रथुम'],['Sankhuwasabha','संखुवासभा'],['Bhojpur','भोजपुर'],['Solukhumbu','सोलुखुम्बु'],['Okhaldhunga','ओखलढुङ्गा'],['Khotang','खोटाङ'],['Udayapur','उदयपुर'],['Saptari','सप्तरी'],['Siraha','सिराहा'],['Dhanusha','धनुषा'],['Mahottari','महोत्तरी'],['Sarlahi','सर्लाही'],['Rautahat','रौतहट'],['Bara','बारा'],['Parsa','पर्सा'],['Dolakha','दोलखा'],['Sindhupalchok','सिन्धुपाल्चोक'],['Rasuwa','रसुवा'],['Dhading','धादिङ'],['Nuwakot','नुवाकोट'],['Kathmandu','काठमाडौं'],['Bhaktapur','भक्तपुर'],['Lalitpur','ललितपुर'],['Kavrepalanchok','काभ्रेपलाञ्चोक'],['Ramechhap','रामेछाप'],['Sindhuli','सिन्धुली'],['Makwanpur','मकवानपुर'],['Chitwan','चितवन'],['Gorkha','गोरखा'],['Manang','मनाङ'],['Mustang','मुस्ताङ'],['Myagdi','म्याग्दी'],['Kaski','कास्की'],['Lamjung','लमजुङ'],['Tanahun','तनहुँ'],['Nawalpur','नवलपुर'],['Syangja','स्याङ्जा'],['Parbat','पर्वत'],['Baglung','बागलुङ'],['Rukum East','रुकुम पूर्व'],['Rolpa','रोल्पा'],['Pyuthan','प्युठान'],['Gulmi','गुल्मी'],['Arghakhanchi','अर्घाखाँची'],['Palpa','पाल्पा'],['Nawalparasi West','नवलपरासी पश्चिम'],['Rupandehi','रुपन्देही'],['Kapilvastu','कपिलवस्तु'],['Dang','दाङ'],['Banke','बाँके'],['Bardiya','बर्दिया'],['Rukum West','रुकुम पश्चिम'],['Salyan','सल्यान'],['Dolpa','डोल्पा'],['Jumla','जुम्ला'],['Mugu','मुगु'],['Humla','हुम्ला'],['Kalikot','कालिकोट'],['Jajarkot','जाजरकोट'],['Dailekh','दैलेख'],['Surkhet','सुर्खेत'],['Bajura','बाजुरा'],['Bajhang','बझाङ'],['Darchula','दार्चुला'],['Baitadi','बैतडी'],['Dadeldhura','डडेलधुरा'],['Doti','डोटी'],['Achham','अछाम'],['Kailali','कैलाली'],['Kanchanpur','कञ्चनपुर']];
const SPECIAL={Nawalpur:['nawalparasi east','nawalparasi purba','bardaghat susta east','नवलपरासी पूर्व','नवलपुर'],'Nawalparasi West':['nawalparasi west','nawalparasi paschim','bardaghat susta west','नवलपरासी पश्चिम'],'Rukum East':['rukum east','eastern rukum','रुकुम पूर्व'],'Rukum West':['rukum west','western rukum','रुकुम पश्चिम'],Kavrepalanchok:['kavre','kavrepalanchok','काभ्रे','काभ्रेपलाञ्चोक']};
const FLOOD=/flood|flash flood|inundat|बाढी|डुबान|river|नदी|खोला/i,HIGH=/danger|red alert|high risk|very high|evacuat|warning|खतरा|उच्च जोखिम|चेतावनी|सतर्कता/i;
let alerts=[],river=[],roads=[],dor=null,media=[],busy=false,mediaBusy=false,lastCheck=0,lastMedia=0,rendering=false,repairQueued=false;
const lang=()=>localStorage.getItem('fs23-lang')==='en'?'en':'ne',tr=(ne,en)=>lang()==='en'?en:ne,rows=j=>Array.isArray(j)?j:(j?.results||j?.data||j?.objects||[]),txt=o=>{try{return JSON.stringify(o||{}).toLowerCase()}catch{return''}},stamp=o=>o?.waterLevelOn||o?.measuredOn||o?.modifiedOn||o?.updatedOn||o?.createdOn||o?.created_at||o?.updated_at||o?.date||null;
async function get(url,ms=6500){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
function time(t=Date.now()){try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return'—'}}
function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}function make(t,c,x){const e=document.createElement(t);if(c)e.className=c;if(x!==undefined)e.textContent=x;return e}
function name(o){if(lang()==='ne')return String(o?.titleNe||o?.nameNe||o?.roadNameNe||o?.highwayNameNe||o?.stationNameNe||o?.roadName||o?.highwayName||o?.name||o?.title||tr('आधिकारिक अपडेट','Official update'));return String(o?.titleEn||o?.nameEn||o?.roadNameEn||o?.highwayNameEn||o?.stationNameEn||o?.roadName||o?.highwayName||o?.name||o?.title||'Official update')}
function place(o){return String(o?.districtName||o?.district_name||o?.district?.title||o?.district?.name||o?.location||o?.place||'')}
function status(o){return String(o?.status||o?.severity||o?.state||o?.condition||o?.roadStatus||o?.road_status||o?.remarks||'')}
function num(v){const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null}
function roadState(o){const s=(status(o)+' '+txt(o)).toLowerCase();if(/partial|partially|partial_open|one.?way|आंशिक|एकतर्फी/.test(s))return'PARTIAL';if(/closed|blocked|obstructed|पूर्ण बन्द|अवरुद्ध|सडक बन्द/.test(s))return'CLOSED';if(/\bopen(?:ed)?\b|fully open|सुचारु|खुला/.test(s))return'OPEN';return'OTHER'}
function reason(o){const s=String(o?.closureReason||o?.closure_reason||o?.reason||o?.cause||o?.descriptionNe||o?.description||o?.remarks||'').toLowerCase();if(/landslide|mudslide|पहिरो|भूस्खलन/.test(s))return tr('पहिरो','Landslide');if(/flood|inundat|बाढी|डुबान/.test(s))return tr('बाढी / डुबान','Flood / inundation');if(/bridge|पुल/.test(s))return tr('पुल वा सडक क्षति','Bridge or road damage');if(/accident|collision|दुर्घटना|ठक्कर/.test(s))return tr('दुर्घटना','Accident');if(/maintenance|repair|मर्मत/.test(s))return tr('मर्मत कार्य','Maintenance work');return tr('कारण स्रोतमा स्पष्ट प्रकाशित छैन','Reason is not clearly published by the source')}
function alt(o){for(const k of ['alternativeRoute','alternative_route','alternateRoute','alternate_route','detour','diversion','reroute']){const v=o?.[k];if(typeof v==='string'&&v.trim().length>2)return v.trim()}return''}
function rKey(o){return (name(o)+' '+place(o)).toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim()}
function latestRoads(){const m=new Map();for(const o of roads){const k=rKey(o);if(!k)continue;const old=m.get(k);if(!old||+new Date(stamp(o)||0)>=+new Date(stamp(old)||0))m.set(k,o)}return[...m.values()]}
function activeAlert(o){const s=(name(o)+' '+status(o)+' '+txt(o));const exp=o?.expiresOn||o?.expireOn||o?.expires_at||o?.endDate;if(exp&&+new Date(exp)<Date.now())return false;if(o?.active===false||o?.isActive===false)return false;return HIGH.test(s)}
function riverStage(o){const wl=num(o?.waterLevel??o?.water_level??o?.currentLevel??o?.level??o?.value),w=num(o?.warningLevel??o?.warning_level??o?.warning),d=num(o?.dangerLevel??o?.danger_level??o?.danger),s=(status(o)+' '+String(o?.trend||o?.steady||'')).toUpperCase();if((d!==null&&wl!==null&&wl>=d)||/DANGER|ABOVE DANGER/.test(s))return{level:'DANGER',wl,w,d};if((w!==null&&wl!==null&&wl>=w)||/WARNING|ABOVE WARNING/.test(s))return{level:'WARNING',wl,w,d};return{level:'NORMAL',wl,w,d}}
function aliases(d){return[d[0].toLowerCase(),d[1],...(SPECIAL[d[0]]||[])].map(x=>String(x).toLowerCase())}function matches(o,d){const s=txt(o);return aliases(d).some(a=>s.includes(a))}
function card(out,tag,title,body,meta,url,red=false){const a=make('article','item');a.dataset.alertOwner='1';if(tag)a.appendChild(make('span','tag '+(red?'red':''),tag));a.appendChild(make('h4','',title));if(body)a.appendChild(make('p','',body));if(meta)a.appendChild(make('div','meta',meta));if(url){const d=make('div','meta'),l=make('a','',tr('स्रोत खोल्नुहोस्','Open source'));l.href=url;l.target='_blank';l.rel='noopener noreferrer';d.appendChild(l);a.appendChild(d)}out.appendChild(a)}
function renderFlood(){const out=$('alertsList');if(!out)return;const high=alerts.filter(o=>activeAlert(o)&&FLOOD.test(name(o)+' '+status(o)+' '+txt(o))),warn=river.map(o=>({o,s:riverStage(o)})).filter(x=>x.s.level!=='NORMAL');clear(out);for(const o of high.slice(0,8))card(out,tr('उच्च बाढी चेतावनी','HIGH FLOOD'),name(o),tr('सक्रिय आधिकारिक बाढी चेतावनी','Active official flood warning'),(stamp(o)?tr('अपडेट ','Updated ')+time(stamp(o)):'BIPAD'),'https://bipadportal.gov.np/',true);for(const x of warn.slice(0,12)){const b=tr('पानी ','Water ')+(x.s.wl??'—')+' m • '+tr('चेतावनी सीमा ','Warning ')+(x.s.w??'—')+' m • '+tr('खतरा सीमा ','Danger ')+(x.s.d??'—')+' m';card(out,x.s.level==='DANGER'?tr('खतरा','DANGER'):tr('चेतावनी','WARNING'),name(x.o),b,(stamp(x.o)?tr('अपडेट ','Updated ')+time(stamp(x.o)):'DHM'),'https://www.dhm.gov.np/hydrology/floodMonitoring',x.s.level==='DANGER')}if(!out.children.length)out.appendChild(make('div','empty',tr('अहिले जोडिएका आधिकारिक स्रोतमा सक्रिय बाढी वा नदी चेतावनी भेटिएको छैन।','No active flood or river warning is currently found in the connected official sources.')));const a=$('alertCount'),r=$('riverAlertCount');if(a)a.textContent=String(high.length);if(r)r.textContent=String(warn.length)}
function renderRoad(){const out=$('roadCurrentList');if(!out)return;const all=latestRoads(),closed=all.filter(o=>roadState(o)==='CLOSED'),partial=all.filter(o=>roadState(o)==='PARTIAL'),open=all.filter(o=>roadState(o)==='OPEN'),problems=[...closed,...partial].sort((a,b)=>+new Date(stamp(b)||0)-+new Date(stamp(a)||0));clear(out);for(const o of problems.slice(0,15)){const st=roadState(o),al=alt(o),body=tr('कारण: ','Reason: ')+reason(o)+(place(o)?' • '+tr('स्थान: ','Location: ')+place(o):'')+'\n'+tr('वैकल्पिक मार्ग: ','Alternative route: ')+(al||tr('विश्वसनीय स्रोतमा प्रकाशित छैन','Not published by a reliable source'));card(out,st==='CLOSED'?tr('बन्द','CLOSED'):tr('आंशिक खुला','PARTIALLY OPEN'),name(o),body,(stamp(o)?tr('अपडेट ','Updated ')+time(stamp(o)):'BIPAD highway'),'https://navigate.dor.gov.np/app/dashboard',st==='CLOSED')}if(!out.children.length)out.appendChild(make('div','empty',tr('अहिले स्रोतमा बन्द वा आंशिक बन्द सडक भेटिएको छैन।','No closed or partially closed road is currently found in the source.')));const officialClosed=Number.isFinite(Number(dor?.closed))?Number(dor.closed):closed.length;if($('roadAlertCount'))$('roadAlertCount').textContent=String(officialClosed);if($('roadOfficialSummary'))$('roadOfficialSummary').textContent=(dor?tr('सडक विभाग: ','DoR: ')+(dor.closed??'—')+tr(' बन्द • ',' closed • ')+(dor.partially_opened??'—')+tr(' आंशिक • ',' partial • ')+(dor.opened??'—')+tr(' खुला',' open'):tr('सडक विभाग सारांश जाँच हुँदैछ','Checking DoR summary'))+' • '+tr('पछिल्लो जाँच ','last checked ')+time(lastCheck)}
function fillDistrictFilter(){const s=$('districtFilter');if(!s)return;const cur=s.value||'ALL';while(s.options.length>1)s.remove(1);for(const [en,ne] of DISTRICTS){const o=document.createElement('option');o.value=en;o.textContent=lang()==='en'?en:ne;s.appendChild(o)}s.value=cur;s.onchange=renderDistrict}
function districtData(d){const a=alerts.filter(o=>matches(o,d)&&activeAlert(o)&&FLOOD.test(txt(o))),r=river.map(o=>({o,s:riverStage(o)})).filter(x=>matches(x.o,d)&&x.s.level!=='NORMAL'),rd=latestRoads().filter(o=>matches(o,d)&&['CLOSED','PARTIAL'].includes(roadState(o)));return{a,r,rd,total:a.length+r.length+rd.length}}
function renderDistrict(){const out=$('districtStatusList');if(!out)return;fillDistrictFilter();const sel=$('districtFilter')?.value||'ALL',arr=sel==='ALL'?DISTRICTS.map(d=>({d,x:districtData(d)})).filter(z=>z.x.total>0).sort((a,b)=>b.x.total-a.x.total):DISTRICTS.filter(d=>d[0]===sel).map(d=>({d,x:districtData(d)}));clear(out);for(const {d,x} of arr.slice(0,20)){const nm=lang()==='en'?d[0]:d[1],body=tr('बाढी चेतावनी ','Flood alerts ')+x.a.length+' • '+tr('नदी चेतावनी ','River warnings ')+x.r.length+' • '+tr('सडक समस्या ','Road problems ')+x.rd.length;card(out,x.total?tr('ध्यान','ATTENTION'):tr('जिल्ला','DISTRICT'),nm,body,x.total?tr('हालको स्रोतमा सक्रिय समस्या','Active issue in current source'):tr('हाल सक्रिय समस्या भेटिएन','No current active issue'),'https://bipadportal.gov.np/',x.total>0)}if(!out.children.length)out.appendChild(make('div','empty',sel==='ALL'?tr('७७ जिल्ला जोडिएका छन् • अहिले स्रोतमा जिल्ला-स्तरको सक्रिय समस्या भेटिएको छैन।','All 77 districts are connected • no district-level active issue is currently found in the source.'):tr('यो जिल्लामा अहिले जोडिएका स्रोतबाट सक्रिय समस्या भेटिएको छैन।','No active issue is currently found for this district in the connected sources.')));if($('districtLiveFresh'))$('districtLiveFresh').textContent=tr('७७ जिल्ला जोडिएको • समस्या भएका जिल्ला पहिले • जाँच ','77 districts connected • issues first • checked ')+time(lastCheck)}
function renderRapid(){const out=$('rapidSignalList');if(!out)return;clear(out);for(const s of media.slice(0,30)){const text=[s.topic_ne,s.topic_en,s.summary_ne,s.summary_en].filter(Boolean).join(' '),is=/(flood|बाढी|landslide|पहिरो|earthquake|भूकम्प)/i.test(text);if(!is)continue;const title=lang()==='en'?(s.topic_en||''):(s.topic_ne||'');if(!title)continue;const src=s.sources?.[0],body=lang()==='en'?(s.summary_en||''):(s.summary_ne||'');card(out,tr('प्रारम्भिक','EARLY'),title,String(body||'').slice(0,220),(src?.publisher||tr('नेपाली सञ्चारमाध्यम','Nepal media')),'',false);if(out.children.length>=5)break}if(!out.children.length)out.appendChild(make('div','empty',tr('नयाँ द्रुत संकेत पर्खिँदै…','Waiting for new rapid signals…')));if($('rapidSignalState'))$('rapidSignalState').textContent=tr('प्रारम्भिक समाचार स्रोत • जाँच ','Early media sources • checked ')+time(lastMedia||lastCheck)}
function renderRoadEarly(){const out=$('roadEarlyList');if(!out)return;clear(out);for(const s of media.slice(0,40)){const text=[s.topic_ne,s.topic_en,s.summary_ne,s.summary_en].filter(Boolean).join(' ');if(!/(road|highway|bridge|सडक|राजमार्ग|पुल)/i.test(text))continue;const title=lang()==='en'?(s.topic_en||''):(s.topic_ne||'');if(!title)continue;const src=s.sources?.[0],body=lang()==='en'?(s.summary_en||''):(s.summary_ne||'');card(out,tr('प्रारम्भिक','EARLY'),title,String(body||'').slice(0,220),(src?.publisher||tr('नेपाली सञ्चारमाध्यम','Nepal media')),(src?.url||s.url||''),false);if(out.children.length>=5)break}if(!out.children.length)out.appendChild(make('div','empty',tr('नयाँ सडक प्रारम्भिक खबर पर्खिँदै…','Waiting for new early road reports…')));if($('roadEarlyStatus'))$('roadEarlyStatus').textContent=tr('समाचार स्रोत • जाँच ','Media source • checked ')+time(lastMedia||lastCheck)}
function health(){if($('healthBipad'))$('healthBipad').textContent=tr('BIPAD चेतावनी ✓','BIPAD alerts ✓');if($('healthRiver'))$('healthRiver').textContent=tr('DHM नदी ✓','DHM river ✓');if($('healthRoad'))$('healthRoad').textContent=tr('सडक डेटा ✓','Road data ✓');if($('liveSourceState'))$('liveSourceState').textContent=tr('बाढी • नदी • सडक owner जोडिएको • जाँच ','Flood • river • road owner connected • checked ')+time(lastCheck)}
function renderAll(){if(rendering)return;rendering=true;try{renderFlood();renderRoad();renderDistrict();renderRapid();renderRoadEarly();health();window.__fsAlertsOwnerState={checkedAt:lastCheck,alertCount:alerts.length,riverCount:river.length,roadCount:roads.length}}finally{rendering=false}}
async function poll(){if(busy||document.hidden||!navigator.onLine)return;busy=true;try{const [a,r,rd,d]=await Promise.allSettled([get(URLS.alerts),get(URLS.river),get(URLS.road),get(DOR,5000)]);if(a.status==='fulfilled')alerts=rows(a.value);if(r.status==='fulfilled')river=rows(r.value);if(rd.status==='fulfilled')roads=rows(rd.value);if(d.status==='fulfilled')dor=d.value;lastCheck=Date.now();renderAll()}finally{busy=false}}
async function pollMedia(force=false){if(mediaBusy||document.hidden||!navigator.onLine||(!force&&Date.now()-lastMedia<30000))return;mediaBusy=true;try{const j=await get(KCHA,7000);media=Array.isArray(j?.stories)?j.stories:[];lastMedia=Date.now();renderRapid();renderRoadEarly()}catch{}finally{mediaBusy=false}}
function repair(){if(rendering||repairQueued||!lastCheck)return;repairQueued=true;queueMicrotask(()=>{repairQueued=false;renderAll()})}
function boot(){fillDistrictFilter();poll();pollMedia(true);for(const id of ['alertsList','roadCurrentList','roadAlertCount','alertCount','riverAlertCount','districtStatusList','roadOfficialSummary']){const e=$(id);if(!e)continue;const ob=new MutationObserver(repair);ob.observe(e,{childList:true,subtree:true,characterData:true});}setInterval(poll,5000);setInterval(()=>{if(lastCheck){health();if($('districtLiveFresh'))$('districtLiveFresh').textContent=tr('७७ जिल्ला जोडिएको • समस्या भएका जिल्ला पहिले • जाँच ','77 districts connected • issues first • checked ')+time(lastCheck)}},1000);setInterval(()=>pollMedia(false),30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){poll();pollMedia(true)}});window.addEventListener('online',()=>{poll();pollMedia(true)});window.addEventListener('fs-language-change',renderAll)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();