(()=>{
'use strict';
const PAGE=document.body.dataset.page||'home';
const $=id=>document.getElementById(id);
const NPT='Asia/Kathmandu';
const BIPAD='https://bipadportal.gov.np/api/v1/';
const DATA='../../data/';
const ALLOWED=new Set([location.hostname,'bipadportal.gov.np','api.open-meteo.com','nominatim.openstreetmap.org']);
const SEV_RE=/danger|warning|evacuat|closed|blocked|rising|very high|high risk|red alert|orange alert|खतरा|चेतावनी|सतर्क|बन्द|अवरुद्ध|बढ्दो/i;
const HAZARD_ALERT_RE=/flash flood|flood warning|flood alert|landslide warning|landslide alert|बाढी चेतावनी|बाढीको चेतावनी|पहिरो चेतावनी/i;
const FLOOD_RE=/flood|flash flood|बाढी|डुबान|rasuwa|rasuwagadhi|bhotekoshi|bhote koshi|trishuli/i;
let weatherPos=null,weatherPlace='';
function npClock(d=Date.now()){try{return new Intl.DateTimeFormat('en-GB',{timeZone:NPT,day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(d))+' NPT'}catch{return'—'}}
function safeUrl(input){const u=new URL(input,location.href);if(!ALLOWED.has(u.hostname))throw Error('Blocked host');if(u.protocol!=='https:'&&u.origin!==location.origin)throw Error('Blocked protocol');return u.toString()}
async function getJSON(url,ms=7000){const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),ms);try{const r=await fetch(safeUrl(url),{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',signal:ctl.signal,headers:{accept:'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(to)}}
function rows(j){if(Array.isArray(j))return j;for(const k of ['results','data','objects','features']){if(Array.isArray(j?.[k]))return j[k];if(Array.isArray(j?.[k]?.results))return j[k].results}return[]}
function val(o,keys){for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null}
function num(v){const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null}
function raw(o){return JSON.stringify(o||{}).toLowerCase()}
function stamp(o){return val(o,['waterLevelOn','measuredOn','modifiedOn','updated_at','updatedAt','createdOn','created_at','createdAt','incidentOn','date','timestamp'])}
function title(o){return String(val(o,['titleNe','title','name','station_name','river_name','road_name','descriptionNe','description'])||'Official update')}
function status(o){return String(val(o,['status','severity','state','condition','remarks','descriptionNe','description','trend','steady'])||'')}
function words(o){const nested=[o?.incident,o?.event,o?.hazard,o?.loss].filter(x=>x&&typeof x==='object');return [title(o),status(o),val(o,['message','eventName','hazardType','incidentType','lossType','loss_type','type']),...nested.flatMap(x=>[title(x),status(x),val(x,['name','type','hazardType','incidentType'])])].filter(Boolean).join(' ').toLowerCase()}
function clear(n){if(n)while(n.firstChild)n.removeChild(n.firstChild)}
function node(tag,cls,txt){const x=document.createElement(tag);if(cls)x.className=cls;if(txt!==undefined)x.textContent=String(txt);return x}
function extLink(label,url){const a=node('a','',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';return a}
function setStatus(ok,msg){const s=$('appStatus');if(s)s.textContent=msg||(ok?'Updated '+npClock():'Data temporarily unavailable')}
function sourceTime(o){const s=stamp(o);if(!s)return'—';const d=new Date(s);return Number.isNaN(d.getTime())?String(s):npClock(d)}
function isHigh(o){const s=words(o);return SEV_RE.test(s)||HAZARD_ALERT_RE.test(s)}
function priority(o){const s=words(o);let p=0;if(/danger|evacuat|red alert|खतरा|खाली|बन्द/.test(s))p+=7;if(/warning|very high|high risk|rising|orange alert|चेतावनी|सतर्क|बढ्दो/.test(s))p+=5;if(HAZARD_ALERT_RE.test(s))p+=4;if(FLOOD_RE.test(s))p+=2;const d=new Date(stamp(o)||0);if(!Number.isNaN(d.getTime()))p+=Math.max(0,3-(Date.now()-d.getTime())/86400000);return p}
function highOnly(list){return list.filter(isHigh).sort((a,b)=>priority(b)-priority(a)||(+new Date(stamp(b)||0))-(+new Date(stamp(a)||0)))}
function card(container,tag,titleText,desc,meta,source){if(!container)return null;const box=node('article','item');if(tag)box.appendChild(node('span','tag'+(/danger|breaking|खतरा/i.test(tag)?' red':''),tag));box.appendChild(node('h4','',titleText));if(desc)box.appendChild(node('p','',desc));if(meta)box.appendChild(node('div','meta',meta));if(source?.url){const m=node('div','meta');m.appendChild(extLink(source.label||'Official source',source.url));box.appendChild(m)}container.appendChild(box);return box}
async function home(){
 const [p,people,cross,alerts]=await Promise.allSettled([getJSON(DATA+'floodsafe-police.json'),getJSON(DATA+'floodsafe-people-status.json'),getJSON(DATA+'rasuwa-crossborder.json'),getJSON(BIPAD+'alert/?limit=250&ordering=-createdOn')]);
 const pd=p.status==='fulfilled'?p.value:null,ps=people.status==='fulfilled'?people.value:null,cx=cross.status==='fulfilled'?cross.value:null,al=alerts.status==='fulfilled'?highOnly(rows(alerts.value)):[];
 if($('homeDeaths'))$('homeDeaths').textContent=pd?.total_deaths??'—';if($('homeMissing'))$('homeMissing').textContent=ps?.missing_minimum!=null?'≥ '+ps.missing_minimum:'—';if($('homeRescued'))$('homeRescued').textContent=ps?.rescued_alive??'—';if($('homeAlerts'))$('homeAlerts').textContent=al.length;
 const hot=$('homeHot');if(hot){clear(hot);if(cx?.severity==='HIGH_ATTENTION')card(hot,'HIGH ATTENTION',cx.event_ne||cx.event,cx.summary_ne||cx.summary,'Verified '+(cx.verified_date||'')+' • China MWR / Nepal authorities',{label:'Details',url:'./alerts.html'});for(const x of al.slice(0,2))card(hot,priority(x)>=9?'BREAKING':'LATEST',title(x),status(x),sourceTime(x),{label:'BIPAD',url:'https://bipadportal.gov.np/'});if(!hot.children.length)hot.appendChild(node('div','empty','हालको verified feed मा breaking/high-priority update भेटिएन। यो “पूर्ण सुरक्षित” भन्ने अर्थ होइन।'))}
 setStatus(!!(pd||ps||cx||al.length),'Official summaries checked • '+npClock());
}
function riverStage(o){const wl=num(val(o,['waterLevel','water_level','currentLevel','level','value'])),w=num(val(o,['warningLevel','warning_level','warning'])),d=num(val(o,['dangerLevel','danger_level','danger'])),s=status(o).toUpperCase();if((d!==null&&wl!==null&&wl>=d)||/DANGER/.test(s))return{tag:'DANGER',score:10,wl,w,d};if((w!==null&&wl!==null&&wl>=w)||/ABOVE WARNING/.test(s))return{tag:'WARNING',score:8,wl,w,d};if(/RISING/.test(s))return{tag:'RISING',score:6,wl,w,d};return{tag:'NORMAL',score:1,wl,w,d}}
async function alertsPage(){
 const [a,r,h,c]=await Promise.allSettled([getJSON(BIPAD+'alert/?limit=300&ordering=-createdOn'),getJSON(BIPAD+'river-stations/?limit=650'),getJSON(BIPAD+'highway/?limit=500'),getJSON(DATA+'rasuwa-crossborder.json')]);
 const alerts=a.status==='fulfilled'?highOnly(rows(a.value)):[],rivers=r.status==='fulfilled'?rows(r.value).map(o=>({o,s:riverStage(o)})).filter(x=>x.s.score>=6).sort((x,y)=>y.s.score-x.s.score):[],roads=h.status==='fulfilled'?rows(h.value).filter(o=>/closed|blocked|partial|अवरुद्ध|बन्द/i.test(words(o))):[],cx=c.status==='fulfilled'?c.value:null;
 if($('alertCount'))$('alertCount').textContent=alerts.length;if($('riverAlertCount'))$('riverAlertCount').textContent=rivers.length;if($('roadAlertCount'))$('roadAlertCount').textContent=roads.length;
 const out=$('alertsList');clear(out);if(cx?.severity==='HIGH_ATTENTION')card(out,'CROSS-BORDER WATCH',cx.event_ne||cx.event,cx.summary_ne||cx.summary,'Verified '+cx.verified_date,{label:'Verified advisory',url:cx.source_url});for(const o of alerts.slice(0,15))card(out,priority(o)>=9?'BREAKING':'HIGH PRIORITY',title(o),status(o),sourceTime(o),{label:'BIPAD/NDRRMA',url:'https://bipadportal.gov.np/'});for(const x of rivers.slice(0,10)){const d=x.s;card(out,d.tag,title(x.o),(d.wl!==null?'Water '+d.wl+' m • ':'')+(d.w!==null?'Warning '+d.w+' m • ':'')+(d.d!==null?'Danger '+d.d+' m':''),sourceTime(x.o),{label:'DHM/BIPAD',url:'https://www.dhm.gov.np/hydrology/floodMonitoring'})}for(const o of roads.slice(0,8))card(out,'ROAD',title(o),status(o),sourceTime(o),{label:'DoR via BIPAD',url:'https://bipadportal.gov.np/'});if(out&&!out.children.length)out.appendChild(node('div','empty','High-priority official alert अहिले feedमा भेटिएन। Feed unavailable भए appले “safe” भनेर assume गर्दैन।'));
 setStatus(!!(alerts.length||rivers.length||roads.length||cx),'High-priority sources checked • '+npClock());
}
function classifyPeople(o){const s=words(o);const count=Math.max(1,Math.round(num(val(o,['count','number','total']))||1));if(/missing|बेपत्ता|सम्पर्कविहीन/.test(s))return['Missing',count];if(/dead|death|deceased|मृत/.test(s))return['Death',count];if(/rescued|rescue|उद्धार/.test(s))return['Rescued',count];if(/injured|घाइते/.test(s))return['Injured',count];return['People record',count]}
function floodPeopleRecord(o){return FLOOD_RE.test(words(o))||FLOOD_RE.test(raw(o))}
async function peoplePage(){
 const [p,s,l]=await Promise.allSettled([getJSON(DATA+'floodsafe-police.json'),getJSON(DATA+'floodsafe-people-status.json'),getJSON(BIPAD+'loss-people/?limit=500')]);const pd=p.status==='fulfilled'?p.value:null,ps=s.status==='fulfilled'?s.value:null,live=l.status==='fulfilled'?rows(l.value).filter(floodPeopleRecord):[];
 if($('peopleBodies'))$('peopleBodies').textContent=pd?.total_deaths??ps?.recovered_bodies??'—';if($('peopleMissing'))$('peopleMissing').textContent=ps?.missing_minimum!=null?'≥ '+ps.missing_minimum:'—';if($('peopleRescued'))$('peopleRescued').textContent=ps?.rescued_alive??'—';if($('bipadPeopleRecords'))$('bipadPeopleRecords').textContent=live.length;
 const breakdown=$('peopleBreakdown');if(breakdown&&ps)breakdown.textContent=`Missing minimum breakdown: tourists ${ps.missing_tourists??'—'} • security ${ps.missing_security_total??'—'} (Army ${ps.missing_security?.nepal_army??'—'}, Nepal Police ${ps.missing_security?.nepal_police??'—'}, APF ${ps.missing_security?.armed_police_force??'—'}). Rescued alive: Nepali ${ps.rescued_nepali??'—'} • foreign ${ps.rescued_foreign??'—'}.`;
 const out=$('peopleLiveList');clear(out);const sorted=live.sort((a,b)=>(+new Date(stamp(b)||0))-(+new Date(stamp(a)||0))).slice(0,20);for(const o of sorted){const [kind,count]=classifyPeople(o);card(out,kind,title(o),`Count/record: ${count} • ${status(o)||'BIPAD people-loss record'}`,sourceTime(o),{label:'BIPAD/NDRRMA live record',url:'https://bipadportal.gov.np/'})}if(out&&!out.children.length)out.appendChild(node('div','empty','BIPAD live people-loss feedमा flood-related record अहिले parse हुन सकेन। Verified snapshot माथि कायम छ।'));
 setStatus(!!(pd||ps||live.length),'People sources checked • '+npClock());
}
function weatherName(code){const m={0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Fog',51:'Light drizzle',53:'Drizzle',55:'Dense drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorm',96:'Thunderstorm + hail',99:'Severe thunderstorm'};return m[Number(code)]||'Weather'}
async function reversePlace(p){try{const j=await getJSON(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${encodeURIComponent(p[0])}&lon=${encodeURIComponent(p[1])}&zoom=16&addressdetails=1&accept-language=ne,en`,5000),a=j.address||{};return[a.village||a.town||a.city||a.municipality||a.suburb,a.county||a.state_district,a.state].filter(Boolean).slice(0,3).join(' • ')||j.display_name?.split(',').slice(0,2).join(', ')||'Your location'}catch{return'Your GPS location'}}
async function weatherLoad(p){if(!p)return;weatherPos=p;const u=`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(p[0])}&longitude=${encodeURIComponent(p[1])}&current=temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,wind_gusts_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum&forecast_days=1&timezone=Asia%2FKathmandu`;try{const [w,place]=await Promise.all([getJSON(u,6500),weatherPlace?Promise.resolve(weatherPlace):reversePlace(p)]);weatherPlace=place;const c=w.current||{},d=w.daily||{};if($('wxPlace'))$('wxPlace').textContent=place+' • '+p[0].toFixed(4)+', '+p[1].toFixed(4);const temp=num(c.temperature_2m);if($('wxTemp'))$('wxTemp').textContent=temp!==null?Math.round(temp)+'°':'—°';if($('wxCondition'))$('wxCondition').textContent=weatherName(c.weather_code);const map={wxFeels:num(c.apparent_temperature)!=null?Math.round(num(c.apparent_temperature))+'°':'—',wxRain:num(c.precipitation)!=null?num(c.precipitation).toFixed(1)+' mm':'—',wxHumidity:num(c.relative_humidity_2m)!=null?Math.round(num(c.relative_humidity_2m))+'%':'—',wxWind:num(c.wind_speed_10m)!=null?Math.round(num(c.wind_speed_10m))+' km/h':'—',wxGust:num(c.wind_gusts_10m)!=null?Math.round(num(c.wind_gusts_10m))+' km/h':'—',wxChance:num(d.precipitation_probability_max?.[0])!=null?Math.round(num(d.precipitation_probability_max[0]))+'%':'—',wxRange:(num(d.temperature_2m_min?.[0])!=null?Math.round(num(d.temperature_2m_min[0]))+'°':'—')+' / '+(num(d.temperature_2m_max?.[0])!=null?Math.round(num(d.temperature_2m_max[0]))+'°':'—')};for(const[k,v]of Object.entries(map))if($(k))$(k).textContent=v;const ch=num(d.precipitation_probability_max?.[0])||0,rain=num(c.precipitation)||0,code=Number(c.weather_code);if($('wxRisk'))$('wxRisk').textContent=code>=95?'⚡ Thunderstorm signal — streams can rise rapidly.':rain>=5||ch>=70?'🌧 High local rain signal — monitor nearby streams and DHM alerts.':'No major weather signal from the local model right now. Always cross-check DHM/BIPAD for flood warnings.';setStatus(true,'Exact-location weather checked • '+npClock())}catch{setStatus(false,'Weather source unavailable — retrying automatically')}}
function askGPS(){const b=$('gpsWeatherBtn');if(b)b.disabled=true;if(!navigator.geolocation){setStatus(false,'GPS not supported');return}navigator.geolocation.getCurrentPosition(p=>{weatherPlace='';weatherLoad([p.coords.latitude,p.coords.longitude]);if(b)b.disabled=false},()=>{setStatus(false,'Location permission required');if(b)b.disabled=false},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function weatherPage(){const b=$('gpsWeatherBtn');if(b)b.addEventListener('click',askGPS);if(navigator.permissions)navigator.permissions.query({name:'geolocation'}).then(x=>{if(x.state==='granted')askGPS()}).catch(()=>{});setInterval(()=>{if(weatherPos&&!document.hidden)weatherLoad(weatherPos)},120000)}
async function newsPage(){
 const [a,b,p,c]=await Promise.allSettled([getJSON(BIPAD+'alert/?limit=300&ordering=-createdOn'),getJSON(BIPAD+'bipad-bulletin/?limit=30&ordering=-createdOn'),getJSON(DATA+'floodsafe-police.json'),getJSON(DATA+'rasuwa-crossborder.json')]);const items=[];if(a.status==='fulfilled')for(const o of highOnly(rows(a.value)).slice(0,16))items.push({rank:priority(o)+10,tag:priority(o)>=9?'BREAKING':'HOT',title:title(o),desc:status(o)||'Official BIPAD alert',time:stamp(o),src:'BIPAD/NDRRMA',url:'https://bipadportal.gov.np/'});if(b.status==='fulfilled')for(const o of highOnly(rows(b.value)).slice(0,8))items.push({rank:priority(o)+4,tag:'LATEST',title:title(o),desc:status(o)||'Official disaster bulletin',time:stamp(o),src:'BIPAD bulletin',url:'https://bipadportal.gov.np/'});if(c.status==='fulfilled'){const x=c.value;items.push({rank:20,tag:'HOT',title:`Rasuwa flood — ${x.total_deaths} verified deaths`,desc:'Nepal Police verified fatality bulletin. Open People Status for missing/rescued breakdown.',time:x.official_update_iso,src:'Nepal Police',url:x.source_url})}if(p.status==='fulfilled'){const x=p.value;items.push({rank:24,tag:'BREAKING WATCH',title:x.event_ne||x.event,desc:x.summary_ne||x.summary,time:x.verified_date,src:'China MWR + Nepal authorities',url:x.source_url})}items.sort((x,y)=>y.rank-x.rank||(+new Date(y.time||0))-(+new Date(x.time||0)));
 const out=$('newsList');clear(out);for(const x of items.slice(0,20))card(out,x.tag,x.title,x.desc,x.time?npClock(x.time):'Latest verified snapshot',{label:x.src,url:x.url});if(out&&!out.children.length)out.appendChild(node('div','empty','Verified BREAKING/HOT/LATEST update अहिले भेटिएन। सामान्य समाचार जानाजानी यहाँ देखाइँदैन।'));if($('newsCount'))$('newsCount').textContent=items.length;setStatus(!!items.length,'Breaking/high-priority sources checked • '+npClock());
}
function boot(){const tick=()=>{if(document.hidden)return;if(PAGE==='home')home();if(PAGE==='alerts')alertsPage();if(PAGE==='people')peoplePage();if(PAGE==='news')newsPage()};if(PAGE==='home')home();else if(PAGE==='alerts')alertsPage();else if(PAGE==='people')peoplePage();else if(PAGE==='weather')weatherPage();else if(PAGE==='news')newsPage();if(['home','alerts','people','news'].includes(PAGE))setInterval(tick,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick()});window.addEventListener('online',tick);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();