(()=>{
'use strict';
if(window.__floodsafeDisasterMonitor)return;window.__floodsafeDisasterMonitor=true;
const PAGE=document.body.dataset.page||'home',$=id=>document.getElementById(id);
const KCHA='https://kchakhabar.com/api/v1/today.json?limit=80';
const USGS='https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson';
const BIPAD='https://bipadportal.gov.np/api/v1/incident/?limit=120&ordering=-incidentOn';
const PEOPLE='../../data/floodsafe-people-status.json',POLICE='../../data/floodsafe-police.json';
const FLOOD=/\b(flood|flash flood|inundat|river flood)\b|बाढी|डुबान|नदीमा बाढी|खोलामा बाढी/i;
const LANDSLIDE=/\b(landslide|mudslide|debris flow)\b|पहिरो|भूस्खलन/i;
const QUAKE=/\b(earthquake|quake|seismic)\b|भूकम्प/i;
const AIR=/\b(plane crash|aircraft crash|air crash|helicopter crash|aviation accident)\b|विमान दुर्घटना|हवाई दुर्घटना|हेलिकप्टर दुर्घटना/i;
const ACCIDENT=/\b(accident|collision|crash|fire|explosion|electrocution|drowning|boat capsiz|bus accident|truck accident|jeep accident)\b|दुर्घटना|ठक्कर|आगलागी|विस्फोट|डुबेर|डुबानबाट मृत्यु|बस दुर्घटना|जीप दुर्घटना|सवारी दुर्घटना/i;
const FOREIGN=/\b(india|indian|china|chinese|pakistan|bangladesh|sri lanka|iran|iraq|israel|gaza|russia|ukraine|united states|usa|america|japan|indonesia|philippines|myanmar|afghanistan|turkey|europe|australia)\b|भारत|चीन|पाकिस्तान|बंगलादेश|श्रीलंका|इरान|इराक|इजरायल|गाजा|रुस|युक्रेन|अमेरिका|जापान|इन्डोनेसिया|फिलिपिन्स|म्यानमार|अफगानिस्तान|टर्की|अष्ट्रेलिया/i;
const NEPAL=/\b(nepal|kathmandu|pokhara|lalitpur|bhaktapur|chitwan|rasuwa|nuwakot|dhading|gorkha|tanahun|mustang|manang|solukhumbu|sindhupalchok|dolakha|kavre|makwanpur|parsa|bara|rautahat|sarlahi|mahottari|dhanusha|siraha|saptari|morang|sunsari|jhapa|ilam|taplejung|panchthar|dhankuta|bhojpur|khotang|udayapur|baglung|myagdi|parbat|kaski|lamjung|syangja|nawalparasi|rupandehi|kapilvastu|dang|banke|bardiya|surkhet|dailekh|jajarkot|rukum|rolpa|pyuthan|gulmi|arghakhanchi|palpa|kailali|kanchanpur|dadeldhura|doti|achham|bajura|bajhang|baitadi|darchula|jumla|humla|mugu|dolpa|kalikot)\b|नेपाल|काठमाडौं|काठमाडौँ|पोखरा|ललितपुर|भक्तपुर|चितवन|रसुवा|नुवाकोट|धादिङ|गोरखा|तनहुँ|मुस्ताङ|मनाङ|सोलुखुम्बु|सिन्धुपाल्चोक|दोलखा|काभ्रे|मकवानपुर|पर्सा|बारा|रौतहट|सर्लाही|महोत्तरी|धनुषा|सिराहा|सप्तरी|मोरङ|सुनसरी|झापा|इलाम|ताप्लेजुङ|पाँचथर|धनकुटा|भोजपुर|खोटाङ|उदयपुर|बागलुङ|म्याग्दी|पर्वत|कास्की|लमजुङ|स्याङ्जा|नवलपरासी|रुपन्देही|कपिलवस्तु|दाङ|बाँके|बर्दिया|सुर्खेत|दैलेख|जाजरकोट|रुकुम|रोल्पा|प्युठान|गुल्मी|अर्घाखाँची|पाल्पा|कैलाली|कञ्चनपुर|डडेलधुरा|डोटी|अछाम|बाजुरा|बझाङ|बैतडी|दार्चुला|जुम्ला|हुम्ला|मुगु|डोल्पा|कालिकोट/i;
let media=[],quakes=[],incidents=[],people=null,police=null,lastMedia=0,lastRapid=0,busy=false;
const norm=s=>String(s||'').toLowerCase().replace(/[^\p{L}\p{N}.]+/gu,' ').trim();
const txt=s=>[s?.topic_ne,s?.topic_en,s?.summary_ne,s?.summary_en].filter(Boolean).join(' ');
const when=s=>s?.updated_at||s?.first_reported||null;
const age=t=>{const n=+new Date(t||0);return n?Math.max(0,Date.now()-n):Infinity};
function make(tag,cls,t){const e=document.createElement(tag);if(cls)e.className=cls;if(t!==undefined)e.textContent=t;return e}
function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}
function nepDigits(s){return String(s).replace(/[०-९]/g,d=>'0123456789'['०१२३४५६७८९'.indexOf(d)])}
function magnitude(s){const t=nepDigits(txt(s));const m=t.match(/(?:magnitude|mag(?:nitude)?|m\s*)?\s*([6-9](?:\.\d+)?)\s*(?:magnitude|mag|richter)?/i);return m?Number(m[1]):null}
function sourceAge(t){const m=Math.max(0,Math.round(age(t)/60000));if(!Number.isFinite(m))return'समय उपलब्ध छैन';return m<1?'अहिले':m<60?m+' मिनेट अघि':Math.round(m/60)+' घण्टा अघि'}
function storyNepal(s){const t=txt(s);if(NEPAL.test(t))return true;if(FOREIGN.test(t))return false;return /[\u0900-\u097F]/.test(t)}
function kindOf(s){const t=txt(s);if(FLOOD.test(t))return'flood';if(LANDSLIDE.test(t))return'landslide';if(AIR.test(t)&&storyNepal(s))return'air';if(QUAKE.test(t)){const m=magnitude(s);if(m!==null&&m>=6.5&&storyNepal(s))return'quake'}return null}
function qualifyingUSGS(){return(quakes||[]).filter(q=>{const c=q?.geometry?.coordinates||[],p=q?.properties||{},lat=Number(c[1]),lon=Number(c[0]),m=Number(p.mag);return Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=26&&lat<=31.8&&lon>=80&&lon<=89.5&&m>=6.5&&age(p.time)<=7*86400e3}).sort((a,b)=>Number(b?.properties?.time||0)-Number(a?.properties?.time||0))}
function mediaMajor(){const qs=qualifyingUSGS(),top=(media||[]).slice(0,24),out=[];for(let i=0;i<top.length;i++){const s=top[i],t=txt(s);if(age(when(s))>12*3600e3||!storyNepal(s))continue;let kind=kindOf(s),q=null;if(!kind&&QUAKE.test(t)&&qs.length){q=qs.find(x=>Math.abs(Number(x.properties.time)-Number(new Date(when(s))))<36*3600e3)||qs[0];if(q)kind='quake'}if(!kind)continue;if(kind==='quake'){q=q||qs[0];const mm=magnitude(s)??Number(q?.properties?.mag);if(!Number.isFinite(mm)||mm<6.5)continue}const priority={flood:400,landslide:300,quake:250,air:200}[kind]||0,coverage=Math.min(30,Number(s.source_count||s.sources?.length||1))*3,recency=Math.max(0,50-Math.floor(age(when(s))/600000)),rank=Math.max(0,24-i);out.push({kind,story:s,quake:q,score:priority+coverage+recency+rank})}return out.sort((a,b)=>b.score-a.score)[0]||null}
function label(k){return k==='flood'?'🌊 बाढी':k==='landslide'?'⛰️ पहिरो':k==='quake'?'🌐 6.5+ भूकम्प':'✈️ नेपाल हवाई दुर्घटना'}
function sourceLine(s){const names=(s?.sources||[]).slice(0,3).map(x=>x.publisher).filter(Boolean);const n=Number(s?.source_count||s?.sources?.length||0);return (n?`${n} newsrooms`:'Nepal media')+(names.length?' • '+names.join(', '):'')+' • '+sourceAge(when(s))}
function eventUrl(x){return x?.story?.url||x?.story?.sources?.[0]?.url||x?.quake?.properties?.url||''}
function summary(x){const s=x.story;let v=String(s?.summary_ne||s?.summary_en||'').trim();if(v.length>260)v=v.slice(0,257)+'…';if(x.kind==='quake'&&x.quake){const p=x.quake.properties||{},c=x.quake.geometry?.coordinates||[];const extra=`USGS: M${Number(p.mag).toFixed(1)} • ${p.place||'Nepal region'}${Number.isFinite(Number(c[2]))?' • depth '+Math.round(Number(c[2]))+' km':''}`;v=v?v+' • '+extra:extra}return v||'विस्तृत जानकारीका लागि स्रोत खोल्नुहोस्।'}
function activeKey(x){return norm((x?.story?.topic_ne||x?.story?.topic_en||'')+' '+label(x?.kind||''))}
function snapshotMatches(x){if(!x||!people)return false;const e=norm((people.event||'')+' '+(people.event_ne||'')),a=activeKey(x)+' '+norm(txt(x.story));if(!e)return false;const tokens=e.split(' ').filter(w=>w.length>=4&&!/flood|बाढी|landslide|पहिरो|earthquake|भूकम्प|crash|दुर्घटना/.test(w));return tokens.some(w=>a.includes(w))}
function accidentStories(){return(media||[]).filter(s=>age(when(s))<=18*3600e3&&storyNepal(s)&&ACCIDENT.test(txt(s))&&!FLOOD.test(txt(s))&&!LANDSLIDE.test(txt(s))&&!QUAKE.test(txt(s))).slice(0,10)}
function incidentRows(j){if(Array.isArray(j))return j;for(const k of ['results','data','objects'])if(Array.isArray(j?.[k]))return j[k];return[]}
function incidentText(o){try{return JSON.stringify(o||{})}catch{return''}}
function accidentIncidents(){return(incidents||[]).filter(o=>ACCIDENT.test(incidentText(o))&&!FLOOD.test(incidentText(o))&&!LANDSLIDE.test(incidentText(o))).slice(0,10)}
function incidentTitle(o){return String(o?.titleNe||o?.title||o?.name||o?.hazard?.titleNe||o?.hazard?.title||o?.hazard?.name||o?.descriptionNe||o?.description||'नेपाल घटना अपडेट')}
function incidentStamp(o){return o?.incidentOn||o?.createdOn||o?.created_at||o?.modifiedOn||o?.updated_at||null}
function incidentDetail(o){const d=o?.peopleDeathCount??o?.peopleDeath??o?.deaths??o?.deathCount,inj=o?.peopleInjuredCount??o?.injured??o?.injuryCount,mis=o?.peopleMissingCount??o?.missing??o?.missingCount,parts=[];if(d!==undefined&&d!==null)parts.push('मृत्यु '+d);if(inj!==undefined&&inj!==null)parts.push('घाइते '+inj);if(mis!==undefined&&mis!==null)parts.push('बेपत्ता '+mis);return parts.join(' • ')||String(o?.descriptionNe||o?.description||o?.remarks||'BIPAD incident report')}
function addCard(out,tag,h,b,meta,url){if(!out)return;const a=make('article','item');a.appendChild(make('span','tag '+(/FLOOD|QUAKE|AIR|LANDSLIDE|ACTIVE/.test(tag)?'red':''),tag));a.appendChild(make('h4','',h));if(b)a.appendChild(make('p','',b));if(meta)a.appendChild(make('div','meta',meta));if(url){const r=make('div','meta'),ln=make('a','','स्रोत खोल्नुहोस्');ln.href=url;ln.target='_blank';ln.rel='noopener noreferrer';ln.referrerPolicy='no-referrer';r.appendChild(ln);a.appendChild(r)}out.appendChild(a)}
function renderSpotlight(active){const out=$('disasterSpotlightList'),state=$('disasterSpotlightState');if(!out)return;clear(out);if(active){const s=active.story,tag=active.kind==='flood'?'FLOOD':active.kind==='landslide'?'LANDSLIDE':active.kind==='quake'?'6.5+ QUAKE':'NEPAL AIR';addCard(out,tag,s.topic_ne||s.topic_en||label(active.kind),summary(active),sourceLine(s),eventUrl(active));if(state)state.textContent='Media highlight सक्रिय • यो घटना top national newsमा रहँदासम्म मात्र यहाँ देखिन्छ';}else{const ai=accidentIncidents(),am=accidentStories();if(ai.length){ai.slice(0,PAGE==='people'?8:3).forEach(o=>addCard(out,'ACCIDENT',incidentTitle(o),incidentDetail(o),'BIPAD • '+sourceAge(incidentStamp(o)),'https://bipadportal.gov.np/incidents/'));if(state)state.textContent='अहिले ठूलो disaster media highlightमा छैन • BIPAD Nepal accident updates';}else if(am.length){am.slice(0,PAGE==='people'?8:3).forEach(s=>addCard(out,'ACCIDENT',s.topic_ne||s.topic_en||'नेपाल दुर्घटना',String(s.summary_ne||s.summary_en||'').slice(0,240),sourceLine(s),s.url||s.sources?.[0]?.url));if(state)state.textContent='अहिले ठूलो disaster media highlightमा छैन • Nepal accident reports';}else{out.appendChild(make('div','empty','अहिले ठूलो disaster highlight वा नयाँ accident report भेटिएको छैन। Monitoring चलिरहेको छ।'));if(state)state.textContent='नेपालभरि नयाँ disaster/accident signal खोजिँदैछ…'}}}
function renderHuman(active){const home=$('humanStatsSection'),peopleSec=$('peopleStatsSection'),live=$('peopleLiveSection'),matched=snapshotMatches(active);if(home)home.hidden=!matched;if(peopleSec)peopleSec.hidden=!matched;if(live)live.hidden=!(active&&['flood','landslide'].includes(active.kind));if(matched){const name=active.story?.topic_ne||active.story?.topic_en||people?.event_ne||people?.event||'Active disaster';const ht=$('humanStatsTitle'),pt=$('peopleStatsTitle');if(ht)ht.textContent=name+' • Human Status';if(pt)pt.textContent=name+' • Human Status';const fresh=people?.updated_date||police?.official_update_iso||'';const hf=$('humanFresh'),pf=$('peopleStatsFresh');if(hf)hf.textContent='यो active media-highlightसँग match भएको verified snapshot • '+(fresh?sourceAge(fresh):'');if(pf)pf.textContent='Verified snapshot • '+(fresh?sourceAge(fresh):'')}}}
function renderRapid(active){const out=$('rapidSignalList');if(!out)return;clear(out);const sig=[];for(const s of(media||[]).slice(0,30)){if(age(when(s))>8*3600e3||!storyNepal(s))continue;const t=txt(s);if(FLOOD.test(t))sig.push({tag:'MEDIA FLOOD',h:s.topic_ne||s.topic_en,b:'Media early signal — official river level होइन। '+String(s.summary_ne||s.summary_en||'').slice(0,180),meta:sourceLine(s),url:s.url});else if(LANDSLIDE.test(t))sig.push({tag:'MEDIA LANDSLIDE',h:s.topic_ne||s.topic_en,b:'Media early signal — BIPAD/DoR confirmationसँग हेर्नुहोस्। '+String(s.summary_ne||s.summary_en||'').slice(0,180),meta:sourceLine(s),url:s.url});if(sig.length>=5)break}for(const q of qualifyingUSGS().slice(0,2)){const p=q.properties||{},c=q.geometry?.coordinates||[];sig.push({tag:'USGS 6.5+',h:`M${Number(p.mag).toFixed(1)} • ${p.place||'Nepal region'}`,b:'USGS rapid earthquake signal'+(Number.isFinite(Number(c[2]))?' • depth '+Math.round(Number(c[2]))+' km':''),meta:sourceAge(p.time),url:p.url})}sig.slice(0,6).forEach(x=>addCard(out,x.tag,x.h,x.b,x.meta,x.url));if(!out.children.length)out.appendChild(make('div','empty','नयाँ rapid flood/landslide/6.5+ earthquake signal खोजिँदैछ…'));const st=$('rapidSignalState');if(st)st.textContent='Early signals मात्र • official flood level/road status DHM/BIPAD/DoR बाटै'}
function render(){const active=mediaMajor();window.__floodsafeDisasterState={active,mediaCount:media.length,quakeCount:qualifyingUSGS().length,at:Date.now()};renderSpotlight(active);renderHuman(active);renderRapid(active)}
async function get(url,ms=7000){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
async function refreshMedia(force=false){if(!force&&Date.now()-lastMedia<55000)return;lastMedia=Date.now();try{const j=await get(KCHA,7000);if(Array.isArray(j?.stories))media=j.stories}catch{}render()}
async function refreshRapid(force=false){if(!force&&Date.now()-lastRapid<55000)return;lastRapid=Date.now();const [q,i,p,po]=await Promise.allSettled([get(USGS,7000),get(BIPAD,6500),get(PEOPLE+'?t='+Date.now(),5000),get(POLICE+'?t='+Date.now(),5000)]);if(q.status==='fulfilled')quakes=q.value?.features||[];if(i.status==='fulfilled')incidents=incidentRows(i.value);if(p.status==='fulfilled')people=p.value;if(po.status==='fulfilled')police=po.value;render()}
async function cycle(force=false){if(busy)return;busy=true;try{await Promise.all([refreshMedia(force),refreshRapid(force)])}finally{busy=false}}
async function boot(){await cycle(true);setInterval(()=>cycle(false),5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)cycle(true)});window.addEventListener('online',()=>cycle(true));const root=document.querySelector('main');if(root){let pending=false;new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;render()})}).observe(root,{childList:true,subtree:true,characterData:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
