(()=>{
'use strict';
if(window.__fsDistrictLiveV4)return;window.__fsDistrictLiveV4=true;
if((document.body.dataset.page||'')!=='alerts')return;
const $=id=>document.getElementById(id),API='https://bipadportal.gov.np/api/v1/';
const DISTRICTS=[['Taplejung','ताप्लेजुङ'],['Panchthar','पाँचथर'],['Ilam','इलाम'],['Jhapa','झापा'],['Morang','मोरङ'],['Sunsari','सुनसरी'],['Dhankuta','धनकुटा'],['Terhathum','तेह्रथुम'],['Sankhuwasabha','संखुवासभा'],['Bhojpur','भोजपुर'],['Solukhumbu','सोलुखुम्बु'],['Okhaldhunga','ओखलढुङ्गा'],['Khotang','खोटाङ'],['Udayapur','उदयपुर'],['Saptari','सप्तरी'],['Siraha','सिराहा'],['Dhanusha','धनुषा'],['Mahottari','महोत्तरी'],['Sarlahi','सर्लाही'],['Rautahat','रौतहट'],['Bara','बारा'],['Parsa','पर्सा'],['Dolakha','दोलखा'],['Sindhupalchok','सिन्धुपाल्चोक'],['Rasuwa','रसुवा'],['Dhading','धादिङ'],['Nuwakot','नुवाकोट'],['Kathmandu','काठमाडौं'],['Bhaktapur','भक्तपुर'],['Lalitpur','ललितपुर'],['Kavrepalanchok','काभ्रेपलाञ्चोक'],['Ramechhap','रामेछाप'],['Sindhuli','सिन्धुली'],['Makwanpur','मकवानपुर'],['Chitwan','चितवन'],['Gorkha','गोरखा'],['Manang','मनाङ'],['Mustang','मुस्ताङ'],['Myagdi','म्याग्दी'],['Kaski','कास्की'],['Lamjung','लमजुङ'],['Tanahun','तनहुँ'],['Nawalpur','नवलपुर'],['Syangja','स्याङ्जा'],['Parbat','पर्वत'],['Baglung','बागलुङ'],['Rukum East','रुकुम पूर्व'],['Rolpa','रोल्पा'],['Pyuthan','प्युठान'],['Gulmi','गुल्मी'],['Arghakhanchi','अर्घाखाँची'],['Palpa','पाल्पा'],['Nawalparasi West','नवलपरासी पश्चिम'],['Rupandehi','रुपन्देही'],['Kapilvastu','कपिलवस्तु'],['Dang','दाङ'],['Banke','बाँके'],['Bardiya','बर्दिया'],['Rukum West','रुकुम पश्चिम'],['Salyan','सल्यान'],['Dolpa','डोल्पा'],['Jumla','जुम्ला'],['Mugu','मुगु'],['Humla','हुम्ला'],['Kalikot','कालिकोट'],['Jajarkot','जाजरकोट'],['Dailekh','दैलेख'],['Surkhet','सुर्खेत'],['Bajura','बाजुरा'],['Bajhang','बझाङ'],['Darchula','दार्चुला'],['Baitadi','बैतडी'],['Dadeldhura','डडेलधुरा'],['Doti','डोटी'],['Achham','अछाम'],['Kailali','कैलाली'],['Kanchanpur','कञ्चनपुर']];
const SPECIAL={Nawalpur:['nawalparasi east','nawalparasi purba','bardaghat susta east','नवलपरासी पूर्व','नवलपुर'],'Nawalparasi West':['nawalparasi west','nawalparasi paschim','bardaghat susta west','नवलपरासी पश्चिम'],'Rukum East':['rukum east','eastern rukum','रुकुम पूर्व'],'Rukum West':['rukum west','western rukum','रुकुम पश्चिम'],Kavrepalanchok:['kavre','kavrepalanchok','काभ्रे','काभ्रेपलाञ्चोक']};
let river=[],rain=[],roads=[],alerts=[],busy=false,lastCheck=0,rendering=false;
const lang=()=>localStorage.getItem('fs23-lang')==='en'?'en':'ne',tr=(ne,en)=>window.FSLang?.pick?window.FSLang.pick(ne,en):(lang()==='en'?en:ne),rows=j=>Array.isArray(j)?j:(j?.results||j?.data||j?.objects||[]),txt=o=>{try{return JSON.stringify(o||{}).toLowerCase()}catch{return''}};
const stamp=o=>o?.modifiedOn||o?.updatedOn||o?.measuredOn||o?.waterLevelOn||o?.createdOn||o?.created_at||o?.updated_at||o?.date||null;
async function get(url,ms=6500){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_district='+Date.now(),{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
function aliases(d){const [en,ne]=d;return [en.toLowerCase(),ne,...(SPECIAL[en]||[])].map(x=>String(x).toLowerCase())}
function matches(o,d){const s=txt(o);return aliases(d).some(a=>s.includes(a))}
function roadState(o){const s=txt(o);if(/partial|partially|partial_open|one.?way|आंशिक|एकतर्फी/.test(s))return'PARTIAL';if(/closed|blocked|obstructed|पूर्ण बन्द|अवरुद्ध|सडक बन्द/.test(s))return'CLOSED';if(/\bopen(?:ed)?\b|fully open|सुचारु|खुला/.test(s))return'OPEN';return'OTHER'}
function alertActive(o){const s=txt(o),exp=o?.expiresOn||o?.expireOn||o?.expires_at||o?.endDate;if(o?.active===false||o?.isActive===false||/inactive|expired|archived|समाप्त/.test(s))return false;if(exp&&+new Date(exp)<Date.now())return false;return /(danger|warning|high|red|orange|खतरा|चेतावनी|उच्च|सतर्क)/.test(s)}
function latestRoads(){const m=new Map();for(const o of roads){const k=String(o?.id||o?.pk||o?.roadName||o?.highwayName||o?.title||o?.name||JSON.stringify(o).slice(0,80));const old=m.get(k);if(!old||+new Date(stamp(o)||0)>=+new Date(stamp(old)||0))m.set(k,o)}return [...m.values()]}
function npTime(t=Date.now()){try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return'—'}}
function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}function make(t,c,x){const e=document.createElement(t);if(c)e.className=c;if(x!==undefined)e.textContent=x;return e}
function fillFilter(){const s=$('districtFilter');if(!s)return;if(s.options.length!==78){s.innerHTML='';const all=document.createElement('option');all.value='ALL';all.textContent=tr('सबै ७७ जिल्ला','All 77 districts');s.appendChild(all);for(const [en,ne] of DISTRICTS){const o=document.createElement('option');o.value=en;o.textContent=lang()==='en'?en:ne;s.appendChild(o)}}if(!s.dataset.bound){s.dataset.bound='1';s.addEventListener('change',render)}}
function dataFor(d){const latest=latestRoads(),rs=river.filter(o=>matches(o,d)),rn=rain.filter(o=>matches(o,d)),rd=latest.filter(o=>matches(o,d)),al=alerts.filter(o=>matches(o,d)&&alertActive(o)),closed=rd.filter(o=>roadState(o)==='CLOSED').length,partial=rd.filter(o=>roadState(o)==='PARTIAL').length;return{d,rs,rn,rd,al,closed,partial,issue:closed+partial+al.length}}
function card(out,x){const [en,ne]=x.d,a=make('article','item');a.dataset.districtOwner='1';if(x.issue)a.appendChild(make('span','tag '+(x.closed?'red':''),x.closed?tr('समस्या','ISSUE'):tr('सतर्क','WATCH')));a.appendChild(make('h4','',lang()==='en'?en:ne));const body=tr('नदी स्टेशन ','River stations ')+x.rs.length+tr(' • वर्षा स्टेशन ',' • rain stations ')+x.rn.length+tr(' • बन्द सडक ',' • closed roads ')+x.closed+tr(' • आंशिक ',' • partial ')+x.partial+tr(' • सक्रिय चेतावनी ',' • active alerts ')+x.al.length;a.appendChild(make('p','',body));a.appendChild(make('div','meta',x.issue?tr('स्रोतमा सक्रिय समस्या भेटियो','Active issue found in source'):tr('हाल feedमा सक्रिय ठूलो समस्या भेटिएको छैन','No major active issue found in the current feed')));out.appendChild(a)}
function render(){const out=$('districtStatusList'),sel=$('districtFilter');if(!out)return;rendering=true;try{fillFilter();const selected=sel?.value||'ALL',sourceSeen=lastCheck>0,all=DISTRICTS.map(dataFor);clear(out);if(!sourceSeen){out.appendChild(make('div','empty',tr('७७ जिल्लाको live source जाँच हुँदैछ…','Checking live sources for all 77 districts…')))}else if(selected==='ALL'){const issues=all.filter(x=>x.issue>0).sort((a,b)=>b.issue-a.issue).slice(0,20);if(issues.length)issues.forEach(x=>card(out,x));else out.appendChild(make('div','empty',tr('अहिले ७७ जिल्लाको connected feedमा सक्रिय सडक/चेतावनी समस्या भेटिएको छैन। जिल्ला छानेर नदी/वर्षा coverage हेर्नुहोस्।','No active road/alert issue is currently found in the connected 77-district feed. Select a district to view river/rain coverage.')))}else{const x=all.find(v=>v.d[0]===selected);if(x)card(out,x)}const f=$('districtLiveFresh');if(f)f.textContent=tr('७७ जिल्ला जोडिएको • स्रोत जाँच ','77 districts connected • source checked ')+npTime(lastCheck||Date.now());window.__fsDistrictState={districts:77,issues:all.filter(x=>x.issue>0).length,checkedAt:lastCheck}}finally{rendering=false}}
async function poll(){if(busy||document.hidden||!navigator.onLine)return;busy=true;try{const [rv,rn,hw,al]=await Promise.allSettled([get(API+'river-stations/?limit=700'),get(API+'rain-stations/?limit=700'),get(API+'highway/?limit=800'),get(API+'alert/?limit=300&ordering=-createdOn')]);if(rv.status==='fulfilled')river=rows(rv.value);if(rn.status==='fulfilled')rain=rows(rn.value);if(hw.status==='fulfilled')roads=rows(hw.value);if(al.status==='fulfilled')alerts=rows(al.value);lastCheck=Date.now();render()}finally{busy=false}}
function boot(){fillFilter();render();poll();const out=$('districtStatusList');if(out){let q=false;const ob=new MutationObserver(()=>{if(rendering||q||!lastCheck)return;q=true;queueMicrotask(()=>{q=false;render()})});ob.observe(out,{childList:true,subtree:true,characterData:true});window.__fsDistrictOwnerObserver=ob}setInterval(poll,15000);setInterval(()=>{if(lastCheck)render()},1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});window.addEventListener('online',poll);window.addEventListener('fs-language-change',()=>{const s=$('districtFilter'),v=s?.value||'ALL';if(s){s.innerHTML='';fillFilter();s.value=v}render()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();