(()=>{'use strict';
if(window.__fsFloodCoreV15)return;window.__fsFloodCoreV15=true;
const $=id=>document.getElementById(id),B={minLon:80,maxLon:88.35,minLat:26.2,maxLat:30.5},HOME_KEY='fs-nepal-monitor-v1',ALERT_KEY='fs-nepal-alerts-on';
const S={lat:null,lon:null,kind:null,stations:[],allRiverStations:[],latestRiverStations:[],lastRiverReadings:[],riverObservations:[],alertsOn:localStorage.getItem(ALERT_KEY)==='1',lastRisk:-1,rainNow:null,lang:localStorage.getItem('fs-flood-lang')==='en'?'en':'ne',updatedAt:null};
const tr=(ne,en)=>S.lang==='en'?en:ne,num=v=>{const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null},val=(o,ks)=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null};
function flat(o){return o&&typeof o==='object'&&o.fields&&typeof o.fields==='object'?Object.assign({},o.fields,o):o}
function coords(o){o=flat(o);const c=o?._stationCoordinate||o?.point?.coordinates||o?.location?.coordinates||o?.geometry?.coordinates;if(Array.isArray(c)&&c.length>=2&&Number.isFinite(+c[0])&&Number.isFinite(+c[1])){const a=+c[0],b=+c[1];if(a>=79.5&&a<=89&&b>=26&&b<=31)return[b,a];if(b>=79.5&&b<=89&&a>=26&&a<=31)return[a,b]}const la=num(val(o,['latitude','lat','stationLatitude','station_latitude'])),lo=num(val(o,['longitude','lon','lng','stationLongitude','station_longitude']));return la!==null&&lo!==null?[la,lo]:null}
const lat=o=>coords(o)?.[0]??null,lon=o=>coords(o)?.[1]??null,name=o=>String(val(flat(o),['river_name','riverName','station_name','stationName','title','name'])||flat(o)?.station?.name||tr('नदी स्टेशन','River station'));
const stamp=o=>val(flat(o),['_measurementTime','waterLevelOn','water_level_on','measuredOn','measured_on','measurementTime','observationTime']);
const level=o=>num(val(flat(o),['waterLevel','water_level','currentWaterLevel','current_water_level','currentLevel','current_level','level','_lastWaterLevel'])),warning=o=>num(val(flat(o),['warningLevel','warning_level','warningThreshold','warning_threshold','_lastWarningLevel'])),danger=o=>num(val(flat(o),['dangerLevel','danger_level','dangerThreshold','danger_threshold','_lastDangerLevel']));
const inside=(la,lo)=>Number.isFinite(la)&&Number.isFinite(lo)&&la>=B.minLat&&la<=B.maxLat&&lo>=B.minLon&&lo<=B.maxLon;
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
function hasReading(o){return !!o&&level(o)!==null}
function stage(o){const wl=level(o),w=warning(o),d=danger(o),raw=String(val(flat(o),['_officialStatus','status','status_name','alertStatus','alert_status','riskLevel','risk_level'])||'').toUpperCase();if(!hasReading(o))return{key:'unknown',rank:-1,wl,w,d};if((wl!==null&&d!==null&&d>0&&wl>=d)||(/DANGER|RED/.test(raw)&&!/BELOW\s+DANGER/.test(raw)))return{key:'danger',rank:3,wl,w,d};if((wl!==null&&w!==null&&w>0&&wl>=w)||(/WARNING|ORANGE/.test(raw)&&!/BELOW\s+WARNING/.test(raw)))return{key:'warning',rank:2,wl,w,d};if(/WATCH|RISING|INCREASING|YELLOW/.test(raw))return{key:'watch',rank:1,wl,w,d};return{key:'normal',rank:0,wl,w,d}}
function age(t){const x=+new Date(t||0);if(!x)return tr('आधिकारिक समय उपलब्ध छैन','Official time unavailable');const s=Math.max(0,Math.floor((Date.now()-x)/1000));if(s<60)return tr(`${s} सेकेन्ड अघि`,`${s}s ago`);const m=Math.floor(s/60);if(m<60)return tr(`${m} मिनेट अघि`,`${m}m ago`);const h=Math.floor(m/60);if(h<48)return tr(`${h} घण्टा अघि`,`${h}h ago`);return tr(`${Math.floor(h/24)} दिन अघि`,`${Math.floor(h/24)}d ago`)}
function statusLabel(k){return S.lang==='en'?({danger:'DANGER',warning:'WARNING',watch:'WATCH',normal:'NORMAL',unknown:'NO OFFICIAL READING'}[k]||'NO OFFICIAL READING'):({danger:'खतरा',warning:'चेतावनी',watch:'निगरानी',normal:'सामान्य',unknown:'आधिकारिक पढाइ छैन'}[k]||'आधिकारिक पढाइ छैन')}
async function get(url,ms=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function weather(){if(!inside(S.lat,S.lon)){S.rainNow=null;return}try{const j=await get(`https://api.open-meteo.com/v1/forecast?latitude=${S.lat}&longitude=${S.lon}&current=temperature_2m,relative_humidity_2m,precipitation,rain,weather_code,wind_speed_10m&timezone=Asia%2FKathmandu`),c=j.current||{};S.rainNow=num(c.rain??c.precipitation);if($('temp'))$('temp').textContent=c.temperature_2m!=null?Math.round(c.temperature_2m)+'°':'—°';if($('rain'))$('rain').textContent=S.rainNow!=null?S.rainNow.toFixed(1)+' mm':'—';if($('humidity'))$('humidity').textContent=c.relative_humidity_2m!=null?Math.round(c.relative_humidity_2m)+'%':'—';if($('wind'))$('wind').textContent=c.wind_speed_10m!=null?Math.round(c.wind_speed_10m)+' km/h':'—';if($('weatherText'))$('weatherText').textContent=(c.precipitation??0)>2?tr('अहिले वर्षा भइरहेको छ','Rain now'):(c.precipitation??0)>0?tr('हल्का वर्षा','Light rain'):tr('अहिले वर्षा कम वा छैन','Little or no rain now')}catch{if($('weatherText'))$('weatherText').textContent=tr('मौसम feed अहिले उपलब्ध छैन','Weather feed unavailable')}}
function sourceRows(){const r=Array.isArray(S.latestRiverStations)&&S.latestRiverStations.length?S.latestRiverStations:(Array.isArray(S.stations)?S.stations:[]);return r.filter(hasReading)}
function nearestFrom(la,lo){return sourceRows().map(o=>{const a=lat(o),b=lon(o);return{o,s:stage(o),d:a!==null&&b!==null?km(la,lo,a,b):Infinity}}).filter(x=>Number.isFinite(x.d)).sort((a,b)=>a.d-b.d)}
function infoFor(o,distanceKm=0){if(!o||!hasReading(o))return null;const s=stage(o);return{name:name(o),distanceKm,status:s.key,statusLabel:statusLabel(s.key),level:s.wl,warning:s.w,danger:s.d,time:stamp(o),age:age(stamp(o)),lat:lat(o),lon:lon(o),basin:String(val(flat(o),['basin','basin_name','basinName'])||''),district:String(val(flat(o),['districtName','district_name','district'])||''),source:String(val(flat(o),['dataSource','data_source'])||'DHM / BIPAD')}}
function stationInfoAt(la,lo,maxKm=80){const x=nearestFrom(la,lo).find(q=>q.d<=maxKm);return x?infoFor(x.o,x.d):null}
function saveHome(la,lo,kind){try{localStorage.setItem(HOME_KEY,JSON.stringify({lat:la,lon:lo,kind,updatedAt:new Date().toISOString()}))}catch{}}
function loadHome(){try{const x=JSON.parse(localStorage.getItem(HOME_KEY)||'null');if(x&&inside(+x.lat,+x.lon))return{lat:+x.lat,lon:+x.lon,kind:x.kind||'saved'}}catch{}return null}
function renderStations(){const out=$('nearStations');if(!out)return;if(!inside(S.lat,S.lon)){out.innerHTML=`<div class="empty">${tr('नेपाल नक्सामा आफ्नो घर/निगरानी स्थान छान्नुहोस्।','Choose your home/monitoring point on the Nepal map.')}</div>`;return}const n=nearestFrom(S.lat,S.lon).filter(x=>x.d<=80).slice(0,8);if(!n.length){out.innerHTML=`<div class="empty">${tr('८० कि.मि. भित्र official नदी पढाइ भेटिएन।','No official river reading found within 80 km.')}</div>`;return}out.innerHTML=n.map(x=>`<div class="station"><strong>${name(x.o)}</strong><span>${x.d.toFixed(1)} km • ${statusLabel(x.s.key)} • ${x.s.wl??'—'} m • ${age(stamp(x.o))}</span></div>`).join('')}
function notify(best,rank){if(!S.alertsOn||!best||rank<2)return;const sig=`${name(best.o)}|${stamp(best.o)||''}|${best.s.key}|${best.s.wl??''}`;if(localStorage.getItem('fs-last-river-alert')===sig)return;localStorage.setItem('fs-last-river-alert',sig);const title=rank>=3?tr('🚨 बाढी खतरा चेतावनी','🚨 Flood danger alert'):tr('⚠️ बाढी चेतावनी','⚠️ Flood warning');const body=`${name(best.o)} • ${best.d.toFixed(1)} km • ${best.s.wl??'—'} m • ${age(stamp(best.o))}`;if('Notification'in window&&Notification.permission==='granted')try{new Notification(title,{body,tag:'floodsafe-river-alert',renotify:true})}catch{}try{navigator.vibrate?.(rank>=3?[180,100,180]:[160])}catch{}}
function risk(){if(!inside(S.lat,S.lon)){if($('riskValue')){$('riskValue').className='risk unknown';$('riskValue').textContent='—'}if($('riskBadge')){$('riskBadge').className='badge';$('riskBadge').textContent='NEPAL'}if($('riskText'))$('riskText').textContent=tr('नेपाल नक्सामा आफ्नो निगरानी स्थान छान्नुहोस्।','Choose your monitoring point on the Nepal map.');return}const near=nearestFrom(S.lat,S.lon).filter(x=>x.d<=80),best=near.slice().sort((a,b)=>b.s.rank-a.s.rank||a.d-b.d)[0]||null,r=best?.s?.rank??-1,k=r>=3?'danger':r===2?'warning':r===1?'watch':r===0?'normal':'unknown';if($('riskValue')){$('riskValue').className='risk '+k;$('riskValue').textContent=statusLabel(k)}if($('riskBadge')){$('riskBadge').className='badge '+(r>=2?'red':r>=0?'green':'');$('riskBadge').textContent=r>=0?'OFFICIAL':'NO DATA'}if($('riskText'))$('riskText').textContent=best?`${name(best.o)} • ${best.d.toFixed(1)} km • ${best.s.wl??'—'} m • ${age(stamp(best.o))}`:tr('नजिक official river reading छैन।','No nearby official river reading.');S.lastRisk=r;if(S.alertsOn&&r>=2){const b=$('alarmBanner'),t=$('alarmText');if(b)b.style.display='block';if(t)t.textContent=r>=3?tr('नजिकको official नदी स्टेशन खतरा अवस्थामा छ।','A nearby official river station is at danger level.'):tr('नजिकको official नदी स्टेशन चेतावनी अवस्थामा छ।','A nearby official river station is at warning level.');notify(best,r)}else if($('alarmBanner'))$('alarmBanner').style.display=''}
function tick(){if($('clock'))$('clock').textContent=new Intl.DateTimeFormat(S.lang==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())+' NPT';const f=$('feedFresh'),st=window.__fsRiverRealtimeState;if(f&&st)f.textContent=tr(`${st.catalogCount||0} official station • ${st.latestCount||st.currentCount||0} latest official reading • ${st.source||''}`,`${st.catalogCount||0} official stations • ${st.latestCount||st.currentCount||0} latest official readings • ${st.source||''}`)}
function applyLanguage(){document.documentElement.lang=S.lang==='en'?'en':'ne';if($('langBtn'))$('langBtn').textContent=S.lang==='ne'?'English':'नेपाली';const T={weatherSupport:['नेपालको मौसम + BIPAD/DHM को पछिल्लो official नदी status','Nepal weather + latest official BIPAD/DHM river status'],locateBtn:['◎ मेरो हालको स्थान','◎ My Current Location'],localRiskTitle:['🛡️ मेरो निगरानी क्षेत्रको बाढी जोखिम','🛡️ Flood Risk at My Monitoring Area'],stationLabel:['सबै official स्टेशन','All official stations'],warningLabel:['चेतावनी','Warning'],dangerLabel:['खतरा','Danger'],nearTitle:['🌊 नजिकका नदी / Gauge','🌊 Nearby Rivers / Gauges'],nearSub:['Official BIPAD/DHM को पछिल्लो उपलब्ध पढाइ','Latest available official BIPAD/DHM readings'],riverStatusTitle:['🌊 नेपालभरि official नदी स्टेशन','🌊 Nepal Official River Stations'],riverStatusSub:['Official मा जे latest देखिन्छ, त्यही यहाँ देखाइन्छ','Shows the same latest official data available at source'],mapTitle:['🇳🇵 प्रत्यक्ष नदी नक्सा','🇳🇵 Live River Map'],mapSub:['नेपालका नदी/खोला + official BIPAD/DHM station र पछिल्लो status','Nepal rivers/streams + official BIPAD/DHM stations and latest status']};for(const[id,a]of Object.entries(T))if($(id))$(id).textContent=a[S.lang==='en'?1:0];renderStations();risk();window.dispatchEvent(new CustomEvent('fslanguage',{detail:{lang:S.lang}}))}
async function setFocus(la,lo,kind='map'){if(!inside(la,lo))return false;S.lat=la;S.lon=lo;S.kind=kind;saveHome(la,lo,kind);if($('outsideNotice'))$('outsideNotice').hidden=true;if($('place'))$('place').textContent=kind==='gps'?tr('📍 नेपालमा हालको स्थान सक्रिय','📍 Current Nepal location active'):tr(`📍 निगरानी स्थान • ${la.toFixed(3)}, ${lo.toFixed(3)}`,`📍 Monitoring point • ${la.toFixed(3)}, ${lo.toFixed(3)}`);await weather();renderStations();risk();return true}
function outside(){const h=loadHome();if($('outsideNotice'))$('outsideNotice').hidden=false;if(h){S.lat=h.lat;S.lon=h.lon;S.kind='saved';if($('place'))$('place').textContent=tr('🇳🇵 नेपाल निगरानी स्थान सक्रिय • तपाईं अहिले नेपाल बाहिर','🇳🇵 Nepal monitoring point active • you are currently outside Nepal');weather();renderStations();risk()}else{S.lat=S.lon=null;S.kind=null;if($('place'))$('place').textContent=tr('🌍 तपाईं नेपाल बाहिर हुनुहुन्छ • नक्साबाट नेपालमा घर छान्नुहोस्','🌍 You are outside Nepal • choose your Nepal home on the map');renderStations();risk()}}
function locate(){if(!navigator.geolocation)return outside();if($('place'))$('place').textContent=tr('📍 GPS स्थान खोजिँदैछ…','📍 Finding GPS location…');navigator.geolocation.getCurrentPosition(p=>inside(p.coords.latitude,p.coords.longitude)?setFocus(p.coords.latitude,p.coords.longitude,'gps'):outside(),()=>{const h=loadHome();if(h)setFocus(h.lat,h.lon,'saved');else if($('place'))$('place').textContent=tr('📍 स्थान अनुमति उपलब्ध छैन • नक्साबाट नेपालमा घर छान्नुहोस्','📍 Location permission unavailable • choose your Nepal home on the map')},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
async function alerts(){S.alertsOn=!S.alertsOn;localStorage.setItem(ALERT_KEY,S.alertsOn?'1':'0');if(S.alertsOn&&'Notification'in window&&Notification.permission==='default')try{await Notification.requestPermission()}catch{}if($('alertBtn'))$('alertBtn').textContent=S.alertsOn?tr('🔔 चेतावनी सक्रिय','🔔 Warning Alert ON'):tr('🔔 बाढी चेतावनी','🔔 Flood Warning Alert');risk()}
function toggleLang(){S.lang=S.lang==='ne'?'en':'ne';localStorage.setItem('fs-flood-lang',S.lang);applyLanguage();tick()}
function poll(){return window.FloodSafeRiverRealtime?.refresh?.()}
window.FloodSafe={setFocus,poll,state:S,stationInfoAt,nearestOfficial:stationInfoAt,stationInfoFor:infoFor,tr,statusLabel,age,fresh5:hasReading,insideNepal:inside,loadMonitoringPoint:loadHome};
function riverChanged(){renderStations();risk();tick()}
function boot(){if($('locateBtn'))$('locateBtn').addEventListener('click',locate);if($('alertBtn')){$('alertBtn').addEventListener('click',alerts);if(S.alertsOn)$('alertBtn').textContent=tr('🔔 चेतावनी सक्रिय','🔔 Warning Alert ON')}if($('langBtn'))$('langBtn').addEventListener('click',toggleLang);const h=loadHome();if(h){S.lat=h.lat;S.lon=h.lon;S.kind='saved';if($('place'))$('place').textContent=tr('📍 सुरक्षित नेपाल निगरानी स्थान लोड भयो','📍 Saved Nepal monitoring point loaded');weather()}applyLanguage();tick();setInterval(tick,1000);setTimeout(poll,700);for(const ev of['fstrustedriverupdate','fsriverupdate','fsriverheartbeat'])window.addEventListener(ev,riverChanged)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
