(()=>{
'use strict';
if(window.__fsFloodLiveV4)return;window.__fsFloodLiveV4=true;const PAGE=document.body.dataset.page||'';if(PAGE!=='alerts'&&PAGE!=='flood')return;
const $=id=>document.getElementById(id),BASE='https://bipadportal.gov.np/api/v1/',URLS={alerts:BASE+'alert/?limit=300&ordering=-createdOn',river:BASE+'river/?limit=700',stations:BASE+'river-stations/?limit=700'};
let alerts=[],rivers=[],busy=false,lastCheck=0;const lang=()=>localStorage.getItem('fs23-lang')==='en'?'en':'ne',tr=(ne,en)=>window.FSLang?.pick?window.FSLang.pick(ne,en):(lang()==='en'?en:ne),rows=j=>Array.isArray(j)?j:(j?.results||j?.data||j?.objects||[]),val=(o,ks)=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null},num=v=>{const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null},stamp=o=>val(o,['waterLevelOn','measuredOn','modifiedOn','updatedOn','updated_at','updatedAt','createdOn','created_at','startedOn','startOn','date','timestamp']),text=o=>{try{return JSON.stringify(o||{}).toLowerCase()}catch{return''}},age=o=>{const n=+new Date(stamp(o)||0);return n?Math.max(0,Date.now()-n):Infinity};
async function get(url,ms=6500){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_fv4='+Date.now(),{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
function stationName(o){if(lang()==='ne')return String(val(o,['river_name_ne','riverNameNe','station_name_ne','stationNameNe','titleNe','nameNe','river_name','riverName','station_name','stationName','title','name'])||o?.station?.name||'DHM नदी स्टेशन');return String(val(o,['river_name_en','riverNameEn','station_name_en','stationNameEn','titleEn','nameEn','river_name','riverName','station_name','stationName','title','name'])||o?.station?.name||'DHM river station')}
function key(o){return String(val(o,['id','pk','uuid','stationSeriesId','station_series_id'])||stationName(o)).toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim()}
function latestByKey(list){const m=new Map();for(const o of list){const k=key(o);if(!k)continue;const old=m.get(k);if(!old||+new Date(stamp(o)||0)>=+new Date(stamp(old)||0))m.set(k,o)}return[...m.values()]}
function trend(s){const x=String(s||'').toUpperCase();if(/RISING|INCREASING/.test(x))return tr('बढ्दो','RISING');if(/FALLING|DECREASING/.test(x))return tr('घट्दो','FALLING');if(/STEADY|STABLE/.test(x))return tr('स्थिर','STEADY');return''}
function stage(o){const wl=num(val(o,['waterLevel','water_level','currentLevel','current_level','level','value'])),w=num(val(o,['warningLevel','warning_level','warning'])),d=num(val(o,['dangerLevel','danger_level','danger'])),raw=String(val(o,['status','state','condition','steady','trend'])||''),s=raw.toUpperCase();if(age(o)>2*3600e3)return{level:'STALE',score:0,wl,w,d,trend:''};if((d!==null&&wl!==null&&wl>=d)||/ABOVE\s+DANGER|DANGER\s+LEVEL\s+EXCEEDED|RED\s+ALERT/.test(s))return{level:'DANGER',score:3,wl,w,d,trend:trend(raw)};if((w!==null&&wl!==null&&wl>=w)||/ABOVE\s+WARNING|WARNING\s+LEVEL\s+EXCEEDED|ORANGE\s+ALERT/.test(s))return{level:'WARNING',score:2,wl,w,d,trend:trend(raw)};if(/RISING|INCREASING/.test(s)&&(w!==null&&wl!==null&&wl>=w*.8))return{level:'WATCH',score:1,wl,w,d,trend:trend(raw)};return{level:'NORMAL',score:0,wl,w,d,trend:trend(raw)}}
function alertActive(o){const s=text(o),now=Date.now(),exp=val(o,['expiresOn','expireOn','expires_at','expiry','endDate','endedOn']),start=val(o,['startedOn','startOn','startDate','createdOn','created_at']);if(o?.active===false||o?.isActive===false||/inactive|expired|archived|समाप्त/.test(s))return false;if(start&&+new Date(start)>now+5*60000)return false;if(exp&&+new Date(exp)<now)return false;if(!exp&&age(o)>12*3600e3)return false;return /(flood|flash flood|river|inundation|बाढी|नदी|खोला|डुबान)/i.test(s)&&/(danger|warning|high|red|orange|evacuat|खतरा|चेतावनी|उच्च|सतर्क)/i.test(s)}
function npTime(t){if(!t)return'—';try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return'—'}}
function ago(t){const n=+new Date(t||0);if(!n)return tr('समय उपलब्ध छैन','time unavailable');const m=Math.max(0,Math.round((Date.now()-n)/60000));if(m<1)return tr('अहिले','just now');if(m<60)return lang()==='en'?m+' min ago':m+' मिनेट अघि';return lang()==='en'?Math.round(m/60)+' hr ago':Math.round(m/60)+' घण्टा अघि'}
function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}function make(t,c,x){const e=document.createElement(t);if(c)e.className=c;if(x!==undefined)e.textContent=x;return e}
function card(out,tag,title,body,meta,url){const a=make('article','item');a.dataset.floodOwner='4';a.appendChild(make('span','tag '+(/DANGER|WARNING|HIGH|खतरा|चेतावनी|उच्च/.test(tag)?'red':''),tag));a.appendChild(make('h4','',title));if(body)a.appendChild(make('p','',body));if(meta)a.appendChild(make('div','meta',meta));if(url){const d=make('div','meta'),l=make('a','',tr('स्रोत खोल्नुहोस्','Open source'));l.href=url;l.target='_blank';l.rel='noopener noreferrer';d.appendChild(l);a.appendChild(d)}out.appendChild(a)}
function alertTitle(o){if(lang()==='ne')return String(val(o,['titleNe','nameNe','descriptionNe'])||'BIPAD बाढी चेतावनी');const x=String(val(o,['titleEn','nameEn','title','name'])||'BIPAD flood alert');return /[\u0900-\u097F]/.test(x)?'BIPAD flood alert':x}
function alertBody(o){if(lang()==='ne'){const x=String(val(o,['descriptionNe','remarksNe','statusNe'])||'');return x||'उच्च प्राथमिकताको आधिकारिक बाढी चेतावनी'}const x=String(val(o,['descriptionEn','remarksEn','statusEn','description','remarks','status'])||'');return x&&!/[\u0900-\u097F]/.test(x)?x:'High-priority official flood warning'}
function tagFor(level){if(level==='DANGER')return tr('खतरा','DANGER');if(level==='WARNING')return tr('चेतावनी','WARNING');if(level==='WATCH')return tr('सतर्क','WATCH');return level}
function render(){const out=$('floodAlertsListLive');if(!out)return;const latest=latestByKey(rivers),warn=latest.map(o=>({o,s:stage(o)})).filter(x=>x.s.score>=2).sort((a,b)=>b.s.score-a.s.score||age(a.o)-age(b.o)),active=alerts.filter(alertActive).sort((a,b)=>(+new Date(stamp(b)||0))-(+new Date(stamp(a)||0)));clear(out);for(const o of active.slice(0,6))card(out,tr('उच्च','HIGH'),alertTitle(o),alertBody(o).slice(0,220),'BIPAD • '+ago(stamp(o)),'https://bipadportal.gov.np/');for(const x of warn.slice(0,10)){const s=x.s,body=tr('पानी ','Water ')+(s.wl!==null?s.wl+' m':'—')+tr(' • चेतावनी ',' • warning ')+(s.w!==null?s.w+' m':'—')+tr(' • खतरा ',' • danger ')+(s.d!==null?s.d+' m':'—')+(s.trend?' • '+s.trend:'');card(out,tagFor(s.level),stationName(x.o),body,tr('मापन ','Measured ')+npTime(stamp(x.o))+' • '+tr('DHM डेटा BIPAD मार्फत','DHM data via BIPAD'),'https://bipadportal.gov.np/realtime/')}if(!out.children.length)out.appendChild(make('div','empty',tr('अहिले ताजा आधिकारिक स्रोतमा सक्रिय बाढी/नदी चेतावनी भेटिएको छैन। यसको अर्थ जोखिम शून्य हो भन्ने होइन; स्रोत जाँच जारी छ।','No active flood/river warning is currently found in the fresh official feed. This does not prove zero risk; source checks continue.')));const ac=$('floodAlertCountLive'),rc=$('riverAlertCountLive');if(ac)ac.textContent=String(active.length);if(rc)rc.textContent=String(warn.length);const f=$('floodLiveFresh');if(f)f.textContent=tr('अन्तिम स्रोत जाँच ','Last source check ')+npTime(lastCheck)+tr(' • हरेक ५ सेकेन्ड',' • every 5 sec');window.__fsFloodState={alerts:active.length,riverWarnings:warn.length,stations:latest.length,checkedAt:lastCheck,owner:'flood-v4'}}
async function poll(){if(busy||document.hidden||!navigator.onLine)return;busy=true;try{const [a,r,s]=await Promise.allSettled([get(URLS.alerts),get(URLS.river),get(URLS.stations)]);if(a.status==='fulfilled')alerts=rows(a.value);let merged=[];if(r.status==='fulfilled')merged.push(...rows(r.value));if(s.status==='fulfilled')merged.push(...rows(s.value));if(merged.length)rivers=latestByKey(merged);lastCheck=Date.now();render()}finally{busy=false}}
function boot(){poll();setInterval(poll,5000);setInterval(()=>{const f=$('floodLiveFresh');if(f&&lastCheck)f.textContent=tr('अन्तिम स्रोत जाँच ','Last source check ')+npTime(lastCheck)+tr(' • हरेक ५ सेकेन्ड',' • every 5 sec')},1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});window.addEventListener('online',poll);window.addEventListener('fs-language-change',render)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();