(()=>{'use strict';
if(window.__fsFloodCoreV8)return;window.__fsFloodCoreV8=true;
const $=id=>document.getElementById(id),B={minLon:80,maxLon:88.35,minLat:26.2,maxLat:30.5},FRESH_MS=6*60*60*1000;
const S={lat:null,lon:null,kind:null,stations:[],lastPoll:0,alertsOn:false,lastRisk:-1,lang:localStorage.getItem('fs-flood-lang')==='en'?'en':'ne'};
const tr=(ne,en)=>S.lang==='en'?en:ne,rows=j=>Array.isArray(j)?j:(j?.results||j?.data||j?.objects||[]),num=v=>{const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null};
const val=(o,ks)=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null};
const lat=o=>num(val(o,['latitude','lat','stationLatitude','station_latitude'])??o?.station?.latitude??o?.location?.latitude),lon=o=>num(val(o,['longitude','lon','lng','stationLongitude','station_longitude'])??o?.station?.longitude??o?.location?.longitude);
const name=o=>String(val(o,['river_name','riverName','station_name','stationName','title','name'])||o?.station?.name||tr('नदी स्टेशन','River station'));
const stamp=o=>val(o,['waterLevelOn','measuredOn','modifiedOn','updatedOn','updated_at','updatedAt','createdOn','date','timestamp']);
const inside=(la,lo)=>Number.isFinite(la)&&Number.isFinite(lo)&&la>=B.minLat&&la<=B.maxLat&&lo>=B.minLon&&lo<=B.maxLon;
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
async function get(url,ms=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_fs8='+Date.now(),{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
function fresh(o){const t=+new Date(stamp(o)||0);return !!t&&Date.now()-t>=-300000&&Date.now()-t<=FRESH_MS}
function stage(o){const wl=num(val(o,['waterLevel','water_level','currentWaterLevel','current_water_level','currentLevel','current_level'])),w=num(val(o,['warningLevel','warning_level','warningThreshold','warning_threshold'])),d=num(val(o,['dangerLevel','danger_level','dangerThreshold','danger_threshold'])),raw=String(val(o,['status','status_name','alertStatus','alert_status','riskLevel','risk_level'])||'').trim().toUpperCase(),isFresh=fresh(o);if(!isFresh)return{key:'unknown',rank:-1,wl,w,d,fresh:false};if(wl!==null&&d!==null&&d>0&&wl>=d)return{key:'danger',rank:3,wl,w,d,fresh:true};if(wl!==null&&w!==null&&w>0&&wl>=w)return{key:'warning',rank:2,wl,w,d,fresh:true};if(['DANGER','RED','ABOVE DANGER'].includes(raw))return{key:'danger',rank:3,wl,w,d,fresh:true};if(['WARNING','ORANGE','ABOVE WARNING'].includes(raw))return{key:'warning',rank:2,wl,w,d,fresh:true};if(['WATCH','RISING','YELLOW'].includes(raw))return{key:'watch',rank:1,wl,w,d,fresh:true};if(['NORMAL','GREEN','SAFE','BELOW WARNING'].includes(raw)||wl!==null)return{key:'normal',rank:0,wl,w,d,fresh:true};return{key:'unknown',rank:-1,wl,w,d,fresh:true}}
function age(t){const x=+new Date(t||0);if(!x)return tr('समय छैन','time unavailable');const s=Math.max(0,Math.floor((Date.now()-x)/1000));if(s<60)return tr(`${s} सेकेन्ड अघि`,`${s}s ago`);const m=Math.floor(s/60);if(m<60)return tr(`${m} मिनेट अघि`,`${m}m ago`);return tr(`${Math.floor(m/60)} घण्टा अघि`,`${Math.floor(m/60)}h ago`)}
function tick(){if($('clock'))$('clock').textContent=new Intl.DateTimeFormat(S.lang==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())+' NPT';if($('feedFresh')&&S.lastPoll)$('feedFresh').textContent=tr(`Official feed ${Math.floor((Date.now()-S.lastPoll)/1000)} सेकेन्ड अघि जाँचियो`,`Official feed checked ${Math.floor((Date.now()-S.lastPoll)/1000)}s ago`)}
function clearWeather(){if($('temp'))$('temp').textContent='—°';for(const id of['rain','humidity','wind'])if($(id))$(id).textContent='—';if($('weatherText'))$('weatherText').textContent=tr('नेपालको monitoring location छान्नुहोस्','Choose a Nepal monitoring location')}
async function weather(){if(!inside(S.lat,S.lon))return clearWeather();try{const j=await get(`https://api.open-meteo.com/v1/forecast?latitude=${S.lat}&longitude=${S.lon}&current=temperature_2m,relative_humidity_2m,precipitation,rain,weather_code,wind_speed_10m&timezone=Asia%2FKathmandu`,7000),c=j.current||{};$('temp').textContent=c.temperature_2m!=null?Math.round(c.temperature_2m)+'°':'—°';$('rain').textContent=(c.rain??c.precipitation)!=null?Number(c.rain??c.precipitation).toFixed(1)+' mm':'—';$('humidity').textContent=c.relative_humidity_2m!=null?Math.round(c.relative_humidity_2m)+'%':'—';$('wind').textContent=c.wind_speed_10m!=null?Math.round(c.wind_speed_10m)+' km/h':'—';$('weatherText').textContent=(c.precipitation??0)>2?tr('अहिले वर्षा भइरहेको छ','Rain now'):(c.precipitation??0)>0?tr('हल्का वर्षा','Light rain'):tr('अहिले वर्षा कम/छैन','Little or no rain now')}catch{if($('weatherText'))$('weatherText').textContent=tr('मौसम feed अहिले उपलब्ध छैन','Weather feed unavailable')}}
function nearest(max=50){if(!inside(S.lat,S.lon))return[];return S.stations.map(o=>{const a=lat(o),b=lon(o);return{o,s:stage(o),d:a!==null&&b!==null?km(S.lat,S.lon,a,b):Infinity}}).filter(x=>Number.isFinite(x.d)).sort((a,b)=>a.d-b.d).slice(0,max)}
function noLocal(msg,badge='LOCATION'){if($('riskValue')){$('riskValue').className='risk unknown';$('riskValue').textContent='—'}if($('riskBadge')){$('riskBadge').className='badge';$('riskBadge').textContent=badge}if($('riskText'))$('riskText').textContent=msg;if($('nearStations'))$('nearStations').innerHTML=`<div class="empty">${msg}</div>`;S.lastRisk=-1}
function renderStations(){const out=$('nearStations');if(!out)return;if(!inside(S.lat,S.lon)){noLocal(tr('नेपाल नक्सामा क्षेत्र छान्नुहोस्।','Choose an area on the Nepal map.'));return}const n=nearest().filter(x=>x.d<=30&&x.s.fresh).slice(0,6);out.innerHTML='';if(!n.length){out.innerHTML=`<div class="empty">${tr('३० किमि भित्र fresh official gauge भेटिएन। Safe/Normal अनुमान गरिएको छैन।','No fresh official gauge within 30 km. Safe/Normal is not assumed.')}</div>`;return}for(const x of n){const d=document.createElement('div');d.className='station';d.innerHTML=`<strong>${name(x.o)}</strong><span>${x.d.toFixed(1)} km • ${x.s.key.toUpperCase()} • ${x.s.wl??'—'} m • ${age(stamp(x.o))}</span>`;out.appendChild(d)}}
function risk(){if(!inside(S.lat,S.lon))return noLocal(tr('नेपालभित्र location वा map area छानेपछि मात्र local risk देखाइन्छ।','Local risk is shown only after choosing a location inside Nepal.'));const n=nearest().filter(x=>x.d<=30&&x.s.rank>=0&&x.s.fresh);if(!n.length){if($('riskValue')){$('riskValue').className='risk unknown';$('riskValue').textContent='UNKNOWN'}if($('riskBadge')){$('riskBadge').className='badge';$('riskBadge').textContent='NO FRESH GAUGE'}if($('riskText'))$('riskText').textContent=tr('३० किमि भित्र fresh verified gauge छैन — NORMAL भनेर अनुमान गरिएको छैन।','No fresh verified gauge within 30 km — NORMAL is not assumed.');S.lastRisk=-1;return}const top=n.sort((a,b)=>b.s.rank-a.s.rank||a.d-b.d)[0],r=top.s.rank,key=top.s.key;$('riskValue').className='risk '+key;$('riskValue').textContent=key.toUpperCase();$('riskBadge').className='badge '+(r>=3?'red':r>=1?'amber':'green');$('riskBadge').textContent=r>=3?'DANGER':r>=2?'WARNING':r===1?'WATCH':'NORMAL';$('riskText').textContent=`${name(top.o)} • ${top.d.toFixed(1)} km • ${top.s.wl??'—'} m • ${age(stamp(top.o))}`;if(r>=2&&S.alertsOn&&r>S.lastRisk)alarm(top);S.lastRisk=r}
function chime(){try{const C=window.AudioContext||window.webkitAudioContext,a=new C(),g=a.createGain();g.gain.setValueAtTime(.0001,a.currentTime);g.gain.exponentialRampToValueAtTime(.1,a.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+1.4);g.connect(a.destination);[0,.38,.76].forEach((q,i)=>{const o=a.createOscillator();o.type='sine';o.frequency.value=[700,850,700][i];o.connect(g);o.start(a.currentTime+q);o.stop(a.currentTime+q+.23)});setTimeout(()=>a.close(),1700)}catch{}}
function alarm(x){chime();if($('alarmBanner'))$('alarmBanner').classList.add('show');if($('alarmTitle'))$('alarmTitle').textContent=x.s.rank>=3?'🚨 DANGER':'⚠️ WARNING';if($('alarmText'))$('alarmText').textContent=`${name(x.o)} • ${x.d.toFixed(1)} km • ${x.s.wl??'—'} m`;if('Notification'in window&&Notification.permission==='granted')new Notification('FloodSafe Nepal',{body:$('alarmText')?.textContent||'Flood warning',icon:'../v24/icon.svg'})}
async function alerts(){S.alertsOn=!S.alertsOn;if(S.alertsOn&&'Notification'in window&&Notification.permission==='default'){try{await Notification.requestPermission()}catch{}}if($('alertBtn')){$('alertBtn').classList.toggle('on',S.alertsOn);$('alertBtn').textContent=S.alertsOn?'🔔 Warning Alert ON':'🔔 Flood Warning Alert'}}
async function poll(){try{const base='https://bipadportal.gov.np/api/v1/',[a,b]=await Promise.allSettled([get(base+'river-stations/?limit=1000'),get(base+'river/?limit=1000')]);let all=a.status==='fulfilled'?rows(a.value):[];if(!all.length&&b.status==='fulfilled')all=rows(b.value);const m=new Map();for(const o of all){const la=lat(o),lo=lon(o),k=String(val(o,['stationSeriesId','station_id','stationId','id','pk','uuid'])||`${name(o)}|${la}|${lo}`);if(!m.has(k))m.set(k,o)}S.stations=[...m.values()];S.lastPoll=Date.now();if($('stationCount'))$('stationCount').textContent=S.stations.length;const st=S.stations.map(stage);if($('warningCount'))$('warningCount').textContent=st.filter(x=>x.rank===2).length;if($('dangerCount'))$('dangerCount').textContent=st.filter(x=>x.rank===3).length;renderStations();risk()}catch{if($('feedFresh'))$('feedFresh').textContent=tr('Official river feed उपलब्ध छैन','Official river feed unavailable')}}
async function setFocus(la,lo,kind='map'){if(!inside(la,lo))return;S.lat=la;S.lon=lo;S.kind=kind;if($('outsideNotice'))$('outsideNotice').hidden=true;if($('place'))$('place').textContent=kind==='gps'?tr('📍 नेपालमा current location सक्रिय','📍 Current Nepal location active'):tr(`📍 नक्साबाट क्षेत्र चयन • ${la.toFixed(3)}, ${lo.toFixed(3)}`,`📍 Map area selected • ${la.toFixed(3)}, ${lo.toFixed(3)}`);await weather();renderStations();risk()}
function outside(){S.lat=S.lon=null;S.kind=null;if($('outsideNotice'))$('outsideNotice').hidden=false;if($('place'))$('place').textContent=tr('🌍 तपाईं अहिले नेपाल बाहिर हुनुहुन्छ','🌍 You are currently outside Nepal');clearWeather();noLocal(tr('नेपाल नक्सामा निगरानी गर्न चाहेको क्षेत्र छान्नुहोस्।','Choose an area on the Nepal map to monitor.'))}
function locate(){if(!navigator.geolocation)return outside();if($('place'))$('place').textContent=tr('📍 GPS location खोजिँदैछ…','📍 Finding GPS location…');navigator.geolocation.getCurrentPosition(p=>inside(p.coords.latitude,p.coords.longitude)?setFocus(p.coords.latitude,p.coords.longitude,'gps'):outside(),()=>{if($('place'))$('place').textContent=tr('📍 Location अनुमति उपलब्ध छैन','📍 Location permission unavailable')},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function toggleLang(){S.lang=S.lang==='ne'?'en':'ne';localStorage.setItem('fs-flood-lang',S.lang);if($('langBtn'))$('langBtn').textContent=S.lang==='ne'?'English':'नेपाली';tick();if(inside(S.lat,S.lon))setFocus(S.lat,S.lon,S.kind||'map');else noLocal(tr('नेपाल नक्सामा क्षेत्र छान्नुहोस्।','Choose an area on the Nepal map.'))}
window.FloodSafe={setFocus,poll,state:S};
function boot(){if($('locateBtn'))$('locateBtn').addEventListener('click',locate);if($('alertBtn'))$('alertBtn').addEventListener('click',alerts);if($('langBtn')){$('langBtn').addEventListener('click',toggleLang);$('langBtn').textContent=S.lang==='ne'?'English':'नेपाली'}tick();setInterval(tick,1000);poll();setInterval(poll,5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();