(()=>{'use strict';
if(window.__fsGaugeBridgeV22)return;window.__fsGaugeBridgeV22=true;
const RECENT=5*60*1000,FUTURE=5*60*1000,SAME_RIVER_LOCAL_KM=50,REGIONAL_KM=70,LINE_EXACT_KM=4.5,UNNAMED_LINE_KM=2.5;
const num=v=>{const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null};
const val=(o,ks)=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null};
const flat=o=>o&&typeof o==='object'&&o.fields&&typeof o.fields==='object'?Object.assign({},o.fields,o):o;
function coord(o){o=flat(o);const rt=window.FloodSafeRiverRealtime?.coords?.(o);if(Array.isArray(rt)&&rt.length>=2)return[+rt[1],+rt[0]];const c=o?._stationCoordinate||o?.point?.coordinates||o?.location?.coordinates||o?.geometry?.coordinates;if(Array.isArray(c)&&c.length>=2&&Number.isFinite(+c[0])&&Number.isFinite(+c[1])){const a=+c[0],b=+c[1];if(a>=79.5&&a<=89&&b>=26&&b<=31)return[b,a];if(b>=79.5&&b<=89&&a>=26&&a<=31)return[a,b]}const p=String(o?.point||o?.location||''),m=p.match(/POINT\s*\(\s*(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s*\)/i);if(m)return[+m[2],+m[1]];const la=num(val(o,['latitude','lat','stationLatitude','station_latitude'])),lo=num(val(o,['longitude','lon','lng','stationLongitude','station_longitude']));return la!==null&&lo!==null?[la,lo]:null}
const name=o=>String(val(flat(o),['river_name','riverName','station_name','stationName','title','name'])||flat(o)?.station?.name||'River station');
const basin=o=>String(val(flat(o),['basin','basin_name','basinName'])||'');
const district=o=>String(val(flat(o),['districtName','district_name','district'])||'');
const stationId=o=>String(val(flat(o),['stationSeriesId','station_series_id','stationId','station_id','stationIndex','station_index','id'])||'');
const discharge=o=>num(val(flat(o),['discharge','currentDischarge','current_discharge','flow','flowRate','flow_rate','_lastDischarge']));
const stamp=o=>val(flat(o),['_measurementTime','waterLevelOn','water_level_on','measuredOn','measured_on','measurementTime','observationTime']);
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
function ageMs(o){const t=+new Date(stamp(o)||0);return t?Date.now()-t:Infinity}
function trusted(o){o=flat(o);if(o?._measurementTimeTrusted===false)return false;const a=ageMs(o),l=num(val(o,['waterLevel','water_level','currentWaterLevel','current_water_level','currentLevel','current_level','level']));return l!==null&&Number.isFinite(a)&&a>=-FUTURE&&a<=RECENT}
function clean(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+(?:at|near)\s+.*/i,' ').replace(/(?:नदी|नदि|खोला)/g,' ').replace(/\b(river|khola|nadi|stream|station|gauge|bridge|rls|hs)\b/g,' ').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim()}
const ALIAS=new Map([['भोटेकोशी','bhotekoshi'],['भोटेकोसी','bhotekoshi'],['bhote koshi','bhotekoshi'],['bhote kosi','bhotekoshi'],['सुनकोशी','sunkoshi'],['sun koshi','sunkoshi'],['सप्तकोशी','saptakoshi'],['sapta koshi','saptakoshi'],['कालीगण्डकी','kaligandaki'],['kali gandaki','kaligandaki'],['बुढीगण्डकी','budhigandaki'],['बूढीगण्डकी','budhigandaki'],['budi gandaki','budhigandaki'],['मर्स्याङ्दी','marsyangdi'],['marsyangdi','marsyangdi'],['त्रिशूली','trishuli'],['त्रिशुली','trishuli'],['नारायणी','narayani'],['कर्णाली','karnali'],['महाकाली','mahakali'],['बागमती','bagmati'],['बबई','babai'],['अरुण','arun'],['तमोर','tamor'],['कन्काई','kankai'],['कमला','kamala'],['मेची','mechi'],['तिनाउ','tinau'],['सेती','seti']]);
function canonical(s){const c=clean(s);return ALIAS.get(c)||c}
function variants(w){const a=[w?.name_en,w?.name_raw,w?.name,w?.name_ne].map(x=>String(x||'').trim()).filter(Boolean),seen=new Set();return a.filter(x=>{const k=canonical(x);if(!k||seen.has(k))return false;seen.add(k);return true})}
function editDistance(a,b){a=canonical(a);b=canonical(b);if(!a||!b)return 99;const n=b.length,p=Array.from({length:n+1},(_,i)=>i),c=new Array(n+1);for(let i=1;i<=a.length;i++){c[0]=i;for(let j=1;j<=n;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<=n;j++)p[j]=c[j]}return p[n]}
function scoreName(a,b){const A=canonical(a),B=canonical(b);if(!A||!B)return 0;if(A===B)return 100;if(A.length>=4&&B.length>=4&&(A.includes(B)||B.includes(A)))return 96;const aa=A.split(' ').filter(x=>x.length>=3),bb=B.split(' ').filter(x=>x.length>=3),common=aa.filter(x=>bb.includes(x));if(common.length){const r=common.length/Math.max(aa.length,bb.length);if(r>=.75)return 93;if(r>=.5)return 88}const mx=Math.max(A.length,B.length),ed=mx<=24?editDistance(A,B):99;if(mx>=5&&ed<=1)return 94;if(mx>=7&&ed<=2)return 91;return 0}
function stage(o){o=flat(o);const level=num(val(o,['waterLevel','water_level','currentWaterLevel','current_water_level','currentLevel','current_level','level'])),warning=num(val(o,['warningLevel','warning_level','warningThreshold','warning_threshold','_lastWarningLevel'])),danger=num(val(o,['dangerLevel','danger_level','dangerThreshold','danger_threshold','_lastDangerLevel'])),raw=String(val(o,['_officialStatus','status','status_name','alertStatus','alert_status','riskLevel','risk_level'])||'').trim().toUpperCase();let status='normal';if(level!==null&&danger!==null&&danger>0&&level>=danger)status='danger';else if(level!==null&&warning!==null&&warning>0&&level>=warning)status='warning';else if(/DANGER|RED/.test(raw)&&!/BELOW\s+DANGER/.test(raw))status='danger';else if(/WARNING|ORANGE/.test(raw)&&!/BELOW\s+WARNING/.test(raw))status='warning';else if(/WATCH|RISING|INCREASING|YELLOW/.test(raw))status='watch';return{level,warning,danger,status,raw}}
function candidate(o,requireFresh){o=flat(o);const c=coord(o);if(!c)return null;const s=stage(o),fresh=trusted(o),lastLevel=num(val(o,['_lastWaterLevel','waterLevel','water_level','currentWaterLevel','current_water_level','level']));if(requireFresh&&!fresh)return null;return{o,name:name(o),basin:basin(o),district:district(o),stationId:stationId(o),lat:c[0],lon:c[1],time:stamp(o),ageMs:ageMs(o),fresh,status:fresh?s.status:'stale',rawStatus:s.raw,level:fresh?s.level:null,lastLevel,warning:s.warning,danger:s.danger,discharge:fresh?discharge(o):null,lastDischarge:discharge(o),source:String(o?.dataSource||o?.data_source||o?._catalogueSource||'DHM / BIPAD'),sourceUrl:String(o?._officialLivePage||o?.source_url||o?.sourceUrl||'https://bipadportal.gov.np/realtime/'),hasCurrent5m:fresh}}
function allBase(){return(window.FloodSafe?.state?.stations||[]).map(x=>candidate(x,true)).filter(Boolean)}
function allCatalog(){return(window.FloodSafe?.state?.allRiverStations||[]).map(x=>candidate(x,false)).filter(Boolean)}
function points(w){if(Array.isArray(w?.pts))return w.pts.filter(p=>Array.isArray(p)&&Number.isFinite(+p[0])&&Number.isFinite(+p[1])).map(p=>[+p[0],+p[1]]);if(Array.isArray(w?.geometry_points))return w.geometry_points;return[]}
function pointSegKm(la,lo,a,b){const lat0=la*Math.PI/180,sc=Math.cos(lat0),x1=(a[0]-lo)*111.32*sc,y1=(a[1]-la)*110.574,x2=(b[0]-lo)*111.32*sc,y2=(b[1]-la)*110.574,dx=x2-x1,dy=y2-y1,den=dx*dx+dy*dy,t=den?Math.max(0,Math.min(1,-(x1*dx+y1*dy)/den)):0,x=x1+t*dx,y=y1+t*dy;return Math.sqrt(x*x+y*y)}
function lineDistanceKm(la,lo,pts){if(!Array.isArray(pts)||pts.length<2)return Infinity;let best=Infinity;for(let i=1;i<pts.length;i++)best=Math.min(best,pointSegKm(la,lo,pts[i-1],pts[i]));return best}
function match(rows,w,la,lo,regional=true){const names=variants(w),pts=points(w),named=names.length>0,geomLimit=named?LINE_EXACT_KM:UNNAMED_LINE_KM;if((!Number.isFinite(la)||!Number.isFinite(lo))&&pts.length){const p=pts[Math.floor((pts.length-1)/2)];lo=p[0];la=p[1]}if(!Number.isFinite(la)||!Number.isFinite(lo))return null;const all=rows.map(c=>{let ns=0;for(const n of names)ns=Math.max(ns,scoreName(n,c.name));return{...c,distanceKm:km(la,lo,c.lat,c.lon),lineDistanceKm:lineDistanceKm(c.lat,c.lon,pts),nameScore:ns}});const local=[];for(const x of all){const byName=named&&x.nameScore>=91&&x.distanceKm<=SAME_RIVER_LOCAL_KM,byGeom=x.lineDistanceKm<=geomLimit;if(!byName&&!byGeom)continue;const method=byName&&byGeom?'name+geometry':byGeom?'geometry':'name';local.push({...x,sameRiver:true,local:true,reference:false,matchMethod:method,matchConfidence:(x.nameScore>=93||x.lineDistanceKm<=1)?'high':'medium'})}local.sort((a,b)=>(b.nameScore-a.nameScore)||(a.lineDistanceKm-b.lineDistanceKm)||(a.distanceKm-b.distanceKm));if(local[0])return local[0];if(!regional)return null;const r=all.filter(x=>x.distanceKm<=REGIONAL_KM).sort((a,b)=>a.distanceKm-b.distanceKm)[0];return r?{...r,sameRiver:false,local:false,reference:true,matchMethod:'regional-nearest',matchConfidence:'reference-only'}:null}
function forWaterway(w,la,lo){const x=match(allBase(),w,la,lo,true);if(!x)return null;return{...x,coverage:x.sameRiver?'same-river-current-5m':'regional-reference'}}
function forWaterwayCatalog(w,la,lo){const x=match(allCatalog(),w,la,lo,false);return x?{...x,coverage:x.local?'official-station-catalogue-local':'official-station-catalogue-same-river'}:null}
function nearby(la,lo,maxKm=40,limit=100){return allBase().map(x=>({...x,distanceKm:km(la,lo,x.lat,x.lon)})).filter(x=>x.distanceKm<=maxKm).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,limit)}
function nearbyCatalog(la,lo,maxKm=40,limit=500){return allCatalog().map(x=>({...x,distanceKm:km(la,lo,x.lat,x.lon)})).filter(x=>x.distanceKm<=maxKm).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,limit)}
window.FloodSafeGauge={forWaterway,forWaterwayCatalog,nearby,nearbyCatalog,SAME_RIVER_LOCAL_KM,REGIONAL_KM,LINE_EXACT_KM,UNNAMED_LINE_KM,RECENT_MS:RECENT,scoreName,canonical,variants,lineDistanceKm,allCatalog};
})();