(()=>{'use strict';
if(window.__fsGaugeBridgeV16)return;window.__fsGaugeBridgeV16=true;
const LIVE=60*1000,RECENT=20*60*1000,SAME_RIVER_LOCAL_KM=25,FUTURE=5*60*1000;
const num=v=>{const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null};
const val=(o,ks)=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null};
const flat=o=>o&&typeof o==='object'&&o.fields&&typeof o.fields==='object'?Object.assign({},o.fields,o):o;
function coord(o){o=flat(o);const c=o?.point?.coordinates||o?.location?.coordinates||o?.geometry?.coordinates;if(Array.isArray(c)&&c.length>=2&&Number.isFinite(+c[0])&&Number.isFinite(+c[1]))return[+c[1],+c[0]];const p=String(o?.point||o?.location||''),m=p.match(/POINT\s*\(\s*(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s*\)/i);if(m)return[+m[2],+m[1]];const la=num(val(o,['latitude','lat','stationLatitude','station_latitude'])),lo=num(val(o,['longitude','lon','lng','stationLongitude','station_longitude']));return la!==null&&lo!==null?[la,lo]:null}
const name=o=>String(val(flat(o),['river_name','riverName','station_name','stationName','title','name'])||flat(o)?.station?.name||'River station');
const basin=o=>String(val(flat(o),['basin','basin_name','basinName'])||'');
// Hydrological observation time only. Never use fetch/created/modified/alert time.
const stamp=o=>val(flat(o),['_measurementTime','waterLevelOn','water_level_on','measuredOn','measured_on','measurementTime','observationTime']);
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
function ageMs(o){const t=+new Date(stamp(o)||0);return t?Date.now()-t:Infinity}
function trusted(o){o=flat(o);if(o?._measurementTimeTrusted===false)return false;const a=ageMs(o);return Number.isFinite(a)&&a>=-FUTURE&&a<=RECENT}
function isLive(o){return trusted(o)&&ageMs(o)<=LIVE}
function clean(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+(?:at|near)\s+.*/i,' ').replace(/(?:नदी|नदि|खोला)/g,' ').replace(/\b(river|khola|nadi|stream|station|gauge|bridge|rls|hs)\b/g,' ').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim()}
function variants(w){return[w?.name_en,w?.name_raw,w?.name,w?.name_ne].map(x=>String(x||'').trim()).filter(Boolean)}
function scoreName(a,b){const A=clean(a),B=clean(b);if(!A||!B)return 0;if(A===B)return 100;if(A.length>=4&&B.length>=4&&(A.startsWith(B+' ')||B.startsWith(A+' ')||A.endsWith(' '+B)||B.endsWith(' '+A)))return 95;const aa=A.split(' ').filter(x=>x.length>=3),bb=B.split(' ').filter(x=>x.length>=3),common=aa.filter(x=>bb.includes(x));return common.length&&common.length===Math.min(aa.length,bb.length)?88:0}
function stage(o){o=flat(o);const level=num(val(o,['waterLevel','water_level','currentWaterLevel','current_water_level','currentLevel','current_level','level'])),warning=num(val(o,['warningLevel','warning_level','warningThreshold','warning_threshold'])),danger=num(val(o,['dangerLevel','danger_level','dangerThreshold','danger_threshold'])),raw=String(val(o,['_officialStatus','status','status_name','alertStatus','alert_status','riskLevel','risk_level'])||'').trim().toUpperCase();let status='normal';if(level!==null&&danger!==null&&danger>0&&level>=danger)status='danger';else if(level!==null&&warning!==null&&warning>0&&level>=warning)status='warning';else if(/DANGER|RED/.test(raw)&&!/BELOW\s+DANGER/.test(raw))status='danger';else if(/WARNING|ORANGE/.test(raw)&&!/BELOW\s+WARNING/.test(raw))status='warning';else if(/WATCH|RISING|INCREASING|YELLOW/.test(raw))status='watch';return{level,warning,danger,status,raw}}
function candidate(o,la,lo){o=flat(o);const c=coord(o),s=stage(o),t=stamp(o);if(!c||!trusted(o)||s.level===null)return null;return{o,name:name(o),basin:basin(o),lat:c[0],lon:c[1],distanceKm:km(la,lo,c[0],c[1]),time:t,ageMs:ageMs(o),fresh:isLive(o),recent:true,status:s.status,rawStatus:s.raw,level:s.level,warning:s.warning,danger:s.danger,source:String(o?.dataSource||o?.data_source||'DHM / BIPAD')}}
function allCandidates(la,lo){return(window.FloodSafe?.state?.stations||[]).map(o=>candidate(o,la,lo)).filter(Boolean)}
function sameRiverHits(names,list){const hits=[];for(const x of list){let sc=0;for(const n of names)sc=Math.max(sc,scoreName(n,x.name));if(sc>=88)hits.push({...x,_score:sc})}return hits.sort((a,b)=>b._score-a._score||a.distanceKm-b.distanceKm||a.ageMs-b.ageMs)}
function forWaterway(w,la,lo){const names=variants(w),all=allCandidates(la,lo);if(!all.length||!names.length)return null;const same=sameRiverHits(names,all);const exact=same.find(x=>x.distanceKm<=SAME_RIVER_LOCAL_KM)||null;if(exact)return{...exact,sameRiver:true,reference:false,archived:false,coverage:exact.fresh?'same-river-live':'same-river-current'};const remote=same[0]||null;return remote?{...remote,sameRiver:false,reference:true,sameRiverRemote:true,archived:false,coverage:'same-river-remote-reference'}:null}
function nearby(la,lo,maxKm=40,limit=100){return allCandidates(la,lo).filter(x=>x.distanceKm<=maxKm).sort((a,b)=>a.distanceKm-b.distanceKm||a.ageMs-b.ageMs).slice(0,limit)}
window.FloodSafeGauge={forWaterway,nearby,SAME_RIVER_LOCAL_KM,LIVE_MS:LIVE,RECENT_MS:RECENT,scoreName,variants};
})();