(()=>{'use strict';
if(window.__fsImpactLiveV1)return;window.__fsImpactLiveV1=true;
const URL='../../data/floodsafe-people-status.json',POLL=15000;
const $=id=>document.getElementById(id),lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne',tr=(ne,en)=>lang()==='en'?en:ne;
const allowed=s=>/(?:ronb|radio\s*nepal|nepal\s*police|ndrrma|national\s*disaster|nepal\s*government|government\s*of\s*nepal|ministry|gov\.np)/i.test(String(s||''));
const safeUrl=u=>{try{const x=new URL(String(u||''));return /^https?:$/.test(x.protocol)?x.href:''}catch{return''}};
const ts=t=>+new Date(t||0)||0;
function fmt(t){if(!ts(t))return'';try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return''}}
function metric(j,kind){const m=kind==='death'?{value:j.recovered_bodies,source:j.recovered_source,url:j.recovered_source_url,time:j.recovered_update_iso||j.recovered_update_time}:kind==='missing'?{value:j.missing_minimum,source:j.missing_source,url:j.missing_source_url,time:j.missing_update_time}:{value:j.rescued_alive,source:j.rescued_source,url:j.rescued_source_url,time:j.rescued_update_time};return allowed(m.source)&&Number.isFinite(Number(m.value))&&Number(m.value)>=0?{...m,value:Number(m.value)}:{...m,value:null}}
function link(m){if(m.value===null)return tr('पुष्टि update प्रतीक्षा','Waiting for verified update');const u=safeUrl(m.url),name=String(m.source||tr('पुष्टि स्रोत','Verified source'));return u?`<a href="${u}" target="_blank" rel="noopener noreferrer">${name}</a>${m.time?' • '+fmt(m.time):''}`:`${name}${m.time?' • '+fmt(m.time):''}`}
function apply(j){const d=metric(j,'death'),m=metric(j,'missing'),r=metric(j,'rescued');if($('impactEvent'))$('impactEvent').textContent=lang()==='en'?(j.event||'Current flood event'):(j.event_ne||'हालको बाढी घटना');if($('impactDeaths'))$('impactDeaths').textContent=d.value??'—';if($('impactMissing'))$('impactMissing').textContent=m.value??'—';if($('impactRescued'))$('impactRescued').textContent=r.value??'—';const newest=Math.max(ts(d.time),ts(m.time),ts(r.time));if($('impactFresh'))$('impactFresh').textContent=newest?tr(`पछिल्लो पुष्टि update • ${fmt(newest)}`,`Latest verified update • ${fmt(newest)}`):tr('RONB • Radio Nepal • सरकारी पुष्टि update प्रतीक्षा','Waiting for RONB • Radio Nepal • government verification');if($('impactDetail'))$('impactDetail').innerHTML=`<div style="display:grid;gap:6px"><div><b>${tr('मृत्यु','Deaths')}:</b> ${link(d)}</div><div><b>${tr('सम्पर्कविहीन','Missing')}:</b> ${link(m)}</div><div><b>${tr('उद्धार/सुरक्षित','Rescued/Safe')}:</b> ${link(r)}</div></div>`}
async function refresh(){try{const r=await fetch(URL+'?_impact='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);apply(await r.json())}catch{if($('impactFresh'))$('impactFresh').textContent=tr('पुष्टि भएको Human Status फेरि जाँच हुँदैछ','Checking verified Human Status again')}}
function boot(){refresh();setInterval(refresh,POLL);window.addEventListener('online',refresh);window.addEventListener('focus',refresh);window.addEventListener('fslanguage',refresh)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
