(()=>{'use strict';
if(window.__fsImpactLiveV3)return;window.__fsImpactLiveV3=true;
const LIVE='https://camkoacuokffryyrygda.supabase.co/functions/v1/human-status-safe-live',FALLBACK='../../data/floodsafe-people-status.json',POLL=10000;
const $=id=>document.getElementById(id),lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne',tr=(ne,en)=>lang()==='en'?en:ne;
const allowed=s=>/(?:ronb|radio\s*nepal|nepal\s*police|ndrrma|national\s*disaster|nepal\s*government|government\s*of\s*nepal|ministry|gov\.np)/i.test(String(s||''));
const safeUrl=u=>{try{const x=new URL(String(u||''));return /^https?:$/.test(x.protocol)?x.href:''}catch{return''}};
const ts=t=>+new Date(t||0)||0;
function fmt(t){if(!ts(t))return'';try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return''}}
function age(t){const x=ts(t);if(!x)return'';const s=Math.max(0,Math.floor((Date.now()-x)/1000));if(s<60)return tr(`${s} सेकेन्ड अघि`,`${s}s ago`);const m=Math.floor(s/60);if(m<60)return tr(`${m} मिनेट अघि`,`${m}m ago`);const h=Math.floor(m/60);return tr(`${h} घण्टा अघि`,`${h}h ago`)}
function metric(j,kind){const m=kind==='death'?{value:j.recovered_bodies,source:j.recovered_source,url:j.recovered_source_url,time:j.recovered_update_iso||j.recovered_update_time,minimum:false}:kind==='missing'?{value:j.missing_minimum,source:j.missing_source,url:j.missing_source_url,time:j.missing_update_time,minimum:Boolean(j.missing_is_minimum)}:{value:j.rescued_alive,source:j.rescued_source,url:j.rescued_source_url,time:j.rescued_update_time,minimum:false};return allowed(m.source)&&Number.isFinite(Number(m.value))&&Number(m.value)>=0?{...m,value:Number(m.value)}:{...m,value:null}}
function shown(m){return m.value===null?'—':`${Math.round(m.value).toLocaleString('en-GB')}${m.minimum?'+':''}`}
function link(m){if(m.value===null)return tr('पुष्टि update प्रतीक्षा','Waiting for verified update');const u=safeUrl(m.url),name=String(m.source||tr('पुष्टि स्रोत','Verified source'));return u?`<a href="${u}" target="_blank" rel="noopener noreferrer">${name}</a>${m.time?' • '+fmt(m.time):''}`:`${name}${m.time?' • '+fmt(m.time):''}`}
function apply(j){const d=metric(j,'death'),m=metric(j,'missing'),r=metric(j,'rescued');if($('impactEvent'))$('impactEvent').textContent=lang()==='en'?(j.event||'Bhotekoshi flash flood'):(j.event_ne||'भोटेकोशी आकस्मिक बाढी');if($('impactDeaths'))$('impactDeaths').textContent=shown(d);if($('impactMissing'))$('impactMissing').textContent=shown(m);if($('impactRescued'))$('impactRescued').textContent=shown(r);const newest=Math.max(ts(d.time),ts(m.time),ts(r.time));if($('impactFresh'))$('impactFresh').textContent=newest?tr(`पछिल्लो पुष्टि update • ${age(newest)} • ${fmt(newest)}`,`Latest verified update • ${age(newest)} • ${fmt(newest)}`):tr('पुष्टि Human Status update प्रतीक्षा','Waiting for verified Human Status update');if($('impactDetail'))$('impactDetail').innerHTML=`<div style="display:grid;gap:6px"><div><b>${tr('मृत्यु','Deaths')}:</b> ${link(d)}</div><div><b>${tr('सम्पर्कविहीन','Missing')}:</b> ${link(m)}${m.minimum?` • ${tr('कम्तीमा','at least')}`:''}</div><div><b>${tr('उद्धार/सुरक्षित','Rescued/Safe')}:</b> ${link(r)}</div></div>`}
async function get(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'_fsimpact='+Date.now(),{cache:'no-store',credentials:'omit'});if(!r.ok)throw Error(String(r.status));return r.json()}
async function refresh(){try{const j=await get(LIVE);if(j?.status==='error')throw Error(j.error||'live error');apply(j);window.__fsImpactLiveState={connected:true,checkedAt:new Date().toISOString()};return}catch(e){console.warn('FloodSafe Human Status',e)}try{apply(await get(FALLBACK));window.__fsImpactLiveState={connected:false,checkedAt:new Date().toISOString()}}catch{if($('impactFresh'))$('impactFresh').textContent=tr('पुष्टि Human Status फेरि जाँच हुँदैछ','Checking verified Human Status again')}}
function boot(){refresh();setInterval(refresh,POLL);window.addEventListener('online',refresh);window.addEventListener('focus',refresh);window.addEventListener('fslanguage',refresh)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
