(()=>{
'use strict';
if(window.__fsV25Language)return;window.__fsV25Language=true;
const KEY='fs23-lang',KCHA='https://kchakhabar.com/api/v1/today.json?limit=100';
const lang=()=>localStorage.getItem(KEY)==='en'?'en':'ne';
const pairs=[
['बाढी सुरक्षा नेपाल','FloodSafe Nepal'],['नेपाल • Live safety information','Nepal • Live safety information'],['नेपाल • प्रत्यक्ष सुरक्षा जानकारी','Nepal • Live safety information'],
['प्रत्यक्ष','LIVE'],['मुख्य जानकारी','Key information'],['नक्सा • चेतावनी • Human Status • मौसम • राष्ट्रिय समाचार','Map • Alerts • Human Status • Weather • National News'],['नक्सा • चेतावनी • मानव स्थिति • मौसम • राष्ट्रिय समाचार','Map • Alerts • Human Status • Weather • National News'],
['नक्सा','Map'],['नदी, बहाव, वर्षा र सडक स्थिति','Rivers, flow, rainfall and road status'],['चेतावनी','Alerts'],['बाढी, नदी र सडक चेतावनी','Flood, river and road alerts'],['मानव स्थिति','Human Status'],['सक्रिय विपद् वा नेपाल दुर्घटना अपडेट','Active disaster or Nepal accident updates'],['मेरो मौसम','My Weather'],['तपाईंको स्थानको विस्तृत मौसम','Detailed weather for your location'],['समाचार','News'],['राष्ट्रिय ताजा समाचार','National Flash News'],['स्रोत','Sources'],['सरकारी र द्रुत सूचना स्रोत','Official and rapid information sources'],
['नेपाल विपद् / दुर्घटना निगरानी','Nepal Disaster / Accident Monitor'],['नेपालभरि सक्रिय मुख्य घटना खोजिँदैछ…','Finding the active main event across Nepal…'],['पुष्टि','VERIFIED'],['मृत्यु','Deaths'],['सम्पर्कविहीन','Missing'],['उद्धार','Rescued'],['प्रत्यक्ष स्रोत अवस्था','Live source health'],['ताजा राष्ट्रिय समाचार','Current National News'],['नयाँ समाचार खोजिँदैछ…','Finding new headlines…'],
['गृहपृष्ठ','Home'],['मानव','People'],['स्रोतहरू','Sources'],
['सक्रिय विपद् • नेपाल दुर्घटना अपडेट','Active disaster • Nepal accident updates'],['नयाँ जानकारी जाँच हुँदैछ…','Checking for new information…'],['सक्रिय विपद् / दुर्घटना','Active Disaster / Accident'],['आधिकारिक स्रोत','Official sources'],['मृत्यु, खोज र उद्धार अपडेट।','Deaths, search and rescue updates.'],['विपद्, सम्पर्कविहीन, उद्धार र क्षति विवरण।','Disaster, missing, rescue and damage information.'],['पछिल्ला BIPAD मानव अपडेट','Latest BIPAD people updates'],
['राष्ट्रिय समाचार','National News'],['नेपालका विभिन्न समाचार कक्षबाट ताजा शीर्षक','Current headlines from Nepal newsrooms'],['ताजा समाचार','Flash News'],['समाचार खोजिँदैछ…','Finding current news…'],
['बाढी तथा सडक चेतावनी','Flood and Road Alerts'],['मेरो क्षेत्रको उच्च चेतावनी','High Alert for My Area'],['स्थान निगरानी सक्रिय गरिएको छैन।','Location monitor is not enabled.'],['🔔 स्थान + अलार्म सक्रिय','🔔 Enable Location + Alarm'],['दायरा','Radius'],['BIPAD उच्च चेतावनी','BIPAD high alerts'],['DHM नदी चेतावनी','DHM river alerts'],['हाल बन्द सडक','Currently closed roads'],['सडकको अहिलेको अवस्था','Current Road Status'],['७७ जिल्ला स्थिति','77 District Status'],['जिल्ला','District'],['सबै ७७ जिल्ला','All 77 districts'],['हालका चेतावनी','Current Alerts'],['द्रुत बाढी / पहिरो / भूकम्प संकेत','Rapid Flood / Landslide / Quake Signals'],['प्रारम्भिक स्रोत जाँच हुँदैछ…','Checking early sources…'],['सडक प्रारम्भिक अपडेट','Road Early Updates'],['नयाँ सडक खबर खोजिँदैछ…','Finding new road reports…'],['स्रोत जडान','Source connection'],
['तपाईंको स्थानको मौसम','Weather at Your Location'],['तापक्रम • वर्षा • हावा • आर्द्रता','Temperature • Rain • Wind • Humidity'],['स्थान पर्खिँदै…','Waiting for location…'],['◎ मेरो स्थान','◎ My location'],['GPS स्थान आवश्यक','GPS location required'],['अहिलेको वर्षा','Current rain'],['आर्द्रता','Humidity'],['हावा','Wind'],['हावाको झोका','Wind gust'],['आज न्यून / उच्च','Today low / high'],['वर्षाको सम्भावना','Rain chance'],['मौसम विवरण लोड हुँदैछ…','Loading weather details…'],['महसुस हुने तापक्रम','Feels like'],
['आधिकारिक स्रोतहरू','Official Sources'],['नदीको पानी सतह, वर्षा र बाढी चेतावनी।','River level, rainfall and flood warnings.'],['मृत्यु, खोज, उद्धार र दुर्घटना सम्बन्धी आधिकारिक अपडेट।','Official updates on deaths, search, rescue and accidents.'],['सडक बन्द, अवरोध र सडक अवस्था।','Road closures, obstructions and road conditions.'],['राष्ट्रिय तथा जिल्ला तहका आपतकालीन सरकारी सूचना।','National and district-level emergency government notices.'],['द्रुत / प्रारम्भिक संकेत','Rapid / early signals'],
['नक्सा खोलिँदैछ…','Opening map…'],['नक्सा प्रत्यक्ष पूर्ण-स्क्रिन मोडमा खुल्छ।','The map opens directly in full-screen mode.'],['नक्सा खोल्नुहोस्','Open map'],
['नेपाल समय • नेपाली पात्रो','Nepal time • Nepali calendar'],['तपाईंको स्थानको मौसम','Weather at your location'],['मौसम जाँच हुँदैछ','Checking weather'],['वर्षा','Rain'],['वर्षा सम्भावना','Rain chance'],['न्यून / उच्च','Low / high'],['◎ मेरो स्थान प्रयोग','◎ Use my location'],['🔔 स्थान उच्च चेतावनी सक्रिय','🔔 Enable Location High Alert'],['उच्च जोखिम निगरानी सक्रिय गरिएको छैन।','High-risk monitoring is not enabled.'],
['पछिल्लो मानव स्थिति जाँच हुँदैछ…','Checking latest Human Status…'],['डेटा जाँच हुँदैछ…','Checking data…'],['फेरि जाँच हुँदैछ…','Rechecking…'],
['⚡ आजको Nepal Safety Snapshot',"⚡ Today's Nepal Safety Snapshot"],['हरेक ५ sec मा स्रोत जाँच','Source check every 5 sec'],['🌐 Earthquake Today','🌐 Earthquake Today'],['⛰️ Landslide Today','⛰️ Landslide Today'],['आज नयाँ record भेटिएको छैन','No new record today'],['आज नयाँ पहिरो report भेटिएको छैन','No new landslide report today'],['🚧 बन्द सडक र वैकल्पिक मार्ग','🚧 Closed roads and alternative routes'],['Road source जाँच हुँदैछ…','Checking road sources…'],['कारण प्रकाशित छैन','Reason not published'],['आधिकारिक/विश्वसनीय स्रोतमा प्रकाशित छैन','Not published by an official/reliable source'],['अहिले sourceमा CLOSED भनेर पुष्टि भएको सडक भेटिएको छैन। Monitoring चलिरहेको छ।','No road is currently confirmed CLOSED by the source. Monitoring continues.'],['नयाँ rapid signal खोजिँदैछ…','Finding new rapid signals…'],['स्रोत खोल्नुहोस्','Open source'],['नेपाल दुर्घटना','Nepal accident'],['नेपाल विपद्','Nepal disaster'],
['FLOOD','Flood'],['LANDSLIDE','Landslide'],['ACCIDENT','Accident'],['CLOSED','Closed'],['MEDIA FLOOD','Media flood signal'],['MEDIA LANDSLIDE','Media landslide signal'],['NEPAL AIR','Nepal aviation'],['6.5+ QUAKE','6.5+ earthquake'],['बाढी अपडेट','Flood update'],['पहिरो अपडेट','Landslide update']
];
const neToEn=new Map(pairs),enToNe=new Map(pairs.map(([ne,en])=>[en,ne]));
let mediaNeToEn=new Map(),mediaEnToNe=new Map(),mediaBusy=false,lastMedia=0;
const hasNe=s=>/[\u0900-\u097F]/.test(String(s||''));
function phraseReplace(raw){let s=raw;if(lang()==='en'){
  const rr=[[/\b(\d+) मिनेट अघि\b/g,'$1 min ago'],[/\b(\d+) घण्टा अघि\b/g,'$1 hr ago'],[/अहिले/g,'just now'],[/समय उपलब्ध छैन/g,'time unavailable'],[/यो घटना हाल national news highlightमा छ/g,'This event is currently a national news highlight'],[/हाल ठूलो disaster highlightमा छैन • पछिल्ला Nepal accident updates/g,'No major disaster is highlighted now • showing recent Nepal accident updates'],[/नयाँ Nepal disaster वा accident update खोजिँदैछ…/g,'Finding new Nepal disaster or accident updates…'],[/Source check प्रत्येक ५ sec/g,'Source check every 5 sec'],[/हरेक ५ sec source check/g,'Source check every 5 sec'],[/official flood\/road values छुट्टै छन्/g,'official flood/road values are shown separately'],[/कारण:\s*/g,'Reason: '],[/वैकल्पिक मार्ग:\s*/g,'Alternative route: '],[/स्रोत:\s*/g,'Source: ']];for(const [r,v] of rr)s=s.replace(r,v)
}else{
  const rr=[[/\b(\d+) min ago\b/g,'$1 मिनेट अघि'],[/\b(\d+) hr ago\b/g,'$1 घण्टा अघि'],[/\bjust now\b/gi,'अहिले'],[/\btime unavailable\b/gi,'समय उपलब्ध छैन'],[/\bSource check every 5 sec\b/gi,'हरेक ५ सेकेन्डमा स्रोत जाँच'],[/\bReason:\s*/gi,'कारण: '],[/\bAlternative route:\s*/gi,'वैकल्पिक मार्ग: '],[/\bOpen source\b/gi,'स्रोत खोल्नुहोस्'],[/\bMedia flood signal\b/gi,'सञ्चार बाढी संकेत'],[/\bMedia landslide signal\b/gi,'सञ्चार पहिरो संकेत'],[/\bClosed\b/g,'बन्द'],[/\bAccident\b/g,'दुर्घटना'],[/\bLandslide\b/g,'पहिरो'],[/\bFlood\b/g,'बाढी'],[/\bNepal aviation\b/g,'नेपाल हवाई दुर्घटना'],[/\b6\.5\+ earthquake\b/g,'६.५+ भूकम्प']];for(const [r,v] of rr)s=s.replace(r,v)
}return s}
function translateText(raw){const t=String(raw||'').trim();if(!t)return raw;const map=lang()==='en'?neToEn:enToNe,media=lang()==='en'?mediaNeToEn:mediaEnToNe;let v=map.get(t)||media.get(t);if(v===undefined)v=phraseReplace(t);const lead=String(raw).match(/^\s*/)?.[0]||'',trail=String(raw).match(/\s*$/)?.[0]||'';return lead+v+trail}
function skip(node){const p=node.parentElement;if(!p)return true;return !!p.closest('script,style,noscript,code,pre,[data-no-i18n]')}
function applyNode(root){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const n of nodes){if(skip(n))continue;const v=translateText(n.nodeValue||'');if(v!==n.nodeValue)n.nodeValue=v}}
function protectTargetLanguage(){const selectors=['#disasterSpotlightList .item','#rapidSignalList .item','#peopleLiveList .item'];for(const sel of selectors){for(const card of document.querySelectorAll(sel)){for(const el of card.querySelectorAll('h4,p')){const raw=(el.textContent||'').trim();if(!raw)continue;const mapped=(lang()==='en'?mediaNeToEn:mediaEnToNe).get(raw);if(mapped){el.textContent=mapped;continue}if(lang()==='en'&&hasNe(raw)){el.textContent='Source text is not available in English.'}else if(lang()==='ne'&&!hasNe(raw)&&/[A-Za-z]{4,}\s+[A-Za-z]{3,}/.test(raw)&&!/^M\d/.test(raw)){el.textContent='स्रोत पाठ नेपालीमा उपलब्ध छैन।'}}}}
function linkLabel(a,ne,en){if(!a)return;let text=[...a.childNodes].find(n=>n.nodeType===Node.TEXT_NODE);if(!text){text=document.createTextNode('');a.appendChild(text)}text.nodeValue=lang()==='en'?en:ne}
function common(){document.documentElement.lang=lang();const nav=document.querySelector('.footerNav');if(nav){linkLabel(nav.querySelector('a[href="./"]'),'गृहपृष्ठ','Home');linkLabel(nav.querySelector('a[href*="map"]'),'नक्सा','Map');linkLabel(nav.querySelector('a[href*="alerts"]'),'चेतावनी','Alerts');linkLabel(nav.querySelector('a[href*="people"]'),'मानव','People');linkLabel(nav.querySelector('a[href*="news"]'),'समाचार','News');linkLabel(nav.querySelector('a[href*="sources"]'),'स्रोत','Sources')}const live=document.querySelector('.livePill');if(live)live.textContent=lang()==='en'?'LIVE':'प्रत्यक्ष'}
function button(){let b=document.getElementById('fsLangToggle');if(!b){b=document.createElement('button');b.id='fsLangToggle';b.type='button';b.style.cssText='border:1px solid #6d4b3e;background:#1a1110;color:#fff;border-radius:999px;padding:7px 10px;font-size:11px;font-weight:900;cursor:pointer;white-space:nowrap';const top=document.querySelector('.top');if(top)top.appendChild(b);b.addEventListener('click',()=>{localStorage.setItem(KEY,lang()==='en'?'ne':'en');apply();loadMediaPairs(true);window.dispatchEvent(new Event('fs-language-change'))})}if(b)b.textContent=lang()==='en'?'नेपाली':'English'}
async function loadMediaPairs(force=false){if(mediaBusy||(!force&&Date.now()-lastMedia<60000))return;mediaBusy=true;lastMedia=Date.now();try{const c=new AbortController(),to=setTimeout(()=>c.abort(),6000);const r=await fetch(KCHA,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',signal:c.signal,headers:{accept:'application/json'}});clearTimeout(to);if(!r.ok)throw Error(r.status);const j=await r.json(),stories=Array.isArray(j?.stories)?j.stories:[],a=new Map(),b=new Map();for(const s of stories){for(const [ne,en] of [[s.topic_ne,s.topic_en],[s.summary_ne,s.summary_en]]){const n=String(ne||'').trim(),e=String(en||'').trim();if(n&&e){a.set(n,e);b.set(e,n)}}}mediaNeToEn=a;mediaEnToNe=b;apply();protectTargetLanguage()}catch{}finally{mediaBusy=false}}
function apply(){common();applyNode(document.body);button();protectTargetLanguage()}
function boot(){apply();loadMediaPairs(true);const obs=new MutationObserver(ms=>{for(const m of ms){for(const n of m.addedNodes){if(n.nodeType===Node.TEXT_NODE){if(!skip(n)){const v=translateText(n.nodeValue||'');if(v!==n.nodeValue)n.nodeValue=v}}else if(n.nodeType===Node.ELEMENT_NODE)applyNode(n)}}common();button();protectTargetLanguage()});obs.observe(document.body,{childList:true,subtree:true});setInterval(()=>loadMediaPairs(false),60000);window.addEventListener('storage',e=>{if(e.key===KEY){apply();loadMediaPairs(true)}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.FSLang={get:lang,pick:(ne,en)=>lang()==='en'?en:ne,apply};
})();
