(()=>{
'use strict';
if(window.__fsLanguageRuntimeV2)return;window.__fsLanguageRuntimeV2=true;
const KEY='fs23-lang',lang=()=>localStorage.getItem(KEY)==='en'?'en':'ne';
const pairs=[
['बाढी • नदी • सडक','Flood • River • Road'],['DHM • BIPAD • सडक विभाग','DHM • BIPAD • Department of Roads'],['प्रत्यक्ष चेतावनी जाँच हुँदैछ…','Checking live alerts…'],['यी प्रारम्भिक संकेत हुन्। नदीको वास्तविक पानी सतह र चेतावनी सीमा DHM/BIPAD कै आधिकारिक डेटा बाट देखाइन्छ।','These are early signals. Actual river level and warning thresholds are shown from official DHM/BIPAD data.'],['आधिकारिक सडक अवस्था नबदलिई सञ्चारमाध्यमको प्रारम्भिक संकेत छुट्टै देखाइन्छ।','Media early signals are shown separately and do not overwrite official road status.'],['सडक विभाग NAVIGATE','DoR NAVIGATE'],['नेपाल','Nepal'],['समस्या','ISSUE'],['सतर्क','WATCH'],
['नेपाल समय • नेपाली पात्रो','Nepal time • Nepali calendar'],['लोड हुँदैछ…','Loading…'],['मौसम जाँच हुँदैछ','Checking weather'],['जीपीएस सक्रिय गरेपछि तपाईंको वास्तविक क्षेत्रको आजको मौसम देखिन्छ।','Enable GPS to see today’s weather for your actual area.'],['🔔 स्थान उच्च चेतावनी सक्रिय','🔔 Enable Location High Alert'],['उच्च जोखिम निगरानी सक्रिय गरिएको छैन।','High-risk monitoring is not enabled.'],['प्रत्यक्ष स्रोत जाँच हुँदैछ…','Checking live sources…'],['📡 प्रत्यक्ष स्रोत अवस्था','📡 Live Source Status'],['BIPAD चेतावनी…','BIPAD alerts…'],['DHM नदी…','DHM river…'],['सडक डेटा…','Road data…'],['मानव डेटा…','Human data…'],['समाचार स्रोत…','News sources…'],['📰 ताजा राष्ट्रिय समाचार','📰 Current National News'],
['नेपाल प्रहरी • NDRRMA/BIPAD • द्रुत सञ्चार संकेत','Nepal Police • NDRRMA/BIPAD • rapid media signals'],['विवरण लोड हुँदैछ…','Loading details…'],['नेपाल प्रहरी','Nepal Police'],['मृत्यु, खोज र उद्धार अपडेट।','Death, search and rescue updates.'],['BIPAD पोर्टल','BIPAD Portal'],['विपद्, सम्पर्कविहीन, उद्धार र क्षति विवरण।','Disaster, missing, rescue and damage information.'],
['राष्ट्रिय • ताजा • पछिल्लो','National • Flash • Latest'],['समाचार','News'],
['वास्तविक जीपीएस स्थान','Actual GPS location'],['स्थानीय','LOCAL'],['स्रोत: Open-Meteo मौसम मोडेल','Source: Open-Meteo weather model'],
['आधिकारिक र द्रुत सूचना','Official and rapid information'],['🏛️ आधिकारिक स्रोत','🏛️ Official Sources'],['DHM • BIPAD/NDRRMA • नेपाल प्रहरी • सडक विभाग • गृह मन्त्रालय','DHM • BIPAD/NDRRMA • Nepal Police • Department of Roads • Home Ministry'],['🌊 DHM नेपाल','🌊 DHM Nepal'],['नदीको पानी सतह, वर्षा र बाढी चेतावनी। बाढी सतहको मुख्य आधिकारिक स्रोत यही रहन्छ।','River levels, rainfall and flood warnings. This remains the primary official source for flood levels.'],['विपद् चेतावनी, घटना, क्षति, उद्धार र घटना विवरण।','Disaster alerts, incidents, losses, rescue and incident details.'],['👮 नेपाल प्रहरी','👮 Nepal Police'],['मृत्यु, खोज, उद्धार र दुर्घटना सम्बन्धी आधिकारिक अपडेट।','Official updates on deaths, search, rescue and accidents.'],['🚧 सडक विभाग','🚧 Department of Roads'],['सडक बन्द, अवरोध र सडक अवस्था।','Road closures, obstructions and road conditions.'],['सडक अवस्था','Road condition'],['🛣️ सडक विभाग NAVIGATE','🛣️ DoR NAVIGATE'],['बन्द, खुलेका र आंशिक खुलेका सडक, घटना विवरण तथा बाढी/पहिरो सडक-सुरक्षा तह।','Closed, open and partially open roads, incident details and flood/landslide road-safety layers.'],['🏠 गृह मन्त्रालय','🏠 Home Ministry'],['राष्ट्रिय तथा जिल्ला तहका आपतकालीन सरकारी सूचना। कुनै एक जिल्लामा स्थिर गरिएको छैन।','National and district-level emergency government information; not fixed to any single district.'],['गृह मन्त्रालय','Home Ministry'],['३५+ नेपाली समाचार कक्षका समूहबद्ध शीर्षकलाई कभरेज र समयअनुसार क्रमबद्ध गरिन्छ। बाढी, पहिरो, सडक र दुर्घटनाको प्रारम्भिक संकेतका लागि; आधिकारिक अलार्म होइन।','Grouped headlines from 35+ Nepal newsrooms are ranked by coverage and time for early flood, landslide, road and accident signals; they are not official alarms.'],['🌐 USGS भूकम्प स्रोत','🌐 USGS Earthquake Source'],['प्रत्यक्ष GeoJSON स्रोत। नेपाल क्षेत्रको ६.५+ भूकम्पको द्रुत तुलना गर्न प्रयोग हुन्छ।','Live GeoJSON source used for rapid cross-checking of magnitude 6.5+ earthquakes relevant to Nepal.'],['जीपीएस स्थानको अहिलेको मौसम र छोटो पूर्वानुमानका लागि दोस्रो मौसम स्रोत। आपतकालीन बाढी सतहको विकल्प होइन।','Secondary weather source for current GPS-location weather and short forecasts; not a substitute for emergency flood-level data.'],['प्राथमिकता: मौसम/बाढी पहिलो • पहिरो दोस्रो • नेपाल क्षेत्रको ६.५+ भूकम्प • नेपालभित्रको हवाई दुर्घटना। ठूलो घटना सञ्चारमाध्यमको मुख्य समाचारबाट हटेपछि मानव स्थितिमा पुरानो विपद् अड्किरहँदैन; पछिल्लो नेपाल दुर्घटना अपडेटमा फर्किन्छ।','Priority: weather/flood first • landslide second • magnitude 6.5+ earthquakes relevant to Nepal • aviation accidents in Nepal. When a major event is no longer a current media highlight, the app moves to recent Nepal accident updates instead of keeping a stale disaster pinned.'],
['नक्सा खोलिँदैछ • बाढी सुरक्षा नेपाल','Opening Map • FloodSafe Nepal'],['प्रत्यक्ष बाढी नक्सा','Live Flood Map'],['पूर्ण-स्क्रिन नक्सा','Full-screen map'],['🗺️ नक्सा खोलिँदैछ…','🗺️ Opening map…'],['नक्सा प्रत्यक्ष पूर्ण-स्क्रिन मोडमा खुल्छ।','The live map opens in full-screen mode.'],['नक्सा खोल्नुहोस्','Open map']
];
const ne2en=new Map(pairs),en2ne=new Map(pairs.map(([a,b])=>[b,a]));
let applying=false;
function replacePhrases(s){let x=String(s||'');if(lang()==='en')return x.replace(/Live update जाँच हुँदैछ…/g,'Checking live updates…').replace(/Live check ([^•]+) • अर्को जाँच ५ sec/g,'Live check $1 • next check 5 sec').replace(/Location High Alert सक्रिय गरिएको छैन।/g,'Location High Alert is not enabled.').replace(/High Alert सक्रिय • location जाँच हुँदैछ/g,'High Alert enabled • checking location').replace(/High Alert सक्रिय • नयाँ स्थानीय खतरा छैन/g,'High Alert enabled • no new local danger').replace(/स्थानीय उच्च जोखिम सक्रिय/g,'local high risks active').replace(/मुख्य live स्रोत (\d+)\/३ connected/g,'Main live sources $1/3 connected').replace(/बाँकी फेरि जाँच हुँदैछ/g,'rechecking the rest').replace(/मुख्य live स्रोत फेरि जाँच हुँदैछ/g,'Rechecking main live sources').replace(/जाँच हुँदैछ/g,'checking').replace(/फेरि जाँच हुँदैछ/g,'rechecking').replace(/स्रोत/g,'source').replace(/अर्को जाँच/g,'next check').replace(/सेकेन्ड/g,'sec');
return x.replace(/Checking live updates…/g,'प्रत्यक्ष अपडेट जाँच हुँदैछ…').replace(/Live check ([^•]+) • next check 5 sec/g,'प्रत्यक्ष जाँच $1 • अर्को जाँच ५ सेकेन्ड').replace(/Location High Alert is not enabled\./g,'स्थान उच्च चेतावनी सक्रिय गरिएको छैन।').replace(/High Alert enabled • checking location/g,'उच्च चेतावनी सक्रिय • स्थान जाँच हुँदैछ').replace(/High Alert enabled • no new local danger/g,'उच्च चेतावनी सक्रिय • नयाँ स्थानीय खतरा छैन').replace(/Main live sources (\d+)\/3 connected/g,'मुख्य प्रत्यक्ष स्रोत $1/३ जडित').replace(/rechecking the rest/g,'बाँकी फेरि जाँच हुँदैछ').replace(/Rechecking main live sources/g,'मुख्य प्रत्यक्ष स्रोत फेरि जाँच हुँदैछ')}
function textValue(raw){const lead=String(raw||'').match(/^\s*/)?.[0]||'',trail=String(raw||'').match(/\s*$/)?.[0]||'',t=String(raw||'').trim();if(!t)return raw;const v=(lang()==='en'?ne2en:en2ne).get(t)||replacePhrases(t);return lead+v+trail}
function eligible(n){const p=n.parentElement;if(!p||p.closest('script,style,noscript,code,pre,[data-no-i18n]'))return false;return !!p.closest('header,.pageHead,.grid,.sectionHead,.notice,.statusLine,.healthChip,.footerNav,.actions,.sourceCard,.weatherMeta,.weatherGrid,.todayHero,.stats,.radiusBox')}
function syncToggle(){const b=document.getElementById('fsLangToggle');if(!b)return;const v=lang()==='en'?'Nepali':'अङ्ग्रेजी';if(b.textContent!==v)b.textContent=v;b.setAttribute('aria-label',lang()==='en'?'Switch to Nepali':'अङ्ग्रेजीमा बदल्नुहोस्')}
function apply(root=document.body){if(applying||!root)return;applying=true;try{const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const n of nodes){if(!eligible(n))continue;const v=textValue(n.nodeValue);if(v!==n.nodeValue)n.nodeValue=v}document.documentElement.lang=lang();syncToggle()}finally{applying=false}}
function boot(){apply();let q=false;const ob=new MutationObserver(ms=>{if(applying||q)return;q=true;queueMicrotask(()=>{q=false;for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1)apply(n);apply()})});ob.observe(document.body,{childList:true,subtree:true,characterData:true});window.addEventListener('fs-language-change',()=>apply());window.addEventListener('storage',e=>{if(e.key===KEY)apply()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();