(()=>{
'use strict';
if(window.__fsLanguageV4)return;window.__fsLanguageV4=true;
const KEY='fs23-lang',KCHA='https://kchakhabar.com/api/v1/today.json?limit=100';
const get=()=>localStorage.getItem(KEY)==='en'?'en':'ne',pick=(ne,en)=>get()==='en'?en:ne;
const pairs=[
['बाढी सुरक्षा नेपाल','FloodSafe Nepal'],['नेपाल • प्रत्यक्ष सुरक्षा जानकारी','Nepal • Live safety information'],['प्रत्यक्ष','LIVE'],['समक्रमण','SYNC'],['अवस्था','STATUS'],['मुख्य जानकारी','Key information'],['नक्सा • चेतावनी • मानव स्थिति • मौसम • राष्ट्रिय समाचार','Map • Alerts • Human Status • Weather • National News'],['नक्सा • चेतावनी • Human Status • मौसम • राष्ट्रिय समाचार','Map • Alerts • Human Status • Weather • National News'],
['गृहपृष्ठ','Home'],['नक्सा','Map'],['चेतावनी','Alerts'],['मानव','People'],['समाचार','News'],['स्रोत','Sources'],['मानव स्थिति','Human Status'],['मेरो मौसम','My Weather'],['नदी, बहाव, वर्षा र सडक स्थिति','Rivers, flow, rainfall and road status'],['बाढी, नदी र सडक चेतावनी','Flood, river and road alerts'],['सक्रिय विपद् वा नेपाल दुर्घटना अपडेट','Active disaster or Nepal accident updates'],['तपाईंको स्थानको विस्तृत मौसम','Detailed weather for your location'],['राष्ट्रिय ताजा समाचार','Current national news'],['सरकारी र द्रुत सूचना स्रोत','Official and rapid information sources'],
['नेपाल विपद् / दुर्घटना निगरानी','Nepal Disaster / Accident Monitor'],['नेपालभरि सक्रिय मुख्य घटना खोजिँदैछ…','Finding the active main event across Nepal…'],['पुष्टि','VERIFIED'],['मृत्यु','Deaths'],['सम्पर्कविहीन','Missing'],['उद्धार','Rescued'],['प्रत्यक्ष स्रोत अवस्था','Live source health'],['ताजा राष्ट्रिय समाचार','Current National News'],['नयाँ समाचार खोजिँदैछ…','Finding current news…'],
['चेतावनी केन्द्र','Alert Centre'],['बाढी / नदी','Flood / River'],['सडक समस्या','Road Problems'],['बाढी र नदीका सक्रिय चेतावनी मात्र','Active flood and river warnings only'],['सडकको अहिलेको अवस्था','Current Road Status'],['मेरो क्षेत्रको उच्च चेतावनी','High Alert for My Area'],['स्थान निगरानी सक्रिय गरिएको छैन।','Location monitor is not enabled.'],['🔔 स्थान + अलार्म सक्रिय','🔔 Enable Location + Alarm'],['दायरा','Radius'],['BIPAD उच्च चेतावनी','BIPAD high alerts'],['DHM नदी चेतावनी','DHM river alerts'],['हाल बन्द सडक','Currently closed roads'],
['🌊 बाढी / नदी चेतावनी','🌊 Flood / River Alerts'],['🚧 सडक समस्या / बन्द–खुला स्थिति','🚧 Road Problems / Open–Closed Status'],['७७ जिल्ला स्थिति','77 District Status'],['समस्या भएका जिल्ला पहिले देखाइन्छन्','Districts with active issues are shown first'],['समस्या भएका जिल्ला','Districts with issues'],['जिल्ला','District'],['सबै ७७ जिल्ला','All 77 districts'],['आधिकारिक प्रत्यक्ष','OFFICIAL LIVE'],['प्रारम्भिक','EARLY'],['⚡ द्रुत बाढी / पहिरो / भूकम्प संकेत','⚡ Rapid Flood / Landslide / Quake Signals'],['प्रारम्भिक स्रोत जाँच हुँदैछ…','Checking early sources…'],
['राष्ट्रिय समाचार','National News'],['नेपालका विभिन्न समाचार कक्षबाट ताजा शीर्षक','Current headlines from Nepal newsrooms'],['ताजा समाचार','Flash News'],['समाचार खोजिँदैछ…','Finding current news…'],['पछिल्लो','LATEST'],['ताजा','FLASH'],['समाचार खोल्नुहोस्','Open article'],
['सक्रिय विपद् • नेपाल दुर्घटना अपडेट','Active disaster • Nepal accident updates'],['सक्रिय विपद् / दुर्घटना','Active Disaster / Accident'],['नयाँ जानकारी जाँच हुँदैछ…','Checking for new information…'],['आधिकारिक स्रोत','Official sources'],['मृत्यु, खोज र उद्धार अपडेट।','Deaths, search and rescue updates.'],['विपद्, सम्पर्कविहीन, उद्धार र क्षति विवरण।','Disaster, missing, rescue and damage information.'],['पछिल्ला BIPAD मानव अपडेट','Latest BIPAD people updates'],
['तपाईंको स्थानको मौसम','Weather at Your Location'],['तापक्रम • वर्षा • हावा • आर्द्रता','Temperature • Rain • Wind • Humidity'],['स्थान पर्खिँदै…','Waiting for location…'],['◎ मेरो स्थान','◎ My location'],['◎ मेरो स्थान प्रयोग','◎ Use my location'],['GPS स्थान आवश्यक','GPS location required'],['अहिलेको वर्षा','Current rain'],['आर्द्रता','Humidity'],['हावा','Wind'],['हावाको झोका','Wind gust'],['आज न्यून / उच्च','Today low / high'],['वर्षाको सम्भावना','Rain chance'],['वर्षा सम्भावना','Rain chance'],['मौसम विवरण लोड हुँदैछ…','Loading weather details…'],['महसुस हुने तापक्रम','Feels like'],['न्यून / उच्च','Low / high'],['वर्षा','Rain'],
['आधिकारिक स्रोतहरू','Official Sources'],['द्रुत / प्रारम्भिक संकेत','Rapid / early signals'],['स्रोत खोल्नुहोस्','Open source'],['⚡ आजको Nepal Safety Snapshot',"⚡ Today's Nepal Safety Snapshot"],['हरेक ५ sec मा स्रोत जाँच','Source check every 5 sec'],['🌐 Earthquake Today','🌐 Earthquake Today'],['⛰️ Landslide Today','⛰️ Landslide Today'],['आज नयाँ record भेटिएको छैन','No new record today'],['आज नयाँ पहिरो report भेटिएको छैन','No new landslide report today'],['नयाँ rapid signal खोजिँदैछ…','Finding new rapid signals…'],
['FLOOD','Flood'],['LANDSLIDE','Landslide'],['ACCIDENT','Accident'],['CLOSED','Closed'],['ROAD','Road'],['HIGH','High'],['WARNING','Warning'],['DANGER','Danger'],['MEDIA FLOOD','Media flood signal'],['MEDIA LANDSLIDE','Media landslide signal'],['NEPAL AIR','Nepal aviation'],['6.5+ QUAKE','6.5+ earthquake'],['EARLY','Early'],['बन्द','CLOSED'],['आंशिक खुला','PARTIALLY OPEN'],['पछिल्लो मानव स्थिति जाँच हुँदैछ…','Checking latest Human Status…'],['पुष्टि भएको मानव स्थिति समक्रमण हुँदैछ…','Syncing verified Human Status…'],['डेटा जाँच हुँदैछ…','Checking data…'],['फेरि जाँच हुँदैछ…','Rechecking…'],['जाँच हुँदैछ…','Checking…']
];
const ne2en=new Map(pairs),en2ne=new Map(pairs.map(([a,b])=>[b,a]));let mediaNe2En=new Map(),mediaEn2Ne=new Map(),mediaBusy=false,lastMedia=0,applying=false,queued=false;
function phrase(s){if(get()==='en')return s.replace(/(\d+) मिनेट अघि/g,'$1 min ago').replace(/(\d+) घण्टा अघि/g,'$1 hr ago').replace(/भर्खर|अहिले/g,'just now').replace(/समय उपलब्ध छैन/g,'time unavailable').replace(/डेटा अपडेट\s*/g,'Data updated ').replace(/पछिल्लो जाँच\s*/g,'last checked ').replace(/कारण:\s*/g,'Reason: ').replace(/वैकल्पिक मार्ग:\s*/g,'Alternative route: ').replace(/स्थान:\s*/g,'Location: ').replace(/अपडेट:\s*/g,'Updated: ').replace(/हरेक ५ सेकेन्ड/g,'every 5 sec').replace(/सेकेन्ड/g,'sec');return s.replace(/(\d+) min ago/g,'$1 मिनेट अघि').replace(/(\d+) hr ago/g,'$1 घण्टा अघि').replace(/\bjust now\b/gi,'अहिले').replace(/\btime unavailable\b/gi,'समय उपलब्ध छैन').replace(/\bData updated\s*/gi,'डेटा अपडेट ').replace(/\blast checked\s*/gi,'पछिल्लो जाँच ').replace(/\bReason:\s*/gi,'कारण: ').replace(/\bAlternative route:\s*/gi,'वैकल्पिक मार्ग: ').replace(/\bLocation:\s*/gi,'स्थान: ').replace(/\bUpdated:\s*/gi,'अपडेट: ').replace(/\bevery 5 sec\b/gi,'हरेक ५ सेकेन्ड')}
function translate(raw){const text=String(raw||''),t=text.trim();if(!t)return text;const map=get()==='en'?ne2en:en2ne,mm=get()==='en'?mediaNe2En:mediaEn2Ne,v=map.get(t)||mm.get(t)||phrase(t);if(v===t)return text;return(text.match(/^\s*/)?.[0]||'')+v+(text.match(/\s*$/)?.[0]||'')}
function skip(n){const p=n.parentElement;return !p||!!p.closest('script,style,noscript,code,pre,[data-no-i18n]')}
function applyRoot(root=document.body){if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),all=[];while(w.nextNode())all.push(w.currentNode);for(const n of all){if(skip(n))continue;const v=translate(n.nodeValue);if(v!==n.nodeValue)n.nodeValue=v}}
function set(sel,ne,en){const e=document.querySelector(sel);if(e&&e.textContent!==pick(ne,en))e.textContent=pick(ne,en)}
function pageLock(){const page=document.body?.dataset?.page||'home';const common={home:['मुख्य जानकारी','Key information','नक्सा • चेतावनी • मानव स्थिति • मौसम • राष्ट्रिय समाचार','Map • Alerts • Human Status • Weather • National News'],alerts:['🚨 चेतावनी केन्द्र','🚨 Alert Centre','DHM • BIPAD • सडक विभाग','DHM • BIPAD • Department of Roads'],flood:['🌊 बाढी / नदी चेतावनी','🌊 Flood / River Alerts','बाढी र नदीका सक्रिय चेतावनी मात्र','Active flood and river warnings only'],roads:['🚧 सडक समस्या / बन्द–खुला स्थिति','🚧 Road Problems / Open–Closed Status','सडकको अहिलेको अवस्था','Current Road Status'],people:['👥 मानव स्थिति','👥 Human Status','नेपाल प्रहरी • NDRRMA/BIPAD • द्रुत सञ्चार संकेत','Nepal Police • NDRRMA/BIPAD • rapid media signals'],nationalnews:['📰 राष्ट्रिय समाचार','📰 National News','नेपालका विभिन्न समाचार कक्षबाट ताजा शीर्षक','Current headlines from Nepal newsrooms'],weather:['🌦️ तपाईंको स्थानको मौसम','🌦️ Weather at Your Location','तापक्रम • वर्षा • हावा • आर्द्रता','Temperature • Rain • Wind • Humidity'],sources:['🏛️ आधिकारिक स्रोत','🏛️ Official Sources','DHM • BIPAD/NDRRMA • नेपाल प्रहरी • सडक विभाग • गृह मन्त्रालय','DHM • BIPAD/NDRRMA • Nepal Police • Department of Roads • Home Ministry']};const x=common[page];if(x){set('.pageHead h2',x[0],x[1]);set('.pageHead p',x[2],x[3])}if(page==='home'){set('.brand h1','बाढी सुरक्षा नेपाल','FloodSafe Nepal');set('.brand small','नेपाल • प्रत्यक्ष सुरक्षा जानकारी','Nepal • Live safety information')}if(page==='alerts'){set('.brand h1','चेतावनी','Alerts');set('.brand small','बाढी • नदी • सडक','Flood • River • Road')}if(page==='flood'){set('.brand h1','बाढी / नदी','Flood / River')}if(page==='roads'){set('.brand h1','सडक समस्या','Road Problems')}if(page==='people'){set('.brand h1','मानव स्थिति','Human Status')}if(page==='nationalnews'){set('.brand h1','समाचार','News')}if(page==='weather'){set('.brand h1','मेरो मौसम','My Weather')}if(page==='sources'){set('.brand h1','स्रोत','Sources')}}
function setLinkLabel(a,label){if(!a)return;let n=[...a.childNodes].find(x=>x.nodeType===Node.TEXT_NODE);if(!n){n=document.createTextNode('');a.appendChild(n)}if(n.nodeValue!==label)n.nodeValue=label}
function nav(){const n=document.querySelector('.footerNav');if(!n)return;const labels=get()==='en'?['Home','Map','Alerts','People','News','Sources']:['गृहपृष्ठ','नक्सा','चेतावनी','मानव','समाचार','स्रोत'];[...n.querySelectorAll('a')].forEach((a,i)=>{if(i<labels.length)setLinkLabel(a,labels[i])})}
function button(){let b=document.getElementById('fsLangToggle');if(!b){b=document.createElement('button');b.id='fsLangToggle';b.type='button';b.className='langToggle';b.style.cssText='flex:0 0 auto;border:1px solid #7b5a4d;background:#201411;color:#fff8ec;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:900;line-height:1;cursor:pointer;white-space:nowrap;box-shadow:0 4px 14px #0005';const top=document.querySelector('.top');if(top){const live=top.querySelector('.livePill');live?top.insertBefore(b,live):top.appendChild(b)}b.addEventListener('click',()=>{const next=get()==='en'?'ne':'en';localStorage.setItem(KEY,next);apply();window.dispatchEvent(new CustomEvent('fs-language-change',{detail:{lang:next}}));loadMedia(true)})}if(b){b.textContent=get()==='en'?'नेपाली':'English';b.setAttribute('aria-label',get()==='en'?'Switch to Nepali':'Switch to English')}}
function apply(){if(applying)return;applying=true;try{applyRoot();pageLock();nav();button();document.documentElement.lang=get();document.body.dataset.lang=get()}finally{applying=false}}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;apply()})}
async function loadMedia(force=false){if(mediaBusy||(!force&&Date.now()-lastMedia<60000))return;mediaBusy=true;lastMedia=Date.now();try{const c=new AbortController(),to=setTimeout(()=>c.abort(),6000),r=await fetch(KCHA,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',signal:c.signal,headers:{accept:'application/json'}});clearTimeout(to);if(!r.ok)throw Error(r.status);const j=await r.json(),a=new Map(),b=new Map();for(const s of(j.stories||[])){for(const [ne,en] of[[s.topic_ne,s.topic_en],[s.summary_ne,s.summary_en]]){const n=String(ne||'').trim(),e=String(en||'').trim();if(n&&e){a.set(n,e);b.set(e,n)}}}mediaNe2En=a;mediaEn2Ne=b;apply()}catch{}finally{mediaBusy=false}}
function boot(){apply();loadMedia(true);const ob=new MutationObserver(ms=>{if(applying)return;if(ms.some(m=>m.type==='characterData'||(m.type==='childList'&&m.addedNodes.length)))schedule()});ob.observe(document.body,{childList:true,subtree:true,characterData:true});setInterval(()=>loadMedia(false),60000);window.addEventListener('storage',e=>{if(e.key===KEY){apply();window.dispatchEvent(new CustomEvent('fs-language-change',{detail:{lang:get()}}))}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.FSLang={get,pick,apply};
})();