(()=>{
'use strict';
if(window.__fsLanguageV2)return;window.__fsLanguageV2=true;
const KEY='fs23-lang',KCHA='https://kchakhabar.com/api/v1/today.json?limit=100';
const get=()=>localStorage.getItem(KEY)==='en'?'en':'ne';
const pairs=[
['बाढी सुरक्षा नेपाल','FloodSafe Nepal'],['नेपाल • प्रत्यक्ष सुरक्षा जानकारी','Nepal • Live safety information'],['प्रत्यक्ष','LIVE'],['समक्रमण','SYNC'],['अवस्था','STATUS'],
['मुख्य जानकारी','Key information'],['नक्सा • चेतावनी • मानव स्थिति • मौसम • राष्ट्रिय समाचार','Map • Alerts • Human Status • Weather • National News'],['नक्सा • चेतावनी • Human Status • मौसम • राष्ट्रिय समाचार','Map • Alerts • Human Status • Weather • National News'],
['गृहपृष्ठ','Home'],['नक्सा','Map'],['चेतावनी','Alerts'],['मानव','People'],['समाचार','News'],['स्रोत','Sources'],['मानव स्थिति','Human Status'],['मेरो मौसम','My Weather'],
['नदी, बहाव, वर्षा र सडक स्थिति','Rivers, flow, rainfall and road status'],['बाढी, नदी र सडक चेतावनी','Flood, river and road alerts'],['सक्रिय विपद् वा नेपाल दुर्घटना अपडेट','Active disaster or Nepal accident updates'],['तपाईंको स्थानको विस्तृत मौसम','Detailed weather for your location'],['राष्ट्रिय ताजा समाचार','Current national news'],['सरकारी र द्रुत सूचना स्रोत','Official and rapid information sources'],
['नेपाल विपद् / दुर्घटना निगरानी','Nepal Disaster / Accident Monitor'],['नेपालभरि सक्रिय मुख्य घटना खोजिँदैछ…','Finding the active main event across Nepal…'],['पुष्टि','VERIFIED'],['मृत्यु','Deaths'],['सम्पर्कविहीन','Missing'],['उद्धार','Rescued'],['प्रत्यक्ष स्रोत अवस्था','Live source health'],['ताजा राष्ट्रिय समाचार','Current National News'],['नयाँ समाचार खोजिँदैछ…','Finding current news…'],
['चेतावनी केन्द्र','Alert Centre'],['बाढी / नदी','Flood / River'],['सडक समस्या','Road Problems'],['मेरो क्षेत्रको उच्च चेतावनी','High Alert for My Area'],['स्थान निगरानी सक्रिय गरिएको छैन।','Location monitor is not enabled.'],['🔔 स्थान + अलार्म सक्रिय','🔔 Enable Location + Alarm'],['दायरा','Radius'],['BIPAD उच्च चेतावनी','BIPAD high alerts'],['DHM नदी चेतावनी','DHM river alerts'],['हाल बन्द सडक','Currently closed roads'],
['🌊 बाढी / नदी चेतावनी','🌊 Flood / River Alerts'],['बाढी र नदीका सक्रिय चेतावनी मात्र','Active flood and river warnings only'],['🚧 सडक समस्या / बन्द–खुला स्थिति','🚧 Road Problems / Open–Closed Status'],['सडकको अहिलेको अवस्था','Current Road Status'],['७७ जिल्ला स्थिति','77 District Status'],['समस्या भएका जिल्ला पहिले देखाइन्छन्','Districts with active issues are shown first'],['जिल्ला','District'],['सबै ७७ जिल्ला','All 77 districts'],['हालका चेतावनी','Current Alerts'],['आधिकारिक प्रत्यक्ष','OFFICIAL LIVE'],
['⚡ द्रुत बाढी / पहिरो / भूकम्प संकेत','⚡ Rapid Flood / Landslide / Quake Signals'],['प्रारम्भिक स्रोत जाँच हुँदैछ…','Checking early sources…'],['प्रारम्भिक','EARLY'],['🚧 सडक प्रारम्भिक अपडेट','🚧 Road Early Updates'],['नयाँ सडक खबर खोजिँदैछ…','Finding new road reports…'],['स्रोत जडान','Source connection'],
['राष्ट्रिय समाचार','National News'],['नेपालका विभिन्न समाचार कक्षबाट ताजा शीर्षक','Current headlines from Nepal newsrooms'],['ताजा समाचार','Flash News'],['समाचार खोजिँदैछ…','Finding current news…'],['पछिल्लो','LATEST'],['ताजा','FLASH'],['समाचार खोल्नुहोस्','Open article'],['⏸ समाचार रोक्नुहोस्','⏸ Pause news'],['▶️ समाचार चलाउनुहोस्','▶️ Resume news'],
['सक्रिय विपद् • नेपाल दुर्घटना अपडेट','Active disaster • Nepal accident updates'],['सक्रिय विपद् / दुर्घटना','Active Disaster / Accident'],['नयाँ जानकारी जाँच हुँदैछ…','Checking for new information…'],['आधिकारिक स्रोत','Official sources'],['मृत्यु, खोज र उद्धार अपडेट।','Deaths, search and rescue updates.'],['विपद्, सम्पर्कविहीन, उद्धार र क्षति विवरण।','Disaster, missing, rescue and damage information.'],['पछिल्ला BIPAD मानव अपडेट','Latest BIPAD people updates'],
['तपाईंको स्थानको मौसम','Weather at Your Location'],['तापक्रम • वर्षा • हावा • आर्द्रता','Temperature • Rain • Wind • Humidity'],['स्थान पर्खिँदै…','Waiting for location…'],['◎ मेरो स्थान','◎ My location'],['◎ मेरो स्थान प्रयोग','◎ Use my location'],['GPS स्थान आवश्यक','GPS location required'],['अहिलेको वर्षा','Current rain'],['आर्द्रता','Humidity'],['हावा','Wind'],['हावाको झोका','Wind gust'],['आज न्यून / उच्च','Today low / high'],['वर्षाको सम्भावना','Rain chance'],['वर्षा सम्भावना','Rain chance'],['मौसम विवरण लोड हुँदैछ…','Loading weather details…'],['महसुस हुने तापक्रम','Feels like'],['न्यून / उच्च','Low / high'],['वर्षा','Rain'],
['आधिकारिक स्रोतहरू','Official Sources'],['द्रुत / प्रारम्भिक संकेत','Rapid / early signals'],['स्रोत खोल्नुहोस्','Open source'],['समाचार स्रोत खोल्नुहोस्','Open news source'],
['⚡ आजको Nepal Safety Snapshot',"⚡ Today's Nepal Safety Snapshot"],['हरेक ५ sec मा स्रोत जाँच','Source check every 5 sec'],['🌐 Earthquake Today','🌐 Earthquake Today'],['⛰️ Landslide Today','⛰️ Landslide Today'],['आज नयाँ record भेटिएको छैन','No new record today'],['आज नयाँ पहिरो report भेटिएको छैन','No new landslide report today'],['नयाँ rapid signal खोजिँदैछ…','Finding new rapid signals…'],
['FLOOD','Flood'],['LANDSLIDE','Landslide'],['ACCIDENT','Accident'],['CLOSED','Closed'],['ROAD','Road'],['HIGH','High'],['WARNING','Warning'],['DANGER','Danger'],['MEDIA FLOOD','Media flood signal'],['MEDIA LANDSLIDE','Media landslide signal'],['NEPAL AIR','Nepal aviation'],['6.5+ QUAKE','6.5+ earthquake'],['EARLY','Early'],
['पछिल्लो मानव स्थिति जाँच हुँदैछ…','Checking latest Human Status…'],['डेटा जाँच हुँदैछ…','Checking data…'],['फेरि जाँच हुँदैछ…','Rechecking…'],['जाँच हुँदैछ…','Checking…']
];
const ne2en=new Map(pairs),en2ne=new Map(pairs.map(([a,b])=>[b,a]));
let mediaNe2En=new Map(),mediaEn2Ne=new Map(),loading=false,lastMedia=0,muting=false;
function phrase(s){if(get()==='en')return s.replace(/(\d+) मिनेट अघि/g,'$1 min ago').replace(/(\d+) घण्टा अघि/g,'$1 hr ago').replace(/भर्खर|अहिले/g,'just now').replace(/समय उपलब्ध छैन/g,'time unavailable').replace(/डेटा अपडेट\s*/g,'Data updated ').replace(/पछिल्लो जाँच\s*/g,'last checked ').replace(/कारण:\s*/g,'Reason: ').replace(/वैकल्पिक मार्ग:\s*/g,'Alternative route: ').replace(/स्थान:\s*/g,'Location: ').replace(/अपडेट:\s*/g,'Updated: ').replace(/अर्को जाँच\s*/g,'next check ').replace(/सेकेन्ड/g,'sec');return s.replace(/(\d+) min ago/g,'$1 मिनेट अघि').replace(/(\d+) hr ago/g,'$1 घण्टा अघि').replace(/\bjust now\b/gi,'अहिले').replace(/\btime unavailable\b/gi,'समय उपलब्ध छैन').replace(/\bData updated\s*/gi,'डेटा अपडेट ').replace(/\blast checked\s*/gi,'पछिल्लो जाँच ').replace(/\bReason:\s*/gi,'कारण: ').replace(/\bAlternative route:\s*/gi,'वैकल्पिक मार्ग: ').replace(/\bLocation:\s*/gi,'स्थान: ').replace(/\bUpdated:\s*/gi,'अपडेट: ')}
function translate(raw){const text=String(raw||''),t=text.trim();if(!t)return text;const map=get()==='en'?ne2en:en2ne,mm=get()==='en'?mediaNe2En:mediaEn2Ne,v=map.get(t)||mm.get(t)||phrase(t);if(v===t)return text;return(text.match(/^\s*/)?.[0]||'')+v+(text.match(/\s*$/)?.[0]||'')}
function skip(n){const p=n.parentElement;return !p||!!p.closest('script,style,noscript,code,pre,[data-no-i18n]')}
function applyRoot(root=document.body){if(!root||muting)return;muting=true;try{const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),all=[];while(w.nextNode())all.push(w.currentNode);for(const n of all){if(skip(n))continue;const v=translate(n.nodeValue);if(v!==n.nodeValue)n.nodeValue=v}document.documentElement.lang=get()}finally{muting=false}}
function setLinkLabel(a,label){if(!a)return;let n=[...a.childNodes].find(x=>x.nodeType===Node.TEXT_NODE);if(!n){n=document.createTextNode('');a.appendChild(n)}if(n.nodeValue!==label)n.nodeValue=label}
function nav(){const n=document.querySelector('.footerNav');if(!n)return;const labs=get()==='en'?['Home','Map','Alerts','People','News','Sources']:['गृहपृष्ठ','नक्सा','चेतावनी','मानव','समाचार','स्रोत'];[...n.querySelectorAll('a')].forEach((a,i)=>{if(i<labs.length)setLinkLabel(a,labs[i])})}
function toggle(){let b=document.getElementById('fsLangToggle');if(!b){b=document.createElement('button');b.id='fsLangToggle';b.type='button';b.className='langToggle';document.querySelector('.top')?.appendChild(b);b.onclick=()=>{localStorage.setItem(KEY,get()==='en'?'ne':'en');apply();window.dispatchEvent(new Event('fs-language-change'));loadMedia(true)}}const label=get()==='en'?'नेपाली':'English';if(b&&b.textContent!==label)b.textContent=label}
function apply(){applyRoot();nav();toggle()}
async function loadMedia(force=false){if(loading||(!force&&Date.now()-lastMedia<60000))return;loading=true;lastMedia=Date.now();try{const c=new AbortController(),to=setTimeout(()=>c.abort(),6000),r=await fetch(KCHA,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',signal:c.signal,headers:{accept:'application/json'}});clearTimeout(to);if(!r.ok)throw Error(r.status);const j=await r.json(),a=new Map(),b=new Map();for(const s of(j.stories||[])){for(const [ne,en] of[[s.topic_ne,s.topic_en],[s.summary_ne,s.summary_en]]){const n=String(ne||'').trim(),e=String(en||'').trim();if(n&&e){a.set(n,e);b.set(e,n)}}}mediaNe2En=a;mediaEn2Ne=b;apply()}catch{}finally{loading=false}}
function boot(){apply();loadMedia(true);const ob=new MutationObserver(ms=>{if(muting)return;let changed=false;for(const m of ms){if(m.type==='childList'&&m.addedNodes.length)changed=true;if(m.type==='characterData')changed=true}if(changed)queueMicrotask(()=>{applyRoot();nav();toggle()})});ob.observe(document.body,{childList:true,subtree:true,characterData:true});setInterval(()=>loadMedia(false),60000);window.addEventListener('storage',e=>{if(e.key===KEY){apply();window.dispatchEvent(new Event('fs-language-change'))}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.FSLang={get,pick:(ne,en)=>get()==='en'?en:ne,apply};
})();