(()=>{
'use strict';
if(window.__floodsafeV25LiveCore)return;window.__floodsafeV25LiveCore=true;
const PAGE=document.body.dataset.page||'home',$=id=>document.getElementById(id),API='https://bipadportal.gov.np/api/v1/',DATA='../../data/',KCHA='https://kchakhabar.com/api/v1/today.json?limit=80',NPT='Asia/Kathmandu';
const HIGH=/danger|red alert|high risk|very high|evacuat|above warning|warning level exceeded|खतरा|उच्च जोखिम|चेतावनी सीमा|सतर्कता/i,FLOOD=/flood|flash flood|बाढी|डुबान|river|नदी|खोला|landslide|पहिरो/i,ROAD=/road|highway|bridge|सडक|राजमार्ग|पुल|अवरुद्ध|बन्द/i;
let feeds={alerts:null,rivers:null,roads:null,people:null,police:null,news:null},health={},busy=false,alarmTimer=null,audioCtx=null,currentRiskKeys=new Set(),mediaRoads=[],mediaAt=0,geoWatch=null;
function rows(j){if(Array.isArray(j))return j;for(const k of ['results','data','objects','features']){const v=j?.[k];if(Array.isArray(v))return v;if(v&&Array.isArray(v.results))return v.results}return[]}
function val(o,ks){for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null}
function num(v){const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null}
function text(o){try{return JSON.stringify(o||{}).toLowerCase()}catch{return''}}
function title(o){return String(val(o,['titleNe','title','name','station_name','river_name','road_name','descriptionNe','description'])||'आधिकारिक अपडेट')}
function status(o){return String(val(o,['status','severity','state','condition','remarks','descriptionNe','description','trend','steady'])||'')}
function stamp(o){return val(o,['waterLevelOn','measuredOn','modifiedOn','updated_at','updatedAt','startedOn','startOn','startDate','createdOn','created_at','createdAt','incidentOn','date','timestamp'])}
function idOf(o){return String(val(o,['id','pk','uuid','stationSeriesId','station_series_id'])||title(o))}
function ageMs(o){const t=+new Date(stamp(o)||0);return t?Math.max(0,Date.now()-t):Infinity}
function coord(o){if(!o||typeof o!=='object')return null;for(const g of [o.geometry,o.geojson,o.location?.geometry,o.station?.geometry,o.properties?.geometry]){if(g&&Array.isArray(g.coordinates)&&g.coordinates.length>=2){const a=+g.coordinates[0],b=+g.coordinates[1],c=Math.abs(a)>40?[b,a]:[a,b];if(c[0]>20&&c[0]<35&&c[1]>75&&c[1]<92)return c}}for(const x of [o,o.location,o.station,o.station_location,o.properties].filter(Boolean)){const la=+val(x,['latitude','lat','y']),lo=+val(x,['longitude','lng','lon','long','x']);if(Number.isFinite(la)&&Number.isFinite(lo)&&la>20&&la<35&&lo>75&&lo<92)return[la,lo]}return null}
function distance(a,b){const R=6371,p=Math.PI/180,d1=(b[0]-a[0])*p,d2=(b[1]-a[1])*p,s=Math.sin(d1/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
function unique(list,key){const out=[],seen=new Set();for(const x of list){const k=key(x);if(seen.has(k))continue;seen.add(k);out.push(x)}return out}
function digits(s){return String(s).replace(/\d/g,d=>'०१२३४५६७८९'[d])}
function npTime(d=Date.now()){try{return new Intl.DateTimeFormat('ne-NP',{timeZone:NPT,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(d))}catch{return'—'}}
function npDateAD(){try{return new Intl.DateTimeFormat('ne-NP',{timeZone:NPT,weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(new Date())}catch{return'—'}}
function bsToday(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:NPT,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),g={};p.forEach(x=>{if(x.type!=='literal')g[x.type]=x.value});const day=Date.UTC(+g.year,+g.month-1,+g.day),start=Date.UTC(2026,3,14),lens=[31,31,32,31,31,31,30,29,30,29,30,30];let n=Math.floor((day-start)/86400000);if(n<0||n>=365)return'वि.सं. पात्रो';let m=0;while(n>=lens[m]){n-=lens[m];m++}return digits(2083)+' '+['बैशाख','जेठ','असार','साउन','भदौ','असोज','कार्तिक','मंसिर','पुस','माघ','फागुन','चैत'][m]+' '+digits(n+1)}
function sourceAge(s){const t=+new Date(s||0);if(!t)return'समय उपलब्ध छैन';const m=Math.max(0,Math.round((Date.now()-t)/60000));return m<1?'अहिले':m<60?digits(m)+' मिनेट अघि':digits(Math.round(m/60))+' घण्टा अघि'}
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function make(tag,cls,t){const e=document.createElement(tag);if(cls)e.className=cls;if(t!==undefined)e.textContent=t;return e}
function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}
function card(parent,tag,h,b,meta,url,label='स्रोत खोल्नुहोस्'){if(!parent)return;const a=make('article','item');if(tag)a.appendChild(make('span','tag'+(/DANGER|HIGH|खतरा/.test(tag)?' red':''),tag));a.appendChild(make('h4','',h));if(b)a.appendChild(make('p','',b));if(meta)a.appendChild(make('div','meta',meta));if(url){const r=make('div','meta'),ln=make('a','',label);ln.href=url;ln.target='_blank';ln.rel='noopener noreferrer';ln.referrerPolicy='no-referrer';r.appendChild(ln);a.appendChild(r)}parent.appendChild(a)}
function renderClock(){setText('npLiveTime',npTime());setText('npBsDate',bsToday());setText('npAdDate',npDateAD())}renderClock();setInterval(renderClock,1000);
async function getJSON(url,ms=4500){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(to)}}
async function read(name,url,ms=4500){try{const j=await getJSON(url,ms);health[name]={ok:true,at:Date.now()};return j}catch(e){health[name]={ok:false,at:Date.now(),error:String(e)};return null}}
function safeActive(o){const s=text(o);if(/inactive|expired|archived|closed alert|समाप्त/.test(s)||o?.isActive===false||o?.active===false)return false;const now=Date.now(),start=val(o,['startedOn','startOn','startDate','createdOn','created_at']),exp=val(o,['expiresOn','expireOn','expires_at','expiry','endDate','endedOn']);if(start&&+new Date(start)>now+5*60000)return false;if(exp&&+new Date(exp)<now)return false;return exp?true:ageMs(o)<=6*3600e3}
function activeAlerts(list){return unique((list||[]).filter(o=>safeActive(o)&&HIGH.test(title(o)+' '+status(o)+' '+text(o))),o=>idOf(o)+'|'+title(o)).sort((a,b)=>(+new Date(stamp(b)||0))-(+new Date(stamp(a)||0)))}
function riverStage(o){const wl=num(val(o,['waterLevel','water_level','currentLevel','current_level','level','value'])),w=num(val(o,['warningLevel','warning_level','warning'])),d=num(val(o,['dangerLevel','danger_level','danger'])),s=(status(o)+' '+String(val(o,['steady','trend'])||'')).toUpperCase();if(ageMs(o)>90*60000)return{level:'STALE',score:0,wl,w,d};if((d!==null&&wl!==null&&wl>=d)||/DANGER|ABOVE DANGER/.test(s))return{level:'DANGER',score:3,wl,w,d};if((w!==null&&wl!==null&&wl>=w)||/ABOVE WARNING|WARNING LEVEL/.test(s))return{level:'WARNING',score:2,wl,w,d};return{level:'NORMAL',score:0,wl,w,d}}
function riverAlerts(list){return unique((list||[]).map(o=>({o,s:riverStage(o)})).filter(x=>x.s.score>=2),x=>idOf(x.o)).sort((a,b)=>b.s.score-a.s.score||ageMs(a.o)-ageMs(b.o))}
function roadIssues(list){return unique((list||[]).filter(o=>ageMs(o)<=48*3600e3&&/closed|blocked|partial|partially|अवरुद्ध|बन्द/i.test(title(o)+' '+status(o))),o=>idOf(o)+'|'+title(o))}
function reason(o){const v=String(val(o,['cause','reason','remarks','descriptionNe','description'])||'');if(v&&v.length<180)return v;const s=(title(o)+' '+status(o)).toLowerCase();if(/landslide|पहिरो/.test(s))return'पहिरो';if(/flood|बाढी|डुबान/.test(s))return'बाढी/डुबान';if(/bridge|पुल/.test(s))return'पुल/सडक क्षति';if(/accident|दुर्घटना/.test(s))return'दुर्घटना';return status(o)||'अवरोधको कारण स्रोतमा स्पष्ट छैन'}
function eta(o){const v=val(o,['estimatedOpen','expectedOpen','expectedReopen','reopenAt','openAt','estimated_reopening','endDate']);if(v)return'खुल्ने अनुमान: '+String(v);const s=String(val(o,['remarks','descriptionNe','description'])||'');const m=s.match(/(?:reopen|open|resume|खुल्ने|सुचारु|सञ्चालन)[^।.!?]{0,90}/i);return m?'खुल्ने जानकारी: '+m[0]:'खुल्ने समय अझै प्रकाशित छैन'}
function renderPeople(){const p=feeds.police,s=feeds.people,missing=s?.missing_minimum??s?.missing_total??'—';if(PAGE==='home'){setText('homeDeaths',p?.total_deaths??'—');setText('homeMissing',missing);setText('homeRescued',s?.rescued_alive??'—');setText('humanFresh',p?.official_update_iso?'Nepal Police • '+sourceAge(p.official_update_iso):'नयाँ आधिकारिक अपडेट जाँच हुँदैछ…')}if(PAGE==='people'){setText('peopleBodies',p?.total_deaths??s?.recovered_bodies??'—');setText('peopleMissing',missing);setText('peopleRescued',s?.rescued_alive??'—');setText('peopleBreakdown','पर्यटक: '+(s?.missing_tourists??'—')+' • सुरक्षा निकाय: '+(s?.missing_security_total??'—')+' • उद्धार नेपाली: '+(s?.rescued_nepali??'—')+' • विदेशी: '+(s?.rescued_foreign??'—'))}}
function renderAlerts(){const a=feeds.alerts===null?null:activeAlerts(feeds.alerts),r=feeds.rivers===null?null:riverAlerts(feeds.rivers),rd=feeds.roads===null?null:roadIssues(feeds.roads);if(PAGE==='alerts'){setText('alertCount',a===null?'—':a.length);setText('riverAlertCount',r===null?'—':r.length);setText('roadAlertCount',rd===null?'—':rd.length);const out=$('alertsList');if(out){clear(out);if(a)for(const o of a.slice(0,10))card(out,'HIGH',title(o),status(o)||'उच्च प्राथमिकता चेतावनी',sourceAge(stamp(o)),'https://bipadportal.gov.np/');if(r)for(const x of r.slice(0,10))card(out,x.s.level,title(x.o),'पानी '+(x.s.wl??'—')+' m • चेतावनी '+(x.s.w??'—')+' m • खतरा '+(x.s.d??'—')+' m',sourceAge(stamp(x.o)),'https://www.dhm.gov.np/hydrology/floodMonitoring');if(rd)for(const o of rd.slice(0,10))card(out,'ROAD',title(o),'कारण: '+reason(o)+' • '+eta(o),sourceAge(stamp(o)),'https://dor.gov.np/home/page/road-condition-update');if(!out.children.length)out.appendChild(make('div','empty','अहिले fresh official feed मा उच्च चेतावनी भेटिएको छैन। Live receiver चलिरहेको छ।'))}}currentRiskKeys=locationRiskKeys(a||[],r||[],rd||[]);maybeAlarm()}
function healthLabel(x,n){if(!x)return n+' • जाँच हुँदैछ';return x.ok?n+' ✓':n+' • फेरि जाँच हुँदैछ'}
function renderHealth(){setText('healthBipad',healthLabel(health.alerts,'BIPAD alerts'));setText('healthRiver',healthLabel(health.rivers,'DHM river'));setText('healthRoad',healthLabel(health.roads,'Road data'));setText('healthPeople',healthLabel((health.people?.ok||health.police?.ok)?{ok:true}:health.people,'Human data'));const nh=$('healthNews');if(nh&&!/K cha khabar|Media feed/.test(nh.textContent||''))nh.textContent=healthLabel(health.news,'News fallback');const ok=['alerts','rivers','roads'].filter(k=>health[k]?.ok).length;setText('liveSourceState',ok===3?'मुख्य live स्रोत ३/३ connected':ok?`मुख्य live स्रोत ${ok}/३ connected • बाँकी फेरि जाँच हुँदैछ`:'मुख्य live स्रोत फेरि जाँच हुँदैछ')}
function savedLoc(){try{const x=JSON.parse(localStorage.getItem('fs-v25-location')||'null');return Array.isArray(x)&&x.length===2?x:null}catch{return null}}
function locationRiskKeys(a,r,roads){const c=savedLoc();if(!c)return new Set();const rad=Math.max(1,Number(localStorage.getItem('fs-v25-radius')||10)),out=new Set();for(const o of a){const p=coord(o);if(p&&distance(c,p)<=rad)out.add('a|'+idOf(o)+'|'+String(stamp(o)||''))}for(const x of r){const p=coord(x.o);if(p&&distance(c,p)<=rad)out.add('r|'+idOf(x.o)+'|'+x.s.level+'|'+String(stamp(x.o)||''))}for(const o of roads){const p=coord(o);if(p&&distance(c,p)<=rad&&FLOOD.test(title(o)+' '+status(o)))out.add('d|'+idOf(o)+'|'+String(stamp(o)||''))}return out}
function acknowledged(k){try{const a=JSON.parse(localStorage.getItem('fs-v25-acks')||'{}');return a[k]&&Date.now()-a[k]<6*3600e3}catch{return false}}
function tone(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const n=audioCtx.currentTime;[[0,610,.18],[.28,790,.18],[.58,690,.3]].forEach(([t,f,d])=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.0001,n+t);g.gain.exponentialRampToValueAtTime(.08,n+t+.02);g.gain.exponentialRampToValueAtTime(.0001,n+t+d);o.connect(g);g.connect(audioCtx.destination);o.start(n+t);o.stop(n+t+d+.03)})}catch{}}
function stopAlarm(){if(alarmTimer){clearInterval(alarmTimer);alarmTimer=null}document.getElementById('localRiskAlarm')?.classList.remove('show')}
function ackRisks(){try{const a=JSON.parse(localStorage.getItem('fs-v25-acks')||'{}');for(const k of currentRiskKeys)a[k]=Date.now();localStorage.setItem('fs-v25-acks',JSON.stringify(a))}catch{}stopAlarm();maybeAlarm()}
function alarmUI(){let b=$('localRiskAlarm');if(b)return b;b=make('div','riskAlarm');b.id='localRiskAlarm';const c=make('div','riskAlarmCard'),i=make('div','riskAlarmIcon','🚨'),h=make('h2','','तपाईंको क्षेत्रभित्र उच्च जोखिम'),p=make('p','','Fresh official data ले तपाईंको radius भित्र उच्च जोखिम देखाएको छ। सुरक्षित स्थानमा जानुहोस् र नक्सा/चेतावनी जाँच गर्नुहोस्।'),ok=make('button','btn primary','OK — मैले चेतावनी देखें');ok.id='riskAlarmOk';ok.onclick=ackRisks;c.append(i,h,p,ok);b.appendChild(c);document.body.appendChild(b);return b}
function startAlarm(){if(alarmTimer)return;alarmUI().classList.add('show');tone();alarmTimer=setInterval(tone,2200);try{navigator.serviceWorker?.ready.then(r=>r.showNotification('बाढी सुरक्षा • स्थानीय उच्च जोखिम',{body:'तपाईंको radius भित्र fresh official warning भेटिएको छ।',icon:'../v24/icon.svg',tag:'floodsafe-high-risk',requireInteraction:true})).catch(()=>{})}catch{}}
function maybeAlarm(){const enabled=localStorage.getItem('fs-v25-alerts-enabled')==='1',fresh=[...currentRiskKeys].filter(k=>!acknowledged(k));if(enabled&&fresh.length)startAlarm();else if(!fresh.length)stopAlarm();setText('localAlertState',!enabled?'Location High Alert सक्रिय गरिएको छैन।':fresh.length?digits(fresh.length)+' स्थानीय उच्च जोखिम सक्रिय':'High Alert सक्रिय • नयाँ स्थानीय खतरा छैन')}
function savePosition(p){localStorage.setItem('fs-v25-location',JSON.stringify([p.coords.latitude,p.coords.longitude]))}
function startGeoWatch(){if(geoWatch!==null||!navigator.geolocation||localStorage.getItem('fs-v25-alerts-enabled')!=='1')return;geoWatch=navigator.geolocation.watchPosition(p=>{savePosition(p);renderAlerts()},()=>{}, {enableHighAccuracy:true,maximumAge:15000,timeout:20000})}
async function armAlerts(){if(!navigator.geolocation){setText('localAlertState','यो device मा location उपलब्ध छैन।');return}navigator.geolocation.getCurrentPosition(async p=>{savePosition(p);localStorage.setItem('fs-v25-alerts-enabled','1');const r=$('alertRadius');if(r)localStorage.setItem('fs-v25-radius',r.value);try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();await audioCtx.resume()}catch{}try{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission()}catch{}startGeoWatch();await poll(true)},()=>setText('localAlertState','Location अनुमति आवश्यक।'),{enableHighAccuracy:true,timeout:15000,maximumAge:10000})}
async function weatherAt(c){return c?read('weather',`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(c[0])}&longitude=${encodeURIComponent(c[1])}&current=temperature_2m,precipitation,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&forecast_days=1&timezone=Asia%2FKathmandu`,7000):null}
function weatherName(c){return({0:'सफा',1:'मुख्यतः सफा',2:'आंशिक बादल',3:'बादल',45:'कुहिरो',51:'हल्का झरी',53:'झरी',55:'घना झरी',61:'हल्का वर्षा',63:'वर्षा',65:'भारी वर्षा',80:'वर्षा झरी',81:'वर्षा झरी',82:'भारी झरी',95:'मेघगर्जन',96:'असिना सहित मेघगर्जन',99:'तीव्र मेघगर्जन'})[Number(c)]||'मौसम'}
async function updateWeather(force=false){if(PAGE!=='home')return;let c=savedLoc();if(force&&!c&&navigator.geolocation)c=await new Promise(res=>navigator.geolocation.getCurrentPosition(p=>{savePosition(p);res([p.coords.latitude,p.coords.longitude])},()=>res(null),{enableHighAccuracy:true,timeout:12000,maximumAge:30000}));if(!c){setText('homeWxStatus','GPS सक्रिय गरेपछि तपाईंको क्षेत्रको आजको मौसम देखिन्छ।');return}const w=await weatherAt(c);if(!w){setText('homeWxStatus','मौसम स्रोत फेरि जाँच हुँदैछ…');return}const x=w.current||{},d=w.daily||{};setText('homeWxTemp',num(x.temperature_2m)!=null?Math.round(num(x.temperature_2m))+'°':'—°');setText('homeWxCondition',weatherName(x.weather_code));setText('homeWxRain',num(x.precipitation)!=null?num(x.precipitation).toFixed(1)+' mm':'—');setText('homeWxWind',num(x.wind_speed_10m)!=null?Math.round(num(x.wind_speed_10m))+' km/h':'—');setText('homeWxChance',num(d.precipitation_probability_max?.[0])!=null?Math.round(num(d.precipitation_probability_max[0]))+'%':'—');setText('homeWxRange',(num(d.temperature_2m_min?.[0])!=null?Math.round(num(d.temperature_2m_min[0]))+'°':'—')+' / '+(num(d.temperature_2m_max?.[0])!=null?Math.round(num(d.temperature_2m_max[0]))+'°':'—'));setText('homeWxPlace',digits(c[0].toFixed(3))+', '+digits(c[1].toFixed(3))+' • तपाईंको स्थान');setText('homeWxStatus',(Number(x.weather_code)>=95||Number(x.precipitation)>=5)?'⚠️ वर्षा/मेघगर्जन संकेत — Alerts र नजिकको नदी जाँच गर्नुहोस्।':'आजको स्थानीय मौसम अपडेट भएको छ।')}
function roadStoryReason(s){const t=((s.topic_ne||s.topic_en||'')+' '+(s.summary_ne||s.summary_en||'')).toLowerCase();if(/पहिरो|landslide/.test(t))return'पहिरो';if(/बाढी|flood|डुबान/.test(t))return'बाढी/डुबान';if(/पुल|bridge/.test(t))return'पुल/सडक क्षति';if(/दुर्घटना|accident/.test(t))return'दुर्घटना';return'विवरण headline मा हेर्नुहोस्'}
function roadStoryEta(s){const z=String(s.summary_ne||s.summary_en||s.topic_ne||s.topic_en||'');const m=z.match(/(?:reopen|open|resume|खुल्ने|सुचारु|सञ्चालन)[^।.!?]{0,100}/i);return m?m[0]:'खुल्ने समय प्रकाशित छैन'}
async function fetchMediaRoads(){if(PAGE!=='alerts'||Date.now()-mediaAt<60000)return;mediaAt=Date.now();const j=await read('mediaRoad',KCHA,7000);if(!j)return;mediaRoads=(j.stories||[]).filter(s=>ROAD.test((s.topic_ne||'')+' '+(s.topic_en||'')+' '+(s.summary_ne||'')+' '+(s.summary_en||''))).filter(s=>Date.now()-new Date(s.updated_at||s.first_reported||0).getTime()<18*3600e3).slice(0,12);renderMediaRoads()}
function renderMediaRoads(){const out=$('roadEarlyList');if(!out)return;clear(out);for(const s of mediaRoads){const src=s.sources?.[0],h=s.topic_ne||s.topic_en||'सडक अपडेट',body='कारण: '+roadStoryReason(s)+' • '+roadStoryEta(s),meta=(src?.publisher||'Nepal media')+' • '+sourceAge(s.updated_at||s.first_reported);card(out,'EARLY',h,body,meta,src?.url||s.url,'समाचार स्रोत खोल्नुहोस्')}if(!out.children.length)out.appendChild(make('div','empty','नयाँ सडक early-signal खोजिँदैछ…'));setText('roadEarlyStatus',health.mediaRoad?.ok?'Media early-signal connected':'Media source फेरि जाँच हुँदैछ…')}
async function renderPeopleLive(){if(PAGE!=='people')return;const j=await read('lossPeople',API+'loss-people/?limit=300',5000),out=$('peopleLiveList');if(!out)return;clear(out);if(j){const list=rows(j).filter(o=>FLOOD.test(text(o))).sort((a,b)=>(+new Date(stamp(b)||0))-(+new Date(stamp(a)||0))).slice(0,15);for(const o of list)card(out,/missing|बेपत्ता|सम्पर्कविहीन/i.test(text(o))?'Missing':/dead|death|मृत/i.test(text(o))?'Death':/rescued|उद्धार/i.test(text(o))?'Rescued':'People',title(o),status(o)||'People update',sourceAge(stamp(o)),'https://bipadportal.gov.np/')}if(!out.children.length)out.appendChild(make('div','empty','नयाँ people update खोजिँदैछ…'))}
async function poll(force=false){if(busy)return;busy=true;const now=Date.now();setText('appStatus','Live update जाँच हुँदैछ…');try{const [a,r,rd,p,po,n]=await Promise.all([read('alerts',API+'alert/?limit=200&ordering=-createdOn'),read('rivers',API+'river/?limit=650'),read('roads',API+'highway/?limit=500'),read('people',DATA+'floodsafe-people-status.json?t='+now),read('police',DATA+'floodsafe-police.json?t='+now),read('news',DATA+'national-news.json?t='+now)]);feeds.alerts=a?rows(a):null;feeds.rivers=r?rows(r):null;feeds.roads=rd?rows(rd):null;feeds.people=p;feeds.police=po;feeds.news=n;renderPeople();renderAlerts();renderHealth();setText('appStatus','Live check '+npTime()+' • अर्को जाँच ५ sec');await fetchMediaRoads()}finally{busy=false}}
function bind(){const loc=$('homeLocationBtn');if(loc)loc.onclick=async()=>{await armAlerts();await updateWeather(true)};const arm=$('armLocalAlerts');if(arm)arm.onclick=armAlerts;const radius=$('alertRadius');if(radius){radius.value=localStorage.getItem('fs-v25-radius')||'10';radius.onchange=()=>{localStorage.setItem('fs-v25-radius',radius.value);renderAlerts()}}if(localStorage.getItem('fs-v25-alerts-enabled')==='1'){setText('localAlertState','High Alert सक्रिय • location जाँच हुँदैछ');startGeoWatch()}}
async function boot(){bind();await updateWeather(false);await poll(true);await renderPeopleLive();setInterval(()=>poll(false),5000);if(PAGE==='home')setInterval(()=>updateWeather(false),120000);if(PAGE==='people')setInterval(renderPeopleLive,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){poll(true);updateWeather(false)}});window.addEventListener('online',()=>poll(true));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();