(()=>{
'use strict';
if(window.__floodsafeV25LiveCore)return;window.__floodsafeV25LiveCore=true;
const PAGE=document.body.dataset.page||'home';
const $=id=>document.getElementById(id);
const API='https://bipadportal.gov.np/api/v1/';
const DATA='../../data/';
const NPT='Asia/Kathmandu';
const HIGH_RE=/danger|red alert|high risk|very high|evacuat|above warning|warning level exceeded|खतरा|उच्च जोखिम|चेतावनी सीमा|सतर्कता/i;
const FLOOD_RE=/flood|flash flood|बाढी|डुबान|river|नदी|खोला/i;
let feeds={alerts:null,rivers:null,roads:null,people:null,police:null,news:null};
let lastPoll=0,pollBusy=false,alarmTimer=null,audioCtx=null,currentRiskKeys=new Set();
const health={};

function rows(j){if(Array.isArray(j))return j;for(const k of ['results','data','objects','features']){const v=j?.[k];if(Array.isArray(v))return v;if(v&&Array.isArray(v.results))return v.results}return[]}
function val(o,keys){for(const k of keys){let v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null}
function num(v){const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null}
function txt(o){return JSON.stringify(o||{}).toLowerCase()}
function title(o){return String(val(o,['titleNe','title','name','station_name','river_name','road_name','descriptionNe','description'])||'आधिकारिक अपडेट')}
function status(o){return String(val(o,['status','severity','state','condition','remarks','descriptionNe','description','trend','steady'])||'')}
function stamp(o){return val(o,['waterLevelOn','measuredOn','modifiedOn','updated_at','updatedAt','createdOn','created_at','createdAt','incidentOn','date','timestamp'])}
function idOf(o){return String(val(o,['id','pk','uuid','stationSeriesId','station_series_id'])||title(o))}
function coord(o){if(!o||typeof o!=='object')return null;const gs=[o.geometry,o.geojson,o.location?.geometry,o.station?.geometry,o.properties?.geometry];for(const g of gs){if(g&&Array.isArray(g.coordinates)&&g.coordinates.length>=2){const a=+g.coordinates[0],b=+g.coordinates[1];if(Number.isFinite(a)&&Number.isFinite(b)){const c=Math.abs(a)>40?[b,a]:[a,b];if(c[0]>20&&c[0]<35&&c[1]>75&&c[1]<92)return c}}}for(const x of [o,o.location,o.station,o.station_location,o.properties].filter(Boolean)){const la=+val(x,['latitude','lat','y']),lo=+val(x,['longitude','lng','lon','long','x']);if(Number.isFinite(la)&&Number.isFinite(lo)&&la>20&&la<35&&lo>75&&lo<92)return[la,lo]}return null}
function distance(a,b){const R=6371,p=Math.PI/180,d1=(b[0]-a[0])*p,d2=(b[1]-a[1])*p,s=Math.sin(d1/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
function ageMs(o){const s=stamp(o);if(!s)return Infinity;const t=+new Date(s);return Number.isFinite(t)?Math.max(0,Date.now()-t):Infinity}
function npTime(d=Date.now()){try{return new Intl.DateTimeFormat('ne-NP',{timeZone:NPT,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(d))}catch{return'—'}}
function npDateAD(d=Date.now()){try{return new Intl.DateTimeFormat('ne-NP',{timeZone:NPT,weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(new Date(d))}catch{return'—'}}
function digits(s){return String(s).replace(/\d/g,d=>'०१२३४५६७८९'[d])}
function bsToday(){
  // Verified current BS-year anchor: 2083-01-01 = 2026-04-14; 2083 Bhadra 12 = 2026-08-28.
  const parts=new Intl.DateTimeFormat('en-CA',{timeZone:NPT,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
  const g={};parts.forEach(x=>{if(x.type!=='literal')g[x.type]=x.value});
  const day=Date.UTC(+g.year,+g.month-1,+g.day),start=Date.UTC(2026,3,14),lens=[31,31,32,31,31,31,30,29,30,29,30,30];
  let n=Math.floor((day-start)/86400000);if(n<0||n>=lens.reduce((a,b)=>a+b,0))return'वि.सं. पात्रो अपडेट आवश्यक';
  let m=0;while(n>=lens[m]){n-=lens[m];m++}const months=['बैशाख','जेठ','असार','साउन','भदौ','असोज','कार्तिक','मंसिर','पुस','माघ','फागुन','चैत'];
  return `${digits(2083)} ${months[m]} ${digits(n+1)}`;
}
function sourceAge(s){if(!s)return'समय छैन';const t=+new Date(s);if(!Number.isFinite(t))return String(s);const m=Math.max(0,Math.round((Date.now()-t)/60000));return m<1?'अहिले':m<60?`${digits(m)} मिनेट अघि`:`${digits(Math.round(m/60))} घण्टा अघि`}
function safeActive(o){const s=txt(o);if(/inactive|expired|archived|closed alert|समाप्त/.test(s))return false;for(const k of ['isActive','active'])if(o?.[k]===false)return false;const exp=val(o,['expiresOn','expireOn','expires_at','expiry','endDate']);if(exp&&+new Date(exp)<Date.now())return false;return true}
function unique(list,keyfn){const out=[],seen=new Set();for(const x of list){const k=keyfn(x);if(seen.has(k))continue;seen.add(k);out.push(x)}return out}
function activeAlerts(list){return unique((list||[]).filter(o=>safeActive(o)&&ageMs(o)<=36*3600e3&&HIGH_RE.test(title(o)+' '+status(o)+' '+txt(o))),o=>idOf(o)+'|'+title(o)).sort((a,b)=>(+new Date(stamp(b)||0))-(+new Date(stamp(a)||0)))}
function riverStage(o){const wl=num(val(o,['waterLevel','water_level','currentLevel','current_level','level','value'])),w=num(val(o,['warningLevel','warning_level','warning'])),d=num(val(o,['dangerLevel','danger_level','danger'])),s=(status(o)+' '+String(val(o,['steady','trend'])||'')).toUpperCase();if(ageMs(o)>3*3600e3)return{level:'STALE',score:0,wl,w,d};if((d!==null&&wl!==null&&wl>=d)||/DANGER|ABOVE DANGER/.test(s))return{level:'DANGER',score:3,wl,w,d};if((w!==null&&wl!==null&&wl>=w)||/ABOVE WARNING|WARNING LEVEL/.test(s))return{level:'WARNING',score:2,wl,w,d};if(/RISING/.test(s)&&w!==null&&wl!==null&&wl>=w*.8)return{level:'WATCH',score:1,wl,w,d};return{level:'NORMAL',score:0,wl,w,d}}
function riverAlerts(list){return unique((list||[]).map(o=>({o,s:riverStage(o)})).filter(x=>x.s.score>=2),x=>idOf(x.o)).sort((a,b)=>b.s.score-a.s.score||ageMs(a.o)-ageMs(b.o))}
function roadIssues(list){return unique((list||[]).filter(o=>/closed|blocked|partial|partially|अवरुद्ध|बन्द/i.test(title(o)+' '+status(o))),o=>idOf(o)+'|'+title(o))}
async function getJSON(url,ms=9000){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(to)}}
async function read(name,url){try{const j=await getJSON(url);health[name]={ok:true,at:Date.now()};return j}catch(e){health[name]={ok:false,at:Date.now(),error:String(e)};return null}}
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function make(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}
function card(parent,tag,heading,body,meta,url){if(!parent)return;const a=make('article','item');if(tag)a.appendChild(make('span','tag'+(/DANGER|HIGH|खतरा/.test(tag)?' red':''),tag));a.appendChild(make('h4','',heading));if(body)a.appendChild(make('p','',body));if(meta)a.appendChild(make('div','meta',meta));if(url){const row=make('div','meta'),ln=make('a','','आधिकारिक स्रोत खोल्नुहोस्');ln.href=url;ln.target='_blank';ln.rel='noopener noreferrer';row.appendChild(ln);a.appendChild(row)}parent.appendChild(a)}

function renderClock(){setText('npLiveTime',npTime());setText('npBsDate',bsToday());setText('npAdDate',npDateAD())}
setInterval(renderClock,1000);renderClock();

async function locate(prompt=false){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>{const c=[p.coords.latitude,p.coords.longitude];localStorage.setItem('fs-v25-location',JSON.stringify(c));resolve(c)},()=>resolve(null),{enableHighAccuracy:true,timeout:14000,maximumAge:30000})})}
function savedLoc(){try{const x=JSON.parse(localStorage.getItem('fs-v25-location')||'null');return Array.isArray(x)&&x.length===2?x:null}catch{return null}}
async function weatherAt(c){if(!c)return null;const u=`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(c[0])}&longitude=${encodeURIComponent(c[1])}&current=temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,rain,weather_code,wind_speed_10m,wind_gusts_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum&forecast_days=1&timezone=Asia%2FKathmandu`;return await read('weather',u)}
function weatherName(code){return({0:'सफा',1:'मुख्यतः सफा',2:'आंशिक बादल',3:'बादल',45:'कुहिरो',48:'कुहिरो',51:'हल्का झरी',53:'झरी',55:'घना झरी',61:'हल्का वर्षा',63:'वर्षा',65:'भारी वर्षा',80:'वर्षा झरी',81:'वर्षा झरी',82:'भारी झरी',95:'मेघगर्जन',96:'असिना सहित मेघगर्जन',99:'तीव्र मेघगर्जन'})[Number(code)]||'मौसम'}
async function updateHomeWeather(force=false){
 if(PAGE!=='home')return;let c=savedLoc();if(!c&&navigator.permissions){try{const p=await navigator.permissions.query({name:'geolocation'});if(p.state==='granted')c=await locate(false)}catch{}}
 if(force&&!c)c=await locate(true);if(!c){setText('homeWxPlace','स्थान अनुमति आवश्यक');setText('homeWxStatus','GPS सक्रिय गरेपछि तपाईंको क्षेत्रको मौसम देखिन्छ।');return}
 const w=await weatherAt(c);if(!w){setText('homeWxStatus','मौसम स्रोत अहिले उपलब्ध छैन — पुरानो data लाई live भनिएको छैन।');return}const x=w.current||{},d=w.daily||{};
 setText('homeWxTemp',num(x.temperature_2m)!=null?Math.round(num(x.temperature_2m))+'°':'—°');setText('homeWxCondition',weatherName(x.weather_code));setText('homeWxRain',num(x.precipitation)!=null?num(x.precipitation).toFixed(1)+' mm':'—');setText('homeWxWind',num(x.wind_speed_10m)!=null?Math.round(num(x.wind_speed_10m))+' km/h':'—');setText('homeWxChance',num(d.precipitation_probability_max?.[0])!=null?Math.round(num(d.precipitation_probability_max[0]))+'%':'—');setText('homeWxRange',(num(d.temperature_2m_min?.[0])!=null?Math.round(num(d.temperature_2m_min[0]))+'°':'—')+' / '+(num(d.temperature_2m_max?.[0])!=null?Math.round(num(d.temperature_2m_max[0]))+'°':'—'));setText('homeWxPlace',digits(c[0].toFixed(3))+', '+digits(c[1].toFixed(3))+' • तपाईंको स्थान');
 const rain=num(x.precipitation)||0,ch=num(d.precipitation_probability_max?.[0])||0,code=Number(x.weather_code);setText('homeWxStatus',code>=95?'⚡ मेघगर्जन — स्थानीय खोला छिटो बढ्न सक्छ।':rain>=5||ch>=70?'🌧 वर्षाको उच्च संकेत — नजिकको नदी/खोला र Alerts जाँच गर्नुहोस्।':'अहिले मौसम मोडेलमा ठूलो वर्षा संकेत छैन। Official DHM/BIPAD चेतावनीलाई प्राथमिकता दिनुहोस्।');
}

function renderPeople(){const p=feeds.police,s=feeds.people;if(PAGE==='home'){setText('homeDeaths',p?.total_deaths??'—');setText('homeMissing',s?.missing_minimum!=null?'≥ '+s.missing_minimum:'—');setText('homeRescued',s?.rescued_alive??'—');setText('humanFresh',p?.official_update_iso?'Nepal Police • '+sourceAge(p.official_update_iso):'स्रोत समय उपलब्ध छैन')}
 if(PAGE==='people'){setText('peopleBodies',p?.total_deaths??s?.recovered_bodies??'—');setText('peopleMissing',s?.missing_minimum!=null?'≥ '+s.missing_minimum:'—');setText('peopleRescued',s?.rescued_alive??'—');const b=$('peopleBreakdown');if(b&&s)b.textContent=`सम्पर्कविहीन न्यूनतम: पर्यटक ${s.missing_tourists??'—'} • सुरक्षा निकाय ${s.missing_security_total??'—'}। उद्धार: नेपाली ${s.rescued_nepali??'—'} • विदेशी ${s.rescued_foreign??'—'}। यो प्रकाशित category हरूको न्यूनतम संख्या हो, अन्तिम nationwide total होइन।`}}

function renderAlerts(){const a=feeds.alerts===null?null:activeAlerts(feeds.alerts),r=feeds.rivers===null?null:riverAlerts(feeds.rivers),roads=feeds.roads===null?null:roadIssues(feeds.roads);if(PAGE==='alerts'){setText('alertCount',a===null?'—':a.length);setText('riverAlertCount',r===null?'—':r.length);setText('roadAlertCount',roads===null?'—':roads.length);const out=$('alertsList');if(out){clear(out);if(a)for(const o of a.slice(0,12))card(out,'HIGH',title(o),status(o)||'BIPAD उच्च प्राथमिकता चेतावनी',stamp(o)?sourceAge(stamp(o)):'समय उपलब्ध छैन','https://bipadportal.gov.np/');if(r)for(const x of r.slice(0,12)){const s=x.s;card(out,s.level,title(x.o),(s.wl!==null?'पानी '+s.wl+' m • ':'')+(s.w!==null?'चेतावनी '+s.w+' m • ':'')+(s.d!==null?'खतरा '+s.d+' m':''),sourceAge(stamp(x.o)),'https://www.dhm.gov.np/hydrology/floodMonitoring')}if(roads)for(const o of roads.slice(0,8))card(out,'ROAD',title(o),status(o)||'सडक अवरोध','Department of Roads via BIPAD','https://bipadportal.gov.np/');if(!out.children.length)out.appendChild(make('div','empty','अहिले fresh official feed मा सक्रिय उच्च चेतावनी भेटिएन। कुनै source unavailable भए “0” होइन “—” देखाइन्छ।'))}}
 currentRiskKeys=locationRiskKeys(a||[],r||[],roads||[]);maybeAlarm();
}

function healthLabel(ok,name){if(ok===undefined)return'जाँच हुँदैछ';return ok?name+' ✓':name+' ✕'}
function renderHealth(){setText('healthBipad',healthLabel(health.alerts?.ok,'BIPAD alerts'));setText('healthRiver',healthLabel(health.rivers?.ok,'DHM river'));setText('healthRoad',healthLabel(health.roads?.ok,'DoR road'));setText('healthPeople',healthLabel((health.people?.ok||health.police?.ok),'Human data'));setText('healthNews',healthLabel(health.news?.ok,'News sync'));const ok=['alerts','rivers','roads'].filter(k=>health[k]?.ok).length;setText('liveSourceState',ok===3?'३/३ मुख्य live feed connected':ok?`${ok}/३ मुख्य live feed connected`:'मुख्य live feed unavailable');}

function locationRiskKeys(alerts,rivers,roads){const c=savedLoc();if(!c)return new Set();const rad=Math.max(1,Number(localStorage.getItem('fs-v25-radius')||10)),out=new Set();for(const o of alerts){const p=coord(o);if(p&&distance(c,p)<=rad)out.add('alert|'+idOf(o)+'|'+String(stamp(o)||''))}for(const x of rivers){const p=coord(x.o);if(p&&distance(c,p)<=rad)out.add('river|'+idOf(x.o)+'|'+x.s.level+'|'+String(stamp(x.o)||''))}for(const o of roads){const p=coord(o),s=(title(o)+' '+status(o)).toLowerCase();if(p&&distance(c,p)<=rad&&FLOOD_RE.test(s))out.add('road|'+idOf(o)+'|'+String(stamp(o)||status(o)))}return out}
function acknowledged(k){try{const a=JSON.parse(localStorage.getItem('fs-v25-acks')||'{}'),t=a[k];return t&&Date.now()-t<6*3600e3}catch{return false}}
function ackRisks(){try{const a=JSON.parse(localStorage.getItem('fs-v25-acks')||'{}');for(const k of currentRiskKeys)a[k]=Date.now();localStorage.setItem('fs-v25-acks',JSON.stringify(a))}catch{}stopAlarm()}
function alarmTone(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const n=audioCtx.currentTime,m=audioCtx.createGain();m.gain.setValueAtTime(.0001,n);m.gain.exponentialRampToValueAtTime(.06,n+.02);m.gain.exponentialRampToValueAtTime(.0001,n+1.15);m.connect(audioCtx.destination);[[0,600,.18],[.28,780,.18],[.58,680,.30]].forEach(([t,f,d])=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.0001,n+t);g.gain.exponentialRampToValueAtTime(.3,n+t+.02);g.gain.exponentialRampToValueAtTime(.0001,n+t+d);o.connect(g);g.connect(m);o.start(n+t);o.stop(n+t+d+.03)})}catch{}}
function ensureAlarmUI(){let box=$('localRiskAlarm');if(box)return box;box=make('div','riskAlarm');box.id='localRiskAlarm';box.innerHTML='<div class="riskAlarmCard"><div class="riskAlarmIcon">🚨</div><h2>तपाईंको क्षेत्रभित्र उच्च जोखिम</h2><p>Fresh official feed ले तपाईंले छानेको radius भित्र उच्च जोखिम भेटाएको छ। सुरक्षित स्थानमा जानुहोस् र Alerts/Map जाँच गर्नुहोस्।</p><button id="riskAlarmOk" class="btn primary">OK — मैले चेतावनी देखें</button></div>';document.body.appendChild(box);$('riskAlarmOk').onclick=ackRisks;return box}
async function notifyRisk(){try{if('Notification'in window&&Notification.permission==='granted'){const reg=await navigator.serviceWorker?.ready;reg?.showNotification('बाढी सुरक्षा • स्थानीय उच्च जोखिम',{body:'तपाईंको सेट गरिएको radius भित्र fresh official warning भेटिएको छ।',icon:'../v24/icon.svg',badge:'../v24/icon.svg',tag:'floodsafe-local-high-risk',requireInteraction:true})}}catch{}}
function startAlarm(){if(alarmTimer)return;const box=ensureAlarmUI();box.classList.add('show');alarmTone();alarmTimer=setInterval(alarmTone,2200);notifyRisk()}
function stopAlarm(){if(alarmTimer){clearInterval(alarmTimer);alarmTimer=null}const b=$('localRiskAlarm');b?.classList.remove('show')}
function maybeAlarm(){if(localStorage.getItem('fs-v25-alerts-enabled')!=='1')return;const fresh=[...currentRiskKeys].filter(k=>!acknowledged(k));if(fresh.length)startAlarm();else stopAlarm();setText('localAlertState',fresh.length?`${digits(fresh.length)} local high-risk active`:'Local high-risk monitor सक्रिय • नयाँ खतरा छैन')}
async function armAlerts(){const c=await locate(true);if(!c){setText('localAlertState','Location अनुमति बिना radius alert चल्दैन।');return}try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();await audioCtx.resume()}catch{}try{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission()}catch{}localStorage.setItem('fs-v25-alerts-enabled','1');const r=$('alertRadius');if(r)localStorage.setItem('fs-v25-radius',r.value);setText('localAlertState','Location + local high-risk alarm सक्रिय');await poll(true);maybeAlarm()}

async function renderPeopleLive(){if(PAGE!=='people')return;const j=await read('lossPeople',API+'loss-people/?limit=500'),list=rows(j).filter(o=>/flood|बाढी|rasuwa|bhotekoshi|trishuli/i.test(txt(o))).sort((a,b)=>(+new Date(stamp(b)||0))-(+new Date(stamp(a)||0))).slice(0,20),out=$('peopleLiveList');if(!out)return;clear(out);for(const o of list)card(out,/missing|बेपत्ता|सम्पर्कविहीन/i.test(txt(o))?'Missing':/dead|death|मृत/i.test(txt(o))?'Death':/rescued|उद्धार/i.test(txt(o))?'Rescued':'People',title(o),status(o)||'BIPAD people-loss record',stamp(o)?sourceAge(stamp(o)):'समय उपलब्ध छैन','https://bipadportal.gov.np/');if(!out.children.length)out.appendChild(make('div','empty','Fresh BIPAD flood-related people record अहिले उपलब्ध छैन; माथि verified snapshot देखाइएको छ।'))}

async function poll(force=false){if(pollBusy||(!force&&document.hidden))return;pollBusy=true;try{const [a,r,rd,p,po,n]=await Promise.all([read('alerts',API+'alert/?limit=300&ordering=-createdOn'),read('rivers',API+'river/?limit=650'),read('roads',API+'highway/?limit=500'),read('people',DATA+'floodsafe-people-status.json?t='+Date.now()),read('police',DATA+'floodsafe-police.json?t='+Date.now()),read('news',DATA+'national-news.json?t='+Date.now())]);feeds.alerts=a?rows(a):null;feeds.rivers=r?rows(r):null;feeds.roads=rd?rows(rd):null;feeds.people=p;feeds.police=po;feeds.news=n;lastPoll=Date.now();renderPeople();renderAlerts();renderHealth();const st=$('appStatus');if(st)st.textContent=`Live check ${npTime()} • stale data लाई live मानिएको छैन`;if(PAGE==='home')setText('homeNewsFresh',n?.generated_at?'News sync • '+sourceAge(n.generated_at):'News sync unavailable')}finally{pollBusy=false}}

function bind(){const loc=$('homeLocationBtn');if(loc)loc.onclick=async()=>{await locate(true);await updateHomeWeather(true);await poll(true)};const arm=$('armLocalAlerts');if(arm)arm.onclick=armAlerts;const radius=$('alertRadius');if(radius){radius.value=localStorage.getItem('fs-v25-radius')||'10';radius.onchange=()=>{localStorage.setItem('fs-v25-radius',radius.value);currentRiskKeys=locationRiskKeys(activeAlerts(feeds.alerts||[]),riverAlerts(feeds.rivers||[]),roadIssues(feeds.roads||[]));maybeAlarm()}}if(localStorage.getItem('fs-v25-alerts-enabled')==='1')setText('localAlertState','Local high-risk monitor armed • location जाँच हुँदैछ');}
async function boot(){bind();renderClock();await updateHomeWeather(false);await poll(true);await renderPeopleLive();setInterval(()=>poll(false),30000);if(PAGE==='home')setInterval(()=>updateHomeWeather(false),120000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){poll(true);updateHomeWeather(false)}});window.addEventListener('online',()=>poll(true));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();