(()=>{'use strict';
if(window.__fsMapV3)return;window.__fsMapV3=true;
const NS='http://www.w3.org/2000/svg',B={minLon:80,maxLon:88.35,minLat:26.2,maxLat:30.5};
const xy=(lo,la)=>[(lo-B.minLon)/(B.maxLon-B.minLon)*1000,600-(la-B.minLat)/(B.maxLat-B.minLat)*600];
const inside=(la,lo)=>Number.isFinite(la)&&Number.isFinite(lo)&&la>=B.minLat&&la<=B.maxLat&&lo>=B.minLon&&lo<=B.maxLon;
let geo=null,token=0,svg=null;
const hint=()=>document.getElementById('mapHint'),detail=()=>document.getElementById('riverDetail');
async function get(u,ms=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(u+(u.includes('?')?'&':'?')+'_mv3='+Date.now(),{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
function ringPath(r){return(r||[]).map((p,i)=>{const[x,y]=xy(p[0],p[1]);return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' ')+' Z'}
function rings(f){const g=f.geometry||{};return g.type==='Polygon'?[g.coordinates?.[0]]:g.type==='MultiPolygon'?g.coordinates.map(p=>p?.[0]):[]}
function bbox(f){let minLo=99,maxLo=0,minLa=99,maxLa=0;for(const r of rings(f))for(const p of r||[]){minLo=Math.min(minLo,p[0]);maxLo=Math.max(maxLo,p[0]);minLa=Math.min(minLa,p[1]);maxLa=Math.max(maxLa,p[1])}return{minLo,maxLo,minLa,maxLa}}
function center(f){const b=bbox(f);return[(b.minLo+b.maxLo)/2,(b.minLa+b.maxLa)/2]}
function districtName(f){return f.properties?.nameEn||f.properties?.DISTRICT||f.properties?.district||'District'}
function viewNepal(){if(svg)svg.setAttribute('viewBox','-45 -30 1090 660')}
function viewDistrict(f){const b=bbox(f),a=xy(b.minLo,b.maxLa),z=xy(b.maxLo,b.minLa),pad=45,x=a[0]-pad,y=a[1]-pad,w=Math.max(230,z[0]-a[0]+pad*2),h=Math.max(170,z[1]-a[1]+pad*2);svg.setAttribute('viewBox',`${x} ${y} ${w} ${h}`)}
function addText(x,y,text,cls='districtLabelV3'){const t=document.createElementNS(NS,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor','middle');t.setAttribute('dominant-baseline','middle');t.setAttribute('class',cls);t.textContent=text;svg.appendChild(t);return t}
function drawBase(){if(!svg||!geo)return;svg.innerHTML='';for(const f of geo.features||[]){for(const r of rings(f)){if(!r?.length)continue;const p=document.createElementNS(NS,'path');p.setAttribute('d',ringPath(r));p.setAttribute('class','districtV3');p.dataset.name=districtName(f);p.addEventListener('click',e=>{e.stopPropagation();selectDistrict(f)});const ti=document.createElementNS(NS,'title');ti.textContent=districtName(f);p.appendChild(ti);svg.appendChild(p)}const c=center(f),q=xy(c[0],c[1]);addText(q[0],q[1],districtName(f))}viewNepal()}
function clearRivers(){svg?.querySelectorAll('.riverV3,.riverLabelV3').forEach(n=>n.remove())}
function riverPath(pts){return pts.map((p,i)=>{const[x,y]=xy(p[0],p[1]);return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' ')}
function drawRivers(els){clearRivers();let shown=0,named=0;for(const e of els.slice(0,650)){const pts=(e.geometry||[]).map(g=>[g.lon,g.lat]).filter(p=>inside(p[1],p[0]));if(pts.length<2)continue;const name=e.tags?.['name:ne']||e.tags?.name||'',type=e.tags?.waterway||'stream',p=document.createElementNS(NS,'path');p.setAttribute('d',riverPath(pts));p.setAttribute('class','riverV3 '+type+(name?' named':' unnamed'));p.addEventListener('click',ev=>{ev.stopPropagation();if(detail())detail().innerHTML=`<strong>${name||'नदी / खोला'}</strong><br>${type==='river'?'River':'Stream'} • selected district`});const ti=document.createElementNS(NS,'title');ti.textContent=name||'River / stream';p.appendChild(ti);svg.appendChild(p);shown++;if(name&&named<12){const mid=pts[Math.floor(pts.length/2)],q=xy(mid[0],mid[1]);addText(q[0],q[1]-3,name,'riverLabelV3');named++}}return shown}
async function queryBox(b,myToken){const pad=.025,s=Math.max(B.minLat,b.minLa-pad),w=Math.max(B.minLon,b.minLo-pad),n=Math.min(B.maxLat,b.maxLa+pad),e=Math.min(B.maxLon,b.maxLo+pad);const qs=[`[out:json][timeout:14];way["waterway"~"river|stream"](${s},${w},${n},${e});out tags geom;`,`[out:json][timeout:10];way["waterway"="river"](${s},${w},${n},${e});out tags geom;`];for(const q of qs){for(const ep of ['https://overpass-api.de/api/interpreter?data=','https://overpass.kumi.systems/api/interpreter?data=']){try{const j=await get(ep+encodeURIComponent(q),15000);if(myToken!==token)return[];const a=(j?.elements||[]).filter(x=>Array.isArray(x.geometry)&&x.geometry.length>1);if(a.length)return a}catch{}}}return[]}
async function selectDistrict(f){const my=++token,name=districtName(f);svg.querySelectorAll('.districtV3').forEach(p=>p.classList.toggle('selected',p.dataset.name===name));viewDistrict(f);clearRivers();if(hint())hint().textContent=`${name} का नदी/खोला लोड हुँदैछन्…`;if(detail())detail().innerHTML=`<strong>${name}</strong><br>नदी/खोला छान्नुहोस्।`;const els=await queryBox(bbox(f),my);if(my!==token)return;const n=drawRivers(els);if(hint())hint().textContent=n?`${name}: ${n} नदी/खोला segments देखाइएका छन्। नदीमा tap गर्नुहोस्।`:`${name} का river/stream data अहिले source बाट आएन। फेरि tap गर्नुहोस्।`}
function install(){const old=document.getElementById('riverMap');if(!old)return;old.style.display='none';svg=document.getElementById('riverMapV3');if(!svg){svg=document.createElementNS(NS,'svg');svg.id='riverMapV3';svg.setAttribute('viewBox','-45 -30 1090 660');svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.setAttribute('role','img');svg.setAttribute('aria-label','नेपाल जिल्ला र नदी नक्सा');old.parentNode.insertBefore(svg,old)}document.getElementById('mapReset')?.addEventListener('click',e=>{e.stopImmediatePropagation();token++;drawBase();if(hint())hint().textContent='जिल्ला tap गर्नुहोस् — त्यस जिल्लाका नदी/खोला खुल्छन्।'},true);document.getElementById('mapZoomIn')?.addEventListener('click',e=>{e.stopImmediatePropagation();const v=svg.viewBox.baseVal,cx=v.x+v.width/2,cy=v.y+v.height/2,w=Math.max(180,v.width*.72),h=w*.605;svg.setAttribute('viewBox',`${cx-w/2} ${cy-h/2} ${w} ${h}`)},true);document.getElementById('mapZoomOut')?.addEventListener('click',e=>{e.stopImmediatePropagation();const v=svg.viewBox.baseVal,cx=v.x+v.width/2,cy=v.y+v.height/2,w=Math.min(1090,v.width*1.38),h=w*.605;svg.setAttribute('viewBox',`${cx-w/2} ${cy-h/2} ${w} ${h}`)},true)}
async function boot(){install();try{geo=await get('../v24/nepal-districts.geojson',7000);drawBase();if(hint())hint().textContent='जिल्ला tap गर्नुहोस् — त्यस जिल्लाका नदी/खोला खुल्छन्।'}catch{if(hint())hint().textContent='नेपाल जिल्ला नक्सा लोड हुन सकेन।'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();