(()=>{'use strict';
if(window.__fsMapV8)return;window.__fsMapV8=true;
const NS='http://www.w3.org/2000/svg',B={minLon:80,maxLon:88.35,minLat:26.2,maxLat:30.5},$=id=>document.getElementById(id);
const lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne',tr=(ne,en)=>lang()==='en'?en:ne;
const NP={Achham:'अछाम',Arghakhanchi:'अर्घाखाँची',Baglung:'बागलुङ',Baitadi:'बैतडी',Bajhang:'बझाङ',Bajura:'बाजुरा',Banke:'बाँके',Bara:'बारा',Bardiya:'बर्दिया',Bhaktapur:'भक्तपुर',Bhojpur:'भोजपुर',Chitwan:'चितवन',Dadeldhura:'डडेलधुरा',Dailekh:'दैलेख',Dang:'दाङ',Darchula:'दार्चुला',Dhading:'धादिङ',Dhankuta:'धनकुटा',Dhanusha:'धनुषा',Dolakha:'दोलखा',Dolpa:'डोल्पा',Doti:'डोटी',Gorkha:'गोरखा',Gulmi:'गुल्मी',Humla:'हुम्ला',Ilam:'इलाम',Jajarkot:'जाजरकोट',Jhapa:'झापा',Jumla:'जुम्ला',Kailali:'कैलाली',Kalikot:'कालिकोट',Kanchanpur:'कञ्चनपुर',Kapilvastu:'कपिलवस्तु',Kaski:'कास्की',Kathmandu:'काठमाडौं',Kavrepalanchok:'काभ्रेपलाञ्चोक',Khotang:'खोटाङ',Lalitpur:'ललितपुर',Lamjung:'लमजुङ',Mahottari:'महोत्तरी',Makwanpur:'मकवानपुर',Manang:'मनाङ',Morang:'मोरङ',Mugu:'मुगु',Mustang:'मुस्ताङ',Myagdi:'म्याग्दी','Nawalparasi East':'नवलपुर','Nawalparasi West':'परासी',Nawalpur:'नवलपुर',Nuwakot:'नुवाकोट',Okhaldhunga:'ओखलढुङ्गा',Palpa:'पाल्पा',Panchthar:'पाँचथर',Parbat:'पर्वत',Parsa:'पर्सा',Pyuthan:'प्युठान',Ramechhap:'रामेछाप',Rasuwa:'रसुवा',Rautahat:'रौतहट',Rolpa:'रोल्पा','Rukum East':'पूर्वी रुकुम','Rukum West':'पश्चिम रुकुम',Rupandehi:'रुपन्देही',Salyan:'सल्यान',Sankhuwasabha:'सङ्खुवासभा',Saptari:'सप्तरी',Sarlahi:'सर्लाही',Sindhuli:'सिन्धुली',Sindhupalchok:'सिन्धुपाल्चोक',Siraha:'सिराहा',Solukhumbu:'सोलुखुम्बु',Sunsari:'सुनसरी',Surkhet:'सुर्खेत',Syangja:'स्याङ्जा',Tanahun:'तनहुँ',Taplejung:'ताप्लेजुङ',Terhathum:'तेह्रथुम',Udayapur:'उदयपुर'};
let svg=null,geo=null,water=null,last=null,selected=null,loadWaterP=null;
const xy=(lo,la)=>[(lo-B.minLon)/(B.maxLon-B.minLon)*1000,600-(la-B.minLat)/(B.maxLat-B.minLat)*600],ll=(x,y)=>[B.minLon+x/1000*(B.maxLon-B.minLon),B.maxLat-y/600*(B.maxLat-B.minLat)];
const inside=(la,lo)=>Number.isFinite(la)&&Number.isFinite(lo)&&la>=B.minLat&&la<=B.maxLat&&lo>=B.minLon&&lo<=B.maxLon;
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
async function get(u,ms=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(u+(u.includes('?')?'&':'?')+'_v8='+Date.now(),{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function loadWater(){if(water)return water;if(loadWaterP)return loadWaterP;loadWaterP=(async()=>{for(const u of['../../data/nepal-waterways-snapshot.json','../../data/nepal-waterways-seed.json']){try{const j=await get(u,10000);if(j?.waterways?.length)return water=j}catch{}}return null})();return loadWaterP}
function rings(f){const g=f.geometry||{};return g.type==='Polygon'?[g.coordinates?.[0]]:g.type==='MultiPolygon'?g.coordinates.map(p=>p?.[0]):[]}
function rawName(f){return f.properties?.nameEn||f.properties?.DISTRICT||f.properties?.district||'District'}
function dname(f){const n=rawName(f);return lang()==='en'?n:(NP[n]||n)}
function ringPath(r){return(r||[]).map((p,i)=>{const q=xy(p[0],p[1]);return(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)}).join(' ')+' Z'}
function center(f){let a=99,b=0,c=99,d=0;for(const r of rings(f))for(const p of r||[]){a=Math.min(a,p[0]);b=Math.max(b,p[0]);c=Math.min(c,p[1]);d=Math.max(d,p[1])}return[(a+b)/2,(c+d)/2]}
function districtFor(la,lo){let best=null,bd=1e9;for(const f of geo?.features||[]){const c=center(f),d=km(la,lo,c[1],c[0]);if(d<bd){bd=d;best=f}}return best}
function text(x,y,s,cls){const t=document.createElementNS(NS,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor','middle');t.setAttribute('dominant-baseline','middle');t.setAttribute('class',cls);t.textContent=s;svg.appendChild(t);return t}
function drawBase(){if(!svg||!geo)return;svg.innerHTML='';for(const f of geo.features||[]){for(const r of rings(f)){if(!r?.length)continue;const p=document.createElementNS(NS,'path');p.setAttribute('d',ringPath(r));p.setAttribute('class','districtV3');p.dataset.key=rawName(f);p.addEventListener('click',e=>{e.stopPropagation();const z=eventLL(e);if(z)choose(z[1],z[0],f)});svg.appendChild(p)}const c=center(f),q=xy(c[0],c[1]);text(q[0],q[1],dname(f),'districtLabelV3')}svg.setAttribute('viewBox','-50 -35 1100 670')}
function eventLL(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const m=svg.getScreenCTM();if(!m)return null;const q=p.matrixTransform(m.inverse());return ll(q.x,q.y)}
function marker(lo,la){svg.querySelectorAll('.selectedPointV3,.selectedRingV3').forEach(n=>n.remove());const q=xy(lo,la),a=document.createElementNS(NS,'circle'),b=document.createElementNS(NS,'circle');a.setAttribute('cx',q[0]);a.setAttribute('cy',q[1]);a.setAttribute('r','10');a.setAttribute('class','selectedRingV3');b.setAttribute('cx',q[0]);b.setAttribute('cy',q[1]);b.setAttribute('r','4');b.setAttribute('class','selectedPointV3');svg.append(a,b)}
function path(pts){return pts.map((p,i)=>{const q=xy(p[0],p[1]);return(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)}).join(' ')}
function wname(w){return lang()==='en'?(w.name_en||w.name||'Unnamed river or stream'):(w.name_ne||w.name||'नाम नखुलेको नदी वा खोला')}
function distTo(w,la,lo){let d=1e9;for(const p of w.pts||[])d=Math.min(d,km(la,lo,p[1],p[0]));return d}
function routeKey(w){const p=w.pts||[],a=p[0]||[],b=p[p.length-1]||[];return `${w.type||'stream'}|${(w.name||w.name_en||w.name_ne||'').toLowerCase()}|${a[0]?.toFixed?.(4)},${a[1]?.toFixed?.(4)}|${b[0]?.toFixed?.(4)},${b[1]?.toFixed?.(4)}`}
function candidates(la,lo){const a=[],seen=new Set();for(const w of water?.waterways||[]){if(!Array.isArray(w.pts)||w.pts.length<2)continue;const d=distTo(w,la,lo);if(d>26)continue;const k=routeKey(w);if(seen.has(k))continue;seen.add(k);a.push({w,d,named:!!(w.name||w.name_en||w.name_ne),river:w.type==='river'})}a.sort((x,y)=>x.d-y.d||(y.river-x.river)||(y.named-x.named));return a.slice(0,42).map(x=>x.w)}
function clearWater(){svg?.querySelectorAll('.riverRouteV8,.riverHitV8,.riverArrowV8').forEach(n=>n.remove())}
function addArrow(pts,frac,routeId){if(pts.length<2)return;const i=Math.min(pts.length-2,Math.max(0,Math.floor((pts.length-1)*frac))),a=xy(pts[i][0],pts[i][1]),b=xy(pts[i+1][0],pts[i+1][1]),x=a[0]+(b[0]-a[0])*.55,y=a[1]+(b[1]-a[1])*.55,ang=Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI;const poly=document.createElementNS(NS,'polygon');poly.setAttribute('points','-4,-3 4,0 -4,3');poly.setAttribute('class','riverArrowV8');poly.dataset.route=routeId;poly.setAttribute('transform',`translate(${x.toFixed(1)} ${y.toFixed(1)}) rotate(${ang.toFixed(1)})`);svg.appendChild(poly)}
function setSelected(routeId){selected=routeId;svg.querySelectorAll('.riverRouteV8').forEach(n=>n.classList.toggle('selected',n.dataset.route===routeId));svg.querySelectorAll('.riverArrowV8').forEach(n=>n.classList.toggle('selected',n.dataset.route===routeId))}
function drawWaterways(ws){clearWater();let n=0;ws.forEach((w,idx)=>{const pts=(w.pts||[]).filter(p=>inside(p[1],p[0]));if(pts.length<2)return;const route='r'+idx,d=path(pts),hit=document.createElementNS(NS,'path'),vis=document.createElementNS(NS,'path');hit.setAttribute('d',d);hit.setAttribute('class','riverHitV8');hit.dataset.route=route;hit.addEventListener('click',e=>{e.stopPropagation();setSelected(route);showSheet(w,pts)});vis.setAttribute('d',d);vis.setAttribute('class','riverRouteV8 '+(w.type==='river'?'river':'stream'));vis.dataset.route=route;svg.append(hit,vis);addArrow(pts,.48,route);if(pts.length>8)addArrow(pts,.76,route);n++});return n}
function ensureSheet(){let s=$('riverSheet');if(s)return s;s=document.createElement('section');s.id='riverSheet';s.className='riverSheetV8';s.hidden=true;s.innerHTML='<button id="riverSheetClose" class="riverSheetCloseV8" type="button" aria-label="Close">×</button><div id="riverSheetBody"></div>';document.body.appendChild(s);$('riverSheetClose').addEventListener('click',()=>{s.hidden=true;selected=null;setSelected('')});return s}
function fmtTime(t){if(!t)return tr('उपलब्ध छैन','Unavailable');try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return String(t)}}
function statusClass(k){return k==='danger'?'danger':k==='warning'?'warning':k==='watch'?'watch':'normal'}
function showSheet(w,pts){const mid=pts[Math.floor(pts.length/2)],g=window.FloodSafe?.stationInfoAt?.(mid[1],mid[0],65),nm=wname(w),typ=w.type==='river'?tr('नदी','River'):tr('खोला','Stream'),sheet=ensureSheet(),body=$('riverSheetBody');const st=g?g.statusLabel:tr('ताजा मापन छैन','NO FRESH GAUGE'),sc=g?statusClass(g.status):'unknown',level=g?.level??'—',warn=g?.warning??'—',danger=g?.danger??'—',trend='—';body.innerHTML=`<div class="sheetEyebrowV8">${tr('छानिएको नदी / खोला','Selected river / stream')}</div><h3>${nm}</h3><div class="sheetStatusV8 ${sc}">${tr('स्थिति','Status')}: <b>${st}</b></div><div class="sheetGridV8"><div><span>${tr('पानीको सतह','Water level')}</span><strong>${level} ${g?.level!=null?tr('मि.','m'):''}</strong></div><div><span>${tr('चेतावनी सीमा','Warning level')}</span><strong>${warn} ${g?.warning!=null?tr('मि.','m'):''}</strong></div><div><span>${tr('खतरा सीमा','Danger level')}</span><strong>${danger} ${g?.danger!=null?tr('मि.','m'):''}</strong></div><div><span>${tr('प्रवृत्ति','Trend')}</span><strong>${trend}</strong><small>${tr('स्रोतले नदिएको','Not supplied')}</small></div></div><div class="sheetMetaV8"><p><b>${tr('प्रकार','Type')}:</b> ${typ}</p><p><b>${tr('नजिकको आधिकारिक स्टेशन','Nearest official station')}:</b> ${g?.name||tr('६५ कि.मि. भित्र ताजा स्टेशन छैन','No fresh station within 65 km')}</p><p><b>${tr('मापन समय','Measured')}:</b> ${g?fmtTime(g.time):tr('उपलब्ध छैन','Unavailable')} ${g?.age?`• ${g.age}`:''}</p><p><b>${tr('स्रोत','Source')}:</b> ${g?'DHM / BIPAD':'OpenStreetMap'} ${g?'• OpenStreetMap route':''}</p></div><div class="sheetMoreV8"><h4>${tr('थप नदी / खोला विवरण','More river / stream details')}</h4><p><b>${tr('नक्सा विवरण','Map detail')}:</b> ${tr('यो रेखा स्थानीय OSM नदी/खोला snapshot बाट आएको वास्तविक route segment हो।','This line is an actual route segment from the local OSM waterways snapshot.')}</p><p class="sheetNoteV8">${tr('तीरले नक्साको route orientation मात्र देखाउँछ; आधिकारिक downstream flow direction data उपलब्ध नभएसम्म यसलाई hydrological direction नमान्नुहोस्।','Arrows show map-route orientation only; they are not verified downstream hydrological direction unless an official direction source is available.')}</p></div>`;sheet.hidden=false}
async function choose(la,lo,f){if(!inside(la,lo))return;f=f||districtFor(la,lo);last={la,lo,f};svg.querySelectorAll('.districtV3').forEach(p=>p.classList.toggle('selected',f&&p.dataset.key===rawName(f)));const q=xy(lo,la),w=315,h=205;svg.setAttribute('viewBox',`${Math.max(-35,Math.min(1035-w,q[0]-w/2))} ${Math.max(-25,Math.min(625-h,q[1]-h/2))} ${w} ${h}`);marker(lo,la);window.FloodSafe?.setFocus?.(la,lo,'map');window.FloodSafeSatellite?.selected?.(la,lo);const nm=f?dname(f):tr('छानिएको क्षेत्र','Selected area');if($('riverDetail'))$('riverDetail').innerHTML=`<strong>${nm}</strong><br>${tr('छानिएको क्षेत्र','Selected area')} • ${la.toFixed(4)}, ${lo.toFixed(4)}`;if($('mapHint'))$('mapHint').textContent=tr(`${nm} वरिपरिका नदी/खोला तयार हुँदैछन्…`,`Loading rivers and streams around ${nm}…`);await loadWater();const ws=candidates(la,lo),n=drawWaterways(ws);marker(lo,la);if($('mapHint'))$('mapHint').textContent=n?tr(`${n} नदी/खोला देखाइएका छन्। cyan रेखा थिच्दा विस्तृत अवस्था खुल्छ।`,`${n} rivers/streams shown. Tap a cyan line for detailed status.`):tr('यो ठाउँ वरिपरि स्थानीय नदी/खोला route भेटिएन।','No local river/stream route found around this point.')}
function replaceButton(id,fn){const b=$(id);if(!b)return;const c=b.cloneNode(true);b.replaceWith(c);c.addEventListener('click',fn)}
async function boot(){const old=$('riverMap');if(!old)return;old.style.display='none';svg=document.createElementNS(NS,'svg');svg.id='riverMapV3';svg.setAttribute('viewBox','-50 -35 1100 670');svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.setAttribute('role','img');svg.setAttribute('aria-label',tr('नेपाल नदी नक्सा','Nepal river map'));old.parentNode.insertBefore(svg,old);ensureSheet();replaceButton('mapReset',()=>{last=null;selected=null;drawBase();clearWater();window.FloodSafeSatellite?.full?.();if($('riverSheet'))$('riverSheet').hidden=true;if($('mapHint'))$('mapHint').textContent=tr('नक्सामा ठाउँ छान्नुहोस् — वरिपरिका नदी/खोला देखिन्छन्।','Tap a place on the map to show nearby rivers and streams.')});replaceButton('mapZoomIn',()=>{const v=svg.viewBox.baseVal,cx=v.x+v.width/2,cy=v.y+v.height/2,w=Math.max(135,v.width*.74),h=w*.65;svg.setAttribute('viewBox',`${cx-w/2} ${cy-h/2} ${w} ${h}`)});replaceButton('mapZoomOut',()=>{const v=svg.viewBox.baseVal,cx=v.x+v.width/2,cy=v.y+v.height/2,w=Math.min(1100,v.width*1.34),h=w*.61;svg.setAttribute('viewBox',`${cx-w/2} ${cy-h/2} ${w} ${h}`)});try{geo=await get('../v24/nepal-districts.geojson',8000);drawBase();await loadWater();if($('mapHint'))$('mapHint').textContent=tr('नक्सामा ठाउँ छान्नुहोस् — cyan नदी/खोला थिच्दा विस्तृत अवस्था खुल्छ।','Tap a place on the map, then tap a cyan river/stream for detailed status.')}catch{if($('mapHint'))$('mapHint').textContent=tr('नक्सा लोड हुन सकेन।','Map could not be loaded.')}}
window.addEventListener('fslanguage',async()=>{const keep=last;if(geo)drawBase();if(keep)await choose(keep.la,keep.lo,keep.f);if($('riverSheet')&&!$('riverSheet').hidden)$('riverSheet').hidden=true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.FloodSafeMap={choose,select:choose,get selected(){return last}};
})();