(()=>{'use strict';
if(window.__fsMapV7)return;window.__fsMapV7=true;
const NS='http://www.w3.org/2000/svg',B={minLon:80,maxLon:88.35,minLat:26.2,maxLat:30.5},$=id=>document.getElementById(id);
const lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne',tr=(ne,en)=>lang()==='en'?en:ne;
const NP={Achham:'अछाम',Arghakhanchi:'अर्घाखाँची',Baglung:'बागलुङ',Baitadi:'बैतडी',Bajhang:'बझाङ',Bajura:'बाजुरा',Banke:'बाँके',Bara:'बारा',Bardiya:'बर्दिया',Bhaktapur:'भक्तपुर',Bhojpur:'भोजपुर',Chitwan:'चितवन',Dadeldhura:'डडेलधुरा',Dailekh:'दैलेख',Dang:'दाङ',Darchula:'दार्चुला',Dhading:'धादिङ',Dhankuta:'धनकुटा',Dhanusha:'धनुषा',Dolakha:'दोलखा',Dolpa:'डोल्पा',Doti:'डोटी',Gorkha:'गोरखा',Gulmi:'गुल्मी',Humla:'हुम्ला',Ilam:'इलाम',Jajarkot:'जाजरकोट',Jhapa:'झापा',Jumla:'जुम्ला',Kailali:'कैलाली',Kalikot:'कालिकोट',Kanchanpur:'कञ्चनपुर',Kapilvastu:'कपिलवस्तु',Kaski:'कास्की',Kathmandu:'काठमाडौं',Kavrepalanchok:'काभ्रेपलाञ्चोक',Khotang:'खोटाङ',Lalitpur:'ललितपुर',Lamjung:'लमजुङ',Mahottari:'महोत्तरी',Makwanpur:'मकवानपुर',Manang:'मनाङ',Morang:'मोरङ',Mugu:'मुगु',Mustang:'मुस्ताङ',Myagdi:'म्याग्दी','Nawalparasi East':'नवलपुर','Nawalparasi West':'परासी',Nawalpur:'नवलपुर',Nuwakot:'नुवाकोट',Okhaldhunga:'ओखलढुङ्गा',Palpa:'पाल्पा',Panchthar:'पाँचथर',Parbat:'पर्वत',Parsa:'पर्सा',Pyuthan:'प्युठान',Ramechhap:'रामेछाप',Rasuwa:'रसुवा',Rautahat:'रौतहट',Rolpa:'रोल्पा','Rukum East':'पूर्वी रुकुम','Rukum West':'पश्चिम रुकुम',Rupandehi:'रुपन्देही',Salyan:'सल्यान',Sankhuwasabha:'सङ्खुवासभा',Saptari:'सप्तरी',Sarlahi:'सर्लाही',Sindhuli:'सिन्धुली',Sindhupalchok:'सिन्धुपाल्चोक',Siraha:'सिराहा',Solukhumbu:'सोलुखुम्बु',Sunsari:'सुनसरी',Surkhet:'सुर्खेत',Syangja:'स्याङ्जा',Tanahun:'तनहुँ',Taplejung:'ताप्लेजुङ',Terhathum:'तेह्रथुम',Udayapur:'उदयपुर'};
let svg=null,geo=null,token=0,last=null;
const xy=(lo,la)=>[(lo-B.minLon)/(B.maxLon-B.minLon)*1000,600-(la-B.minLat)/(B.maxLat-B.minLat)*600];
const ll=(x,y)=>[B.minLon+x/1000*(B.maxLon-B.minLon),B.maxLat-y/600*(B.maxLat-B.minLat)];
const inside=(la,lo)=>Number.isFinite(la)&&Number.isFinite(lo)&&la>=B.minLat&&la<=B.maxLat&&lo>=B.minLon&&lo<=B.maxLon;
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
async function get(u,ms=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(u+(u.includes('?')?'&':'?')+'_v7='+Date.now(),{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function over(q,ms=9000){for(const ep of['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter']){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(ep,{method:'POST',cache:'no-store',credentials:'omit',signal:c.signal,headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','Accept':'application/json'},body:'data='+encodeURIComponent(q)});if(r.ok){const j=await r.json();if(j?.elements?.length)return j}}catch{}finally{clearTimeout(t)}}return{elements:[]}}
function rings(f){const g=f.geometry||{};return g.type==='Polygon'?[g.coordinates?.[0]]:g.type==='MultiPolygon'?g.coordinates.map(p=>p?.[0]):[]}
function rawName(f){return f.properties?.nameEn||f.properties?.DISTRICT||f.properties?.district||'District'}
function dname(f){const n=rawName(f);return lang()==='en'?n:(NP[n]||n)}
function ringPath(r){return(r||[]).map((p,i)=>{const q=xy(p[0],p[1]);return(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)}).join(' ')+' Z'}
function center(f){let a=99,b=0,c=99,d=0;for(const r of rings(f))for(const p of r||[]){a=Math.min(a,p[0]);b=Math.max(b,p[0]);c=Math.min(c,p[1]);d=Math.max(d,p[1])}return[(a+b)/2,(c+d)/2]}
function text(x,y,s,cls){const t=document.createElementNS(NS,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor','middle');t.setAttribute('dominant-baseline','middle');t.setAttribute('class',cls);t.textContent=s;svg.appendChild(t);return t}
function drawBase(){svg.innerHTML='';for(const f of geo?.features||[]){for(const r of rings(f)){if(!r?.length)continue;const p=document.createElementNS(NS,'path');p.setAttribute('d',ringPath(r));p.setAttribute('class','districtV3');p.dataset.key=rawName(f);p.addEventListener('click',e=>{e.stopPropagation();const z=eventLL(e);if(z)selectAt(z[1],z[0],f)});svg.appendChild(p)}const c=center(f),q=xy(c[0],c[1]);text(q[0],q[1],dname(f),'districtLabelV3')}svg.setAttribute('viewBox','-50 -35 1100 670')}
function eventLL(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const m=svg.getScreenCTM();if(!m)return null;const q=p.matrixTransform(m.inverse());return ll(q.x,q.y)}
function clearDynamic(){svg.querySelectorAll('.riverV3,.riverHitV3,.riverLabelV3,.selectedPointV3,.selectedRingV3').forEach(n=>n.remove())}
function marker(lo,la){svg.querySelectorAll('.selectedPointV3,.selectedRingV3').forEach(n=>n.remove());const q=xy(lo,la),a=document.createElementNS(NS,'circle'),b=document.createElementNS(NS,'circle');a.setAttribute('cx',q[0]);a.setAttribute('cy',q[1]);a.setAttribute('r','10');a.setAttribute('class','selectedRingV3');b.setAttribute('cx',q[0]);b.setAttribute('cy',q[1]);b.setAttribute('r','4');b.setAttribute('class','selectedPointV3');svg.append(a,b)}
function path(pts){return pts.map((p,i)=>{const q=xy(p[0],p[1]);return(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)}).join(' ')}
function rname(e){return lang()==='en'?(e.tags?.['name:en']||e.tags?.name||'Unnamed river or stream'):(e.tags?.['name:ne']||e.tags?.name_ne||e.tags?.name||'नाम नखुलेको नदी वा खोला')}
function detailFor(e,pts){const mid=pts[Math.floor(pts.length/2)],g=window.FloodSafe?.stationInfoAt?.(mid[1],mid[0],55),nm=rname(e),type=e.tags?.waterway==='river'?tr('नदी','River'):tr('खोला','Stream');let h=`<strong>${nm}</strong><br>${tr('प्रकार','Type')}: ${type}<br>${tr('नक्सा स्रोत','Map source')}: OpenStreetMap`;if(g)h+=`<br>${tr('नजिकको आधिकारिक मापन केन्द्र','Nearest official gauge')}: ${g.name}<br>${tr('अवस्था','Status')}: <b>${g.statusLabel}</b><br>${tr('पानीको तह','Water level')}: <b>${g.level??'—'} ${tr('मि.','m')}</b><br>${tr('मापन समय','Measured')}: ${g.age}`;else h+=`<br>${tr('५५ कि.मि. भित्र ताजा आधिकारिक मापन केन्द्र भेटिएन।','No fresh official gauge found within 55 km.')}`;$('riverDetail').innerHTML=h}
function pointDist(e,la,lo){let d=1e9;for(const g of e.geometry||[])d=Math.min(d,km(la,lo,g.lat,g.lon));return d}
function uniqueKey(e){const nm=(e.tags?.['name:ne']||e.tags?.['name:en']||e.tags?.name||'').trim().toLowerCase();const g=e.geometry||[],a=g[0],b=g[g.length-1];return `${e.tags?.waterway||'stream'}|${nm}|${a?.lat?.toFixed?.(4)},${a?.lon?.toFixed?.(4)}|${b?.lat?.toFixed?.(4)},${b?.lon?.toFixed?.(4)}`}
function prepare(els,la,lo){const seen=new Set(),a=[];for(const e of els||[]){if(!Array.isArray(e.geometry)||e.geometry.length<2)continue;const d=pointDist(e,la,lo);if(d>24)continue;const k=uniqueKey(e);if(seen.has(k))continue;seen.add(k);a.push({e,d,named:!!(e.tags?.['name:ne']||e.tags?.['name:en']||e.tags?.name),river:e.tags?.waterway==='river'})}a.sort((x,y)=>x.d-y.d||(y.named-x.named)||(y.river-x.river));const out=[],streams=[];for(const x of a){if(x.river||x.named)out.push(x.e);else streams.push(x.e);if(out.length>=45)break}for(const e of streams){if(out.length>=70)break;out.push(e)}return out}
function labelOK(boxes,x,y,label){const w=Math.max(34,Math.min(95,label.length*6.2)),h=15,b={l:x-w/2,r:x+w/2,t:y-h/2,b:y+h/2};for(const q of boxes)if(!(b.r<q.l||b.l>q.r||b.b<q.t||b.t>q.b))return false;boxes.push(b);return true}
function drawRivers(els,la,lo){svg.querySelectorAll('.riverV3,.riverHitV3,.riverLabelV3').forEach(n=>n.remove());const pick=prepare(els,la,lo),boxes=[];let shown=0,labels=0;for(const e of pick){const pts=(e.geometry||[]).map(g=>[g.lon,g.lat]).filter(p=>inside(p[1],p[0]));if(pts.length<2)continue;const d=path(pts),type=e.tags?.waterway||'stream';const hit=document.createElementNS(NS,'path');hit.setAttribute('d',d);hit.setAttribute('class','riverHitV3');hit.addEventListener('click',ev=>{ev.stopPropagation();detailFor(e,pts)});svg.appendChild(hit);const p=document.createElementNS(NS,'path');p.setAttribute('d',d);p.setAttribute('class','riverV3 '+type);p.setAttribute('aria-hidden','true');svg.appendChild(p);shown++;const nm=rname(e);if(labels<7&&!/^Unnamed|^नाम नखुलेको/.test(nm)){const m=pts[Math.floor(pts.length/2)],q=xy(m[0],m[1]);if(labelOK(boxes,q[0],q[1]-5,nm)){text(q[0],q[1]-5,nm,'riverLabelV3');labels++}}}return shown}
async function nearby(la,lo,my){for(const radius of[14,20,28]){const dl=radius/111,dlo=radius/(111*Math.max(.25,Math.cos(la*Math.PI/180))),s=Math.max(B.minLat,la-dl),w=Math.max(B.minLon,lo-dlo),n=Math.min(B.maxLat,la+dl),e=Math.min(B.maxLon,lo+dlo),q=`[out:json][timeout:10];(way["waterway"="river"](${s},${w},${n},${e});way["waterway"="stream"](${s},${w},${n},${e}););out tags geom;`,j=await over(q,8500);if(my!==token)return[];const a=(j?.elements||[]).filter(x=>Array.isArray(x.geometry)&&x.geometry.length>1);if(a.length)return a}return[]}
function districtFor(la,lo){let best=null,bd=1e9;for(const f of geo?.features||[]){const c=center(f),d=km(la,lo,c[1],c[0]);if(d<bd){bd=d;best=f}}return best}
async function selectAt(la,lo,f){if(!inside(la,lo))return;const my=++token;f=f||districtFor(la,lo);last={la,lo,f};svg.querySelectorAll('.districtV3').forEach(p=>p.classList.toggle('selected',f&&p.dataset.key===rawName(f)));clearDynamic();const q=xy(lo,la),w=285,h=175;svg.setAttribute('viewBox',`${Math.max(-35,Math.min(1035-w,q[0]-w/2))} ${Math.max(-25,Math.min(625-h,q[1]-h/2))} ${w} ${h}`);marker(lo,la);window.FloodSafe?.setFocus?.(la,lo,'map');const nm=f?dname(f):tr('छानिएको क्षेत्र','Selected area');if($('mapHint'))$('mapHint').textContent=tr(`${nm} वरिपरिका नदी/खोला खोजिँदैछन्…`,`Finding rivers and streams around ${nm}…`);if($('riverDetail'))$('riverDetail').innerHTML=`<strong>${nm}</strong><br>${tr('छानिएको क्षेत्र','Selected area')} • ${la.toFixed(4)}, ${lo.toFixed(4)}`;
let local=0;try{local=await window.FloodSafeLocalWaterways?.draw?.(la,lo)||0}catch{}if(my!==token)return;
const els=await nearby(la,lo,my);if(my!==token)return;const n=drawRivers(els,la,lo);marker(lo,la);if($('mapHint'))$('mapHint').textContent=n?tr(`${nm}: ${n} वटा नजिकका नदी/खोला छुट्टाछुट्टै नीलो डटेड लाइनमा देखाइएका छन्। लाइन थिच्दा विवरण खुल्छ।`,`${nm}: ${n} nearby rivers/streams are shown as separate blue dotted lines. Tap a line for details.`):(local?tr(`${nm}: स्थानीय नदी नक्सा देखाइएको छ।`,`${nm}: local river map data is shown.`):tr(`${nm}: अहिले यो ठाउँ वरिपरि नदी/खोला data आउन सकेन।`,`${nm}: river/stream data is unavailable around this point right now.`))}
function replaceButton(id,fn){const b=$(id);if(!b)return;const c=b.cloneNode(true);b.replaceWith(c);c.addEventListener('click',fn)}
function reset(){token++;last=null;drawBase();if($('mapHint'))$('mapHint').textContent=tr('नक्सामा ठाउँ छान्नुहोस् — वरिपरिका नदी/खोला छुट्टाछुट्टै डटेड लाइनमा खुल्छन्।','Tap a place on the map — nearby rivers/streams appear as separate dotted lines.');if($('riverDetail'))$('riverDetail').innerHTML=`<strong>${tr('नदी विवरण','River detail')}</strong><br>${tr('नदी/खोला थिच्दा ताजा मापन विवरण देखिन्छ।','Tap a river/stream to see fresh gauge details.')}`}
function install(){const old=$('riverMap');if(!old)return;old.style.display='none';svg=document.createElementNS(NS,'svg');svg.id='riverMapV3';svg.setAttribute('viewBox','-50 -35 1100 670');svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.setAttribute('role','img');old.parentNode.insertBefore(svg,old);replaceButton('mapReset',reset);replaceButton('mapZoomIn',()=>{const v=svg.viewBox.baseVal,cx=v.x+v.width/2,cy=v.y+v.height/2,w=Math.max(135,v.width*.74),h=w*.61;svg.setAttribute('viewBox',`${cx-w/2} ${cy-h/2} ${w} ${h}`)});replaceButton('mapZoomOut',()=>{const v=svg.viewBox.baseVal,cx=v.x+v.width/2,cy=v.y+v.height/2,w=Math.min(1100,v.width*1.35),h=w*.61;svg.setAttribute('viewBox',`${cx-w/2} ${cy-h/2} ${w} ${h}`)})}
async function boot(){install();try{geo=await get('../v24/nepal-districts.geojson',7000);drawBase();reset()}catch{if($('mapHint'))$('mapHint').textContent=tr('नेपाल जिल्ला नक्सा लोड हुन सकेन।','Nepal district map could not be loaded.')}}
window.addEventListener('fslanguage',()=>{if(last)selectAt(last.la,last.lo,last.f);else reset()});
window.FloodSafeMap={select:(la,lo)=>selectAt(Number(la),Number(lo),districtFor(Number(la),Number(lo))),reset};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();