import * as maplibregl from 'https://unpkg.com/maplibre-gl@6.6.0/dist/maplibre-gl.mjs';

const $=id=>document.getElementById(id);
const NEPAL_BOUNDS=[[80.0,26.2],[88.35,30.5]];
const HARD_BOUNDS=[[79.35,25.55],[89.0,31.05]];
const EMPTY={type:'FeatureCollection',features:[]};
const lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne';
const tr=(ne,en)=>lang()==='en'?en:ne;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
let map=null,water=null,last=null,is3D=true,selected=null,visible=[],national=[],particles=[],lastParticleFrame=0,districtGeo=null,districtMarkers=[];

function wname(w){return lang()==='en'?(w.name_en||w.name||'Unnamed river or stream'):(w.name_ne||w.name||'नाम नखुलेको नदी वा खोला')}
function routeKey(w){const p=w.pts||[],a=p[0]||[],b=p[p.length-1]||[];return `${w.type||'stream'}|${(w.name||w.name_en||w.name_ne||'').toLowerCase()}|${a[0]?.toFixed?.(4)},${a[1]?.toFixed?.(4)}|${b[0]?.toFixed?.(4)},${b[1]?.toFixed?.(4)}`}
async function get(url,ms=18000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_gl3='+Date.now(),{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function loadWater(){if(water)return water;for(const u of['https://raw.githubusercontent.com/Pujan1234-hub/assigment/main/data/nepal-waterways-snapshot.json','https://raw.githubusercontent.com/Pujan1234-hub/assigment/main/data/nepal-waterways-seed.json','../../data/nepal-waterways-snapshot.json','../../data/nepal-waterways-seed.json']){try{const j=await get(u,26000);if(j?.waterways?.length>=100){water=j;return j}}catch{}}return null}
function distanceTo(w,la,lo){let best=1e9;for(const p of w.pts||[]){if(Math.abs(p[1]-la)>.42||Math.abs(p[0]-lo)>.52)continue;best=Math.min(best,km(la,lo,p[1],p[0]))}return best}
function nearbyWater(la,lo){const a=[],seen=new Set();for(const w of water?.waterways||[]){if(!Array.isArray(w.pts)||w.pts.length<2)continue;const d=distanceTo(w,la,lo);if(d>32)continue;const k=routeKey(w);if(seen.has(k))continue;seen.add(k);a.push({w,d,named:!!(w.name||w.name_en||w.name_ne),river:w.type==='river',len:w.pts.length})}a.sort((x,y)=>x.d-y.d||(y.river-x.river)||(y.named-x.named)||(y.len-x.len));return a.slice(0,40).map(x=>x.w)}
function nationalWater(){const a=[],seen=new Set();for(const w of water?.waterways||[]){if(!Array.isArray(w.pts)||w.pts.length<2)continue;const named=!!(w.name||w.name_en||w.name_ne),river=w.type==='river';if(!river&&!named)continue;const k=routeKey(w);if(seen.has(k))continue;seen.add(k);let minX=999,maxX=-999,minY=999,maxY=-999;for(const p of w.pts){if(!Array.isArray(p)||p.length<2)continue;minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1])}const span=(maxX-minX)+(maxY-minY),score=(river?130:0)+(named?55:0)+Math.min(80,w.pts.length*2)+Math.min(70,span*120);a.push({w,score})}a.sort((x,y)=>y.score-x.score);return a.slice(0,1100).map(x=>x.w)}
function gaugeFor(w,la,lo){return window.FloodSafeGauge?.forWaterway?.(w,la,lo)||null}
function lineFeatures(ws,la=null,lo=null,withGauge=false){return ws.map(w=>{const g=withGauge?gaugeFor(w,la,lo):null,key=routeKey(w),same=!!g?.sameRiver;return{type:'Feature',geometry:{type:'LineString',coordinates:w.pts},properties:{key,name:wname(w),type:w.type||'stream',status:same?(g.status||'normal'):'unknown',selected:selected?.key===key}}})}
function gaugeFeatures(la,lo){return (window.FloodSafeGauge?.nearby?.(la,lo,65,16)||[]).map(g=>({type:'Feature',geometry:{type:'Point',coordinates:[g.lon,g.lat]},properties:{name:g.name,status:g.status||'normal',statusLabel:g.statusLabel||'',level:g.level??'',warning:g.warning??'',danger:g.danger??'',time:g.time||'',distanceKm:g.distanceKm??0}}))}
function setSource(id,data){const s=map?.getSource(id);if(s)s.setData(data)}
function rebuildParticles(){const cap=last?28:36;particles=visible.slice(0,cap).filter(w=>w.pts?.length>1).map((w,i)=>({key:routeKey(w),pts:w.pts,offset:(i*.173)%1}))}
function animateParticles(ts){if(map&&ts-lastParticleFrame>140&&map.getSource('flow-particles')){lastParticleFrame=ts;const phase=(ts%5600)/5600,features=[];for(const p of particles){const n=p.pts.length-1,v=((phase+p.offset)%1)*n,i=Math.floor(v),f=v-i,a=p.pts[i],b=p.pts[Math.min(n,i+1)];features.push({type:'Feature',geometry:{type:'Point',coordinates:[a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f]},properties:{key:p.key}})}setSource('flow-particles',{type:'FeatureCollection',features})}requestAnimationFrame(animateParticles)}
function statusText(k){return lang()==='en'?({danger:'DANGER',warning:'WARNING',watch:'WATCH',normal:'NORMAL'}[k]||'NO DIRECT GAUGE'):({danger:'खतरा',warning:'चेतावनी',watch:'निगरानी',normal:'सामान्य'}[k]||'प्रत्यक्ष मापन केन्द्र छैन')}
function fmtTime(t){if(!t)return tr('उपलब्ध छैन','Unavailable');try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return String(t)}}
function ensureSheet(){let s=$('riverSheetGL');if(s)return s;s=document.createElement('section');s.id='riverSheetGL';s.className='riverSheetGL';s.hidden=true;s.innerHTML='<button id="riverSheetGLClose" class="riverSheetGLClose" type="button">×</button><div id="riverSheetGLBody"></div>';document.body.appendChild(s);$('riverSheetGLClose').addEventListener('click',()=>{s.hidden=true;selected=null;refreshWater()});return s}
function sheetHtml(w,g){const direct=!!g?.sameRiver,st=g?statusText(g.status):statusText('unknown'),kind=direct?tr('यही नदीको प्रत्यक्ष मापन','LIVE GAUGE ON THIS RIVER'):g?tr('नजिकको आधिकारिक सन्दर्भ मापन','NEAREST OFFICIAL REFERENCE GAUGE'):tr('प्रत्यक्ष मापन उपलब्ध छैन','NO DIRECT GAUGE');return `<div class="sheetEyebrowGL">${tr('छानिएको नदी / खोला','Selected river / stream')}</div><h3>${esc(wname(w))}</h3><div class="sheetStatusGL ${esc(g?.status||'unknown')}">${esc(kind)} • <b>${esc(st)}</b></div><div class="sheetAutoGL">↻ ${tr('DHM/BIPAD मापन हरेक ५ सेकेन्डमा स्वतः जाँचिन्छ','DHM/BIPAD gauge data is checked automatically every 5 seconds')}</div><div class="sheetGridGL"><div><span>${tr('पानीको सतह','Water level')}</span><strong>${g?.level!=null?esc(g.level)+' m':'—'}</strong></div><div><span>${tr('चेतावनी सीमा','Warning level')}</span><strong>${g?.warning!=null?esc(g.warning)+' m':'—'}</strong></div><div><span>${tr('खतरा सीमा','Danger level')}</span><strong>${g?.danger!=null?esc(g.danger)+' m':'—'}</strong></div><div><span>${tr('अवस्था','Status')}</span><strong>${g?esc(st):'—'}</strong></div></div><div class="sheetMetaGL"><p><b>${tr('मापन केन्द्र','Gauge')}:</b> ${g?esc(g.name):tr('उपलब्ध छैन','Unavailable')}${g?` • ${Number(g.distanceKm||0).toFixed(1)} km`:''}</p><p><b>${tr('मापन समय','Measured')}:</b> ${g?esc(fmtTime(g.time)):tr('उपलब्ध छैन','Unavailable')}</p><p><b>${tr('स्रोत','Source')}:</b> ${g?'DHM / BIPAD':'OpenStreetMap river geometry'}</p></div>${g&&!direct?`<div class="sheetWarnGL">${tr('यो reading छानिएको नदीकै होइन; नजिकको आधिकारिक मापन केन्द्रको सन्दर्भ हो।','This reading is not from the selected river; it is the nearest official reference gauge.')}</div>`:''}<div class="sheetNoteGL">${tr('सानो सेतो बिन्दु route animation हो; आधिकारिक downstream direction नभएसम्म प्रमाणित बहाव-दिशा होइन।','The small white dot is a route animation, not verified downstream direction unless an official direction source exists.')}</div>`}
function renderSelected(){if(!selected)return;const p=selected.w.pts[Math.floor(selected.w.pts.length/2)],g=gaugeFor(selected.w,p[1],p[0]),s=ensureSheet();$('riverSheetGLBody').innerHTML=sheetHtml(selected.w,g);s.hidden=false}
function showGauge(props){const s=ensureSheet(),st=statusText(props.status);$('riverSheetGLBody').innerHTML=`<div class="sheetEyebrowGL">${tr('आधिकारिक नदी मापन केन्द्र','Official river gauge')}</div><h3>${esc(props.name)}</h3><div class="sheetStatusGL ${esc(props.status)}"><b>${esc(st)}</b></div><div class="sheetAutoGL">↻ ${tr('हरेक ५ सेकेन्डमा स्वतः अद्यावधिक','Auto-updates every 5 seconds')}</div><div class="sheetGridGL"><div><span>${tr('पानीको सतह','Water level')}</span><strong>${props.level!==''?esc(props.level)+' m':'—'}</strong></div><div><span>${tr('चेतावनी सीमा','Warning level')}</span><strong>${props.warning!==''?esc(props.warning)+' m':'—'}</strong></div><div><span>${tr('खतरा सीमा','Danger level')}</span><strong>${props.danger!==''?esc(props.danger)+' m':'—'}</strong></div><div><span>${tr('अवस्था','Status')}</span><strong>${esc(st)}</strong></div></div><div class="sheetMetaGL"><p><b>${tr('मापन समय','Measured')}:</b> ${esc(fmtTime(props.time))}</p><p><b>${tr('स्रोत','Source')}:</b> DHM / BIPAD</p></div>`;s.hidden=false}
function refreshWater(){if(!map?.getSource('rivers'))return;const local=!!last;setSource('rivers',{type:'FeatureCollection',features:lineFeatures(visible,last?.la,last?.lo,local)});setSource('gauges',local?{type:'FeatureCollection',features:gaugeFeatures(last.la,last.lo)}:EMPTY);setSource('focus',local?{type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[last.lo,last.la]},properties:{}}]}:EMPTY);rebuildParticles()}
function districtNameAt(point){try{const f=map.queryRenderedFeatures(point,{layers:['district-hit']})[0];return f?.properties?.nameEn||''}catch{return''}}
async function select(la,lo,zoomTo=true,point=null){if(!(la>=26.2&&la<=30.5&&lo>=80&&lo<=88.35))return;last={la,lo};selected=null;if($('riverSheetGL'))$('riverSheetGL').hidden=true;if(!water)await loadWater();visible=nearbyWater(la,lo);refreshWater();window.FloodSafe?.setFocus?.(la,lo,'map');if(zoomTo)map.easeTo({center:[lo,la],zoom:Math.max(map.getZoom(),11.6),pitch:is3D?58:0,bearing:0,duration:700});const dn=point?districtNameAt(point):'';if($('mapHint'))$('mapHint').textContent=visible.length?tr(`${dn?dn+' • ':''}${visible.length} नजिकका नदी/खोला • cyan line वा gauge थिच्नुहोस्`,`${dn?dn+' • ':''}${visible.length} nearby rivers/streams • tap a cyan line or gauge`):tr('यो ठाउँ वरिपरि local river route भेटिएन; Nepal-wide network हेर्न 🇳🇵 नेपाल थिच्नुहोस्।','No local river route found here; press 🇳🇵 Nepal for the national network.')}
function focusNepal(animated=true){const p=Math.max(12,Math.min(42,window.innerWidth<620?26:38));map.fitBounds(NEPAL_BOUNDS,{padding:window.innerWidth<620?12:28,pitch:0,bearing:0,duration:0});const z=Math.max(4.9,map.getZoom()-(window.innerWidth<620?.12:.28));map.easeTo({center:[84.15,28.1],zoom:z,pitch:is3D?p:0,bearing:0,duration:animated?650:0})}
function showNational(){last=null;selected=null;if($('riverSheetGL'))$('riverSheetGL').hidden=true;national=national.length?national:nationalWater();visible=national;refreshWater();if($('mapHint'))$('mapHint').textContent=national.length?tr(`🇳🇵 नेपाल • ७७ जिल्ला • ${national.length} मुख्य/नाम भएका नदी–खोला देखाइएका छन् • ठाउँ छान्दा local detail खुल्छ`,`🇳🇵 Nepal • 77 districts • ${national.length} major/named river routes shown • tap a place for local detail`):tr('🇳🇵 नेपाल र ७७ जिल्ला देखिएका छन् • नदी data लोड हुन सकेन।','🇳🇵 Nepal and 77 districts are visible • river data could not load.')}
async function reset(){focusNepal(true);if(!water)await loadWater();showNational()}
function set3D(on){is3D=!!on;try{map.setTerrain(is3D?{source:'terrain',exaggeration:1.18}:null)}catch{}map.easeTo({pitch:is3D?(window.innerWidth<620?30:48):0,bearing:0,duration:550});const b=$('map3D');if(b)b.textContent=is3D?tr('▱ २D नक्सा','▱ 2D Map'):tr('◈ ३D भू-आकृति','◈ 3D Terrain');b?.classList.toggle('active',is3D)}
function addCoreLayers(){map.addSource('rivers',{type:'geojson',data:EMPTY,lineMetrics:true});map.addLayer({id:'river-hit',type:'line',source:'rivers',paint:{'line-color':'rgba(0,0,0,0)','line-width':22}});map.addLayer({id:'river-base',type:'line',source:'rivers',paint:{'line-color':['case',['==',['get','selected'],true],'#00f6ff',['match',['get','status'],'danger','#ff5366','warning','#ff9d42','watch','#ffd65b','#25e6ff']],'line-width':['interpolate',['linear'],['zoom'],5,.9,7,1.5,10,2.7,14,4.4,18,6.6],'line-opacity':['interpolate',['linear'],['zoom'],5,.78,7,.95]}});map.addLayer({id:'river-glow',type:'line',source:'rivers',paint:{'line-color':'#e9fdff','line-width':['interpolate',['linear'],['zoom'],5,.35,10,.8,16,1.8],'line-opacity':.46}});map.addSource('flow-particles',{type:'geojson',data:EMPTY});map.addLayer({id:'flow-particles',type:'circle',source:'flow-particles',paint:{'circle-radius':['interpolate',['linear'],['zoom'],5,.7,12,2.1,17,3.2],'circle-color':'#fff','circle-stroke-color':'#00dff5','circle-stroke-width':.8,'circle-opacity':.9}});map.addSource('gauges',{type:'geojson',data:EMPTY});map.addLayer({id:'gauges',type:'circle',source:'gauges',paint:{'circle-radius':['interpolate',['linear'],['zoom'],6,3,12,5,17,7],'circle-color':['match',['get','status'],'danger','#dc3549','warning','#ef7d24','watch','#e8b82d','#1faf75'],'circle-stroke-color':'#fff','circle-stroke-width':1.5,'circle-opacity':.98}});map.addSource('focus',{type:'geojson',data:EMPTY});map.addLayer({id:'focus-ring',type:'circle',source:'focus',paint:{'circle-radius':12,'circle-color':'rgba(255,95,145,.2)','circle-stroke-color':'#ff5f91','circle-stroke-width':3}});map.addLayer({id:'focus-dot',type:'circle',source:'focus',paint:{'circle-radius':5,'circle-color':'#ff5f91','circle-stroke-color':'#fff','circle-stroke-width':2}})}
function allRings(f){const g=f?.geometry;if(!g)return[];if(g.type==='Polygon')return g.coordinates||[];if(g.type==='MultiPolygon')return (g.coordinates||[]).flat();return[]}
function countryBorder(geo){const edges=new Map();for(const f of geo.features||[])for(const ring of allRings(f)){for(let i=1;i<ring.length;i++){const a=ring[i-1],b=ring[i],qa=`${a[0].toFixed(4)},${a[1].toFixed(4)}`,qb=`${b[0].toFixed(4)},${b[1].toFixed(4)}`,k=qa<qb?qa+'|'+qb:qb+'|'+qa,e=edges.get(k);if(e)e.n++;else edges.set(k,{n:1,a,b})}}}return{type:'FeatureCollection',features:[...edges.values()].filter(e=>e.n===1).map(e=>({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[e.a,e.b]}}))}}
function districtCenter(f){let minX=999,maxX=-999,minY=999,maxY=-999;for(const ring of allRings(f))for(const p of ring){minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1])}return[(minX+maxX)/2,(minY+maxY)/2]}
function addDistrictMarkers(geo){districtMarkers.forEach(m=>m.remove());districtMarkers=[];for(const f of geo.features||[]){const el=document.createElement('div');el.className='districtLabelGL';el.textContent=f.properties?.nameEn||'';el.dataset.district=f.properties?.nameEn||'';const m=new maplibregl.Marker({element:el,anchor:'center'}).setLngLat(districtCenter(f)).addTo(map);districtMarkers.push(m)}}
async function addDistricts(){const geo=await get('../v24/nepal-districts.geojson',18000);if(!geo?.features?.length)throw Error('district geojson empty');districtGeo=geo;map.addSource('districts',{type:'geojson',data:geo});map.addLayer({id:'district-fill',type:'fill',source:'districts',paint:{'fill-color':'#c8f5ff','fill-opacity':['interpolate',['linear'],['zoom'],5,.10,9,.035]}});map.addLayer({id:'district-hit',type:'fill',source:'districts',paint:{'fill-color':'#fff','fill-opacity':.01}});map.addLayer({id:'district-lines-shadow',type:'line',source:'districts',paint:{'line-color':'rgba(0,18,28,.75)','line-width':['interpolate',['linear'],['zoom'],5,2.1,10,3.0],'line-opacity':.75}});map.addLayer({id:'district-lines',type:'line',source:'districts',paint:{'line-color':'rgba(235,252,255,.98)','line-width':['interpolate',['linear'],['zoom'],5,.8,10,1.6],'line-opacity':.98}});map.addSource('nepal-border',{type:'geojson',data:countryBorder(geo)});map.addLayer({id:'nepal-border-shadow',type:'line',source:'nepal-border',paint:{'line-color':'#001923','line-width':['interpolate',['linear'],['zoom'],5,6,10,9],'line-opacity':.95}});map.addLayer({id:'nepal-border',type:'line',source:'nepal-border',paint:{'line-color':'#38efff','line-width':['interpolate',['linear'],['zoom'],5,2.6,10,4.2],'line-opacity':1}});addDistrictMarkers(geo)}
function wireInteractions(){map.on('click','river-hit',e=>{e.preventDefault();const f=e.features?.[0];if(!f)return;const w=visible.find(x=>routeKey(x)===f.properties?.key);if(!w)return;selected={key:routeKey(w),w};refreshWater();renderSelected();if($('mapHint'))$('mapHint').textContent=tr(`${wname(w)} छानियो • आधिकारिक gauge उपलब्ध भए reading स्वतः refresh हुन्छ`,`Selected ${wname(w)} • official gauge reading auto-refreshes when available`)});map.on('click','gauges',e=>{e.preventDefault();const p=e.features?.[0]?.properties;if(p)showGauge(p)});map.on('click',e=>{if(e.defaultPrevented)return;select(e.lngLat.lat,e.lngLat.lng,true,e.point)});map.on('mouseenter','river-hit',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','river-hit',()=>map.getCanvas().style.cursor='');map.on('mouseenter','gauges',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','gauges',()=>map.getCanvas().style.cursor='')}
function updateLanguage(){const b=$('map3D');if(b)b.textContent=is3D?tr('▱ २D नक्सा','▱ 2D Map'):tr('◈ ३D भू-आकृति','◈ 3D Terrain');if(selected)renderSelected();else if(last&&$('mapHint'))$('mapHint').textContent=tr(`${visible.length} नजिकका नदी/खोला • cyan line वा gauge थिच्नुहोस्`,`${visible.length} nearby rivers/streams • tap a cyan line or gauge`);else if($('mapHint'))showNational()}
async function boot(){const host=$('riverMapGL');if(!host)return;ensureSheet();map=new maplibregl.Map({container:'riverMapGL',center:[84.15,28.1],zoom:5.5,pitch:0,bearing:0,maxZoom:19.5,maxPitch:85,maxBounds:HARD_BOUNDS,antialias:true,attributionControl:true,style:{version:8,sources:{satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Imagery © Esri'},terrain:{type:'raster-dem',tiles:['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],tileSize:256,encoding:'terrarium',minzoom:0,maxzoom:15,attribution:'Terrain © AWS Terrain Tiles'}},layers:[{id:'satellite',type:'raster',source:'satellite'},{id:'hillshade',type:'hillshade',source:'terrain',paint:{'hillshade-exaggeration':.34,'hillshade-shadow-color':'#14242c','hillshade-highlight-color':'#f2fdff','hillshade-accent-color':'#4f7f8e'}}],terrain:{source:'terrain',exaggeration:1.18}}});window.FloodSafeMap={select,choose:select,reset,showNational,get map(){return map},get is3D(){return is3D},get districtCount(){return districtGeo?.features?.length||0},get nationalRiverCount(){return national.length},set3D};map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');map.addControl(new maplibregl.ScaleControl({unit:'metric'}),'bottom-left');map.on('error',e=>console.warn('FloodSafe map source error',e?.error?.message||e?.message||e));map.on('load',async()=>{addCoreLayers();wireInteractions();requestAnimationFrame(animateParticles);try{await addDistricts()}catch(e){console.error('District layer failed',e)}focusNepal(false);const j=await loadWater();if(j)showNational();else if($('mapHint'))$('mapHint').textContent=tr('🇳🇵 नेपाल र जिल्ला boundary तयार छन् • river network load हुन सकेन।','🇳🇵 Nepal and district boundaries are ready • river network could not load.');});$('mapZoomIn')?.addEventListener('click',()=>map.zoomTo(Math.min(19,map.getZoom()+1.7),{duration:350}));$('mapZoomOut')?.addEventListener('click',()=>map.zoomTo(Math.max(4.8,map.getZoom()-1.5),{duration:350}));$('mapReset')?.addEventListener('click',reset);$('map3D')?.addEventListener('click',()=>set3D(!is3D));window.addEventListener('fsriverupdate',()=>{if(last){refreshWater();if(selected)renderSelected()}});window.addEventListener('fslanguage',updateLanguage);window.addEventListener('resize',()=>{if(!last)focusNepal(false)});setInterval(()=>{if(last){refreshWater();if(selected)renderSelected()}},5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
