(()=>{'use strict';
if(window.__fsMapV4)return;window.__fsMapV4=true;
const NS='http://www.w3.org/2000/svg',B={minLon:80,maxLon:88.35,minLat:26.2,maxLat:30.5};
const xy=(lo,la)=>[(lo-B.minLon)/(B.maxLon-B.minLon)*1000,600-(la-B.minLat)/(B.maxLat-B.minLat)*600];
const ll=(x,y)=>[B.minLon+(x/1000)*(B.maxLon-B.minLon),B.maxLat-(y/600)*(B.maxLat-B.minLat)];
const inside=(la,lo)=>Number.isFinite(la)&&Number.isFinite(lo)&&la>=B.minLat&&la<=B.maxLat&&lo>=B.minLon&&lo<=B.maxLon;
let geo=null,token=0,svg=null;
const hint=()=>document.getElementById('mapHint'),detail=()=>document.getElementById('riverDetail');
async function get(u,ms=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(u+(u.includes('?')?'&':'?')+'_mv4='+Date.now(),{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function overpass(endpoint,q,ms=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(endpoint,{method:'POST',cache:'no-store',credentials:'omit',signal:c.signal,headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','Accept':'application/json'},body:'data='+encodeURIComponent(q)});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
function rings(f){const g=f.geometry||{};return g.type==='Polygon'?[g.coordinates?.[0]]:g.type==='MultiPolygon'?g.coordinates.map(p=>p?.[0]):[]}
function ringPath(r){return(r||[]).map((p,i)=>{const[x,y]=xy(p[0],p[1]);return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' ')+' Z'}
function bbox(f){let minLo=99,maxLo=0,minLa=99,maxLa=0;for(const r of rings(f))for(const p of r||[]){minLo=Math.min(minLo,p[0]);maxLo=Math.max(maxLo,p[0]);minLa=Math.min(minLa,p[1]);maxLa=Math.max(maxLa,p[1])}return{minLo,maxLo,minLa,maxLa}}
function center(f){const b=bbox(f);return[(b.minLo+b.maxLo)/2,(b.minLa+b.maxLa)/2]}
const dname=f=>f.properties?.nameEn||f.properties?.DISTRICT||f.properties?.district||'District';
function text(x,y,s,cls){const t=document.createElementNS(NS,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor','middle');t.setAttribute('dominant-baseline','middle');t.setAttribute('class',cls);t.textContent=s;svg.appendChild(t);return t}
function viewNepal(){svg?.setAttribute('viewBox','-50 -35 1100 670')}
function viewPoint(lo,la){const[x,y]=xy(lo,la),w=300,h=190;svg.setAttribute('viewBox',`${Math.max(-35,Math.min(1035-w,x-w/2))} ${Math.max(-25,Math.min(625-h,y-h/2))} ${w} ${h}`)}
function clearDynamic(){svg?.querySelectorAll('.riverV3,.riverLabelV3,.selectedPointV3,.selectedRingV3').forEach(n=>n.remove())}
function drawBase(){if(!svg||!geo)return;svg.innerHTML='';for(const f of geo.features||[]){for(const r of rings(f)){if(!r?.length)continue;const p=document.createElementNS(NS,'path');p.setAttribute('d',ringPath(r));p.setAttribute('class','districtV3');p.dataset.name=dname(f);p.addEventListener('click',e=>{e.stopPropagation();selectAtEvent(e,f)});const ti=document.createElementNS(NS,'title');ti.textContent=dname(f);p.appendChild(ti);svg.appendChild(p)}const c=center(f),q=xy(c[0],c[1]);text(q[0],q[1],dname(f),'districtLabelV3')}viewNepal()}
function riverPath(pts){return pts.map((p,i)=>{const[x,y]=xy(p[0],p[1]);return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' ')}
function marker(lo,la){svg.querySelectorAll('.selectedPointV3,.selectedRingV3').forEach(n=>n.remove());const[x,y]=xy(lo,la),r=document.createElementNS(NS,'circle'),c=document.createElementNS(NS,'circle');r.setAttribute('cx',x);r.setAttribute('cy',y);r.setAttribute('r','12');r.setAttribute('class','selectedRingV3');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r','5');c.setAttribute('class','selectedPointV3');svg.appendChild(r);svg.appendChild(c)}
function drawRivers(els){svg.querySelectorAll('.riverV3,.riverLabelV3').forEach(n=>n.remove());let shown=0,named=0;for(const e of els.slice(0,500)){const pts=(e.geometry||[]).map(g=>[g.lon,g.lat]).filter(p=>inside(p[1],p[0]));if(pts.length<2)continue;const nm=e.tags?.['name:ne']||e.tags?.name||'',type=e.tags?.waterway||'stream',p=document.createElementNS(NS,'path');p.setAttribute('d',riverPath(pts));p.setAttribute('class','riverV3 '+type+(nm?' named':' unnamed'));p.addEventListener('click',ev=>{ev.stopPropagation();if(detail())detail().innerHTML=`<strong>${nm||'नदी / खोला'}</strong><br>${type==='river'?'River':'Stream'} • selected area`});const ti=document.createElementNS(NS,'title');ti.textContent=nm||'River / stream';p.appendChild(ti);svg.appendChild(p);shown++;if(nm&&named<10){const mid=pts[Math.floor(pts.length/2)],q=xy(mid[0],mid[1]);text(q[0],q[1]-3,nm,'riverLabelV3');named++}}return shown}
async function nearby(la,lo,my){for(const radius of [12,20,30]){const dl=radius/111,dlo=radius/(111*Math.max(.2,Math.cos(la*Math.PI/180))),s=Math.max(B.minLat,la-dl),w=Math.max(B.minLon,lo-dlo),n=Math.min(B.maxLat,la+dl),e=Math.min(B.maxLon,lo+dlo),q=`[out:json][timeout:12];(way["waterway"="river"](${s},${w},${n},${e});way["waterway"="stream"](${s},${w},${n},${e}););out tags geom;`;for(const ep of ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter']){try{const j=await overpass(ep,q,13000);if(my!==token)return[];const a=(j?.elements||[]).filter(x=>Array.isArray(x.geometry)&&x.geometry.length>1);if(a.length)return a}catch{}}}return[]}
function eventLonLat(e){const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const m=svg.getScreenCTM();if(!m)return null;const p=pt.matrixTransform(m.inverse());return ll(p.x,p.y)}
async function selectAtEvent(e,f){const pos=eventLonLat(e);if(!pos)return;const[lo,la]=pos;if(!inside(la,lo))return;const my=++token,nm=dname(f);svg.querySelectorAll('.districtV3').forEach(p=>p.classList.toggle('selected',p.dataset.name===nm));clearDynamic();viewPoint(lo,la);marker(lo,la);window.FloodSafe?.setFocus?.(la,lo,'map');if(hint())hint().textContent=`${nm} मा tap गरेको ठाउँको वरिपरिका नदी/खोला खोजिँदैछन्…`;if(detail())detail().innerHTML=`<strong>${nm}</strong><br>Selected area • ${la.toFixed(4)}, ${lo.toFixed(4)}`;const els=await nearby(la,lo,my);if(my!==token)return;const n=drawRivers(els);marker(lo,la);if(hint())hint().textContent=n?`${nm}: tap गरेको ठाउँ वरिपरि ${n} river/stream segments देखाइएका छन्। नीलो रेखा tap गर्नुहोस्।`:`${nm}: tap गरेको ठाउँ वरिपरि river/stream source ले data दिएन। अर्को नजिकको ठाउँ tap गर्नुहोस्।`}
function replaceButton(id,fn){const b=document.getElementById(id);if(!b)return;const c=b.cloneNode(true);b.replaceWith(c);c.addEventListener('click',fn)}
function install(){const old=document.getElementById('riverMap');if(!old)return;old.style.display='none';svg=document.createElementNS(NS,'svg');svg.id='riverMapV3';svg.setAttribute('viewBox','-50 -35 1100 670');svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.setAttribute('role','img');svg.setAttribute('aria-label','नेपाल जिल्ला र नदी नक्सा');old.parentNode.insertBefore(svg,old);replaceButton('mapReset',()=>{token++;drawBase();if(hint())hint().textContent='नक्सामा जुन ठाउँ tap गर्नुहुन्छ, त्यही ठाउँ वरिपरिका नदी/खोला खुल्छन्।'});replaceButton('mapZoomIn',()=>{const v=svg.viewBox.baseVal,cx=v.x+v.width/2,cy=v.y+v.height/2,w=Math.max(150,v.width*.72),h=w*.61;svg.setAttribute('viewBox',`${cx-w/2} ${cy-h/2} ${w} ${h}`)});replaceButton('mapZoomOut',()=>{const v=svg.viewBox.baseVal,cx=v.x+v.width/2,cy=v.y+v.height/2,w=Math.min(1100,v.width*1.38),h=w*.61;svg.setAttribute('viewBox',`${cx-w/2} ${cy-h/2} ${w} ${h}`)})}
async function boot(){install();try{geo=await get('../v24/nepal-districts.geojson',7000);drawBase();if(hint())hint().textContent='नक्सामा area tap गर्नुहोस् — त्यही ठाउँको १२–३० किमि वरिपरिका नदी/खोला खुल्छन्।'}catch{if(hint())hint().textContent='नेपाल जिल्ला नक्सा लोड हुन सकेन।'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();