(()=>{'use strict';
if(window.__fsMapCoreV5)return;window.__fsMapCoreV5=true;
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isEn=()=>((window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne')==='en');
function statusText(p){const s=String(p?.status||'').toLowerCase();if(Number(p?.has_latest)===0)return isEn()?'No official reading':'आधिकारिक पढाइ छैन';if(s==='danger')return isEn()?'Danger':'खतरा';if(s==='warning')return isEn()?'Warning':'चेतावनी';if(s==='watch')return isEn()?'Watch':'सतर्क';return isEn()?'Normal':'सामान्य'}
function fmtTime(t){if(!t)return'—';const d=new Date(t);if(!Number.isFinite(+d))return'—';return new Intl.DateTimeFormat(isEn()?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)+' NPT'}
function ageText(t){const x=+new Date(t||0);if(!x)return isEn()?'No official reading':'आधिकारिक पढाइ छैन';const sec=Math.max(0,Math.floor((Date.now()-x)/1000));if(sec<60)return isEn()?`${sec}s ago`:`${sec} सेकेन्ड अघि`;const m=Math.floor(sec/60);if(m<60)return isEn()?`${m}m ago`:`${m} मिनेट अघि`;const h=Math.floor(m/60);if(h<48)return isEn()?`${h}h ago`:`${h} घण्टा अघि`;const d=Math.floor(h/24);return isEn()?`${d}d ago`:`${d} दिन अघि`}
function ensureUI(){const host=document.querySelector('.mapCanvas');if(!host||document.getElementById('fsMapSimpleStatus'))return;const box=document.createElement('div');box.id='fsMapSimpleStatus';box.innerHTML='<div class="fs-live-title">🌊 नेपाल नदी नक्सा</div><div id="fsMapSimpleCounts">आधिकारिक live data जोडिँदैछ…</div><div class="fs-live-legend"><span>🔵 सामान्य</span><span>🟡 सतर्क</span><span>🟠 चेतावनी</span><span>🔴 खतरा</span><span>⚪ पढाइ छैन</span></div>';host.appendChild(box)}
function updateUI(){ensureUI();const el=document.getElementById('fsMapSimpleCounts');if(!el)return;const s=window.__fsRiverRealtimeState||{},catalog=Number(s.catalogCount||s.catalog||window.FloodSafeMap?.stationCatalogCount||0),latest=Number(s.latestCount||s.latest||window.FloodSafeMap?.latestStationCount||0),src=String(s.source||'');el.textContent=isEn()?`${catalog} official stations • ${latest} latest official readings${src?' • '+src:''}`:`${catalog} आधिकारिक स्टेशन • ${latest} पछिल्लो आधिकारिक पढाइ${src?' • '+src:''}`;try{window.FloodSafeMap?.refreshGauges?.()}catch{}}
function simplePopup(){const map=window.FloodSafeMap?.map;if(!map||map.__fsSimplePopupV5)return;map.__fsSimplePopupV5=true;map.on('click','gauges',e=>{const f=e.features?.[0];if(!f)return;setTimeout(()=>{document.querySelectorAll('.maplibregl-popup').forEach(x=>x.remove());const p=f.properties||{},has=Number(p.has_latest)===1,title=esc(p.name||'River station'),lvl=has&&p.level!==''?`${esc(p.level)} m`:'—',obs=fmtTime(p.time),age=ageText(p.time),state=esc(statusText(p));new window.maplibregl.Popup({maxWidth:'330px',closeButton:true}).setLngLat(e.lngLat).setHTML(`<div class="fs-simple-popup"><div class="fs-popup-title">${title}</div><div class="fs-popup-state">${state}</div><div><b>${isEn()?'Water level':'पानीको सतह'}:</b> ${lvl}</div><div><b>${isEn()?'Latest official reading':'पछिल्लो आधिकारिक पढाइ'}:</b> ${esc(obs)}</div><div class="fs-popup-age">${esc(age)}</div><a href="https://bipadportal.gov.np/realtime/" target="_blank" rel="noopener noreferrer">${isEn()?'Open official BIPAD/DHM source':'आधिकारिक BIPAD/DHM स्रोत खोल्नुहोस्'}</a></div>`).addTo(map)},0)});}
function boot(){ensureUI();const wait=()=>{if(window.FloodSafeMap?.map){simplePopup();updateUI()}else setTimeout(wait,350)};wait();['fstrustedriverupdate','fsriverupdate','fsriverheartbeat','fsgaugesrendered'].forEach(n=>window.addEventListener(n,updateUI));setInterval(updateUI,10000)}
window.FloodSafeMapCoreV4={sync:()=>window.FloodSafeRiverRealtime?.refresh?.(),refresh:updateUI};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
