import * as maplibregl from 'https://unpkg.com/maplibre-gl@6.6.0/dist/maplibre-gl.mjs';

const $=id=>document.getElementById(id);
const NEPAL_BOUNDS=[[80.0,26.2],[88.35,30.5]];
const lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne';
const tr=(ne,en)=>lang()==='en'?en:ne;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
let map=null,water=null,last=null,is3D=true,selected=null,visible=[],particles=[],animFrame=0,lastParticleFrame=0;

function wname(w){return lang()==='en'?(w.name_en||w.name||'Unnamed river or stream'):(w.name_ne||w.name||'नाम नखुलेको नदी वा खोला')}
function routeKey(w){const p=w.pts||[],a=p[0]||[],b=p[p.length-1]||[];return `${w.type||'stream'}|${(w.name||w.name_en||w.name_ne||'').toLowerCase()}|${a[0]?.toFixed?.(4)},${a[1]?.toFixed?.(4)}|${b[0]?.toFixed?.(4)},${b[1]?.toFixed?.(4)}`}
async function get(url,ms=15000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_gl='+Date.now(),{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function loadWater(){if(water)return water;for(const u of['https://raw.githubusercontent.com/Pujan1234-hub/assigment/main/data/nepal-waterways-snapshot.json','https://raw.githubusercontent.com/Pujan1234-hub/assigment/main/data/nepal-waterways-seed.json','../../data/nepal-waterways-snapshot.json','../../data/nepal-waterways-seed.json']){try{const j=await get(u);if(j?.waterways?.length>=100){water=j;return j}}catch{}}return null}
function distanceTo(w,la,lo){let best=1e9;const latPad=.38,lonPad=.46;for(const p of w.pts||[]){if(Math.abs(p[1]-la)>latPad||Math.abs(p[0]-lo)>lonPad)continue;best=Math.min(best,km(la,lo,p[1],p[0]))}return best}
function nearbyWater(la,lo){const a=[],seen=new Set();for(const w of water?.waterways||[]){if(!Array.isArray(w.pts)||w.pts.length<2)continue;const d=distanceTo(w,la,lo);if(d>32)continue;const k=routeKey(w);if(seen.has(k))continue;seen.add(k);a.push({w,d,named:!!(w.name||w.name_en||w.name_ne),river:w.type==='river',len:w.pts.length})}a.sort((x,y)=>x.d-y.d||(y.river-x.river)||(y.named-x.named)||(y.len-x.len));return a.slice(0,26).map(x=>x.w)}
function gaugeFor(w,la,lo){return window.FloodSafeGauge?.forWaterway?.(w,la,lo)||null}
function lineFeatures(ws,la,lo){return ws.map(w=>{const g=gaugeFor(w,la,lo),same=!!g?.sameRiver,key=routeKey(w);return{type:'Feature',geometry:{type:'LineString',coordinates:w.pts},properties:{key,name:wname(w),type:w.type||'stream',status:same?(g.status||'normal'):'unknown',selected:selected?.key===key}}})}
function gaugeFeatures(la,lo){return (window.FloodSafeGauge?.nearby?.(la,lo,65,14)||[]).map(g=>({type:'Feature',geometry:{type:'Point',coordinates:[g.lon,g.lat]},properties:{name:g.name,status:g.status||'normal',statusLabel:g.statusLabel||'',level:g.level??'',warning:g.warning??'',danger:g.danger??'',time:g.time||'',distanceKm:g.distanceKm??0}}))}
function setSource(id,data){const s=map?.getSource(id);if(s)s.setData(data)}
function rebuildParticles(){particles=visible.slice(0,20).filter(w=>w.pts?.length>1).map((w,i)=>({key:routeKey(w),pts:w.pts,offset:(i*.173)%1}))}
function animateParticles(ts){if(map&&ts-lastParticleFrame>130&&map.getSource('flow-particles')){lastParticleFrame=ts;const phase=(ts%5200)/5200,features=[];for(const p of particles){const n=p.pts.length-1,v=((phase+p.offset)%1)*n,i=Math.floor(v),f=v-i,a=p.pts[i],b=p.pts[Math.min(n,i+1)];features.push({type:'Feature',geometry:{type:'Point',coordinates:[a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f]},properties:{key:p.key}})}setSource('flow-particles',{type:'FeatureCollection',features})}animFrame=requestAnimationFrame(animateParticles)}
function statusText(k){return lang()==='en'?({danger:'DANGER',warning:'WARNING',watch:'WATCH',normal:'NORMAL'}[k]||'NO DIRECT GAUGE'):({danger:'खतरा',warning:'चेतावनी',watch:'निगरानी',normal:'सामान्य'}[k]||'प्रत्यक्ष मापन केन्द्र छैन')}
function fmtTime(t){if(!t)return tr('उपलब्ध छैन','Unavailable');try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return String(t)}}
function ensureSheet(){let s=$('riverSheetGL');if(s)return s;s=document.createElement('section');s.id='riverSheetGL';s.className='riverSheetGL';s.hidden=true;s.innerHTML='<button id="riverSheetGLClose" class="riverSheetGLClose" type="button">×</button><div id="riverSheetGLBody"></div>';document.body.appendChild(s);$('riverSheetGLClose').addEventListener('click',()=>{s.hidden=true;selected=null;refreshLines()});return s}
function sheetHtml(w,g){const direct=!!g?.sameRiver,st=g?statusText(g.status):statusText('unknown'),kind=direct?tr('यही नदीको प्रत्यक्ष मापन','LIVE GAUGE ON THIS RIVER'):g?tr('नजिकको आधिकारिक सन्दर्भ मापन','NEAREST OFFICIAL REFERENCE GAUGE'):tr('प्रत्यक्ष मापन उपलब्ध छैन','NO DIRECT GAUGE');return `<div class="sheetEyebrowGL">${tr('छानिएको नदी / खोला','Selected river / stream')}</div><h3>${esc(wname(w))}</h3><div class="sheetStatusGL ${esc(g?.status||'unknown')}">${esc(kind)} • <b>${esc(st)}</b></div><div class="sheetAutoGL">↻ ${tr('DHM/BIPAD मापन हरेक ५ सेकेन्डमा स्वतः जाँचिन्छ','DHM/BIPAD gauge data is checked automatically every 5 seconds')}</div><div class="sheetGridGL"><div><span>${tr('पानीको सतह','Water level')}</span><strong>${g?.level!=null?esc(g.level)+' m':'—'}</strong></div><div><span>${tr('चेतावनी सीमा','Warning level')}</span><strong>${g?.warning!=null?esc(g.warning)+' m':'—'}</strong></div><div><span>${tr('खतरा सीमा','Danger level')}</span><strong>${g?.danger!=null?esc(g.danger)+' m':'—'}</strong></div><div><span>${tr('अवस्था','Status')}</span><strong>${g?esc(st):'—'}</strong></div></div><div class="sheetMetaGL"><p><b>${tr('मापन केन्द्र','Gauge')}:</b> ${g?esc(g.name):tr('उपलब्ध छैन','Unavailable')}${g?` • ${Number(g.distanceKm||0).toFixed(1)} km`:''}</p><p><b>${tr('मापन समय','Measured')}:</b> ${g?esc(fmtTime(g.time)):tr('उपलब्ध छैन','Unavailable')}</p><p><b>${tr('स्रोत','Source')}:</b> ${g?'DHM / BIPAD':'OpenStreetMap river geometry'}</p></div>${g&&!direct?`<div class="sheetWarnGL">${tr('यो reading छानिएको नदीकै होइन; नजिकको आधिकारिक मापन केन्द्रको सन्दर्भ हो।','This reading is not from the selected river; it is the nearest official reference gauge.')}</div>`:''}<div class="sheetNoteGL">${tr('चलिरहेका साना सेता बिन्दु route animation हुन्; आधिकारिक downstream दिशा उपलब्ध नभएसम्म तिनलाई प्रमाणित बहाव-दिशा नमान्नुहोस्।','The small moving white dots are a route animation, not a verified downstream direction unless an official direction source is available.')}</div>`}
function renderSelected(){if(!selected)return;const p=selected.w.pts[Math.floor(selected.w.pts.length/2)],g=gaugeFor(selected.w,p[1],p[0]),s=ensureSheet();$('riverSheetGLBody').innerHTML=sheetHtml(selected.w,g);s.hidden=false}
function showGauge(props){const s=ensureSheet(),st=statusText(props.status);$('riverSheetGLBody').innerHTML=`<div class="sheetEyebrowGL">${tr('आधिकारिक नदी मापन केन्द्र','Official river gauge')}</div><h3>${esc(props.name)}</h3><div class="sheetStatusGL ${esc(props.status)}"><b>${esc(st)}</b></div><div class="sheetAutoGL">↻ ${tr('हरेक ५ सेकेन्डमा स्वतः अद्यावधिक','Auto-updates every 5 seconds')}</div><div class="sheetGridGL"><div><span>${tr('पानीको सतह','Water level')}</span><strong>${props.level!==''?esc(props.level)+' m':'—'}</strong></div><div><span>${tr('चेतावनी सीमा','Warning level')}</span><strong>${props.warning!==''?esc(props.warning)+' m':'—'}</strong></div><div><span>${tr('खतरा सीमा','Danger level')}</span><strong>${props.danger!==''?esc(props.danger)+' m':'—'}</strong></div><div><span>${tr('अवस्था','Status')}</span><strong>${esc(st)}</strong></div></div><div class="sheetMetaGL"><p><b>${tr('मापन समय','Measured')}:</b> ${esc(fmtTime(props.time))}</p><p><b>${tr('स्रोत','Source')}:</b> DHM / BIPAD</p></div>`;s.hidden=false}
function refreshLines(){if(!map||!last)return;const features=lineFeatures(visible,last.la,last.lo);setSource('rivers',{type:'FeatureCollection',features});setSource('gauges',{type:'FeatureCollection',features:gaugeFeatures(last.la,last.lo)});setSource('focus',{type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[last.lo,last.la]},properties:{}}]});rebuildParticles()}
function districtNameAt(point){try{const f=map.queryRenderedFeatures(point,{layers:['district-hit']})[0];return f?.properties?.nameEn||f?.properties?.DISTRICT||f?.properties?.district||''}catch{return''}}
async function select(la,lo,zoomTo=true,point=null){if(!(la>=26.2&&la<=30.5&&lo>=80&&lo<=88.35))return;last={la,lo};selected=null;if($('riverSheetGL'))$('riverSheetGL').hidden=true;if(!water)await loadWater();visible=nearbyWater(la,lo);refreshLines();window.FloodSafe?.setFocus?.(la,lo,'map');if(zoomTo)map.easeTo({center:[lo,la],zoom:Math.max(map.getZoom(),11.6),pitch:is3D?58:0,duration:700});const dn=point?districtNameAt(point):'';if($('mapHint'))$('mapHint').textContent=visible.length?tr(`${dn?dn+' • ':''}${visible.length} नदी/खोला देखिएका छन् • pinch/scroll गरेर अझै zoom गर्नुहोस् • cyan line थिच्नुहोस्`,`${dn?dn+' • ':''}${visible.length} rivers/streams shown • pinch/scroll for deeper zoom • tap a cyan line`):tr('यो ठाउँ वरिपरि नदी/खोला route भेटिएन।','No river/stream route found around this point.')}
function reset(){last=null;selected=null;visible=[];particles=[];setSource('rivers',{type:'FeatureCollection',features:[]});setSource('gauges',{type:'FeatureCollection',features:[]});setSource('focus',{type:'FeatureCollection',features:[]});setSource('flow-particles',{type:'FeatureCollection',features:[]});if($('riverSheetGL'))$('riverSheetGL').hidden=true;map.fitBounds(NEPAL_BOUNDS,{padding:24,pitch:is3D?48:0,duration:700});if($('mapHint'))$('mapHint').textContent=tr('नक्सामा ठाउँ छान्नुहोस् — mouse wheel/pinch ले गहिरो zoom हुन्छ।','Tap a place on the map — use mouse wheel/pinch for deep zoom.')}
function set3D(on){is3D=!!on;try{map.setTerrain(is3D?{source:'terrain',exaggeration:1.25}:null)}catch{}map.easeTo({pitch:is3D?58:0,bearing:is3D?8:0,duration:550});const b=$('map3D');if(b)b.textContent=is3D?tr('▱ २D नक्सा','▱ 2D Map'):tr('◈ ३D भू-आकृति','◈ 3D Terrain');b?.classList.toggle('active',is3D)}
function addCoreLayers(){map.addSource('rivers',{type:'geojson',data:{type:'FeatureCollection',features:[]},lineMetrics:true});map.addLayer({id:'river-hit',type:'line',source:'rivers',paint:{'line-color':'rgba(0,0,0,0)','line-width':22}});map.addLayer({id:'river-base',type:'line',source:'rivers',paint:{'line-color':['case',['==',['get','selected'],true],'#00f0ff',['match',['get','status'],'danger','#ff5366','warning','#ff9d42','watch','#ffd65b','#20ddf4']],'line-width':['interpolate',['linear'],['zoom'],6,1.2,10,2.6,14,4.2,18,6.5],'line-opacity':.96}});map.addLayer({id:'river-glow',type:'line',source:'rivers',paint:{'line-color':'#dffcff','line-width':['interpolate',['linear'],['zoom'],8,.7,13,1.3,18,2.2],'line-opacity':.42,'line-dasharray':[1,5]}});map.addSource('flow-particles',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'flow-particles',type:'circle',source:'flow-particles',paint:{'circle-radius':['interpolate',['linear'],['zoom'],7,1.2,12,2.2,17,3.3],'circle-color':'#ffffff','circle-stroke-color':'#00dff5','circle-stroke-width':1,'circle-opacity':.95}});map.addSource('gauges',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'gauges',type:'circle',source:'gauges',paint:{'circle-radius':['interpolate',['linear'],['zoom'],6,3,12,5,17,7],'circle-color':['match',['get','status'],'danger','#dc3549','warning','#ef7d24','watch','#e8b82d','#1faf75'],'circle-stroke-color':'#fff','circle-stroke-width':1.5,'circle-opacity':.98}});map.addSource('focus',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'focus-ring',type:'circle',source:'focus',paint:{'circle-radius':12,'circle-color':'rgba(255,95,145,.2)','circle-stroke-color':'#ff5f91','circle-stroke-width':3}});map.addLayer({id:'focus-dot',type:'circle',source:'focus',paint:{'circle-radius':5,'circle-color':'#ff5f91','circle-stroke-color':'#fff','circle-stroke-width':2}})}
async function addDistricts(){try{const geo=await get('../v24/nepal-districts.geojson',12000);map.addSource('districts',{type:'geojson',data:geo});map.addLayer({id:'district-hit',type:'fill',source:'districts',paint:{'fill-color':'#fff','fill-opacity':.01}});map.addLayer({id:'district-lines',type:'line',source:'districts',paint:{'line-color':'rgba(240,250,255,.8)','line-width':['interpolate',['linear'],['zoom'],5,.6,12,1.4],'line-opacity':['interpolate',['linear'],['zoom'],5,.75,11,.35]}})}catch{}}
function wireInteractions(){map.on('click','river-hit',e=>{e.preventDefault();const f=e.features?.[0];if(!f)return;const w=visible.find(x=>routeKey(x)===f.properties?.key);if(!w)return;selected={key:routeKey(w),w};refreshLines();renderSelected();if($('mapHint'))$('mapHint').textContent=tr(`${wname(w)} छानियो • gauge data स्वतः अद्यावधिक हुन्छ`,`Selected ${wname(w)} • gauge data updates automatically`)});map.on('click','gauges',e=>{e.preventDefault();const p=e.features?.[0]?.properties;if(p)showGauge(p)});map.on('click',e=>{if(e.defaultPrevented)return;select(e.lngLat.lat,e.lngLat.lng,true,e.point)});map.on('mouseenter','river-hit',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','river-hit',()=>map.getCanvas().style.cursor='');map.on('mouseenter','gauges',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','gauges',()=>map.getCanvas().style.cursor='')}
function updateLanguage(){const b=$('map3D');if(b)b.textContent=is3D?tr('▱ २D नक्सा','▱ 2D Map'):tr('◈ ३D भू-आकृति','◈ 3D Terrain');if(selected)renderSelected();if($('mapHint')&&last)$('mapHint').textContent=tr(`${visible.length} नदी/खोला • cyan line वा रंगीन gauge थिच्नुहोस्`,` ${visible.length} rivers/streams • tap a cyan line or coloured gauge`) }
async function boot(){const host=$('riverMapGL');if(!host)return;ensureSheet();map=new maplibregl.Map({container:'riverMapGL',center:[84.15,28.25],zoom:5.65,pitch:48,bearing:5,maxZoom:19.5,maxPitch:85,antialias:true,attributionControl:true,style:{version:8,sources:{satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Imagery © Esri'},terrain:{type:'raster-dem',url:'https://tiles.mapterhorn.com/tilejson.json',tileSize:256},hillshade:{type:'raster-dem',url:'https://tiles.mapterhorn.com/tilejson.json',tileSize:256}},layers:[{id:'satellite',type:'raster',source:'satellite'},{id:'hillshade',type:'hillshade',source:'hillshade',paint:{'hillshade-exaggeration':.42,'hillshade-shadow-color':'#15252d','hillshade-highlight-color':'#effcff','hillshade-accent-color':'#4a7180'}}]}});map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');map.addControl(new maplibregl.ScaleControl({unit:'metric'}),'bottom-left');map.on('load',async()=>{addCoreLayers();await addDistricts();try{map.setTerrain({source:'terrain',exaggeration:1.25})}catch{}map.fitBounds(NEPAL_BOUNDS,{padding:22,pitch:48,duration:0});wireInteractions();loadWater();if($('mapHint'))$('mapHint').textContent=tr('यो वास्तविक ३D भू-आकृति नक्सा हो • ठाउँ छान्नुहोस् • mouse wheel/pinch ले गहिरो zoom गर्नुहोस्।','This is a real 3D terrain map • select a place • use mouse wheel/pinch for deep zoom.');animFrame=requestAnimationFrame(animateParticles)});$('mapZoomIn')?.addEventListener('click',()=>map.zoomTo(Math.min(19,map.getZoom()+1.7),{duration:350}));$('mapZoomOut')?.addEventListener('click',()=>map.zoomTo(Math.max(4.8,map.getZoom()-1.5),{duration:350}));$('mapReset')?.addEventListener('click',reset);$('map3D')?.addEventListener('click',()=>set3D(!is3D));window.addEventListener('fsriverupdate',()=>{if(last){refreshLines();if(selected)renderSelected()}});window.addEventListener('fslanguage',updateLanguage);setInterval(()=>{if(last){refreshLines();if(selected)renderSelected()}},5000);window.FloodSafeMap={select,choose:select,reset,get map(){return map},get is3D(){return is3D},set3D}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
