(()=>{'use strict';
if(window.__fsMapCoreV4)return;window.__fsMapCoreV4=true;

const API='https://bipadportal.gov.np/api/v1';
const ENDPOINTS={catalog:`${API}/river-stations/?limit=1000`,latest:`${API}/river/?limit=1000`};
const POLL_MS=90*1000;
const MAX_AGE_DISPLAY_MS=365*24*60*60*1000;
let running=false,timer=null,lastOk=0,lastCounts={catalog:0,latest:0,matched:0};

const arr=v=>Array.isArray(v)?v:Array.isArray(v?.results)?v.results:Array.isArray(v?.data)?v.data:Array.isArray(v?.items)?v.items:[];
const val=(o,keys)=>{for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null};
const num=v=>{const n=Number(String(v??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null};
const norm=s=>String(s??'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9\u0900-\u097f]+/g,' ').trim();
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nepXY=(a,b)=>{a=+a;b=+b;if(!Number.isFinite(a)||!Number.isFinite(b))return null;if(a>=79.5&&a<=89&&b>=26&&b<=31)return[a,b];if(b>=79.5&&b<=89&&a>=26&&a<=31)return[b,a];return null};
function coords(o){const c=o?.point?.coordinates||o?.geometry?.coordinates||o?.location?.coordinates||o?.centroid?.coordinates||o?._stationCoordinate;if(Array.isArray(c)&&c.length>=2){const n=nepXY(c[0],c[1]);if(n)return n}const lo=num(val(o,['longitude','lon','lng','stationLongitude','station_longitude'])),la=num(val(o,['latitude','lat','stationLatitude','station_latitude']));return nepXY(lo,la)}
function sid(o){return String(val(o,['stationSeriesId','station_series_id','stationId','station_id','stationIndex','station_index','id'])??'')}
function name(o){return String(val(o,['river_name','riverName','station_name','stationName','title','name'])||o?.station?.name||'')}
function stamp(o){return val(o,['_measurementTime','waterLevelOn','water_level_on','measuredOn','measured_on','measurementTime','observationTime','observedOn','observed_on','dateTime','datetime','createdOn']);}
function level(o){return num(val(o,['waterLevel','water_level','currentWaterLevel','current_water_level','level','value']));}
function matchKey(o){const id=sid(o);if(id)return`id:${id}`;const c=coords(o);return`n:${norm(name(o))}|${c?c.map(x=>x.toFixed(3)).join(','):''}`}
function altKeys(o){const out=new Set([matchKey(o)]),n=norm(name(o)),c=coords(o);if(n)out.add(`name:${n}`);if(c)out.add(`xy:${c[0].toFixed(3)},${c[1].toFixed(3)}`);return [...out]}
function combine(base,live){const c=coords(base)||coords(live);const t=stamp(live)||stamp(base);const l=level(live)??level(base);return {...base,...live,_stationCoordinate:c||base?._stationCoordinate,_measurementTime:t||base?._measurementTime,_lastWaterLevel:l??base?._lastWaterLevel,_measurementTimeTrusted:!!t,_officialLivePage:'https://bipadportal.gov.np/realtime/',dataSource:'BIPAD / DHM'};}
async function getJSON(url){const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'},signal:ctl.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(to)}}
async function fetchAll(url){let next=url,out=[],seen=new Set(),pages=0;while(next&&pages<20){if(seen.has(next))break;seen.add(next);pages++;const j=await getJSON(next),rows=arr(j);out.push(...rows);next=typeof j?.next==='string'&&j.next?j.next:null;if(!next&&rows.length>=1000&&pages===1){break}}return out}
function reconcile(catalog,latest){const idx=new Map();for(const c of catalog){for(const k of altKeys(c))if(!idx.has(k))idx.set(k,c)}const merged=[],used=new Set();for(const l of latest){let c=null;for(const k of altKeys(l)){if(idx.has(k)){c=idx.get(k);break}}const m=combine(c||{},l);merged.push(m);used.add(matchKey(c||l))}const all=catalog.map(c=>{const k=matchKey(c);const live=merged.find(x=>matchKey(x)===k);return live||combine(c,{})});return{all,latest:merged,matched:used.size}}
function publish(data){const S=window.FloodSafe?.state;if(!S)return false;S.allRiverStations=data.all;S.latestRiverStations=data.latest;S.stations=data.latest;window.__fsRiverRealtimeState={...(window.__fsRiverRealtimeState||{}),catalog:data.all.length,current:data.latest.length,latest:data.latest.length,matched:data.matched,catalogWithCoordinates:data.all.filter(x=>!!coords(x)).length,lastOfficialSync:new Date().toISOString(),source:'BIPAD / DHM direct'};lastCounts={catalog:data.all.length,latest:data.latest.length,matched:data.matched};lastOk=Date.now();try{window.FloodSafeMap?.refreshGauges?.()}catch{}window.dispatchEvent(new CustomEvent('fsriverrealtime',{detail:window.__fsRiverRealtimeState}));window.dispatchEvent(new CustomEvent('fsriverdatachange',{detail:window.__fsRiverRealtimeState}));updateSimpleUI();return true}
function statusText(p){const s=String(p?.status||'').toLowerCase();if(s==='danger')return['खतरा','Danger'];if(s==='warning')return['चेतावनी','Warning'];if(s==='watch')return['सतर्क','Watch'];if(Number(p?.has_latest)===0)return['पढाइ छैन','No reading'];return['सामान्य','Normal']}
function fmtTime(t){if(!t)return'—';const d=new Date(t);if(!Number.isFinite(+d))return'—';return new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kathmandu',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)+' NPT'}
function ensureSimpleUI(){const host=document.querySelector('.mapCanvas');if(!host||document.getElementById('fsMapSimpleStatus'))return;const box=document.createElement('div');box.id='fsMapSimpleStatus';box.style.cssText='position:absolute;left:12px;top:12px;z-index:7;max-width:min(360px,calc(100% - 24px));background:rgba(4,24,32,.88);color:#fff;padding:10px 12px;border-radius:14px;box-shadow:0 6px 22px rgba(0,0,0,.24);backdrop-filter:blur(8px);font:600 12px/1.35 system-ui';box.innerHTML='<div style="font-size:14px;margin-bottom:5px">🌊 नेपाल नदी Live Map</div><div id="fsMapSimpleCounts" style="opacity:.9">Official data जोडिँदैछ…</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:7px;font-weight:700"><span>🔵 सामान्य</span><span>🟡 सतर्क</span><span>🟠 चेतावनी</span><span>🔴 खतरा</span><span>⚪ पढाइ छैन</span></div>';host.appendChild(box)}
function updateSimpleUI(){ensureSimpleUI();const el=document.getElementById('fsMapSimpleCounts');if(!el)return;const age=lastOk?Math.max(0,Math.round((Date.now()-lastOk)/1000)):null;el.textContent=`${lastCounts.catalog} official station • ${lastCounts.latest} latest reading • ${age===null?'syncing':age+'s ago'}`;}
function simplifyPopup(){const map=window.FloodSafeMap?.map;if(!map||map.__fsSimplePopupV4)return;map.__fsSimplePopupV4=true;map.on('click','gauges',e=>{const f=e.features?.[0];if(!f)return;setTimeout(()=>{document.querySelectorAll('.maplibregl-popup').forEach(x=>x.remove());const p=f.properties||{},st=statusText(p),isEn=(window.FloodSafe?.state?.lang||'ne')==='en';const title=esc(p.name||'River station'),state=esc(st[isEn?1:0]),lvl=p.level!==''?`${esc(p.level)} m`:'—',obs=esc(fmtTime(p.time)),src='https://bipadportal.gov.np/realtime/';new window.maplibregl.Popup({maxWidth:'320px',closeButton:true}).setLngLat(e.lngLat).setHTML(`<div style="font:500 14px/1.45 system-ui;min-width:220px"><b style="font-size:16px">${title}</b><div style="margin:7px 0;font-size:15px"><strong>${state}</strong></div><div>${isEn?'Water level':'पानीको सतह'}: <b>${lvl}</b></div><div>${isEn?'Official time':'आधिकारिक समय'}: <b>${obs}</b></div><div style="margin-top:8px"><a href="${src}" target="_blank" rel="noopener">${isEn?'Open official BIPAD source':'आधिकारिक BIPAD स्रोत खोल्नुहोस्'}</a></div></div>`).addTo(map)},0)});}
async function sync(){if(running)return;running=true;try{const [catalog,latest]=await Promise.all([fetchAll(ENDPOINTS.catalog),fetchAll(ENDPOINTS.latest)]);if(!catalog.length)throw Error('official station catalogue empty');publish(reconcile(catalog,latest));}catch(err){console.warn('FloodSafe map official sync v4:',err);updateSimpleUI()}finally{running=false}}
function start(){ensureSimpleUI();const wait=()=>{if(window.FloodSafe?.state&&window.FloodSafeMap?.map){simplifyPopup();sync();if(timer)clearInterval(timer);timer=setInterval(sync,POLL_MS);setInterval(updateSimpleUI,10000)}else setTimeout(wait,500)};wait()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
window.FloodSafeMapCoreV4={sync,get lastCounts(){return{...lastCounts}},get lastOfficialSync(){return lastOk?new Date(lastOk).toISOString():null}};
})();
