(()=>{'use strict';
if(window.__fsMapFixV1)return;window.__fsMapFixV1=true;
const NS='http://www.w3.org/2000/svg',B={minLon:80,maxLon:88.35,minLat:26.2,maxLat:30.5},svg=()=>document.getElementById('riverMap'),hint=()=>document.getElementById('mapHint'),detail=()=>document.getElementById('riverDetail');
const xy=(lo,la)=>[(lo-B.minLon)/(B.maxLon-B.minLon)*1000,600-(la-B.minLat)/(B.maxLat-B.minLat)*600];
const inside=(la,lo)=>la>=B.minLat&&la<=B.maxLat&&lo>=B.minLon&&lo<=B.maxLon;
async function get(u,ms=9000){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(u+(u.includes('?')?'&':'?')+'_mf='+Date.now(),{cache:'no-store',signal:c.signal,credentials:'omit'});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
function districtCenter(f){const g=f.geometry||{},rings=g.type==='Polygon'?[g.coordinates?.[0]]:g.type==='MultiPolygon'?g.coordinates.map(p=>p?.[0]):[];let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const ring of rings)for(const p of ring||[]){if(!p)continue;minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1])}return Number.isFinite(minX)?[(minX+maxX)/2,(minY+maxY)/2]:null}
function addLabels(geo){const s=svg();if(!s)return;s.querySelectorAll('.districtLabel').forEach(n=>n.remove());for(const f of geo.features||[]){const c=districtCenter(f);if(!c)continue;const [x,y]=xy(c[0],c[1]),t=document.createElementNS(NS,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor','middle');t.setAttribute('dominant-baseline','middle');t.setAttribute('class','districtLabel');t.textContent=f.properties?.nameEn||f.properties?.DISTRICT||'';s.appendChild(t)}}
function paddedView(){const s=svg();if(s)s.setAttribute('viewBox','-28 -20 1056 640')}
function focusView(lo,la){const s=svg();if(!s)return;const[x,y]=xy(lo,la),w=470,h=300,minX=-25,maxX=1025-w,minY=-20,maxY=620-h;s.setAttribute('viewBox',`${Math.max(minX,Math.min(maxX,x-w/2))} ${Math.max(minY,Math.min(maxY,y-h/2))} ${w} ${h}`)}
function clearSmart(){svg()?.querySelectorAll('.riverSmart,.riverSmartLabel').forEach(n=>n.remove())}
function smartPath(pts){return pts.map((p,i)=>{const[x,y]=xy(p[0],p[1]);return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' ')}
async function queryRivers(la,lo){clearSmart();if(hint())hint().textContent='छानिएको क्षेत्रका नदी/खोला खोजिँदैछ…';const attempts=[{r:12,named:true},{r:12,named:false},{r:7,named:false}];let els=[];for(const a of attempts){const dl=a.r/111,dlo=a.r/(111*Math.cos(la*Math.PI/180)),south=Math.max(B.minLat,la-dl),west=Math.max(B.minLon,lo-dlo),north=Math.min(B.maxLat,la+dl),east=Math.min(B.maxLon,lo+dlo),filter=a.named?'[name]':'',q=`[out:json][timeout:10];way["waterway"~"river|stream"]${filter}(${south},${west},${north},${east});out tags geom;`;for(const ep of ['https://overpass-api.de/api/interpreter?data=','https://overpass.kumi.systems/api/interpreter?data=']){try{const j=await get(ep+encodeURIComponent(q),11000);els=(j?.elements||[]).filter(e=>Array.isArray(e.geometry)&&e.geometry.length>1);if(els.length)break}catch{}}if(els.length)break}
const s=svg();if(!s)return;if(!els.length){if(hint())hint().textContent='यो area मा river geometry अहिले भेटिएन। अर्को नजिकको area छान्नुहोस्।';return}const rivers=els.slice(0,180).map(e=>({name:e.tags?.['name:ne']||e.tags?.name||'',type:e.tags?.waterway||'stream',pts:e.geometry.map(g=>[g.lon,g.lat]).filter(p=>inside(p[1],p[0]))})).filter(r=>r.pts.length>1);for(const r of rivers){const p=document.createElementNS(NS,'path');p.setAttribute('d',smartPath(r.pts));p.setAttribute('class','riverSmart '+r.type);p.addEventListener('click',e=>{e.stopPropagation();if(detail())detail().innerHTML=`<strong>${r.name||'नदी / खोला'}</strong><br>${r.type==='river'?'River':'Stream'} • selected area`});const ti=document.createElementNS(NS,'title');ti.textContent=r.name||'River / stream';p.appendChild(ti);s.appendChild(p)}if(hint())hint().textContent=`${rivers.length} नदी/खोला देखाइएका छन्। नदीमा tap गर्दा detail खुल्छ।`}
async function boot(){let geo=null;try{geo=await get('../v24/nepal-districts.geojson',7000);setTimeout(()=>addLabels(geo),400)}catch{}paddedView();const s=svg();if(!s)return;const obs=new MutationObserver(()=>{if(geo&&!s.querySelector('.districtLabel'))setTimeout(()=>addLabels(geo),0)});obs.observe(s,{childList:true});s.addEventListener('click',e=>{if(e.target.closest?.('.riverSmart,.gauge'))return;const pt=s.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const m=s.getScreenCTM();if(!m)return;const p=pt.matrixTransform(m.inverse()),lo=B.minLon+(p.x/1000)*(B.maxLon-B.minLon),la=B.maxLat-(p.y/600)*(B.maxLat-B.minLat);if(!inside(la,lo))return;setTimeout(()=>focusView(lo,la),0);queryRivers(la,lo)},true);document.getElementById('mapReset')?.addEventListener('click',()=>setTimeout(paddedView,0));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();