import * as maplibregl from 'https://unpkg.com/maplibre-gl@6.6.0/dist/maplibre-gl.mjs';

const $=id=>document.getElementById(id);
const NEPAL_BOUNDS=[[80.0,26.2],[88.35,30.5]];
const HARD_BOUNDS=[[79.2,25.4],[89.15,31.15]];
const EMPTY=()=>({type:'FeatureCollection',features:[]});
const lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne';
const tr=(ne,en)=>lang()==='en'?en:ne;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
let map,water,districtGeo,last=null,selected=null,is3D=true,visible=[],national=[],particles=[],districtMarkers=[],initialized=false,lastParticleFrame=0;

function wname(w){return lang()==='en'?(w.name_en||w.name||'Unnamed river / stream'):(w.name_ne||w.name||'नाम नखुलेको नदी / खोला')}
function routeKey(w){const p=w.pts||[],a=p[0]||[],b=p[p.length-1]||[];return `${w.type||'stream'}|${(w.name||w.name_en||w.name_ne||'').toLowerCase()}|${Number(a[0]||0).toFixed(4)},${Number(a[1]||0).toFixed(4)}|${Number(b[0]||0).toFixed(4)},${Number(b[1]||0).toFixed(4)}`}
async function getJSON(url,ms=20000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_v4='+Date.now(),{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(`${r.status} ${url}`);return await r.json()}finally{clearTimeout(t)}}
async function loadWater(){if(water)return water;const urls=['https://raw.githubusercontent.com/Pujan1234-hub/assigment/main/data/nepal-waterways-snapshot.json','https://raw.githubusercontent.com/Pujan1234-hub/assigment/main/data/nepal-waterways-seed.json','../../data/nepal-waterways-snapshot.json','../../data/nepal-waterways-seed.json'];for(const u of urls){try{const j=await getJSON(u,28000);if(j?.waterways?.length>=100){water=j;return j}}catch(e){console.warn('water source',e.message)}}return null}
function distanceTo(w,la,lo){let best=1e9;for(const p of w.pts||[]){if(!Array.isArray(p)||p.length<2)continue;if(Math.abs(p[1]-la)>.45||Math.abs(p[0]-lo)>.55)continue;best=Math.min(best,km(la,lo,p[1],p[0]))}return best}
function nearbyWater(la,lo){const a=[],seen=new Set();for(const w of water?.waterways||[]){if(!Array.isArray(w.pts)||w.pts.length<2)continue;const d=distanceTo(w,la,lo);if(d>34)continue;const k=routeKey(w);if(seen.has(k))continue;seen.add(k);a.push({w,d,score:(w.type==='river'?80:0)+((w.name||w.name_en||w.name_ne)?40:0)+Math.min(50,w.pts.length)})}a.sort((x,y)=>x.d-y.d||y.score-x.score);return a.slice(0,48).map(x=>x.w)}
function nationalWater(){const a=[],seen=new Set();for(const w of water?.waterways||[]){if(!Array.isArray(w.pts)||w.pts.length<2)continue;const named=!!(w.name||w.name_en||w.name_ne),river=w.type==='river';if(!river&&!named)continue;const k=routeKey(w);if(seen.has(k))continue;seen.add(k);let minX=999,maxX=-999,minY=999,maxY=-999;for(const p of w.pts){if(!Array.isArray(p)||p.length<2)continue;minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1])}const span=(maxX-minX)+(maxY-minY),score=(river?160:0)+(named?70:0)+Math.min(90,w.pts.length*2)+Math.min(90,span*140);a.push({w,score})}a.sort((x,y)=>y.score-x.score);return a.slice(0,1400).map(x=>x.w)}
function gaugeFor(w,la,lo){return window.FloodSafeGauge?.forWaterway?.(w,la,lo)||null}
function riverFC(ws,withGauge=false){return{type:'FeatureCollection',features:ws.map(w=>{const g=withGauge&&last?gaugeFor(w,last.la,last.lo):null,key=routeKey(w);return{type:'Feature',geometry:{type:'LineString',coordinates:w.pts},properties:{key,name:wname(w),status:g?.sameRiver?(g.status||'normal'):'unknown',selected:selected?.key===key}}})}}
function gaugeFC(){if(!last)return EMPTY();return{type:'FeatureCollection',features:(window.FloodSafeGauge?.nearby?.(last.la,last.lo,70,16)||[]).map(g=>({type:'Feature',geometry:{type:'Point',coordinates:[g.lon,g.lat]},properties:{name:g.name,status:g.status||'normal',level:g.level??'',warning:g.warning??'',danger:g.danger??'',time:g.time||'',distanceKm:g.distanceKm??0}}))}}
function setData(id,data){map?.getSource(id)?.setData(data)}
function rebuildParticles(){particles=visible.slice(0,last?30:40).filter(w=>w.pts?.length>1).map((w,i)=>({pts:w.pts,off:(i*.173)%1}))}
function animate(ts){if(map&&ts-lastParticleFrame>150&&map.getSource('flow-particles')){lastParticleFrame=ts;const phase=(ts%6000)/6000,features=[];for(const p of particles){const n=p.pts.length-1,v=((phase+p.off)%1)*n,i=Math.floor(v),f=v-i,a=p.pts[i],b=p.pts[Math.min(n,i+1)];features.push({type:'Feature',geometry:{type:'Point',coordinates:[a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f]},properties:{}})}setData('flow-particles',{type:'FeatureCollection',features})}requestAnimationFrame(animate)}
function refreshWater(){if(!map?.getSource('rivers'))return;setData('rivers',riverFC(visible,!!last));setData('gauges',gaugeFC());setData('focus',last?{type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[last.lo,last.la]},properties:{}}]}:EMPTY());rebuildParticles()}
function statusText(s){return lang()==='en'?({danger:'DANGER',warning:'WARNING',watch:'WATCH',normal:'NORMAL'}[s]||'NO DIRECT GAUGE'):({danger:'खतरा',warning:'चेतावनी',watch:'निगरानी',normal:'सामान्य'}[s]||'प्रत्यक्ष मापन छैन')}
function fmtTime(t){if(!t)return tr('उपलब्ध छैन','Unavailable');try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return String(t)}}
function ensureSheet(){let s=$('riverSheetGL');if(s)return s;s=document.createElement('section');s.id='riverSheetGL';s.className='riverSheetGL';s.hidden=true;s.innerHTML='<button id="riverSheetGLClose" class="riverSheetGLClose" type="button">×</button><div id="riverSheetGLBody"></div>';document.body.appendChild(s);$('riverSheetGLClose').onclick=()=>{s.hidden=true;selected=null;refreshWater()};return s}
function selectedHTML(w,g){const direct=!!g?.sameRiver,st=statusText(g?.status),source=g?'DHM / BIPAD':'OpenStreetMap river geometry';return `<div class="sheetEyebrowGL">${tr('छानिएको नदी / खोला','Selected river / stream')}</div><h3>${esc(wname(w))}</h3><div class="sheetStatusGL ${esc(g?.status||'unknown')}"><b>${esc(direct?st:g?tr('नजिकको gauge सन्दर्भ','NEAREST GAUGE REFERENCE'):st)}</b></div><div class="sheetAutoGL">↻ ${tr('आधिकारिक gauge data हरेक ५ सेकेन्डमा जाँचिन्छ','Official gauge data is checked every 5 seconds')}</div><div class="sheetGridGL"><div><span>${tr('पानीको सतह','Water level')}</span><strong>${g?.level!=null?esc(g.level)+' m':'—'}</strong></div><div><span>${tr('चेतावनी सीमा','Warning level')}</span><strong>${g?.warning!=null?esc(g.warning)+' m':'—'}</strong></div><div><span>${tr('खतरा सीमा','Danger level')}</span><strong>${g?.danger!=null?esc(g.danger)+' m':'—'}</strong></div><div><span>${tr('अवस्था','Status')}</span><strong>${g?esc(st):'—'}</strong></div></div><div class="sheetMetaGL"><p><b>${tr('मापन केन्द्र','Gauge')}:</b> ${g?esc(g.name):tr('उपलब्ध छैन','Unavailable')}${g?` • ${Number(g.distanceKm||0).toFixed(1)} km`:''}</p><p><b>${tr('मापन समय','Measured')}:</b> ${g?esc(fmtTime(g.time)):tr('उपलब्ध छैन','Unavailable')}</p><p><b>${tr('स्रोत','Source')}:</b> ${esc(source)}</p></div>${g&&!direct?`<div class="sheetWarnGL">${tr('यो reading छानिएको नदीकै प्रत्यक्ष reading होइन; नजिकको आधिकारिक gauge सन्दर्भ हो।','This is a nearby official gauge reference, not a direct reading from the selected river.')}</div>`:''}`}
function renderSelected(){if(!selected)return;const w=selected.w,p=w.pts[Math.floor(w.pts.length/2)],g=gaugeFor(w,p[1],p[0]),s=ensureSheet();$('riverSheetGLBody').innerHTML=selectedHTML(w,g);s.hidden=false}
function showGauge(p){const s=ensureSheet(),st=statusText(p.status);$('riverSheetGLBody').innerHTML=`<div class="sheetEyebrowGL">${tr('आधिकारिक नदी मापन केन्द्र','Official river gauge')}</div><h3>${esc(p.name)}</h3><div class="sheetStatusGL ${esc(p.status)}"><b>${esc(st)}</b></div><div class="sheetAutoGL">↻ ${tr('हरेक ५ सेकेन्डमा स्वतः जाँच','Checked automatically every 5 seconds')}</div><div class="sheetGridGL"><div><span>${tr('पानीको सतह','Water level')}</span><strong>${p.level!==''?esc(p.level)+' m':'—'}</strong></div><div><span>${tr('चेतावनी सीमा','Warning level')}</span><strong>${p.warning!==''?esc(p.warning)+' m':'—'}</strong></div><div><span>${tr('खतरा सीमा','Danger level')}</span><strong>${p.danger!==''?esc(p.danger)+' m':'—'}</strong></div><div><span>${tr('अवस्था','Status')}</span><strong>${esc(st)}</strong></div></div><div class="sheetMetaGL"><p><b>${tr('मापन समय','Measured')}:</b> ${esc(fmtTime(p.time))}</p><p><b>${tr('स्रोत','Source')}:</b> DHM / BIPAD</p></div>`;s.hidden=false}
function polygonRings(f){const g=f?.geometry;if(!g)return[];if(g.type==='Polygon')return[g.coordinates?.[0]].filter(Boolean);if(g.type==='MultiPolygon')return(g.coordinates||[]).map(p=>p?.[0]).filter(Boolean);return[]}
function maskFromDistricts(geo){const outer=[[79.1,25.3],[89.25,25.3],[89.25,31.25],[79.1,31.25],[79.1,25.3]],holes=[];for(const f of geo.features||[])for(const r of polygonRings(f))holes.push(r);return{type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[outer,...holes]}}}
function outerBorder(geo){const edges=new Map();for(const f of geo.features||[]){for(const ring of polygonRings(f)){for(let i=1;i<ring.length;i++){const a=ring[i-1],b=ring[i];if(!a||!b)continue;const qa=`${Number(a[0]).toFixed(4)},${Number(a[1]).toFixed(4)}`,qb=`${Number(b[0]).toFixed(4)},${Number(b[1]).toFixed(4)}`,key=qa<qb?qa+'|'+qb:qb+'|'+qa;if(edges.has(key))edges.get(key).n++;else edges.set(key,{n:1,a,b})}}}return{type:'FeatureCollection',features:[...edges.values()].filter(e=>e.n===1).map(e=>({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[e.a,e.b]}}))}}
function centerOf(f){let minX=999,maxX=-999,minY=999,maxY=-999;for(const r of polygonRings(f))for(const p of r){minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1])}return[(minX+maxX)/2,(minY+maxY)/2]}
function addDistrictLabels(geo){districtMarkers.forEach(m=>m.remove());districtMarkers=[];for(const f of geo.features||[]){const el=document.createElement('div');el.className='districtLabelGL';el.textContent=f.properties?.nameEn||'';const m=new maplibregl.Marker({element:el,anchor:'center'}).setLngLat(centerOf(f)).addTo(map);districtMarkers.push(m)}}
async function addDistricts(){const geo=await getJSON('../v24/nepal-districts.geojson',20000);if(!geo?.features?.length)throw Error('district file empty');districtGeo=geo;map.addSource('districts',{type:'geojson',data:geo});map.addSource('nepal-mask',{type:'geojson',data:maskFromDistricts(geo)});map.addSource('nepal-border',{type:'geojson',data:outerBorder(geo)});map.addLayer({id:'nepal-mask',type:'fill',source:'nepal-mask',paint:{'fill-color':'#06141c','fill-opacity':.50}});map.addLayer({id:'district-fill',type:'fill',source:'districts',paint:{'fill-color':'#8deeff','fill-opacity':['interpolate',['linear'],['zoom'],5,.09,10,.025]}});map.addLayer({id:'district-hit',type:'fill',source:'districts',paint:{'fill-color':'#fff','fill-opacity':.01}});map.addLayer({id:'district-lines-shadow',type:'line',source:'districts',paint:{'line-color':'#00151e','line-width':['interpolate',['linear'],['zoom'],5,2.2,11,3.4],'line-opacity':.9}});map.addLayer({id:'district-lines',type:'line',source:'districts',paint:{'line-color':'#f1fdff','line-width':['interpolate',['linear'],['zoom'],5,.8,11,1.5],'line-opacity':.96}});map.addLayer({id:'nepal-border-shadow',type:'line',source:'nepal-border',paint:{'line-color':'#00131c','line-width':['interpolate',['linear'],['zoom'],5,6,11,10],'line-opacity':1}});map.addLayer({id:'nepal-border',type:'line',source:'nepal-border',paint:{'line-color':'#21edff','line-width':['interpolate',['linear'],['zoom'],5,2.8,11,4.6],'line-opacity':1}});addDistrictLabels(geo)}
function addRiverLayers(){map.addSource('rivers',{type:'geojson',data:EMPTY(),lineMetrics:true});map.addLayer({id:'river-hit',type:'line',source:'rivers',paint:{'line-color':'rgba(0,0,0,0)','line-width':24}});map.addLayer({id:'river-shadow',type:'line',source:'rivers',paint:{'line-color':'#003a4b','line-width':['interpolate',['linear'],['zoom'],5,2.6,11,5.4,17,8.5],'line-opacity':.8}});map.addLayer({id:'river-base',type:'line',source:'rivers',paint:{'line-color':['case',['==',['get','selected'],true],'#ffffff',['match',['get','status'],'danger','#ff5366','warning','#ff9d42','watch','#ffd65b','#22e7ff']],'line-width':['interpolate',['linear'],['zoom'],5,1.15,8,1.9,12,3.3,17,5.6],'line-opacity':.98}});map.addSource('flow-particles',{type:'geojson',data:EMPTY()});map.addLayer({id:'flow-particles',type:'circle',source:'flow-particles',paint:{'circle-radius':['interpolate',['linear'],['zoom'],5,.7,12,2,17,3.1],'circle-color':'#fff','circle-stroke-color':'#00dff5','circle-stroke-width':.8,'circle-opacity':.9}});map.addSource('gauges',{type:'geojson',data:EMPTY()});map.addLayer({id:'gauges',type:'circle',source:'gauges',paint:{'circle-radius':['interpolate',['linear'],['zoom'],6,3,12,5,17,7],'circle-color':['match',['get','status'],'danger','#dc3549','warning','#ef7d24','watch','#e8b82d','#1faf75'],'circle-stroke-color':'#fff','circle-stroke-width':1.5}});map.addSource('focus',{type:'geojson',data:EMPTY()});map.addLayer({id:'focus-ring',type:'circle',source:'focus',paint:{'circle-radius':12,'circle-color':'rgba(255,95,145,.2)','circle-stroke-color':'#ff5f91','circle-stroke-width':3}});map.addLayer({id:'focus-dot',type:'circle',source:'focus',paint:{'circle-radius':5,'circle-color':'#ff5f91','circle-stroke-color':'#fff','circle-stroke-width':2}})}
function districtAt(point){try{return map.queryRenderedFeatures(point,{layers:['district-hit']})[0]?.properties?.nameEn||''}catch{return''}}
function wire(){map.on('click','river-hit',e=>{e.preventDefault();const f=e.features?.[0],w=visible.find(x=>routeKey(x)===f?.properties?.key);if(!w)return;selected={key:routeKey(w),w};refreshWater();renderSelected()});map.on('click','gauges',e=>{e.preventDefault();const p=e.features?.[0]?.properties;if(p)showGauge(p)});map.on('click',e=>{if(e.defaultPrevented)return;select(e.lngLat.lat,e.lngLat.lng,true,e.point)});for(const layer of ['river-hit','gauges']){map.on('mouseenter',layer,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',layer,()=>map.getCanvas().style.cursor='')}}
function focusNepal(animated=false){map.fitBounds(NEPAL_BOUNDS,{padding:window.innerWidth<620?14:32,pitch:0,bearing:0,duration:0});const z=Math.max(4.85,map.getZoom()-(window.innerWidth<620?.12:.28));map.easeTo({center:[84.15,28.1],zoom:z,pitch:is3D?(window.innerWidth<620?24:34):0,bearing:0,duration:animated?650:0})}
function showNational(){last=null;selected=null;ensureSheet().hidden=true;national=national.length?national:nationalWater();visible=national;refreshWater();$('mapHint').textContent=national.length?tr(`🇳🇵 नेपाल • ७७ जिल्ला • ${national.length} मुख्य/नाम भएका नदी–खोला • ठाउँ थिच्दा local detail`,`🇳🇵 Nepal • 77 districts • ${national.length} major/named river routes • tap a place for local detail`):tr('नेपाल र जिल्ला तयार छन्; नदी data उपलब्ध भएन।','Nepal and districts are ready; river data unavailable.')}
async function select(la,lo,zoomTo=true,point=null){if(!(la>=26.2&&la<=30.5&&lo>=80&&lo<=88.35))return;if(!water)await loadWater();last={la,lo};selected=null;ensureSheet().hidden=true;visible=nearbyWater(la,lo);refreshWater();window.FloodSafe?.setFocus?.(la,lo,'map');if(zoomTo)map.easeTo({center:[lo,la],zoom:Math.max(map.getZoom(),11.7),pitch:is3D?55:0,bearing:0,duration:700});const d=point?districtAt(point):'';$('mapHint').textContent=visible.length?tr(`${d?d+' • ':''}${visible.length} नजिकका नदी/खोला • cyan line वा gauge थिच्नुहोस्`,`${d?d+' • ':''}${visible.length} nearby rivers/streams • tap a cyan line or gauge`):tr('यो ठाउँ नजिक local river route भेटिएन; 🇳🇵 नेपाल थिचेर national network हेर्नुहोस्।','No local river route found here; press 🇳🇵 Nepal for the national network.')}
async function reset(){focusNepal(true);if(!water)await loadWater();showNational()}
function set3D(on){is3D=!!on;try{map.setTerrain(is3D?{source:'terrain',exaggeration:1.18}:null)}catch{}map.easeTo({pitch:is3D?(window.innerWidth<620?28:45):0,bearing:0,duration:550});const b=$('map3D');if(b)b.textContent=is3D?tr('▱ २D नक्सा','▱ 2D Map'):tr('◈ ३D भू-आकृति','◈ 3D Terrain');b?.classList.toggle('active',is3D)}
function updateLanguage(){const b=$('map3D');if(b)b.textContent=is3D?tr('▱ २D नक्सा','▱ 2D Map'):tr('◈ ३D भू-आकृति','◈ 3D Terrain');if(selected)renderSelected();else if(last)$('mapHint').textContent=tr(`${visible.length} नजिकका नदी/खोला • cyan line वा gauge थिच्नुहोस्`,`${visible.length} nearby rivers/streams • tap a cyan line or gauge`);else showNational()}
async function initLayers(){if(initialized||!map?.isStyleLoaded?.())return;initialized=true;addRiverLayers();wire();requestAnimationFrame(animate);focusNepal(false);try{await addDistricts()}catch(e){console.error('district init failed',e);$('mapHint').textContent=tr('जिल्ला data load हुन सकेन।','District data could not load.')}const j=await loadWater();if(j)showNational();else $('mapHint').textContent=tr('नेपालका जिल्ला देखिएका छन्; river network load हुन सकेन।','Nepal districts are visible; river network could not load.')}
function boot(){const host=$('riverMapGL');if(!host)return;ensureSheet();map=new maplibregl.Map({container:'riverMapGL',center:[84.15,28.1],zoom:5.4,pitch:0,bearing:0,maxZoom:19.5,maxPitch:85,maxBounds:HARD_BOUNDS,antialias:true,attributionControl:true,style:{version:8,sources:{satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Imagery © Esri'},terrain:{type:'raster-dem',tiles:['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],tileSize:256,encoding:'terrarium',minzoom:0,maxzoom:15,attribution:'Terrain © AWS Terrain Tiles'}},layers:[{id:'satellite',type:'raster',source:'satellite'},{id:'hillshade',type:'hillshade',source:'terrain',paint:{'hillshade-exaggeration':.30,'hillshade-shadow-color':'#14242c','hillshade-highlight-color':'#f2fdff','hillshade-accent-color':'#4f7f8e'}}],terrain:{source:'terrain',exaggeration:1.18}}});window.FloodSafeMap={select,choose:select,reset,showNational,set3D,get map(){return map},get is3D(){return is3D},get districtCount(){return districtGeo?.features?.length||0},get nationalRiverCount(){return national.length},get initialized(){return initialized}};map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');map.addControl(new maplibregl.ScaleControl({unit:'metric'}),'bottom-left');map.on('error',e=>console.warn('FloodSafe map source',e?.error?.message||e?.message||e));map.on('style.load',initLayers);setTimeout(()=>{if(map?.isStyleLoaded?.())initLayers()},400);setTimeout(()=>{if(map?.isStyleLoaded?.())initLayers()},1200);$('mapZoomIn')?.addEventListener('click',()=>map.zoomTo(Math.min(19,map.getZoom()+1.7),{duration:350}));$('mapZoomOut')?.addEventListener('click',()=>map.zoomTo(Math.max(4.8,map.getZoom()-1.5),{duration:350}));$('mapReset')?.addEventListener('click',reset);$('map3D')?.addEventListener('click',()=>set3D(!is3D));window.addEventListener('fsriverupdate',()=>{if(last){refreshWater();if(selected)renderSelected()}});window.addEventListener('fslanguage',updateLanguage);window.addEventListener('resize',()=>{if(!last&&initialized)focusNepal(false)});setInterval(()=>{if(last){refreshWater();if(selected)renderSelected()}},5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
