(()=>{'use strict';
if(window.__fsMapCoreV6)return;window.__fsMapCoreV6=true;
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]||c));
const isEn=()=>((window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne')==='en');
const rt=()=>window.FloodSafeRiverRealtime;
const val=(o,ks)=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null};
function fmtNum(v,u=''){if(v===null||v===undefined||v==='')return'—';const n=Number(v);return `${Number.isFinite(n)?n.toFixed(3).replace(/0+$/,'').replace(/\.$/,''):v}${u}`}
function fmtTime(t){if(!t)return'—';const d=new Date(t);if(!Number.isFinite(+d))return String(t);return new Intl.DateTimeFormat(isEn()?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(d)+' NPT'}
function ageText(t){const x=+new Date(t||0);if(!x)return'—';const sec=Math.max(0,Math.floor((Date.now()-x)/1000));if(sec<60)return isEn()?`${sec}s ago`:`${sec} सेकेन्ड अघि`;const m=Math.floor(sec/60);if(m<60)return isEn()?`${m}m ago`:`${m} मिनेट अघि`;const h=Math.floor(m/60);if(h<48)return isEn()?`${h}h ago`:`${h} घण्टा अघि`;return isEn()?`${Math.floor(h/24)}d ago`:`${Math.floor(h/24)} दिन अघि`}
function yesNo(v){if(v===null||v===undefined||v==='')return'—';if(typeof v==='boolean')return v?(isEn()?'Yes':'हो'):(isEn()?'No':'होइन');const s=String(v).toLowerCase();if(['true','1','yes'].includes(s))return isEn()?'Yes':'हो';if(['false','0','no'].includes(s))return isEn()?'No':'होइन';return String(v)}
function ensureUI(){const host=document.querySelector('.mapCanvas');if(!host||document.getElementById('fsMapSimpleStatus'))return;const box=document.createElement('div');box.id='fsMapSimpleStatus';box.innerHTML='<div class="fs-live-title">🌊 BIPAD नदी Live</div><div id="fsMapSimpleCounts">BIPAD नदी data जोडिँदैछ…</div><div class="fs-live-legend"><span>🔵 सामान्य</span><span>🟡 सतर्क</span><span>🟠 चेतावनी</span><span>🔴 खतरा</span><span>⚪ पढाइ छैन</span></div>';host.appendChild(box)}
function updateUI(){ensureUI();const el=document.getElementById('fsMapSimpleCounts');if(!el)return;const s=window.__fsRiverRealtimeState||{},catalog=Number(s.catalogCount||0),latest=Number(s.latestCount||0),ok=s.connected!==false;el.textContent=isEn()?`${catalog} BIPAD river stations • ${latest} latest official readings • ${ok?'direct live sync':'reconnecting'}`:`${catalog} BIPAD नदी स्टेशन • ${latest} पछिल्लो आधिकारिक पढाइ • ${ok?'direct live sync':'पुनः जडान हुँदैछ'}`;try{window.FloodSafeMap?.refreshGauges?.()}catch{}}
function stationFromFeature(p){return rt()?.findStation?.({id:p.id,station_id:p.station_id,stationId:p.station_id,stationSeriesId:p.station_id,name:p.name})||rt()?.findStation?.({name:p.name})||null}
function officialStatus(o,p){const raw=val(o||{},['status','status_name','alertStatus','alert_status','riskLevel','risk_level']);if(raw!==null)return String(raw);const s=String(p?.status||o?._derivedStatus||'').toLowerCase();return ({danger:isEn()?'Danger':'खतरा',warning:isEn()?'Warning':'चेतावनी',watch:isEn()?'Watch':'सतर्क',normal:isEn()?'Normal':'सामान्य'})[s]||'—'}
function detailHTML(o,p){const title=val(o,['title','name','river_name','riverName','station_name','stationName'])||p.name||'River station',basin=val(o,['basin','basin_name','basinName']),water=rt()?.level?.(o),warning=rt()?.warning?.(o),danger=rt()?.danger?.(o),time=rt()?.measureTime?.(o),status=officialStatus(o,p),elevation=val(o,['elevation','stationElevation','station_elevation']),steady=val(o,['steady','isSteady','is_steady']),description=val(o,['description','desc']),sid=val(o,['stationSeriesId','station_series_id','stationId','station_id','stationIndex','station_index'])??o?.id,discharge=rt()?.discharge?.(o);const row=(ne,en,v)=>`<div><b>${isEn()?en:ne}:</b> ${esc(v??'—')}</div>`;return `<div class="fs-simple-popup"><div class="fs-popup-title">${esc(title)}</div><div class="fs-popup-state">${esc(status)}</div>${row('Basin','Basin',basin)}${row('पानीको सतह','Water level',fmtNum(water,' m'))}${row('खतरा तह','Danger level',fmtNum(danger,' m'))}${row('चेतावनी तह','Warning level',fmtNum(warning,' m'))}${row('आधिकारिक समय','Water level on',fmtTime(time))}<div class="fs-popup-age">${esc(ageText(time))}</div>${row('Status','Status',status)}${row('उचाइ','Elevation',fmtNum(elevation,' m'))}${row('स्थिर','Steady',yesNo(steady))}${discharge!==null?row('बहाव','Discharge',fmtNum(discharge,' m³/s')):''}${row('विवरण','Description',description)}${row('Station series ID','Station series ID',sid)}<div style="margin-top:8px;font-size:12px;opacity:.82">${isEn()?'Source: direct BIPAD river-stations API':'स्रोत: direct BIPAD river-stations API'}</div><a href="https://bipadportal.gov.np/realtime/" target="_blank" rel="noopener noreferrer">${isEn()?'Open official BIPAD realtime':'आधिकारिक BIPAD realtime खोल्नुहोस्'}</a></div>`}
function simplePopup(){const map=window.FloodSafeMap?.map;if(!map||map.__fsSimplePopupV6)return;map.__fsSimplePopupV6=true;map.on('click','gauges',e=>{const f=e.features?.[0];if(!f)return;setTimeout(()=>{document.querySelectorAll('.maplibregl-popup').forEach(x=>x.remove());const p=f.properties||{},o=stationFromFeature(p);new window.maplibregl.Popup({maxWidth:'360px',closeButton:true}).setLngLat(e.lngLat).setHTML(o?detailHTML(o,p):`<div class="fs-simple-popup"><b>${esc(p.name||'River station')}</b><div>${isEn()?'Official BIPAD detail is syncing…':'Official BIPAD detail sync हुँदैछ…'}</div></div>`).addTo(map)},0)})}
function boot(){ensureUI();const wait=()=>{if(window.FloodSafeMap?.map){simplePopup();updateUI()}else setTimeout(wait,350)};wait();['fstrustedriverupdate','fsriverupdate','fsriverheartbeat','fsgaugesrendered'].forEach(n=>window.addEventListener(n,updateUI));setInterval(updateUI,10000)}
window.FloodSafeMapCoreV4={sync:()=>rt()?.refresh?.(),refresh:updateUI};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
