(()=>{'use strict';
if(window.__fsMapV9)return;window.__fsMapV9=true;
const NS='http://www.w3.org/2000/svg',B={minLon:80,maxLon:88.35,minLat:26.2,maxLat:30.5},$=id=>document.getElementById(id);
const lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne',tr=(ne,en)=>lang()==='en'?en:ne;
const NP={Achham:'अछाम',Arghakhanchi:'अर्घाखाँची',Baglung:'बागलुङ',Baitadi:'बैतडी',Bajhang:'बझाङ',Bajura:'बाजुरा',Banke:'बाँके',Bara:'बारा',Bardiya:'बर्दिया',Bhaktapur:'भक्तपुर',Bhojpur:'भोजपुर',Chitwan:'चितवन',Dadeldhura:'डडेलधुरा',Dailekh:'दैलेख',Dang:'दाङ',Darchula:'दार्चुला',Dhading:'धादिङ',Dhankuta:'धनकुटा',Dhanusha:'धनुषा',Dolakha:'दोलखा',Dolpa:'डोल्पा',Doti:'डोटी',Gorkha:'गोरखा',Gulmi:'गुल्मी',Humla:'हुम्ला',Ilam:'इलाम',Jajarkot:'जाजरकोट',Jhapa:'झापा',Jumla:'जुम्ला',Kailali:'कैलाली',Kalikot:'कालिकोट',Kanchanpur:'कञ्चनपुर',Kapilvastu:'कपिलवस्तु',Kaski:'कास्की',Kathmandu:'काठमाडौं',Kavrepalanchok:'काभ्रेपलाञ्चोक',Khotang:'खोटाङ',Lalitpur:'ललितपुर',Lamjung:'लमजुङ',Mahottari:'महोत्तरी',Makwanpur:'मकवानपुर',Manang:'मनाङ',Morang:'मोरङ',Mugu:'मुगु',Mustang:'मुस्ताङ',Myagdi:'म्याग्दी','Nawalparasi East':'नवलपुर','Nawalparasi West':'परासी',Nawalpur:'नवलपुर',Nuwakot:'नुवाकोट',Okhaldhunga:'ओखलढुङ्गा',Palpa:'पाल्पा',Panchthar:'पाँचथर',Parbat:'पर्वत',Parsa:'पर्सा',Pyuthan:'प्युठान',Ramechhap:'रामेछाप',Rasuwa:'रसुवा',Rautahat:'रौतहट',Rolpa:'रोल्पा','Rukum East':'पूर्वी रुकुम','Rukum West':'पश्चिमी रुकुम',Rupandehi:'रुपन्देही',Salyan:'सल्यान',Sankhuwasabha:'सङ्खुवासभा',Saptari:'सप्तरी',Sarlahi:'सर्लाही',Sindhuli:'सिन्धुली',Sindhupalchok:'सिन्धुपाल्चोक',Siraha:'सिराहा',Solukhumbu:'सोलुखुम्बु',Sunsari:'सुनसरी',Surkhet:'सुर्खेत',Syangja:'स्याङ्जा',Tanahun:'तनहुँ',Taplejung:'ताप्लेजुङ',Terhathum:'तेह्रथुम',Udayapur:'उदयपुर'};
let svg=null,geo=null,water=null,last=null,selected=null,loadWaterP=null,is3D=false;
const xy=(lo,la)=>[(lo-B.minLon)/(B.maxLon-B.minLon)*1000,600-(la-B.minLat)/(B.maxLat-B.minLat)*600],ll=(x,y)=>[B.minLon+x/1000*(B.maxLon-B.minLon),B.maxLat-y/600*(B.maxLat-B.minLat)];
const inside=(la,lo)=>Number.isFinite(la)&&Number.isFinite(lo)&&la>=B.minLat&&la<=B.maxLat&&lo>=B.minLon&&lo<=B.maxLon;
const km=(a,b,c,d)=>{const R=6371,p=x=>x*Math.PI/180,q=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
async function get(u,ms=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(u+(u.includes('?')?'&':'?')+'_v9='+Date.now(),{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function loadWater(){if(water)return water;if(loadWaterP)return loadWaterP;loadWaterP=(async()=>{const urls=['https://raw.githubusercontent.com/Pujan1234-hub/assigment/main/data/nepal-waterways-snapshot.json','https://raw.githubusercontent.com/Pujan1234-hub/assigment/main/data/nepal-waterways-seed.json','../../data/nepal-waterways-snapshot.json','../../data/nepal-waterways-seed.json'];for(const u of urls){try{const j=await get(u,14000);if(j?.waterways?.length>=100)return water=j}catch{}}return null})();return loadWaterP}
function rings(f){const g=f.geometry||{};return g.type==='Polygon'?[g.coordinates?.[0]]:g.type==='MultiPolygon'?g.coordinates.map(p=>p?.[0]):[]}
function rawName(f){return f.properties?.nameEn||f.properties?.DISTRICT||f.properties?.district||'District'}
function dname(f){const n=rawName(f);return lang()==='en'?n:(NP[n]||n)}
function ringPath(r){return(r||[]).map((p,i)=>{const q=xy(p[0],p[1]);return(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)}).join(' ')+' Z'}
function center(f){let a=99,b=0,c=99,d=0;for(const r of rings(f))for(const p of r||[]){a=Math.min(a,p[0]);b=Math.max(b,p[0]);c=Math.min(c,p[1]);d=Math.max(d,p[1])}return[(a+b)/2,(c+d)/2]}
function districtFor(la,lo){let best=null,bd=1e9;for(const f of geo?.features||[]){const c=center(f),d=km(la,lo,c[1],c[0]);if(d<bd){bd=d;best=f}}return best}
function text(x,y,s,cls){const t=document.createElementNS(NS,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor','middle');t.setAttribute('dominant-baseline','middle');t.setAttribute('class',cls);t.textContent=s;svg.appendChild(t);return t}
function drawBase(){if(!svg||!geo)return;svg.innerHTML='';for(const f of geo.features||[]){for(const r of rings(f)){if(!r?.length)continue;const p=document.createElementNS(NS,'path');p.setAttribute('d',ringPath(r));p.setAttribute('class','districtV9');p.dataset.key=rawName(f);p.addEventListener('click',e=>{e.stopPropagation();const z=eventLL(e);if(z)choose(z[1],z[0],f)});svg.appendChild(p)}const c=center(f),q=xy(c[0],c[1]);text(q[0],q[1],dname(f),'districtLabelV9')}svg.setAttribute('viewBox','-50 -35 1100 670')}
function eventLL(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const m=svg.getScreenCTM();if(!m)return null;const q=p.matrixTransform(m.inverse());return ll(q.x,q.y)}
function marker(lo,la){svg.querySelectorAll('.selectedPointV9,.selectedRingV9').forEach(n=>n.remove());const q=xy(lo,la),a=document.createElementNS(NS,'circle'),b=document.createElementNS(NS,'circle');a.setAttribute('cx',q[0]);a.setAttribute('cy',q[1]);a.setAttribute('r','5.5');a.setAttribute('class','selectedRingV9');b.setAttribute('cx',q[0]);b.setAttribute('cy',q[1]);b.setAttribute('r','2.4');b.setAttribute('class','selectedPointV9');svg.append(a,b)}
function path(pts){return pts.map((p,i)=>{const q=xy(p[0],p[1]);return(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)}).join(' ')}
function wname(w){return lang()==='en'?(w.name_en||w.name||'Unnamed river or stream'):(w.name_ne||w.name||'नाम नखुलेको नदी वा खोला')}
function distTo(w,la,lo){let d=1e9;for(const p of w.pts||[])d=Math.min(d,km(la,lo,p[1],p[0]));return d}
function routeKey(w){const p=w.pts||[],a=p[0]||[],b=p[p.length-1]||[];return `${w.type||'stream'}|${(w.name||w.name_en||w.name_ne||'').toLowerCase()}|${a[0]?.toFixed?.(4)},${a[1]?.toFixed?.(4)}|${b[0]?.toFixed?.(4)},${b[1]?.toFixed?.(4)}`}
function pick(radius,la,lo){const a=[],seen=new Set();for(const w of water?.waterways||[]){if(!Array.isArray(w.pts)||w.pts.length<2)continue;const d=distTo(w,la,lo);if(d>radius)continue;const k=routeKey(w);if(seen.has(k))continue;seen.add(k);a.push({w,d,named:!!(w.name||w.name_en||w.name_ne),river:w.type==='river',len:w.pts.length})}a.sort((x,y)=>x.d-y.d||(y.river-x.river)||(y.named-x.named)||(y.len-x.len));return a}
function candidates(la,lo){let a=pick(18,la,lo);if(a.length<7)a=pick(30,la,lo);return a.slice(0,22).map(x=>x.w)}
function clearWater(){svg?.querySelectorAll('.riverRouteV9,.riverFlowV9,.riverHitV9,.gaugeDotV9,.gaugeHaloV9').forEach(n=>n.remove())}
function routeStatus(w){if(!last||!window.FloodSafeGauge?.forWaterway)return null;const g=window.FloodSafeGauge.forWaterway(w,last.la,last.lo);return g?.sameRiver?g.status:null}
function setSelected(key){svg?.querySelectorAll('.riverRouteV9,.riverFlowV9').forEach(n=>n.classList.toggle('selected',n.dataset.key===key))}
function drawWaterways(ws){clearWater();const selectedKey=selected?.w?routeKey(selected.w):null;let n=0;ws.forEach((w,idx)=>{const pts=(w.pts||[]).filter(p=>inside(p[1],p[0]));if(pts.length<2)return;const key=routeKey(w),d=path(pts),st=routeStatus(w),hit=document.createElementNS(NS,'path'),base=document.createElementNS(NS,'path'),flow=document.createElementNS(NS,'path');hit.setAttribute('d',d);hit.setAttribute('class','riverHitV9');hit.dataset.key=key;hit.addEventListener('click',e=>{e.stopPropagation();selected={w,pts,key};setSelected(key);renderSheet();if($('mapHint'))$('mapHint').textContent=tr(`${wname(w)} छानियो • मापन स्वतः अद्यावधिक हुन्छ`,`Selected ${wname(w)} • gauge data updates automatically`)});base.setAttribute('d',d);base.setAttribute('class','riverRouteV9 '+(w.type==='river'?'river':'stream')+(st?' status-'+st:''));base.dataset.key=key;flow.setAttribute('d',d);flow.setAttribute('class','riverFlowV9'+(st?' status-'+st:''));flow.dataset.key=key;svg.append(hit,base,flow);n++});if(selectedKey)setSelected(selectedKey);return n}
function drawGauges(){svg?.querySelectorAll('.gaugeDotV9,.gaugeHaloV9').forEach(n=>n.remove());if(!last||!window.FloodSafeGauge?.nearby)return 0;const gs=window.FloodSafeGauge.nearby(last.la,last.lo,48,8);for(const g of gs){const q=xy(g.lon,g.lat),halo=document.createElementNS(NS,'circle'),dot=document.createElementNS(NS,'circle'),title=document.createElementNS(NS,'title');halo.setAttribute('cx',q[0]);halo.setAttribute('cy',q[1]);halo.setAttribute('r','2.8');halo.setAttribute('class','gaugeHaloV9 '+g.status);dot.setAttribute('cx',q[0]);dot.setAttribute('cy',q[1]);dot.setAttribute('r','1.45');dot.setAttribute('class','gaugeDotV9 '+g.status);title.textContent=`${g.name} • ${g.statusLabel} • ${g.level??'—'} m`;dot.appendChild(title);dot.addEventListener('click',e=>{e.stopPropagation();showGaugeSheet(g)});svg.append(halo,dot)}return gs.length}
function ensureSheet(){let s=$('riverSheet');if(s)return s;s=document.createElement('section');s.id='riverSheet';s.className='riverSheetV9';s.hidden=true;s.innerHTML='<button id="riverSheetClose" class="riverSheetCloseV9" type="button" aria-label="Close">×</button><div id="riverSheetBody"></div>';document.body.appendChild(s);$('riverSheetClose').addEventListener('click',()=>{s.hidden=true;selected=null;setSelected('')});return s}
function fmtTime(t){if(!t)return tr('उपलब्ध छैन','Unavailable');try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return String(t)}}
function statusClass(k){return ['danger','warning','watch','normal'].includes(k)?k:'unknown'}
function refPoint(pts){if(!last)return pts[Math.floor(pts.length/2)];let best=pts[0],bd=1e9;for(const p of pts){const d=km(last.la,last.lo,p[1],p[0]);if(d<bd){bd=d;best=p}}return best}
function renderSheet(){if(!selected)return;const {w,pts,key}=selected,p=refPoint(pts),g=window.FloodSafeGauge?.forWaterway?.(w,p[1],p[0])||null,nm=wname(w),typ=w.type==='river'?tr('नदी','River'):tr('खोला','Stream'),sheet=ensureSheet(),body=$('riverSheetBody');const direct=!!g?.sameRiver,st=g?g.statusLabel:tr('प्रत्यक्ष मापन केन्द्र छैन','NO DIRECT GAUGE'),sc=g?statusClass(g.status):'unknown',level=g?.level??'—',warn=g?.warning??'—',danger=g?.danger??'—';const gaugeType=direct?tr('यही नदीको प्रत्यक्ष मापन','LIVE GAUGE ON THIS RIVER'):g?tr('नजिकको सन्दर्भ मापन','NEAREST REFERENCE GAUGE'):tr('प्रत्यक्ष मापन उपलब्ध छैन','NO DIRECT GAUGE');body.innerHTML=`<div class="sheetEyebrowV9">${tr('छानिएको नदी / खोला','Selected river / stream')}</div><h3>${nm}</h3><div class="sheetStatusV9 ${sc}">${gaugeType} • <b>${st}</b></div><div class="sheetAutoV9">↻ ${tr('हरेक ५ सेकेन्डमा आधिकारिक मापन स्वतः जाँचिन्छ','Official gauge data auto-refreshes every 5 seconds')}</div><div class="sheetGridV9"><div><span>${tr('पानीको सतह','Water level')}</span><strong>${level}${g?.level!=null?' m':''}</strong></div><div><span>${tr('चेतावनी सीमा','Warning level')}</span><strong>${warn}${g?.warning!=null?' m':''}</strong></div><div><span>${tr('खतरा सीमा','Danger level')}</span><strong>${danger}${g?.danger!=null?' m':''}</strong></div><div><span>${tr('अवस्था','Status')}</span><strong>${g?st:'—'}</strong></div></div><div class="sheetMetaV9"><p><b>${tr('प्रकार','Type')}:</b> ${typ}</p><p><b>${tr(direct?'आधिकारिक मापन केन्द्र':'नजिकको आधिकारिक सन्दर्भ केन्द्र',direct?'Official gauge':'Nearest official reference gauge')}:</b> ${g?.name||tr('उपलब्ध छैन','Unavailable')}${g?` • ${g.distanceKm.toFixed(1)} km`:''}</p><p><b>${tr('मापन समय','Measured')}:</b> ${g?fmtTime(g.time):tr('उपलब्ध छैन','Unavailable')}</p><p><b>${tr('स्रोत','Source')}:</b> ${g?'DHM / BIPAD':'OpenStreetMap route only'}</p></div>${g&&!direct?`<div class="sheetWarningV9">${tr('यो मापन छानिएको नदीकै होइन; नजिकको आधिकारिक मापन केन्द्रको सन्दर्भ मात्र हो।','This reading is not from the selected river; it is the nearest official reference gauge.')}</div>`:''}<div class="sheetNoteV9">${tr('चलिरहेको cyan trace ले नक्सामा प्रवाह देखाउन सहयोग गर्छ। आधिकारिक downstream direction उपलब्ध नभएसम्म animation लाई प्रमाणित बहाव-दिशा नमान्नुहोस्।','The moving cyan trace helps visualise flow on the map. It is not a verified downstream direction unless an official direction source is available.')}</div>`;sheet.hidden=false;setSelected(key)}
function showGaugeSheet(g){selected=null;setSelected('');const sheet=ensureSheet(),body=$('riverSheetBody');body.innerHTML=`<div class="sheetEyebrowV9">${tr('आधिकारिक नदी मापन केन्द्र','Official river gauge')}</div><h3>${g.name}</h3><div class="sheetStatusV9 ${statusClass(g.status)}"><b>${g.statusLabel}</b></div><div class="sheetAutoV9">↻ ${tr('हरेक ५ सेकेन्डमा स्वतः अद्यावधिक','Auto-updates every 5 seconds')}</div><div class="sheetGridV9"><div><span>${tr('पानीको सतह','Water level')}</span><strong>${g.level??'—'}${g.level!=null?' m':''}</strong></div><div><span>${tr('चेतावनी सीमा','Warning level')}</span><strong>${g.warning??'—'}${g.warning!=null?' m':''}</strong></div><div><span>${tr('खतरा सीमा','Danger level')}</span><strong>${g.danger??'—'}${g.danger!=null?' m':''}</strong></div><div><span>${tr('दूरी','Distance')}</span><strong>${g.distanceKm.toFixed(1)} km</strong></div></div><div class="sheetMetaV9"><p><b>${tr('मापन समय','Measured')}:</b> ${fmtTime(g.time)}</p><p><b>${tr('स्रोत','Source')}:</b> DHM / BIPAD</p></div>`;sheet.hidden=false}
function setFocusView(la,lo){const q=xy(lo,la),w=285,h=185,x=Math.max(-35,Math.min(1035-w,q[0]-w/2)),y=Math.max(-25,Math.min(625-h,q[1]-h/2));svg.setAttribute('viewBox',`${x} ${y} ${w} ${h}`)}
function redrawLive(){if(!last||!water)return;const ws=candidates(last.la,last.lo),n=drawWaterways(ws),g=drawGauges();marker(last.lo,last.la);if($('mapHint')&&!selected)$('mapHint').textContent=n?tr(`${n} नदी/खोला • ${g} ताजा मापन केन्द्र • cyan रेखा वा रंगीन मापन बिन्दु थिच्नुहोस्`,`${n} rivers/streams • ${g} fresh gauges • tap a cyan line or coloured gauge dot`):tr('यो ठाउँ वरिपरि नदी/खोला route भेटिएन।','No river/stream route found around this point.')}
async function choose(la,lo,f){if(!inside(la,lo))return;f=f||districtFor(la,lo);last={la,lo,f};selected=null;svg.classList.add('focused');document.querySelector('#map .mapCanvas')?.classList.add('focused');svg.querySelectorAll('.districtV9').forEach(p=>p.classList.toggle('selected',f&&p.dataset.key===rawName(f)));setFocusView(la,lo);window.FloodSafe?.setFocus?.(la,lo,'map');window.FloodSafeSatellite?.selected?.(la,lo);if($('riverSheet'))$('riverSheet').hidden=true;const nm=f?dname(f):tr('छानिएको क्षेत्र','Selected area');if($('mapHint'))$('mapHint').textContent=tr(`${nm} वरिपरिका नदी/खोला तयार हुँदैछन्…`,`Loading rivers and streams around ${nm}…`);await loadWater();redrawLive()}
function zoom(f){const v=svg.viewBox.baseVal,cx=v.x+v.width/2,cy=v.y+v.height/2,w=Math.max(58,Math.min(1100,v.width*f)),h=w*.65,x=Math.max(-50,Math.min(1050-w,cx-w/2)),y=Math.max(-35,Math.min(635-h,cy-h/2));svg.setAttribute('viewBox',`${x} ${y} ${w} ${h}`);if(last){drawGauges();marker(last.lo,last.la)}}
function reset(){last=null;selected=null;svg.classList.remove('focused');document.querySelector('#map .mapCanvas')?.classList.remove('focused');drawBase();clearWater();window.FloodSafeSatellite?.full?.();if($('riverSheet'))$('riverSheet').hidden=true;if($('mapHint'))$('mapHint').textContent=tr('नक्सामा ठाउँ छान्नुहोस् — वरिपरिका नदी/खोला देखिन्छन्।','Tap a place on the map to show nearby rivers and streams.')}
function toggle3D(){is3D=!is3D;const c=document.querySelector('#map .mapCanvas'),b=$('map3D');c?.classList.toggle('terrain3d',is3D);b?.classList.toggle('active',is3D);if(b)b.textContent=is3D?tr('◈ ३D बन्द','◈ 3D Off'):tr('◈ ३D भू-आकृति','◈ 3D Terrain');window.FloodSafeSatellite?.set3D?.(is3D)}
function replaceButton(id,fn){const b=$(id);if(!b)return;const c=b.cloneNode(true);b.replaceWith(c);c.addEventListener('click',fn)}
async function boot(){const old=$('riverMap');if(!old)return;old.style.display='none';svg=document.createElementNS(NS,'svg');svg.id='riverMapV3';svg.setAttribute('viewBox','-50 -35 1100 670');svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.setAttribute('role','img');svg.setAttribute('aria-label',tr('नेपाल नदी नक्सा','Nepal river map'));old.parentNode.insertBefore(svg,old);ensureSheet();replaceButton('mapReset',reset);replaceButton('mapZoomIn',()=>zoom(.66));replaceButton('mapZoomOut',()=>zoom(1.5));replaceButton('map3D',toggle3D);try{geo=await get('../v24/nepal-districts.geojson',9000);drawBase();await loadWater();if($('mapHint'))$('mapHint').textContent=tr('ठाउँ छान्नुहोस्, त्यसपछि cyan नदी/खोला वा रंगीन मापन बिन्दु थिच्नुहोस्।','Tap a place, then tap a cyan river/stream or coloured gauge dot.')}catch{if($('mapHint'))$('mapHint').textContent=tr('नक्सा लोड हुन सकेन।','Map could not be loaded.')}}
window.addEventListener('fslanguage',async()=>{const keep=last;if(geo)drawBase();if(keep)await choose(keep.la,keep.lo,keep.f);if($('riverSheet')&&!$('riverSheet').hidden&&selected)renderSheet()});
window.addEventListener('fsriverupdate',()=>{if(last)redrawLive();if(selected&&$('riverSheet')&&!$('riverSheet').hidden)renderSheet()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.FloodSafeMap={choose,select:choose,redraw:redrawLive,get selected(){return last},get is3D(){return is3D}};
})();