(()=>{
'use strict';
const PAGE=document.body.dataset.page||'home',$=id=>document.getElementById(id),KCHA='https://kchakhabar.com/api/v1/today.json?limit=80',FALLBACK='../../data/national-news.json';
let items=[],cursor=0,lastTop='',sourceOk=false,nextRotate=10,lastKcha=0,kchaBusy=false,fallbackBusy=false;
const norm=s=>String(s||'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const age=t=>{const x=+new Date(t||0);if(!x)return Infinity;return Math.max(0,Date.now()-x)};
function make(tag,cls,t){const e=document.createElement(tag);if(cls)e.className=cls;if(t!==undefined)e.textContent=t;return e}
function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}
function fmt(t){try{return new Intl.DateTimeFormat('ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',day:'numeric',month:'short'}).format(new Date(t))}catch{return''}}
function dedup(list){const out=[],seen=[];for(const x of list){const k=norm(x.title);if(!k||seen.some(s=>(k.includes(s)||s.includes(k))&&Math.min(k.length,s.length)>24))continue;seen.push(k);out.push(x)}return out}
function fromKcha(j){const raw=Array.isArray(j?.stories)?j.stories:[],fresh=raw.filter(s=>age(s.updated_at||s.first_reported)<=8*3600e3),use=fresh.length>=8?fresh:raw.filter(s=>age(s.updated_at||s.first_reported)<=24*3600e3);return dedup(use.map(s=>{const src=s.sources?.[0];return{title:s.topic_ne||s.topic_en||'',source:src?.publisher||'Nepal media',url:src?.url||s.url,updated:s.updated_at||s.first_reported,flash:age(s.updated_at||s.first_reported)<=90*60000}}))}
function fromFallback(j){return dedup((j?.items||[]).map(x=>({title:x.title,source:x.source,url:x.url,updated:j.generated_at,flash:!!x.flash}))) }
function storyCard(x){const box=make('article','item');box.appendChild(make('span','tag '+(x.flash?'red':''),x.flash?'FLASH':'LATEST'));box.appendChild(make('h4','',x.title));box.appendChild(make('div','meta',x.source+(x.updated?' • '+fmt(x.updated):'')));if(x.url){const r=make('div','meta'),a=make('a','','समाचार खोल्नुहोस्');a.href=x.url;a.target='_blank';a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';r.appendChild(a);box.appendChild(r)}return box}
function render(){const list=PAGE==='nationalnews'?$('newsList'):$('nationalHomeNews');if(!list)return;clear(list);if(!items.length){list.appendChild(make('div','empty','नयाँ राष्ट्रिय समाचार खोजिँदैछ…'));return}const n=PAGE==='nationalnews'?6:3,batch=[];for(let i=0;i<Math.min(n,items.length);i++)batch.push(items[(cursor+i)%items.length]);if(batch[0]?.title===lastTop&&items.length>1){cursor=(cursor+1)%items.length;return render()}lastTop=batch[0]?.title||'';batch.forEach(x=>list.appendChild(storyCard(x)));if($('newsCount'))$('newsCount').textContent=items.length;const status=sourceOk?'Live national feed • source check 1 sec • अर्को headline '+nextRotate+' sec':'Media feed फेरि जाँच हुँदैछ…';if($('appStatus'))$('appStatus').textContent=status;if($('homeNewsFresh'))$('homeNewsFresh').textContent=status;if($('healthNews'))$('healthNews').textContent=sourceOk?'Media feed ✓ • 1-sec receiver':'Media feed • फेरि जाँच हुँदैछ'}
async function get(url,ms=7000){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_rt='+Date.now(),{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',signal:c.signal,headers:{accept:'application/json'}});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
async function loadKcha(force=false){if(kchaBusy||(!force&&Date.now()-lastKcha<900))return;kchaBusy=true;lastKcha=Date.now();try{const j=await get(KCHA),next=fromKcha(j);if(next.length){const before=items[0]?.title||'';items=next;sourceOk=true;if(items[0]?.title!==before){cursor=0;lastTop=''}render();return}}catch{}finally{kchaBusy=false}sourceOk=false}
async function loadFallback(){if(fallbackBusy)return;fallbackBusy=true;try{const j=await get(FALLBACK,5000);if(!items.length){items=fromFallback(j);render()}}catch{}finally{fallbackBusy=false}}
function rotate(){if(items.length){cursor=(cursor+(PAGE==='nationalnews'?6:3))%items.length;nextRotate=10;lastTop='';render()}else{nextRotate=10;loadKcha(true);loadFallback()}}
async function boot(){await Promise.all([loadKcha(true),loadFallback()]);render();setInterval(()=>{nextRotate--;if(nextRotate<=0)rotate();else{if($('appStatus')&&sourceOk)$('appStatus').textContent='Live national feed • source check 1 sec • अर्को headline '+nextRotate+' sec';if($('homeNewsFresh')&&sourceOk)$('homeNewsFresh').textContent='Live national feed • source check 1 sec • अर्को headline '+nextRotate+' sec'}},1000);setInterval(loadFallback,1000);setInterval(()=>loadKcha(false),1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){loadKcha(true);loadFallback();render()}});window.addEventListener('online',()=>{loadKcha(true);loadFallback()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();