(()=>{
'use strict';
if(window.__fsNationalNewsV4)return;window.__fsNationalNewsV4=true;
const PAGE=document.body.dataset.page||'home',$=id=>document.getElementById(id),KCHA='https://kchakhabar.com/api/v1/today.json?limit=100',LOCAL='../../data/national-news.json',FLASH=3600e3,RECENT=6*3600e3;
let feeds={k:[],l:[]},busy=false,lastCheck=0,ok={k:false,l:false};
const lang=()=>localStorage.getItem('fs23-lang')==='en'?'en':'ne',pick=(ne,en)=>lang()==='en'?en:ne,hasNe=s=>/[\u0900-\u097F]/.test(String(s||'')),age=t=>{const n=+new Date(t||0);return n?Math.max(0,Date.now()-n):Infinity},norm=s=>String(s||'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
function validTitle(s){return lang()==='en'?!hasNe(s):hasNe(s)}
function make(t,c,x){const e=document.createElement(t);if(c)e.className=c;if(x!==undefined)e.textContent=x;return e}function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}
function fmt(t){try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',day:'numeric',month:'short'}).format(new Date(t))}catch{return''}}
function ago(t){const m=Math.max(0,Math.floor(age(t)/60000));if(lang()==='en')return m<1?'just now':m<60?m+' min ago':Math.floor(m/60)+' hr '+m%60+' min ago';return m<1?'भर्खर':m<60?m+' मिनेट अघि':Math.floor(m/60)+' घण्टा '+m%60+' मिनेट अघि'}
function kcha(j){return (j?.stories||[]).map((s,i)=>{const src=s.sources?.[0],published=s.first_reported||s.updated_at,title=lang()==='en'?(s.topic_en||''):(s.topic_ne||'');return{id:'k'+(s.id||i),title,source:src?.publisher||pick('नेपाली सञ्चारमाध्यम','Nepal media'),url:src?.url||s.url||'',published}}).filter(x=>x.title&&validTitle(x.title)&&x.published&&age(x.published)<RECENT)}
function local(j){return (j?.items||[]).map((x,i)=>({id:'l'+i,title:x.title||'',source:x.source||pick('नेपाली सञ्चारमाध्यम','Nepal media'),url:x.url||'',published:x.published_at||x.published||x.date||null})).filter(x=>x.title&&validTitle(x.title)&&x.published&&age(x.published)<RECENT)}
function merged(){const out=[],seen=[];for(const x of [...feeds.k,...feeds.l].sort((a,b)=>+new Date(b.published)-+new Date(a.published))){const k=norm(x.title);if(!k||seen.some(z=>z===k||((z.includes(k)||k.includes(z))&&Math.min(z.length,k.length)>24)))continue;seen.push(k);out.push(x)}return out.slice(0,50)}
function card(x){const a=make('article','item'),flash=age(x.published)<FLASH;a.appendChild(make('span',flash?'tag red':'tag',flash?pick('ताजा','FLASH'):pick('पछिल्लो','LATEST')));a.appendChild(make('h4','',x.title));a.appendChild(make('div','meta',x.source+' • '+ago(x.published)+' • '+fmt(x.published)));if(x.url){const d=make('div','meta'),l=make('a','',pick('समाचार खोल्नुहोस्','Open article'));l.href=x.url;l.target='_blank';l.rel='noopener noreferrer';l.referrerPolicy='no-referrer';d.appendChild(l);a.appendChild(d)}return a}
function status(items){const flash=items.some(x=>age(x.published)<FLASH),connected=ok.k||ok.l;if(!connected)return pick('समाचार स्रोत फेरि जाँच हुँदैछ…','Rechecking news sources…');if(!items.length)return pick('६ घण्टाभित्र पुष्टि भएको नयाँ समाचार भेटिएको छैन • स्रोत जाँच जारी छ','No verified story was found within 6 hours • source checks continue');return flash?pick('ताजा समाचार • पछिल्लो १ घण्टा • स्रोत हरेक १० सेकेन्ड जाँच','Flash News • last 1 hour • sources checked every 10 sec'):pick('पछिल्लो १ घण्टामा ताजा समाचार छैन • ६ घण्टाभित्रका पुष्टि समाचार','No Flash News in the last hour • showing verified stories within 6 hours')}
function render(){const list=PAGE==='nationalnews'?$('newsList'):$('nationalHomeNews');if(!list)return;const items=merged(),count=PAGE==='nationalnews'?8:3;clear(list);for(const x of items.slice(0,count))list.appendChild(card(x));if(!list.children.length)list.appendChild(make('div','empty',status(items)));if($('newsCount'))$('newsCount').textContent=String(items.length);const s=status(items);if($('appStatus'))$('appStatus').textContent=s;if($('homeNewsFresh'))$('homeNewsFresh').textContent=s;if($('healthNews'))$('healthNews').textContent=(ok.k||ok.l)?pick('समाचार स्रोत जोडिएको','News sources connected'):pick('समाचार स्रोत फेरि जाँच हुँदैछ','Rechecking news sources');window.__fsNewsState={count:items.length,flash:items.filter(x=>age(x.published)<FLASH).length,checkedAt:lastCheck,sources:{kcha:ok.k,local:ok.l},owner:'news-v4'}}
async function get(u,ms=6500){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(u+(u.includes('?')?'&':'?')+'_news4='+Date.now(),{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
async function load(){if(busy||document.hidden||!navigator.onLine)return;busy=true;lastCheck=Date.now();const tasks=[get(LOCAL,4500).then(j=>{feeds.l=local(j);ok.l=true;render()}).catch(()=>{ok.l=false;render()}),get(KCHA,6500).then(j=>{feeds.k=kcha(j);ok.k=true;render()}).catch(()=>{ok.k=false;render()})];try{await Promise.allSettled(tasks)}finally{lastCheck=Date.now();busy=false;render()}}
function boot(){render();load();setInterval(load,10000);setInterval(render,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});window.addEventListener('online',load);window.addEventListener('fs-language-change',()=>{feeds={k:[],l:[]};ok={k:false,l:false};render();load()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();