(()=>{
'use strict';
if(window.__fsNewsOwnerV1)return;window.__fsNewsOwnerV1=true;
const PAGE=document.body.dataset.page||'home',$=id=>document.getElementById(id),KCHA='https://kchakhabar.com/api/v1/today.json?limit=100',LOCAL='../../data/national-news.json';
if(PAGE!=='home'&&PAGE!=='nationalnews')return;
const FLASH=60*60*1000,RECENT=6*60*60*1000,ROTATE=30;
let items=[],visible=[],lastBatch=[],seen=new Set(),known=new Set(),busy=false,lastFetch=0,next=ROTATE,paused=false,waiting=false,rendering=false;
const lang=()=>localStorage.getItem('fs23-lang')==='en'?'en':'ne',tr=(ne,en)=>lang()==='en'?en:ne,age=t=>{const x=+new Date(t||0);return x?Math.max(0,Date.now()-x):Infinity},norm=s=>String(s||'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
async function get(url,ms=6500){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
function fromKcha(j){return(Array.isArray(j?.stories)?j.stories:[]).map(s=>{const src=s.sources?.[0],published=s.first_reported||s.updated_at,title=lang()==='en'?(s.topic_en||''):(s.topic_ne||'');return{title,source:src?.publisher||tr('नेपाली सञ्चारमाध्यम','Nepal media'),url:src?.url||s.url||'',published}}).filter(x=>x.title&&x.published&&age(x.published)<RECENT)}
function fromLocal(j){if(lang()==='en'||!Array.isArray(j?.items))return[];return j.items.map(x=>({title:x.title||'',source:x.source||'नेपाली सञ्चारमाध्यम',url:x.url||'',published:x.published_at||x.published||null})).filter(x=>x.title&&x.published&&age(x.published)<RECENT)}
function dedup(list){const out=[],keys=[];for(const x of list.sort((a,b)=>+new Date(b.published||0)-+new Date(a.published||0))){const k=norm(x.title);if(!k||keys.some(q=>q===k||((q.includes(k)||k.includes(q))&&Math.min(q.length,k.length)>24)))continue;keys.push(k);out.push(x)}return out}
function key(x){return norm(x.title)}function isFlash(x){return age(x.published)<FLASH}
function ago(t){const m=Math.floor(age(t)/60000);if(lang()==='en')return m<1?'just now':m<60?m+' min ago':Math.floor(m/60)+' hr '+(m%60)+' min ago';return m<1?'भर्खर':m<60?m+' मिनेट अघि':Math.floor(m/60)+' घण्टा '+(m%60)+' मिनेट अघि'}
function fmt(t){try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(t))}catch{return''}}
function make(t,c,x){const e=document.createElement(t);if(c)e.className=c;if(x!==undefined)e.textContent=x;return e}function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}
function card(x){const a=make('article','item');a.dataset.newsOwner='1';a.appendChild(make('span',isFlash(x)?'tag red':'tag',isFlash(x)?tr('ताजा','FLASH'):tr('पछिल्लो','LATEST')));a.appendChild(make('h4','',x.title));a.appendChild(make('div','meta',x.source+' • '+ago(x.published)+' • '+fmt(x.published)));if(x.url){const d=make('div','meta'),l=make('a','',tr('समाचार खोल्नुहोस्','Open article'));l.href=x.url;l.target='_blank';l.rel='noopener noreferrer';d.appendChild(l);a.appendChild(d)}return a}
function listEl(){return PAGE==='nationalnews'?$('newsList'):$('nationalHomeNews')}
function status(){if(paused)return tr('समाचार पढ्नका लागि रोकिएको','News paused for reading');if(waiting)return tr('उपलब्ध नयाँ समाचार देखाइएको छ • नयाँ समाचार पर्खिँदै…','Available current headlines shown • waiting for new stories…');if(visible.some(isFlash))return tr('ताजा समाचार • पछिल्लो १ घण्टा • अर्को ','Flash News • last 1 hour • next in ')+next+tr(' सेकेन्ड',' sec');return tr('पछिल्लो पुष्टि समाचार • अर्को ','Verified recent news • next in ')+next+tr(' सेकेन्ड',' sec')}
function ensurePause(){const out=listEl();if(!out||document.getElementById('fsNewsPause'))return;const b=make('button','newsPause',tr('⏸ समाचार रोक्नुहोस्','⏸ Pause news'));b.id='fsNewsPause';b.type='button';b.style.cssText='margin:0 0 10px;padding:8px 12px;border-radius:999px;border:1px solid #6d4b3e;background:#1a1110;color:#fff;font-weight:850;font-size:12px';b.onclick=()=>{paused=!paused;b.textContent=paused?tr('▶️ समाचार चलाउनुहोस्','▶️ Resume news'):tr('⏸ समाचार रोक्नुहोस्','⏸ Pause news');renderStatus()};out.parentElement?.insertBefore(b,out)}
function renderStatus(){const s=status();if($('homeNewsFresh'))$('homeNewsFresh').textContent=s;if(PAGE==='nationalnews'&&$('appStatus'))$('appStatus').textContent=s;if($('healthNews'))$('healthNews').textContent=tr('समाचार स्रोत जोडिएको','News sources connected')}
function render(){const out=listEl();if(!out||rendering)return;rendering=true;try{ensurePause();clear(out);for(const x of visible)out.appendChild(card(x));if(!out.children.length)out.appendChild(make('div','empty',tr('नयाँ पुष्टि समाचार पर्खिँदै…','Waiting for new verified stories…')));if($('newsCount'))$('newsCount').textContent=String(items.length);renderStatus()}finally{rendering=false}}
function take(src){return src.slice(0,PAGE==='nationalnews'?6:3)}
function show(batch){batch=batch.filter(x=>age(x.published)<RECENT);if(!batch.length)return false;visible=batch;lastBatch=batch.slice();for(const x of batch)seen.add(key(x));waiting=false;next=ROTATE;render();return true}
function chooseNext(){const unseenFlash=items.filter(isFlash).filter(x=>!seen.has(key(x)));if(show(take(unseenFlash)))return;const unseenRecent=items.filter(x=>!isFlash(x)&&!seen.has(key(x)));if(show(take(unseenRecent)))return;visible=lastBatch.filter(x=>age(x.published)<RECENT);if(!visible.length)visible=take(items);waiting=true;next=0;render()}
async function load(force=false){if(busy||(!force&&Date.now()-lastFetch<14000))return;busy=true;lastFetch=Date.now();try{const [a,b]=await Promise.allSettled([get(KCHA,7000),get(LOCAL+'?t='+Date.now(),5000)]),nextItems=dedup([...(a.status==='fulfilled'?fromKcha(a.value):[]),...(b.status==='fulfilled'?fromLocal(b.value):[])]).slice(0,50),brand=nextItems.filter(x=>!known.has(key(x)));items=nextItems;for(const x of items)known.add(key(x));visible=visible.filter(x=>items.some(y=>key(y)===key(x))&&age(x.published)<RECENT);const freshBrand=brand.filter(isFlash).filter(x=>!seen.has(key(x)));if(freshBrand.length){show(take(freshBrand));return}if(!visible.length){chooseNext();return}render()}catch{render()}finally{busy=false}}
function tick(){items=items.filter(x=>age(x.published)<RECENT);visible=visible.filter(x=>age(x.published)<RECENT);if(!visible.length){chooseNext();return}if(!paused&&!waiting){next--;if(next<=0)chooseNext()}renderStatus()}
function reset(){items=[];visible=[];lastBatch=[];seen.clear();known.clear();lastFetch=0;waiting=false;next=ROTATE;load(true)}
function boot(){load(true);setInterval(tick,1000);setInterval(()=>load(false),15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load(true)});window.addEventListener('online',()=>load(true));window.addEventListener('fs-language-change',reset);window.addEventListener('storage',e=>{if(e.key==='fs23-lang')reset()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();