(()=>{'use strict';if(window.__fsNewsSnapshot)return;window.__fsNewsSnapshot=true;
const REFRESH=10*60*1000,NEW_WINDOW=10*60*1000,RECENT_WINDOW=30*60*1000,FUTURE_ALLOW=5*60*1000;
const URLS=['../../data/national-news.json','../../data/floodsafe-news.json'];let cache=[],last=0,loadError=false,feedMeta={};
const el=()=>document.getElementById('liveNews'),lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne',tr=(n,e)=>lang()==='en'?e:n,ts=v=>+new Date(v||0)||0,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function age(t){const m=Math.max(0,Math.floor((Date.now()-ts(t))/60000));return m<1?tr('अहिले','Now'):tr(`${m} मिनेट अघि`,`${m} min ago`)}
function card(x,isNew){const a=document.createElement('article');a.className='newsItem '+(isNew?'':'oldNews');a.innerHTML=`<h4>${esc(x.title)}</h4><div class="meta">${esc(x.source||'Verified source')} • ${age(x.published_at)} ${isNew?'<b class="liveDot">NEW</b>':''}</div><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${tr('समाचार खोल्नुहोस्','Open article')} ↗</a>`;return a}
function render(){const o=el();if(!o)return;const now=Date.now();const all=cache.filter(x=>{const t=ts(x.published_at);const d=now-t;return t&&d>=-FUTURE_ALLOW&&d<=RECENT_WINDOW}).sort((a,b)=>ts(b.published_at)-ts(a.published_at));const fresh=all.filter(x=>now-ts(x.published_at)<=NEW_WINDOW);const previous=all.filter(x=>{const d=now-ts(x.published_at);return d>NEW_WINDOW&&d<=RECENT_WINDOW});o.innerHTML='';const n=document.createElement('div');n.className='newsFreshBox';n.innerHTML=`<div class="newsBoxTitle"><strong>${tr('अहिलेका नयाँ समाचार','Latest news')}</strong><span>${tr('हरेक १० मिनेटमा नयाँ समाचार जाँच','checks for new stories every 10 min')}</span></div>`;fresh.slice(0,20).forEach(x=>n.appendChild(card(x,true)));if(!fresh.length)n.innerHTML+=`<div class="empty">${loadError?tr('समाचार फिड लोड हुन सकेन। केही बेरमा फेरि जाँच हुन्छ।','News feed could not load. It will retry automatically.'):tr('पछिल्लो १० मिनेटमा नयाँ समाचार छैन।','No new story in the last 10 minutes.')}</div>`;o.appendChild(n);const p=document.createElement('aside');p.className='newsArchiveBox';p.innerHTML=`<div class="newsBoxTitle"><strong>${tr('भर्खरका पुराना समाचार','Recent / previous')}</strong><span>${tr('१० मिनेटपछि यहाँ सर्छ • ३० मिनेटपछि हट्छ','moves here after 10 min • removed after 30 min')}</span></div>`;previous.slice(0,20).forEach(x=>p.appendChild(card(x,false)));if(!previous.length)p.innerHTML+=`<div class="empty">${tr('अहिले १०–३० मिनेट पुरानो समाचार छैन।','No 10–30 minute old stories right now.')}</div>`;o.appendChild(p)}
async function sync(force){if(!force&&Date.now()-last<REFRESH)return;last=Date.now();loadError=false;let loaded=false;for(const url of URLS){try{const r=await fetch(url+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)continue;const j=await r.json();if(Array.isArray(j.items)){cache=j.items;feedMeta=j;loaded=true;break}}catch(e){}}if(!loaded)loadError=true;render()}
function boot(){sync(true);setInterval(()=>sync(false),60000);setInterval(render,15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync(true)});window.addEventListener('online',()=>sync(true));window.addEventListener('fslanguage',render);window.FloodSafeNews={refresh:()=>sync(true),get items(){return cache.slice()},get meta(){return feedMeta}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();