(()=>{'use strict';
if(window.__fsNewsV5)return;window.__fsNewsV5=true;
const POLL=10000,NEW=10*60*1000,MAX=30*60*1000,FUTURE=5*60*1000;
const ALLOWED=new Set(['RONB Post','Radio Nepal','News24 Nepal']);
const SNAP=['https://raw.githubusercontent.com/Pujan1234-hub/assigment/main/data/floodsafe-news.json','../../data/floodsafe-news.json'];
const RONB='https://www.ronbpost.com/wp-json/wp/v2/posts?per_page=30&_fields=date_gmt,modified_gmt,link,title';
let snap=[],direct=[],failed=false;
const $=id=>document.getElementById(id),lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne',tr=(ne,en)=>lang()==='en'?en:ne,ts=t=>+new Date(t||0)||0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function age(t){const m=Math.max(0,Math.floor((Date.now()-ts(t))/60000));if(m<1)return tr('अहिले','Now');return m<60?tr(`${m} मिनेट अघि`,`${m} min ago`):tr(`${Math.floor(m/60)} घण्टा अघि`,`${Math.floor(m/60)} hr ago`)}
function merged(){const out=[],u=new Set(),t=new Set();for(const x of[...direct,...snap].filter(x=>ALLOWED.has(x.source)).sort((a,b)=>ts(b.published_at)-ts(a.published_at))){const url=String(x.url||'').split('#')[0],k=String(x.title||'').toLowerCase().replace(/\W+/g,' ').trim();if(!k||u.has(url)||t.has(k))continue;u.add(url);t.add(k);out.push(x)}return out}
function card(x,latest){return `<article class="newsItem ${latest?'':'oldNews'}"><h4>${esc(x.title)}</h4><div class="meta">${esc(x.source)} • ${esc(age(x.published_at))}${latest?' • <b class="liveDot">NEW</b>':''}</div><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${tr('खोल्नुहोस्','Open')} ↗</a></article>`}
function safety(){return `<div class="newsFreshBox"><div class="newsBoxTitle"><strong>${tr('🛟 अहिले नयाँ समाचार छैन — सुरक्षित रहने छोटो जानकारी','🛟 No new story right now — quick safety guidance')}</strong></div><article class="newsItem"><h4>${tr('बाढी बढेमा खोलाको किनार, पुल र डुबान भएको सडकबाट टाढा जानुहोस्। सुरक्षित अग्लो स्थान रोज्नुहोस्।','If water is rising, move away from riverbanks, bridges and flooded roads and go to safe higher ground.')}</h4><a href="https://ndrrma.gov.np/" target="_blank" rel="noopener noreferrer">NDRRMA ↗</a></article><article class="newsItem"><h4>${tr('बगिरहेको पानीमा हिँड्ने वा गाडी चलाउने प्रयास नगर्नुहोस्। आधिकारिक चेतावनी र evacuation निर्देशन पालना गर्नुहोस्।','Do not walk or drive through moving floodwater. Follow official warnings and evacuation instructions.')}</h4><a href="https://bipadportal.gov.np/" target="_blank" rel="noopener noreferrer">BIPAD ↗</a></article><article class="newsItem"><h4>${tr('फोन चार्ज, टर्च, पानी, औषधि र आवश्यक कागजात सजिलै लिन मिल्ने गरी तयार राख्नुहोस्।','Keep a charged phone, torch, drinking water, medicines and essential documents ready to take.')}</h4><a href="https://ndrrma.gov.np/" target="_blank" rel="noopener noreferrer">NDRRMA ↗</a></article></div>`}
function render(){const host=$('liveNews');if(!host)return;const sub=$('newsSub');if(sub)sub.textContent=tr('RONB Post • Radio Nepal • News24 Nepal','RONB Post • Radio Nepal • News24 Nepal');const now=Date.now(),all=merged().filter(x=>{const d=now-ts(x.published_at);return ts(x.published_at)&&d>=-FUTURE&&d<MAX}),latest=all.filter(x=>now-ts(x.published_at)<NEW),older=all.filter(x=>{const d=now-ts(x.published_at);return d>=NEW&&d<MAX});let html='';if(latest.length)html+=`<div class="newsFreshBox"><div class="newsBoxTitle"><strong>${tr('नयाँ समाचार • १० मिनेटभित्र','New • within 10 minutes')}</strong></div>${latest.slice(0,24).map(x=>card(x,true)).join('')}</div>`;if(older.length)html+=`<aside class="newsArchiveBox"><div class="newsBoxTitle"><strong>${tr('अघिल्लो अपडेट • १०–३० मिनेट','Earlier updates • 10–30 minutes')}</strong></div>${older.slice(0,30).map(x=>card(x,false)).join('')}</aside>`;if(!all.length)html=safety();host.innerHTML=html||`<div class="empty">${failed?tr('समाचार स्रोत फेरि जाँच हुँदैछ','Checking news sources again'):tr('नयाँ अपडेट प्रतीक्षा','Waiting for new updates')}</div>`}
async function snapshot(){let ok=false;for(const u of SNAP)try{const r=await fetch(u+'?_news='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);const j=await r.json();if(Array.isArray(j.items)){snap=j.items.filter(x=>ALLOWED.has(x.source));ok=true;break}}catch{}failed=!ok&&!direct.length;render()}
async function ronb(){try{const r=await fetch(RONB+'&_news='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);const j=await r.json();if(Array.isArray(j)){direct=j.map(x=>{let t=x.date_gmt||x.modified_gmt||'';if(t&&!/[zZ]|[+-]\d\d:\d\d$/.test(t))t+='Z';return{title:String(x?.title?.rendered||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim(),url:x.link,published_at:t,source:'RONB Post'}}).filter(x=>x.title&&x.url&&ts(x.published_at));failed=false}}catch{}render()}
function sync(){snapshot();ronb()}
function boot(){sync();setInterval(sync,POLL);setInterval(render,5000);window.addEventListener('online',sync);window.addEventListener('focus',sync);window.addEventListener('fslanguage',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});window.FloodSafeNews={refresh:sync,get items(){return merged()}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
