(()=>{'use strict';if(window.__fsNewsSnapshot)return;window.__fsNewsSnapshot=true;
const REFRESH=10*60*1000,NEW_WINDOW=60*60*1000,RECENT_WINDOW=6*60*60*1000,FUTURE_ALLOW=10*60*1000;
const URLS=['../../data/national-news.json','../../data/floodsafe-news.json'];let cache=[],last=0,loadError=false,feedMeta={};
const el=()=>document.getElementById('liveNews'),lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne',tr=(n,e)=>lang()==='en'?e:n,ts=v=>+new Date(v||0)||0,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function age(t){const m=Math.max(0,Math.floor((Date.now()-ts(t))/60000));if(m<1)return tr('अहिले','Now');if(m<60)return tr(`${m} मिनेट अघि`,`${m} min ago`);const h=Math.floor(m/60);return tr(`${h} घण्टा अघि`,`${h} hr ago`)}
function card(x,isNew){const a=document.createElement('article');a.className='newsItem '+(isNew?'':'oldNews');a.innerHTML=`<h4>${esc(x.title)}</h4><div class="meta">${esc(x.source||'Verified source')} • ${age(x.published_at)} ${isNew?'<b class="liveDot">NEW</b>':''}</div><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${tr('समाचार खोल्नुहोस्','Open article')} ↗</a>`;return a}
function render(){const o=el();if(!o)return;const now=Date.now();const all=cache.filter(x=>{const t=ts(x.published_at);return t&&now-t>=-FUTURE_ALLOW&&now-t<=RECENT_WINDOW}).sort((a,b)=>ts(b.published_at)-ts(a.published_at));const fresh=all.filter(x=>now-ts(x.published_at)<=NEW_WINDOW);const headline=(fresh.length?fresh:all.slice(0,5)).slice(0,12);const used=new Set(headline.map(x=>x.url||x.title));const rest=all.filter(x=>!used.has(x.url||x.title));o.innerHTML='';const n=document.createElement('div');n.className='newsFreshBox';n.innerHTML=`<div class="newsBoxTitle"><strong>${tr('पछिल्ला प्रमाणित समाचार','Latest verified news')}</strong><span>${tr('हरेक १० मिनेटमा नयाँ समाचार जाँच','checks for new stories every 10 min')}</span></div>`;headline.forEach(x=>n.appendChild(card(x,now-ts(x.published_at)<=NEW_WINDOW)));if(!headline.length)n.innerHTML+=`<div class="empty">${loadError?tr('समाचार फिड लोड हुन सकेन। केही बेरमा फेरि जाँच हुन्छ।','News feed could not load. It will retry automatically.'):tr('पछिल्ला ६ घण्टामा प्रमाणित नयाँ समाचार भेटिएन।','No verified story found in the last 6 hours.')}</div>`;o.appendChild(n);const p=document.createElement('aside');p.className='newsArchiveBox';p.innerHTML=`<div class="newsBoxTitle"><strong>${tr('अघिल्ला समाचार','Earlier today')}</strong><span>${tr('पछिल्ला ६ घण्टासम्म देखाइन्छ','kept for up to 6 hours')}</span></div>`;rest.slice(0,20).forEach(x=>p.appendChild(card(x,false)));if(!rest.length&&headline.length)p.innerHTML+=`<div class="empty">${tr('अहिले थप पुराना समाचार छैनन्।','No more recent stories right now.')}</div>`;o.appendChild(p)}
async function sync(force){if(!force&&Date.now()-last<REFRESH)return;last=Date.now();loadError=false;let loaded=false;for(const url of URLS){try{const r=await fetch(url+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)continue;const j=await r.json();if(Array.isArray(j.items)){cache=j.items;feedMeta=j;loaded=true;break}}catch(e){}}if(!loaded)loadError=true;render()}
function boot(){sync(true);setInterval(()=>sync(false),60000);setInterval(render,15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync(true)});window.addEventListener('online',()=>sync(true));window.addEventListener('fslanguage',render);window.FloodSafeNews={refresh:()=>sync(true),get items(){return cache.slice()},get meta(){return feedMeta}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();