(()=>{'use strict';
if(window.__fsRainTimingV2)return;window.__fsRainTimingV2=true;
const $=id=>document.getElementById(id),B={minLon:80,maxLon:88.35,minLat:26.2,maxLat:30.5};
const G={lat:null,lon:null,lastWet:null,lastForecastKey:'',lastNotifyKey:'',lastFetch:0,lastMilestone:''};
const lang=()=>window.FloodSafe?.state?.lang||localStorage.getItem('fs-flood-lang')||'ne';
const tr=(ne,en)=>lang()==='en'?en:ne;
const insideNepal=(la,lo)=>Number.isFinite(la)&&Number.isFinite(lo)&&la>=B.minLat&&la<=B.maxLat&&lo>=B.minLon&&lo<=B.maxLon;
const wet=v=>Number(v||0)>=0.05;
function clock(t){try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{hour:'2-digit',minute:'2-digit',hour12:false}).format(t)}catch{return''}}
function mins(ms){return Math.max(0,Math.ceil(ms/60000))}
function setOutsideLanguage(){const strong=document.querySelector('#outsideNotice strong');if(strong)strong.textContent=tr('🌍 तपाईंको हालको स्थान नेपाल बाहिर छ','🌍 Your current location is outside Nepal');if($('outsideNoticeText'))$('outsideNoticeText').textContent=tr('तपाईं नेपाल बाहिर हुनुहुन्छ। नेपालका नदी/बाढी स्थिति हेर्न नक्साबाट क्षेत्र छान्नुहोस्; मौसम तपाईंको हालको स्थानकै देखिन्छ।','You are outside Nepal. Choose a Nepal area on the map for river/flood status; weather stays on your current location.')}
function setPlace(){if(G.lat==null)return;const p=$('place');if(!p)return;p.textContent=insideNepal(G.lat,G.lon)?tr(`📍 हालको स्थान • ${G.lat.toFixed(3)}, ${G.lon.toFixed(3)}`,`📍 Current location • ${G.lat.toFixed(3)}, ${G.lon.toFixed(3)}`):tr(`🌍 हालको स्थान • नेपाल बाहिर • ${G.lat.toFixed(3)}, ${G.lon.toFixed(3)}`,`🌍 Current location • outside Nepal • ${G.lat.toFixed(3)}, ${G.lon.toFixed(3)}`)}
function notify(title,body,key){if(!window.FloodSafe?.state?.alertsOn||!('Notification'in window)||Notification.permission!=='granted'||G.lastNotifyKey===key)return;G.lastNotifyKey=key;try{new Notification(title,{body,icon:'../v24/icon.svg',tag:'floodsafe-rain-'+key,renotify:false})}catch{}}
function transition(j,currentWet){const times=j?.minutely_15?.time||[],vals=(j?.minutely_15?.precipitation||j?.minutely_15?.rain||[]).map(Number),now=Date.now(),a=[];for(let i=0;i<Math.min(times.length,vals.length);i++){const raw=String(times[i]),t=Date.parse(raw.endsWith('Z')?raw:raw+'Z');if(Number.isFinite(t)&&t>=now-5*60000)a.push({t,v:vals[i]})}if(!a.length)return null;if(!currentWet){const x=a.find(q=>wet(q.v));return x?{type:'start',time:x.t,minutes:mins(x.t-now)}:null}let seenWet=false;for(const q of a){if(wet(q.v)){seenWet=true;continue}if(seenWet||q.t<=now+20*60000)return{type:'stop',time:q.t,minutes:mins(q.t-now)}}return null}
function timingText(ev,currentWet){if(!ev)return currentWet?tr('🌧️ अहिले पानी परिरहेको छ • नजिकको forecast मा रोक्ने समय देखिएको छैन','🌧️ Raining now • no stop time in the near-term forecast'):tr('☁️ नजिकको forecast मा पानी सुरु हुने समय देखिएको छैन','☁️ No rain start in the near-term forecast');const at=clock(new Date(ev.time)),m=ev.minutes;if(ev.type==='start')return tr(`🌧️ पानी सुरु हुन करिब ${m} मिनेट • अनुमानित समय ${at}`,`🌧️ Rain starts in about ${m} min • around ${at}`);return tr(`🌤️ पानी रोकिन करिब ${m} मिनेट • अनुमानित समय ${at}`,`🌤️ Rain stops in about ${m} min • around ${at}`)}
function updateNotificationState(currentWet,ev){if(G.lastWet!==null&&currentWet!==G.lastWet){if(currentWet)notify(tr('🌧️ पानी सुरु भयो','🌧️ Rain started'),tr('तपाईंको हालको स्थानमा पानी सुरु भएको छ।','Rain has started at your current location.'),'actual-start-'+Math.floor(Date.now()/60000));else notify(tr('🌤️ पानी रोकियो','🌤️ Rain stopped'),tr('तपाईंको हालको स्थानमा पानी रोकिएको छ।','Rain has stopped at your current location.'),'actual-stop-'+Math.floor(Date.now()/60000))}G.lastWet=currentWet;if(!ev||ev.minutes<=0||ev.minutes>60)return;const thresholds=[15,10,5,1],milestone=thresholds.find(x=>ev.minutes<=x);if(!milestone)return;const key=`${ev.type}-${ev.time}-${milestone}`;if(G.lastMilestone===key)return;G.lastMilestone=key;const at=clock(new Date(ev.time));if(ev.type==='start')notify(tr(`🌧️ करिब ${ev.minutes} मिनेटमा पानी`,`🌧️ Rain in about ${ev.minutes} min`),tr(`अनुमानित सुरु समय ${at}।`,`Expected start around ${at}.`),key);else notify(tr(`🌤️ करिब ${ev.minutes} मिनेटमा पानी रोकिने`,`🌤️ Rain stops in about ${ev.minutes} min`),tr(`अनुमानित रोक्ने समय ${at}।`,`Expected stop around ${at}.`),key)}
async function refresh(force=false){if(G.lat==null||G.lon==null)return;if(!force&&Date.now()-G.lastFetch<30000)return;G.lastFetch=Date.now();try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${G.lat}&longitude=${G.lon}&current=temperature_2m,relative_humidity_2m,precipitation,rain,weather_code,wind_speed_10m&minutely_15=precipitation,rain&forecast_minutely_15=32&timezone=GMT`;const r=await fetch(url+'&_rain='+Date.now(),{cache:'no-store',credentials:'omit'});if(!r.ok)throw Error(r.status);const j=await r.json(),c=j.current||{},p=Number(c.rain??c.precipitation??0),nowWet=wet(p);if($('temp'))$('temp').textContent=c.temperature_2m!=null?Math.round(c.temperature_2m)+'°':'—°';if($('rain'))$('rain').textContent=Number.isFinite(p)?p.toFixed(1)+' mm':'—';if($('humidity'))$('humidity').textContent=c.relative_humidity_2m!=null?Math.round(c.relative_humidity_2m)+'%':'—';if($('wind'))$('wind').textContent=c.wind_speed_10m!=null?Math.round(c.wind_speed_10m)+' km/h':'—';if($('weatherText'))$('weatherText').textContent=nowWet?(p>2?tr('अहिले पानी परिरहेको छ','Raining now'):tr('अहिले हल्का पानी परिरहेको छ','Light rain now')):tr('अहिले पानी परेको छैन','No rain right now');const ev=transition(j,nowWet);if($('rainTiming'))$('rainTiming').textContent=timingText(ev,nowWet);setPlace();setOutsideLanguage();updateNotificationState(nowWet,ev)}catch{if($('rainTiming'))$('rainTiming').textContent=tr('वर्षा सुरु/रोक्ने समय अहिले उपलब्ध छैन','Rain start/stop timing is temporarily unavailable')}}
function got(p){G.lat=p.coords.latitude;G.lon=p.coords.longitude;const inNP=insideNepal(G.lat,G.lon);setPlace();setOutsideLanguage();if($('outsideNotice'))$('outsideNotice').hidden=inNP;if(inNP){window.FloodSafe?.setFocus?.(G.lat,G.lon,'gps');setTimeout(()=>window.FloodSafeMap?.select?.(G.lat,G.lon,true),100)}refresh(true)}
function request(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(got,()=>{}, {enableHighAccuracy:true,timeout:12000,maximumAge:15000})}
document.getElementById('locateBtn')?.addEventListener('click',()=>setTimeout(request,0),true);
document.getElementById('alertBtn')?.addEventListener('click',()=>setTimeout(()=>refresh(true),700));
window.addEventListener('fslanguage',()=>{setPlace();setOutsideLanguage();if(G.lat!=null)refresh(true)});
setOutsideLanguage();setInterval(()=>{if(G.lat!=null)refresh(true)},30000);setInterval(setOutsideLanguage,1500);
window.FloodSafeRain={refresh,request,get state(){return{lat:G.lat,lon:G.lon,lastWet:G.lastWet}}};
})();