(()=>{
'use strict';
if(window.__fsRoadLiveV5)return;window.__fsRoadLiveV5=true;const PAGE=document.body.dataset.page||'';if(PAGE!=='alerts'&&PAGE!=='roads')return;
const $=id=>document.getElementById(id),API='https://bipadportal.gov.np/api/v1/highway/?limit=800',DOR='../../data/dor-road-summary.json';
let roads=[],dor=null,busy=false,lastCheck=0;const lang=()=>localStorage.getItem('fs23-lang')==='en'?'en':'ne',tr=(ne,en)=>window.FSLang?.pick?window.FSLang.pick(ne,en):(lang()==='en'?en:ne),rows=j=>Array.isArray(j)?j:(j?.results||j?.data||j?.objects||[]),norm=s=>String(s||'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim(),stamp=o=>o?.modifiedOn||o?.updatedOn||o?.createdOn||o?.created_at||o?.updated_at||o?.date||null;
async function get(url,ms=6500){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_rv5='+Date.now(),{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
function name(o){if(lang()==='ne')return String(o?.roadNameNe||o?.road_name_ne||o?.highwayNameNe||o?.highway_name_ne||o?.titleNe||o?.nameNe||o?.roadName||o?.road_name||o?.highwayName||o?.highway_name||o?.highway?.name||o?.title||o?.name||o?.routeName||'सडक अपडेट');return String(o?.roadNameEn||o?.road_name_en||o?.highwayNameEn||o?.highway_name_en||o?.titleEn||o?.nameEn||o?.roadName||o?.road_name||o?.highwayName||o?.highway_name||o?.highway?.name||o?.title||o?.name||o?.routeName||'Road update')}
function place(o){if(lang()==='ne')return String(o?.locationNe||o?.placeNe||o?.districtNameNe||o?.district_name_ne||o?.district?.titleNe||o?.district?.nameNe||o?.location||o?.place||o?.districtName||o?.district_name||o?.district?.title||o?.district?.name||'');return String(o?.locationEn||o?.placeEn||o?.districtNameEn||o?.district_name_en||o?.district?.titleEn||o?.district?.nameEn||o?.location||o?.place||o?.districtName||o?.district_name||o?.district?.title||o?.district?.name||'')}
function raw(o){try{return [o?.status,o?.roadStatus,o?.road_status,o?.closureStatus,o?.closure_status,o?.condition,o?.state,o?.remarks,JSON.stringify(o||{})].filter(Boolean).join(' ').toLowerCase()}catch{return''}}
function state(o){const s=raw(o);if(/partial|partially|partial_open|one.?way|आंशिक|एकतर्फी/.test(s))return'PARTIAL';if(/closed|blocked|obstructed|पूर्ण बन्द|अवरुद्ध|सडक बन्द/.test(s))return'CLOSED';if(/\bopen(?:ed)?\b|fully open|सुचारु|खुला/.test(s))return'OPEN';return'OTHER'}
function reason(o){const s=String(o?.closureReason||o?.closure_reason||o?.reason||o?.cause||o?.descriptionNe||o?.descriptionEn||o?.description||o?.remarks||'').toLowerCase();if(/landslide|mudslide|पहिरो|भूस्खलन/.test(s))return tr('पहिरो','Landslide');if(/flood|inundat|बाढी|डुबान/.test(s))return tr('बाढी / डुबान','Flood / inundation');if(/bridge|पुल/.test(s))return tr('पुल वा सडक क्षति','Bridge or road damage');if(/accident|collision|दुर्घटना|ठक्कर/.test(s))return tr('दुर्घटना','Accident');if(/maintenance|repair|मर्मत/.test(s))return tr('मर्मत कार्य','Maintenance work');return tr('कारण विश्वसनीय स्रोतमा स्पष्ट प्रकाशित छैन','Reason is not clearly published by a reliable source')}
function alt(o){for(const k of ['alternativeRoute','alternative_route','alternateRoute','alternate_route','detour','diversion','reroute','routeAlternative','alternative']){const v=o?.[k];if(typeof v==='string'&&v.trim().length>2)return v.trim()}const s=String(o?.remarks||o?.description||o?.details||''),m=s.match(/(?:alternative route|alternate route|detour|diversion|वैकल्पिक मार्ग|वैकल्पिक सडक)\s*[:\-]?\s*([^।.;]{3,180})/i);return m?m[1].trim():''}
function routeKey(o){const rawName=String(o?.roadName||o?.road_name||o?.highwayName||o?.highway_name||o?.highway?.name||o?.title||o?.name||o?.routeName||'');return norm(rawName).replace(/\b(highway|road|rajmarg)\b/g,'').replace(/राजमार्ग|मार्ग/g,'').trim()||norm(rawName)}
function grouped(){const m=new Map();for(const o of roads){const k=routeKey(o);if(!k)continue;const old=m.get(k),nt=+new Date(stamp(o)||0),ot=+new Date(stamp(old)||0);if(!old){m.set(k,o);continue}if(nt&&ot){if(nt>=ot)m.set(k,o);continue}if(nt&&!ot){m.set(k,o);continue}if(!nt&&!ot&&state(old)==='OTHER'&&state(o)!=='OTHER')m.set(k,o)}return[...m.values()].sort((a,b)=>(+new Date(stamp(b)||0))-(+new Date(stamp(a)||0)))}
function npTime(t=Date.now()){try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return'—'}}
function clear(e){if(e)while(e.firstChild)e.removeChild(e.firstChild)}function make(t,c,x){const e=document.createElement(t);if(c)e.className=c;if(x!==undefined)e.textContent=x;return e}
function card(out,o){const st=state(o),a=make('article','item');a.dataset.roadOwner='5';a.appendChild(make('span','tag '+(st==='CLOSED'?'red':''),st==='CLOSED'?tr('बन्द','CLOSED'):tr('आंशिक खुला','PARTIALLY OPEN')));a.appendChild(make('h4','',name(o)));const al=alt(o),body=tr('कारण: ','Reason: ')+reason(o)+(place(o)?' • '+tr('स्थान: ','Location: ')+place(o):'')+'\n'+tr('वैकल्पिक मार्ग: ','Alternative route: ')+(al||tr('आधिकारिक/विश्वसनीय स्रोतमा प्रकाशित छैन','Not published by an official/reliable source'));a.appendChild(make('p','',body));a.appendChild(make('div','meta',(stamp(o)?tr('अपडेट: ','Updated: ')+npTime(stamp(o))+' • ':'')+'BIPAD highway'));const d=make('div','meta'),l=make('a','',tr('स्रोत खोल्नुहोस्','Open source'));l.href='https://navigate.dor.gov.np/app/dashboard';l.target='_blank';l.rel='noopener noreferrer';d.appendChild(l);a.appendChild(d);out.appendChild(a)}
function render(){const out=$('roadCurrentListLive');if(!out)return;const all=grouped(),closed=all.filter(o=>state(o)==='CLOSED'),partial=all.filter(o=>state(o)==='PARTIAL'),open=all.filter(o=>state(o)==='OPEN'),problems=[...closed,...partial].sort((a,b)=>(+new Date(stamp(b)||0))-(+new Date(stamp(a)||0))).slice(0,12);clear(out);for(const o of problems)card(out,o);if(!problems.length)out.appendChild(make('div','empty',tr('अहिले स्रोतमा बन्द वा आंशिक बन्द सडक समस्या भेटिएको छैन।','No closed or partially closed road problem is currently found in the source.')));const officialClosed=Number.isFinite(Number(dor?.closed))?Number(dor.closed):closed.length,c=$('roadAlertCountLive');if(c)c.textContent=String(officialClosed);const s=$('roadOfficialSummaryLive');if(s){const ds=dor?tr('सडक विभाग: ','DoR: ')+(dor.closed??'—')+tr(' बन्द • ',' closed • ')+(dor.partially_opened??'—')+tr(' आंशिक • ',' partial • ')+(dor.opened??'—')+tr(' खुला',' open'):tr('सडक विभाग सारांश जाँच हुँदैछ','Checking DoR summary');s.textContent=ds+' • BIPAD '+closed.length+tr(' बन्द • ',' closed • ')+partial.length+tr(' आंशिक • ',' partial • ')+open.length+tr(' खुला • ',' open • ')+tr('जाँच ','checked ')+(lastCheck?npTime(lastCheck):'—')}window.__fsRoadState={dor:dor?{closed:Number(dor.closed),partial:Number(dor.partially_opened),open:Number(dor.opened)}:null,bipad:{closed:closed.length,partial:partial.length,open:open.length},checkedAt:lastCheck,owner:'road-v5'}}
async function poll(){if(busy||document.hidden||!navigator.onLine)return;busy=true;try{const [a,b]=await Promise.allSettled([get(API),get(DOR,5000)]);if(a.status==='fulfilled')roads=rows(a.value);if(b.status==='fulfilled')dor=b.value;lastCheck=Date.now();render()}finally{busy=false}}
function boot(){poll();setInterval(poll,5000);setInterval(()=>{const s=$('roadOfficialSummaryLive');if(s&&lastCheck&&!busy&&window.__fsRoadState)s.dataset.heartbeat=String(Date.now())},1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});window.addEventListener('online',poll);window.addEventListener('fs-language-change',render)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();