(()=>{
'use strict';
const $=id=>document.getElementById(id),NPT='Asia/Kathmandu',FETCH_MS=60000;let pos=null,place='',busy=false,watch=null,lastFetch=0,lastGood=0;
const lang=()=>localStorage.getItem('fs23-lang')==='en'?'en':'ne',tr=(ne,en)=>window.FSLang?.pick?window.FSLang.pick(ne,en):(lang()==='en'?en:ne);
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function set(id,v){const e=$(id);if(e&&e.textContent!==String(v))e.textContent=v}
function name(c){const ne={0:'सफा',1:'मुख्यतः सफा',2:'आंशिक बादल',3:'बादल',45:'कुहिरो',48:'कुहिरो',51:'हल्का झरी',53:'झरी',55:'घना झरी',61:'हल्का वर्षा',63:'वर्षा',65:'भारी वर्षा',80:'वर्षा झरी',81:'वर्षा झरी',82:'भारी झरी',95:'मेघगर्जन',96:'असिना सहित मेघगर्जन',99:'तीव्र मेघगर्जन'},en={0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Cloudy',45:'Fog',48:'Fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorm',96:'Thunderstorm with hail',99:'Severe thunderstorm'};return(lang()==='en'?en:ne)[Number(c)]||tr('मौसम','Weather')}
function npt(t=Date.now()){try{return new Intl.DateTimeFormat(lang()==='en'?'en-GB':'ne-NP',{timeZone:NPT,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t))+' NPT'}catch{return'—'}}
async function json(url,ms=7000){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_rt='+Date.now(),{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(to)}}
async function reverse(c){try{const j=await json(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${c[0]}&lon=${c[1]}&zoom=16&addressdetails=1&accept-language=${lang()==='en'?'en':'ne,en'}`,5000),a=j.address||{};return[a.village||a.town||a.city||a.municipality||a.suburb,a.county||a.state_district,a.state].filter(Boolean).slice(0,3).join(' • ')||tr('तपाईंको स्थान','Your location')}catch{return tr('तपाईंको GPS स्थान','Your GPS location')}}
function heartbeat(){if(!pos){set('appStatus',tr('GPS/स्थान पर्खिँदै • app प्रत्यक्ष ','Waiting for GPS/location • app live ')+npt());return}set('appStatus',(lastGood?tr('मौसम स्रोत ','Weather source ')+npt(lastGood):tr('मौसम स्रोत जाँच हुँदैछ','Checking weather source'))+tr(' • app प्रत्यक्ष ',' • app live ')+npt())}
async function load(force=false){if(!pos||busy||document.hidden||!navigator.onLine)return;if(!force&&Date.now()-lastFetch<FETCH_MS)return;busy=true;lastFetch=Date.now();set('appStatus',tr('मौसम स्रोत जाँच हुँदैछ…','Checking weather source…'));try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${pos[0]}&longitude=${pos[1]}&current=temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,rain,weather_code,wind_speed_10m,wind_gusts_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum&forecast_days=1&timezone=Asia%2FKathmandu`,[w,p]=await Promise.all([json(u),place?Promise.resolve(place):reverse(pos)]);place=p;const c=w.current||{},d=w.daily||{};lastGood=Date.now();set('wxPlace',p+' • '+pos[0].toFixed(4)+', '+pos[1].toFixed(4));set('wxTemp',num(c.temperature_2m)!=null?Math.round(c.temperature_2m)+'°':'—°');set('wxCondition',name(c.weather_code));set('wxFeels',num(c.apparent_temperature)!=null?Math.round(c.apparent_temperature)+'°':'—');set('wxRain',num(c.precipitation)!=null?Number(c.precipitation).toFixed(1)+' mm':'—');set('wxHumidity',num(c.relative_humidity_2m)!=null?Math.round(c.relative_humidity_2m)+'%':'—');set('wxWind',num(c.wind_speed_10m)!=null?Math.round(c.wind_speed_10m)+' km/h':'—');set('wxGust',num(c.wind_gusts_10m)!=null?Math.round(c.wind_gusts_10m)+' km/h':'—');set('wxRange',(num(d.temperature_2m_min?.[0])!=null?Math.round(d.temperature_2m_min[0])+'°':'—')+' / '+(num(d.temperature_2m_max?.[0])!=null?Math.round(d.temperature_2m_max[0])+'°':'—'));set('wxChance',num(d.precipitation_probability_max?.[0])!=null?Math.round(d.precipitation_probability_max[0])+'%':'—');const rain=num(c.precipitation)||0,ch=num(d.precipitation_probability_max?.[0])||0,code=Number(c.weather_code);set('wxRisk',code>=95?tr('⚡ मेघगर्जन संकेत — स्थानीय खोला छिटो बढ्न सक्छ।','⚡ Thunderstorm signal — local streams can rise quickly.'):rain>=5||ch>=70?tr('🌧 वर्षाको उच्च संकेत — चेतावनी र नजिकको नदी जाँच गर्नुहोस्।','🌧 High rain signal — check alerts and nearby rivers.'):tr('आजको स्थानीय मौसम मोडेलमा ठूलो वर्षा संकेत छैन।','No major rain signal in today’s local weather model.'));heartbeat()}catch{set('appStatus',tr('मौसम स्रोत पुनः जडान हुँदैछ • app प्रत्यक्ष ','Reconnecting weather source • app live ')+npt())}finally{busy=false}}
function save(p){const next=[p.coords.latitude,p.coords.longitude],moved=!pos||Math.abs(next[0]-pos[0])+Math.abs(next[1]-pos[1])>.002;pos=next;localStorage.setItem('fs-v25-location',JSON.stringify(pos));if(moved){place='';load(true)}}
function arm(){if(!navigator.geolocation){set('appStatus',tr('GPS उपलब्ध छैन','GPS unavailable'));return}navigator.geolocation.getCurrentPosition(p=>{save(p);load(true);if(watch===null)watch=navigator.geolocation.watchPosition(save,()=>{}, {enableHighAccuracy:true,maximumAge:15000,timeout:20000})},()=>set('appStatus',tr('स्थान अनुमति आवश्यक','Location permission required')),{enableHighAccuracy:true,maximumAge:10000,timeout:15000})}
function boot(){try{const s=JSON.parse(localStorage.getItem('fs-v25-location')||'null');if(Array.isArray(s)&&s.length===2){pos=s;load(true)}}catch{}$('gpsWeatherBtn')?.addEventListener('click',arm);if(navigator.permissions)navigator.permissions.query({name:'geolocation'}).then(x=>{if(x.state==='granted')arm()}).catch(()=>{});heartbeat();setInterval(heartbeat,1000);setInterval(()=>load(false),30000);window.addEventListener('online',()=>load(true));document.addEventListener('visibilitychange',()=>{if(!document.hidden)load(true)});window.addEventListener('fs-language-change',()=>{place='';load(true);heartbeat()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();