import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CATALOG="https://bipadportal.gov.np/api/v1/river-stations/?limit=2000";
const LATEST="https://bipadportal.gov.np/api/v1/river-stations/?latest=true&limit=2000";
const OBS="https://bipadportal.gov.np/api/v1/river/?limit=2000";
const BACKGROUND_SYNC_AFTER_MS=10000;
const FRESH_MS=10*60*1000;
const CORS={
  "content-type":"application/json",
  "access-control-allow-origin":"*",
  "access-control-allow-headers":"content-type, apikey, authorization",
  "access-control-allow-methods":"GET,POST,OPTIONS",
  "cache-control":"no-store, no-cache, must-revalidate"
};
const val=(o:any,ks:string[])=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=="")return v}return null};
const num=(v:any)=>{if(typeof v==="number")return Number.isFinite(v)?v:null;if(typeof v!=="string"||!/^[-+]?(?:\d+\.?\d*|\.\d+)$/.test(v.trim()))return null;const n=Number(v);return Number.isFinite(n)?n:null};
const rows=(j:any)=>Array.isArray(j)?j:Array.isArray(j?.results)?j.results:Array.isArray(j?.data)?j.data:Array.isArray(j?.data?.results)?j.data.results:[];
const observed=(o:any)=>val(o,["waterLevelOn","water_level_on","measuredOn","measured_on","measurementTime","measurement_time","observationTime","observation_time","observedAt","observed_at","datetime","timestamp"]);
const level=(o:any)=>num(val(o,["waterLevel","water_level","currentWaterLevel","current_water_level","currentLevel","current_level","level","value","_lastWaterLevel"]));
const warning=(o:any)=>num(val(o,["warningLevel","warning_level","warningThreshold","warning_threshold","_lastWarningLevel"]));
const danger=(o:any)=>num(val(o,["dangerLevel","danger_level","dangerThreshold","danger_threshold","_lastDangerLevel"]));
const discharge=(o:any)=>num(val(o,["discharge","currentDischarge","current_discharge","flowRate","flow_rate","flow","_lastDischarge"]));
const status=(o:any)=>String(val(o,["status","status_name","statusText","status_text","alertStatus","alert_status","riskLevel","risk_level"])??"");
const name=(o:any)=>String(val(o,["title","name","stationName","station_name","riverName","river_name"])??o?.station?.name??"");
function ids(o:any){const out:string[]=[];for(const src of[o,o?.station,o?.riverStation,o?.river_station]){if(!src||typeof src!=="object")continue;for(const k of["stationSeriesId","station_series_id","stationId","station_id","stationIndex","station_index","id"]){const v=src?.[k];if(v!==undefined&&v!==null&&v!=="")out.push(String(v))}}return[...new Set(out)]}
function key(o:any){return ids(o)[0]||`name:${name(o).toLowerCase().trim()}`}
function coords(o:any){for(const c of[o?.point?.coordinates,o?.location?.coordinates,o?.geometry?.coordinates,o?.centroid?.coordinates]){if(Array.isArray(c)&&c.length>=2){const a=num(c[0]),b=num(c[1]);if(a!==null&&b!==null){if(a>=79.5&&a<=89&&b>=26&&b<=31)return{longitude:a,latitude:b};if(b>=79.5&&b<=89&&a>=26&&a<=31)return{longitude:b,latitude:a}}}}return{longitude:num(val(o,["longitude","lng","lon","stationLongitude","station_longitude"])),latitude:num(val(o,["latitude","lat","stationLatitude","station_latitude"]))}}
function client(){const u=Deno.env.get("SUPABASE_URL"),k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!u||!k)throw Error("Supabase service environment unavailable");return createClient(u,k,{auth:{persistSession:false}})}
async function fetchAll(url:string){let next:string|null=url,out:any[]=[],seen=new Set<string>();for(let p=0;next&&p<30;p++){if(seen.has(next))break;seen.add(next);const requestUrl=new URL(next);requestUrl.searchParams.set("_fs",String(Date.now()));const r=await fetch(requestUrl,{headers:{accept:"application/json","cache-control":"no-cache"},cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error(`BIPAD ${r.status}`);const j=await r.json(),part=rows(j);out.push(...part);const n=j?.next??j?.data?.next??null;if(!n||!part.length)break;next=/^https?:/i.test(n)?n:new URL(n,url).href}return out}
function latestIndex(items:any[]){const by=new Map<string,any>();for(const o of items||[]){if(level(o)===null||!Number.isFinite(Date.parse(String(observed(o)||"")))||Date.parse(String(observed(o)))>Date.now()+300000)continue;const t=Date.parse(String(observed(o)||""))||0;for(const id of ids(o)){const old=by.get(id),ot=old?(Date.parse(String(observed(old)||""))||0):-1;if(!old||t>=ot)by.set(id,o)}}return by}
function merge(catalog:any[],liveRows:any[]){const idx=latestIndex(liveRows),seen=new Set<string>(),out:any[]=[];for(const meta of catalog){let live:any=null;for(const id of ids(meta)){if(idx.has(id)){live=idx.get(id);break}}const c=coords(meta),payload={...meta,...(live||{}),stationSeriesId:val(meta,["stationSeriesId","station_series_id"])??val(live,["stationSeriesId","station_series_id"]),stationId:val(meta,["stationId","station_id","id"])??val(live,["stationId","station_id"]),title:name(meta)||name(live),basin:val(meta,["basin","basinName","basin_name"])??val(live,["basin","basinName","basin_name"]),district:val(meta,["district","districtName","district_name"])??val(live,["district","districtName","district_name"]),longitude:c.longitude,latitude:c.latitude,waterLevel:live?level(live):null,warningLevel:(live?warning(live):null)??warning(meta),dangerLevel:(live?danger(live):null)??danger(meta),discharge:live?discharge(live):null,waterLevelOn:live?observed(live):null,status:live?status(live):null,_floodsafeOfficialMerged:true,_floodsafeObservationSource:live?"BIPAD latest/river observation":null};const k=key(payload);if(k&&!seen.has(k)){seen.add(k);out.push(payload)}}for(const live of liveRows){const k=key(live);if(k&&!seen.has(k)){seen.add(k);out.push({...live,_floodsafeOfficialMerged:true,_floodsafeObservationSource:"BIPAD live observation"})}}return out}
async function sync(){const started=new Date().toISOString();const [catalogRes,latestRes,obsRes]=await Promise.allSettled([fetchAll(CATALOG),fetchAll(LATEST),fetchAll(OBS)]);const catalog=catalogRes.status==='fulfilled'?catalogRes.value:[];if(!catalog.length)throw Error("BIPAD catalogue empty");const latest=latestRes.status==='fulfilled'?latestRes.value:[],obs=obsRes.status==='fulfilled'?obsRes.value:[];if(!latest.length&&!obs.length)throw Error("BIPAD live river feeds empty");const all=merge(catalog,[...latest,...obs]),sb=client();const mapped=all.map((o:any)=>{const c=coords(o);return{station_key:key(o),station_id:String(val(o,["stationId","station_id","id"])??""),station_series_id:String(val(o,["stationSeriesId","station_series_id"])??""),name:name(o),basin:String(val(o,["basin","basinName","basin_name"])??""),district:String(val(o,["district","districtName","district_name"])??""),latitude:c.latitude,longitude:c.longitude,water_level:level(o),warning_level:warning(o),danger_level:danger(o),official_status:status(o),measured_at:observed(o),official_payload:o,source:"BIPAD/DHM official cached mirror",synced_at:started}}).filter((x:any)=>x.station_key);for(let i=0;i<mapped.length;i+=200){const {error}=await sb.from("river_stations").upsert(mapped.slice(i,i+200),{onConflict:"station_key"});if(error)throw error}const latestCount=all.filter((x:any)=>level(x)!==null&&!!observed(x)).length,now=Date.now(),freshCount=all.filter((x:any)=>{const t=Date.parse(String(observed(x)||""));return level(x)!==null&&Number.isFinite(t)&&now-t>=-5*60*1000&&now-t<=FRESH_MS}).length,times=all.map((x:any)=>Date.parse(String(observed(x)||""))).filter(Number.isFinite);const {error}=await sb.from("river_sync_status").upsert({id:1,source:"BIPAD river-stations + river observations cached mirror",station_count:all.length,latest_count:latestCount,last_success_at:started,last_attempt_at:started,error:null},{onConflict:"id"});if(error)throw error;return{all,latestCount,freshCount,newest:times.length?new Date(Math.max(...times)).toISOString():null,started}}
async function cached(){const sb=client();const [{data,error},{data:state,error:se}]=await Promise.all([sb.from("river_stations").select("official_payload,measured_at").order("measured_at",{ascending:false,nullsFirst:false}),sb.from("river_sync_status").select("*").eq("id",1).maybeSingle()]);if(error)throw error;if(se)throw se;const all=(data||[]).map((x:any)=>x.official_payload).filter(Boolean),now=Date.now(),freshCount=all.filter((x:any)=>{const t=Date.parse(String(observed(x)||""));return level(x)!==null&&Number.isFinite(t)&&now-t>=-5*60*1000&&now-t<=FRESH_MS}).length,times=all.map((x:any)=>Date.parse(String(observed(x)||""))).filter(Number.isFinite);return{all,state,freshCount,newest:times.length?new Date(Math.max(...times)).toISOString():null}}
async function recordError(message:string){try{const sb=client();await sb.from("river_sync_status").upsert({id:1,last_attempt_at:new Date().toISOString(),error:message},{onConflict:"id"})}catch{}}
let pending:Promise<any>|null=null;
function queueSync(){if(pending)return;const p=sync().catch(async e=>{await recordError(e instanceof Error?e.message:String(e))}).finally(()=>{pending=null});pending=p;const rt=(globalThis as any).EdgeRuntime;if(rt?.waitUntil)rt.waitUntil(p)}
function response(x:any){return new Response(JSON.stringify({source:"BIPAD/DHM official cached mirror",fetched_at:x.state?.last_success_at??null,count:x.all.length,latest_count:x.all.filter((o:any)=>level(o)!==null&&!!observed(o)).length,fresh_10m_count:x.freshCount??0,newest_observation:x.newest??null,results:x.all}),{headers:CORS})}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});try{if(req.method!=='GET'&&req.method!=='POST')return new Response(JSON.stringify({error:'Method not allowed'}),{status:405,headers:CORS});if(req.method==='POST'){const s=await sync();return new Response(JSON.stringify({source:"BIPAD/DHM official cached mirror",fetched_at:s.started,count:s.all.length,latest_count:s.latestCount,fresh_10m_count:s.freshCount,newest_observation:s.newest,results:s.all}),{headers:CORS})}let x=await cached();if(!x.all.length){const s=await sync();x={all:s.all,state:{last_success_at:s.started,latest_count:s.latestCount},freshCount:s.freshCount,newest:s.newest};return response(x)}const age=x.state?.last_success_at?Date.now()-Date.parse(x.state.last_success_at):Infinity;if(age>BACKGROUND_SYNC_AFTER_MS)queueSync();return response(x)}catch(e){const message=e instanceof Error?e.message:String(e);await recordError(message);return new Response(JSON.stringify({error:message,source:"BIPAD/DHM official"}),{status:502,headers:CORS})}});
