(()=>{
'use strict';
const API='https://bipadportal.gov.np/api/v1/';
const POLL_STATION=10000, POLL_ROAD=15000, POLL_IMPACT=30000, POLL_WEATHER=60000;
const state={lang:localStorage.getItem('floodsafe-lang')||'ne',stations:[],prev:new Map(),stage:new Map(),lastStation:null,lastWeather:null,lastRoad:null,lastImpact:null,alerts:localStorage.getItem('floodsafe-pro-alerts')==='1',audio:null,districtNames:new Map(),busy:false};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nfmt=n=>Number.isFinite(+n)?(+n).toFixed(2).replace(/\.00$/,''):'—';
const exact={
'नेपाल समय':'Nepal time','अन्तिम लाइभ अपडेट':'Last live update','अहिलेको मौसम':'Current weather','स्थान छान्नुहोस्':'Select location','डेटा पर्खिँदै':'Waiting for data','अवस्था':'Condition','वर्षा':'Rain','हावा':'Wind','तपाईंको क्षेत्र पहिले':'Your area first','मेरो वरिपरि बाढीको अवस्था':'Flood situation around me','मेरो स्थान प्रयोग':'Use my location','नक्साको बीच छान्नुहोस्':'Use map centre','वरिपरि':'Radius','स्थान छानिएको छैन':'No location selected','स्थानीय जोखिम':'Local risk','नजिकका नदी स्टेशन':'Nearby river stations','सडक समस्या':'Road issues','वर्षा स्टेशन':'Rain stations','वरिपरिका खोला / नदी':'Nearby streams / rivers','नजिकको सडक अवस्था':'Nearby road condition','आजको बाढी प्रभाव':'Today’s flood impact','मृतक':'Deaths','घाइते':'Injured','बेपत्ता':'Missing','बाढी घटना':'Flood incidents','अहिलेको जानकारी':'Current information','लाइभ सूचना':'Live information','७७ जिल्ला स्थिति':'77 district status','जिल्ला छान्नुहोस्':'Choose district','बाढी चेतावनी ध्वनि':'Flood alert sound','सूचना सक्रिय गर्नुहोस्':'Enable alerts','ध्वनि परीक्षण':'Test sound','नेपाल बाढी नक्सा':'Nepal flood map','उपग्रह':'Satellite','सडक':'Road','NASA वर्षा':'NASA rain','लाइभ':'Live','खतरा / बन्द':'Danger / closed','चेतावनी / आंशिक':'Warning / partial','नदी/वर्षा स्टेशन':'River/rain station','तपाईंको स्थान':'Your location','नेपाल':'Nepal','ठूलो चेतावनी छैन':'No major warning','उच्च सतर्कता':'High alert','सतर्क':'Caution','ठूलो चेतावनी भेटिएन':'No major warning found','GPS सक्रिय':'GPS active','अघिल्लो स्थान':'Saved location','नक्साबाट छानिएको':'Map-selected','जिल्ला केन्द्र':'District centre','आधिकारिक रेकर्ड':'Official record','मापन उपलब्ध':'Measurement available','नाम नखुलेको खोला':'Unnamed stream','अहिले':'now','पानी बढ्दैछ':'Water rising','सामान्य':'Normal','चेतावनी':'Warning','खतरा':'Danger','प्रारम्भिक सतर्कता':'Early watch','आजको मौसम':'Today’s weather','अधिकतम':'High','न्यूनतम':'Low','वर्षाको सम्भावना':'Rain chance','आर्द्रता':'Humidity','बादल':'Cloud cover','महसुस तापक्रम':'Feels like','स्टेशन लाइभ रिपोर्ट':'Live station report','माथिल्लो बहाव निगरानी':'Upstream watch','आधिकारिक सीमा':'Official threshold','एपले देखेको बढ्दो ट्रेन्ड':'App-detected rising trend','मापन समय':'Measurement time','स्रोत':'Source','पानी सतह':'Water level','चेतावनी सतह':'Warning level','खतरा सतह':'Danger level','स्थिति':'Status','माथिल्लो स्टेशन':'Upstream station','नजिकको स्टेशन':'Nearest station','चेक समय':'Checked','आज':'Today'};
const replacements=[[/किमि टाढा/g,'km away'],[/किमि/g,'km'],[/मिनेट अघि/g,'min ago'],[/घण्टा अघि/g,'hr ago'],[/सेकेन्ड/g,'seconds'],[/से\./g,'s'],[/नदी स्टेशन/g,'river stations'],[/वर्षा स्टेशन/g,'rain stations'],[/सडक समस्या/g,'road issues'],[/आधिकारिक/g,'official'],[/चेतावनी/g,'warning'],[/सतर्कता/g,'watch'],[/खतरा/g,'danger'],[/बन्द/g,'closed'],[/आंशिक/g,'partial'],[/अपडेट/g,'update'],[/पानी सतह/g,'water level'],[/वर्षा/g,'rain'],[/तपाईंको क्षेत्र/g,'your area'],[/स्थान/g,'location'],[/जिल्ला/g,'district']];
const originals=new WeakMap(); let translating=false;
function translateText(s){const raw=String(s),trim=raw.trim();if(!trim)return raw;if(state.districtNames.has(trim))return raw.replace(trim,state.districtNames.get(trim));let out=exact[trim]||trim;if(out===trim)for(const [a,b] of replacements)out=out.replace(a,b);return raw.replace(trim,out)}
function processTextNode(n,resetOriginal=false){if(n.nodeType!==3)return;if(resetOriginal||!originals.has(n))originals.set(n,n.nodeValue);const base=originals.get(n);n.nodeValue=state.lang==='en'?translateText(base):base}
function walk(root,reset=false){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const arr=[];while(w.nextNode())arr.push(w.currentNode);arr.forEach(n=>processTextNode(n,reset))}
const mo=new MutationObserver(ms=>{if(translating)return;translating=true;for(const m of ms){if(m.type==='characterData'){originals.set(m.target,m.target.nodeValue);processTextNode(m.target)}else for(const n of m.addedNodes){if(n.nodeType===3)processTextNode(n,true);else if(n.nodeType===1)walk(n,true)}}translating=false});
function setLang(lang){state.lang=lang;localStorage.setItem('floodsafe-lang',lang);document.documentElement.lang=lang==='en'?'en':'ne';document.querySelectorAll('.langBtn').forEach(b=>b.classList.toggle('on',b.dataset.lang===lang));translating=true;walk(document.body,false);translating=false;renderStations();renderUpstream();refreshTodayWeather(false);}
function injectCSS(){const s=document.createElement('style');s.textContent=`
.langBar{display:flex;gap:5px;margin:10px 0 0}.langBtn{border:1px solid #406987;background:#071b30;color:#fff;border-radius:9px;padding:6px 9px;font-weight:900;font-size:10px;cursor:pointer}.langBtn.on{background:#dc143c;border-color:#ff6b83}.proPanel{margin-top:9px;padding:11px;background:#0a2139;border:1px solid #315777;border-radius:14px}.proHead{display:flex;align-items:center;justify-content:space-between;gap:8px}.proHead h3{font-size:14px;margin:0}.proBadge{font-size:8.5px;border-radius:99px;padding:4px 7px;background:#143d5d;color:#d9effd;font-weight:850}.proBadge.live{background:#15543e;color:#b8f5dc}.todayGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.stationCard{background:#071b30;border:1px solid #294b68;border-radius:11px;padding:9px;margin-top:7px}.stationTop{display:flex;justify-content:space-between;gap:8px}.stationCard b{font-size:11.5px}.stationCard small{display:block;color:#9fb2c3;margin-top:3px;line-height:1.35}.stage{font-size:8.5px;border-radius:99px;padding:4px 7px;font-weight:900;white-space:nowrap}.stage.normal{background:#15543e;color:#b8f5dc}.stage.rising{background:#5e4b16;color:#ffe598}.stage.warning{background:#76461b;color:#ffe1b6}.stage.danger{background:#7b2033;color:#ffd5dd}.levelBar{height:6px;background:#102e49;border-radius:99px;overflow:hidden;margin-top:7px}.levelFill{height:100%;background:linear-gradient(90deg,#2dd58b,#f7c64b,#ff9f43,#ff3f5d)}.stationMeta{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:7px}.stationMeta span{font-size:9px;background:#0b2640;border:1px solid #244763;border-radius:8px;padding:5px}.upstreamAlert{border-left:4px solid #f7c64b}.upstreamAlert.danger{border-left-color:#ff3f5d}.sourceStrip{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.sourceStrip div{font-size:9px;background:#071b30;border:1px solid #294b68;border-radius:9px;padding:7px;color:#b9cbd8}.sourceStrip b{display:block;color:#fff;margin-bottom:3px}.proNote{font-size:9.5px;color:#aebfcd;line-height:1.45;margin-top:7px}.freshPulse{animation:freshPulse .55s}@keyframes freshPulse{50%{box-shadow:0 0 0 2px #47cef755;border-color:#47cef7}}@media(max-width:900px){.todayGrid,.sourceStrip{grid-template-columns:repeat(2,1fr)}.stationMeta{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s)}
function injectUI(){const brand=document.querySelector('.brand');if(brand&&!document.getElementById('langBar')){const bar=document.createElement('div');bar.id='langBar';bar.className='langBar';bar.innerHTML='<button class="langBtn" data-lang="ne">नेपाली</button><button class="langBtn" data-lang="en">English</button><span class="proBadge live" style="align-self:center">PRO LIVE</span>';brand.insertAdjacentElement('afterend',bar);bar.querySelectorAll('button').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));}
const weather=document.querySelector('.weather');if(weather&&!$('todayWeatherPro')){const d=document.createElement('div');d.id='todayWeatherPro';d.className='proPanel';d.innerHTML='<div class="proHead"><h3>🌦 आजको मौसम</h3><span class="proBadge" id="todayWeatherAge">—</span></div><div class="todayGrid"><div class="mini"><small>अधिकतम</small><b id="wxMax">—</b></div><div class="mini"><small>न्यूनतम</small><b id="wxMin">—</b></div><div class="mini"><small>वर्षाको सम्भावना</small><b id="wxProb">—</b></div><div class="mini"><small>आर्द्रता</small><b id="wxHum">—</b></div><div class="mini"><small>बादल</small><b id="wxCloud">—</b></div><div class="mini"><small>महसुस तापक्रम</small><b id="wxFeel">—</b></div></div><div class="proNote" id="wxNote">GPS वा नक्साबाट स्थान छानेपछि आजको विस्तृत मौसम देखिन्छ।</div>';weather.insertAdjacentElement('afterend',d)}
const stats=document.querySelector('.stats');if(stats&&!$('stationPro')){const p=document.createElement('section');p.id='stationPro';p.className='proPanel';p.innerHTML='<div class="proHead"><h3>⚡ स्टेशन लाइभ रिपोर्ट</h3><span class="proBadge live" id="stationAge">—</span></div><div class="sourceStrip"><div><b>DHM / BIPAD</b><span id="stationTotal">—</span> stations</div><div><b>चेतावनी / खतरा</b><span id="stationWarn">—</span></div><div><b>बढ्दो ट्रेन्ड</b><span id="stationRise">—</span></div></div><div id="stationList"></div><div class="proNote">Official warning/danger = DHM station threshold. “Rising” = station steady=RISING वा पछिल्लो प्राप्त reading भन्दा पानी बढेको app trend; यसलाई official warning भनेर देखाइँदैन।</div>';stats.insertAdjacentElement('afterend',p);const u=document.createElement('section');u.id='upstreamPro';u.className='proPanel upstreamAlert';u.innerHTML='<div class="proHead"><h3>⛰️ माथिल्लो बहाव निगरानी</h3><span class="proBadge" id="upstreamBadge">—</span></div><div id="upstreamBody" class="proNote">स्थान छानेपछि नजिकको नदीसँग मिल्ने माथिल्लो स्टेशन जाँच हुन्छ।</div>';p.insertAdjacentElement('afterend',u)}
const ticker=$('tickerMsg')?.closest('.panel');if(ticker&&!$('sourcePro')){const s=document.createElement('section');s.id='sourcePro';s.className='proPanel';s.innerHTML='<div class="proHead"><h3>🛰️ डेटा स्रोत</h3><span class="proBadge">VERIFIED SOURCES</span></div><div class="sourceStrip"><div><b>DHM / hydrology.gov.np</b>नदी पानी सतह, warning/danger threshold</div><div><b>BIPAD</b>alert, incident/loss, road integration</div><div><b>NASA GPM IMERG</b>satellite rainfall animation; सरकारी चेतावनी होइन</div></div>';ticker.insertAdjacentElement('afterend',s)}
}
function focus(){try{const c=JSON.parse(localStorage.getItem('floodsafe-focus')||'null');return Array.isArray(c)&&c.length===2?c.map(Number):null}catch{return null}}
function dist(a,b){const R=6371,p=Math.PI/180,d1=(b[0]-a[0])*p,d2=(b[1]-a[1])*p,s=Math.sin(d1/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
async function fetchJSON(url,ms=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
function rows(j){if(Array.isArray(j))return j;return j?.results||j?.data||j?.objects||[]}
function point(o){const g=o?.point||o?.corrected_point||o?.provided_point||o?.geometry||o?.location?.geometry;if(g?.coordinates?.length>=2)return [+g.coordinates[1],+g.coordinates[0]];const lat=+(o?.latitude??o?.lat),lon=+(o?.longitude??o?.lng??o?.lon);return Number.isFinite(lat)&&Number.isFinite(lon)?[lat,lon]:null}
function stName(o){return String(o?.title||o?.station_name||o?.name||'River station')}
function riverName(o){if(o?.river_name)return String(o.river_name);const t=stName(o);return t.split(/\s+at\s+/i)[0].trim()}
function riverKey(o){return riverName(o).toLowerCase().replace(/\b(river|khola|gadh|gad|nadi)\b/g,'').replace(/[^a-z0-9\u0900-\u097f]+/g,' ').trim()}
function measurement(o){return o?.waterLevelOn||o?.water_level_on||o?.modifiedOn||o?.modified_on||o?.updated_at||o?.createdOn||null}
function ageText(s){if(!s)return'—';const d=new Date(s);if(Number.isNaN(d.getTime()))return String(s);const m=Math.max(0,Math.round((Date.now()-d)/60000));if(state.lang==='en')return m<1?'now':m<60?m+' min ago':Math.round(m/60)+' hr ago';return m<1?'अहिले':m<60?m+' मिनेट अघि':Math.round(m/60)+' घण्टा अघि'}
function classify(o,prev){const wl=+o.waterLevel,w=+o.warningLevel,d=+o.dangerLevel,s=String(o.status||'').toUpperCase(),steady=String(o.steady||'').toUpperCase();let stage='normal';if(Number.isFinite(d)&&Number.isFinite(wl)&&wl>=d||/ABOVE DANGER/.test(s))stage='danger';else if(Number.isFinite(w)&&Number.isFinite(wl)&&wl>=w||/ABOVE WARNING/.test(s))stage='warning';else{const delta=Number.isFinite(prev)&&Number.isFinite(wl)?wl-prev:0,ratio=Number.isFinite(w)&&w>0&&Number.isFinite(wl)?wl/w:0;if(steady.includes('RISING')||delta>=0.03||ratio>=0.85)stage='rising'}return{stage,wl:Number.isFinite(wl)?wl:null,w:Number.isFinite(w)?w:null,d:Number.isFinite(d)?d:null,steady,delta:Number.isFinite(prev)&&Number.isFinite(wl)?wl-prev:null,ratio:Number.isFinite(w)&&w>0&&Number.isFinite(wl)?wl/w:null}}
const stageRank={normal:0,rising:1,warning:2,danger:3};
function stageLabel(s){const m=state.lang==='en'?{normal:'Normal',rising:'Early watch',warning:'Warning',danger:'Danger'}:{normal:'सामान्य',rising:'प्रारम्भिक सतर्कता',warning:'चेतावनी',danger:'खतरा'};return m[s]}
function notify(title,body){if(!state.alerts)return;try{if(Notification.permission==='granted')new Notification(title,{body,icon:'./icon.svg'})}catch{};sound()}
function sound(){try{state.audio=state.audio||new(window.AudioContext||window.webkitAudioContext)();if(state.audio.state==='suspended')state.audio.resume();const n=state.audio.currentTime,g=state.audio.createGain();g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.045,n+.02);g.gain.exponentialRampToValueAtTime(.0001,n+.85);g.connect(state.audio.destination);[[0,620,.16],[.22,780,.18],[.46,680,.22]].forEach(([t,f,d])=>{const o=state.audio.createOscillator(),a=state.audio.createGain();o.frequency.value=f;o.type='sine';a.gain.setValueAtTime(.0001,n+t);a.gain.exponentialRampToValueAtTime(.28,n+t+.015);a.gain.exponentialRampToValueAtTime(.0001,n+t+d);o.connect(a);a.connect(g);o.start(n+t);o.stop(n+t+d+.03)})}catch{}}
function stationDistance(o){const f=focus(),p=point(o);return f&&p?dist(f,p):Infinity}
function currentRadius(){return +($('radius')?.value||25)}
function stationCard(o){const prev=state.prev.get(String(o.id??o.stationSeriesId??stName(o))),c=classify(o,prev),p=point(o),km=stationDistance(o),pct=c.ratio?Math.min(130,Math.max(0,c.ratio*100)):null,src=o.dataSource||o.provider_1||'DHM';const dem=o.affectedDemography||{};return `<div class="stationCard"><div class="stationTop"><div><b>${esc(stName(o))}</b><small>${esc(riverName(o))}${o.basin?' • '+esc(o.basin):''}${Number.isFinite(km)?' • '+km.toFixed(1)+' km':''}</small></div><span class="stage ${c.stage}">${stageLabel(c.stage)}</span></div><div class="stationMeta"><span>${state.lang==='en'?'Water':'पानी'} <b>${nfmt(c.wl)} m</b></span><span>${state.lang==='en'?'Warning':'चेतावनी'} <b>${nfmt(c.w)} m</b></span><span>${state.lang==='en'?'Danger':'खतरा'} <b>${nfmt(c.d)} m</b></span></div>${pct!==null?`<div class="levelBar"><div class="levelFill" style="width:${Math.min(100,pct)}%"></div></div><small>${Math.round(pct)}% ${state.lang==='en'?'of warning level':'चेतावनी सतहको'}</small>`:''}<small>${state.lang==='en'?'Trend':'ट्रेन्ड'}: ${esc(o.steady||'—')}${c.delta!==null?' • Δ '+(c.delta>=0?'+':'')+c.delta.toFixed(3)+' m':''}</small><small>${state.lang==='en'?'Measurement':'मापन'}: ${esc(ageText(measurement(o)))} • ${state.lang==='en'?'Source':'स्रोत'}: ${esc(src)}${o.stationSeriesId?' • ID '+esc(o.stationSeriesId):''}</small>${dem.householdCount?`<small>${state.lang==='en'?'Station affected-demography reference':'स्टेशन प्रभावित जनसांख्यिक सन्दर्भ'}: ${Number(dem.householdCount).toLocaleString()} ${state.lang==='en'?'households':'घरधुरी'}</small>`:''}</div>`}
function renderStations(){if(!$('stationList'))return;const f=focus(),rad=currentRadius();let arr=state.stations.map(o=>({o,d:stationDistance(o),c:classify(o,state.prev.get(String(o.id??o.stationSeriesId??stName(o))))}));if(f)arr=arr.filter(x=>x.d<=Math.max(rad,25));arr.sort((a,b)=>stageRank[b.c.stage]-stageRank[a.c.stage]||a.d-b.d);const warning=state.stations.filter(o=>stageRank[classify(o,state.prev.get(String(o.id??o.stationSeriesId??stName(o)))).stage]>=2).length,rising=state.stations.filter(o=>classify(o,state.prev.get(String(o.id??o.stationSeriesId??stName(o)))).stage==='rising').length;$('stationTotal').textContent=state.stations.length;$('stationWarn').textContent=warning;$('stationRise').textContent=rising;$('stationAge').textContent=state.lastStation?(state.lang==='en'?'checked '+ageText(state.lastStation):'चेक '+ageText(state.lastStation)):'—';$('stationList').innerHTML=(arr.slice(0,f?10:8).map(x=>stationCard(x.o)).join('')||`<div class="stationCard"><small>${state.lang==='en'?'No station found in the selected radius.':'छानिएको दूरीभित्र स्टेशन भेटिएन।'}</small></div>`)}
function renderUpstream(){if(!$('upstreamBody'))return;const f=focus();if(!f||!state.stations.length){$('upstreamBody').textContent=state.lang==='en'?'Select a location to check matching upstream stations.':'स्थान छानेपछि नजिकको नदीसँग मिल्ने माथिल्लो स्टेशन जाँच हुन्छ।';return}const valid=state.stations.filter(o=>point(o));valid.sort((a,b)=>stationDistance(a)-stationDistance(b));const near=valid[0];if(!near){return}const key=riverKey(near),e0=+near.elevation;const ups=valid.filter(o=>o!==near&&riverKey(o)===key&&key&&Number.isFinite(+o.elevation)&&Number.isFinite(e0)&&+o.elevation>e0+10&&stationDistance(o)<180).map(o=>({o,d:stationDistance(o),c:classify(o,state.prev.get(String(o.id??o.stationSeriesId??stName(o))))})).sort((a,b)=>stageRank[b.c.stage]-stageRank[a.c.stage]||a.d-b.d).slice(0,3);$('upstreamBadge').textContent=esc(riverName(near));const max=ups.reduce((m,x)=>Math.max(m,stageRank[x.c.stage]),0);$('upstreamPro').classList.toggle('danger',max>=2);if(!ups.length){$('upstreamBody').innerHTML=`${state.lang==='en'?'Nearest station':'नजिकको स्टेशन'}: <b>${esc(stName(near))}</b><br>${state.lang==='en'?'No same-river higher-elevation station could be matched automatically.':'उही नदीको बढी उचाइमा रहेको स्टेशन स्वतः मिलाउन सकिएन।'} <br><small>${state.lang==='en'?'This avoids guessing a false upstream route.':'गलत upstream route अनुमान नगर्न यस्तो राखिएको हो।'}</small>`;return}$('upstreamBody').innerHTML=`${state.lang==='en'?'Nearest station':'नजिकको स्टेशन'}: <b>${esc(stName(near))}</b><br>`+ups.map(x=>`<div class="stationCard"><span class="stage ${x.c.stage}">${stageLabel(x.c.stage)}</span><b>${esc(stName(x.o))}</b><small>${esc(riverName(x.o))} • ${x.d.toFixed(1)} km • ${state.lang==='en'?'elevation':'उचाइ'} ${nfmt(x.o.elevation)} m</small><small>${state.lang==='en'?'Water':'पानी'} ${nfmt(x.c.wl)} m • ${state.lang==='en'?'warning':'चेतावनी'} ${nfmt(x.c.w)} m • ${esc(x.o.steady||'—')}</small></div>`).join('')+`<div class="proNote">${state.lang==='en'?'Upstream candidate = same river name + higher station elevation. It is an early-awareness aid, not a full hydraulic routing model.':'माथिल्लो candidate = उही नदीको नाम + बढी स्टेशन उचाइ। यो early-awareness हो; पूर्ण hydraulic routing model होइन।'}</div>`}
function alertEscalations(oldStages){const f=focus();if(!f||!state.alerts)return;const rad=Math.max(25,currentRadius());for(const o of state.stations){const id=String(o.id??o.stationSeriesId??stName(o)),c=classify(o,state.prev.get(id)),old=oldStages.get(id)||'normal',km=stationDistance(o);if(km<=rad&&stageRank[c.stage]>stageRank[old]&&stageRank[c.stage]>=1){notify(state.lang==='en'?'FloodSafe river alert':'बाढी सुरक्षा नदी चेतावनी',`${stName(o)} • ${stageLabel(c.stage)} • ${nfmt(c.wl)} m${Number.isFinite(km)?' • '+km.toFixed(1)+' km':''}`)}}}
async function refreshStations(){if(state.busy)return;state.busy=true;try{const [a,b]=await Promise.allSettled([fetchJSON(API+'river-stations/?limit=1800'),fetchJSON(API+'river/?limit=1800')]);const merged=new Map();for(const r of [a,b])if(r.status==='fulfilled')for(const o of rows(r.value)){const k=String(o.stationSeriesId??o.station??o.id??stName(o));const cur=merged.get(k);if(!cur||new Date(measurement(o)||0)>new Date(measurement(cur)||0))merged.set(k,o)}const oldStages=new Map(state.stage);const next=[...merged.values()];for(const o of next){const id=String(o.id??o.stationSeriesId??o.station??stName(o)),old=state.stations.find(x=>String(x.id??x.stationSeriesId??x.station??stName(x))===id);if(old&&Number.isFinite(+old.waterLevel))state.prev.set(id,+old.waterLevel);const c=classify(o,state.prev.get(id));state.stage.set(id,c.stage)}state.stations=next;state.lastStation=new Date();renderStations();renderUpstream();alertEscalations(oldStages);$('stationPro')?.classList.add('freshPulse');setTimeout(()=>$('stationPro')?.classList.remove('freshPulse'),600)}catch(e){console.warn('station pro refresh',e)}finally{state.busy=false}}
async function refreshTodayWeather(force=true){const f=focus();if(!f||!$('todayWeatherPro'))return;try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${f[0]}&longitude=${f[1]}&current=temperature_2m,apparent_temperature,relative_humidity_2m,cloud_cover,precipitation,rain,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,sunrise,sunset&timezone=Asia%2FKathmandu&forecast_days=1`;const j=await fetchJSON(u,9000),c=j.current||{},d=j.daily||{};$('wxMax').textContent=Number.isFinite(+d.temperature_2m_max?.[0])?Math.round(+d.temperature_2m_max[0])+'°C':'—';$('wxMin').textContent=Number.isFinite(+d.temperature_2m_min?.[0])?Math.round(+d.temperature_2m_min[0])+'°C':'—';$('wxProb').textContent=Number.isFinite(+d.precipitation_probability_max?.[0])?Math.round(+d.precipitation_probability_max[0])+'%':'—';$('wxHum').textContent=Number.isFinite(+c.relative_humidity_2m)?Math.round(+c.relative_humidity_2m)+'%':'—';$('wxCloud').textContent=Number.isFinite(+c.cloud_cover)?Math.round(+c.cloud_cover)+'%':'—';$('wxFeel').textContent=Number.isFinite(+c.apparent_temperature)?Math.round(+c.apparent_temperature)+'°C':'—';state.lastWeather=new Date();$('todayWeatherAge').textContent=state.lang==='en'?'model updated':'मोडेल अपडेट';$('wxNote').textContent=state.lang==='en'?`Today: precipitation ${nfmt(d.precipitation_sum?.[0])} mm • sunrise ${d.sunrise?.[0]?.slice(11,16)||'—'} • sunset ${d.sunset?.[0]?.slice(11,16)||'—'}. Forecast model; nearby DHM/BIPAD station remains the official observation source.`:`आज: कुल वर्षा ${nfmt(d.precipitation_sum?.[0])} mm • सूर्योदय ${d.sunrise?.[0]?.slice(11,16)||'—'} • सूर्यास्त ${d.sunset?.[0]?.slice(11,16)||'—'}। यो forecast model हो; नजिकको DHM/BIPAD स्टेशन official observation source हो।`}catch(e){console.warn('weather detail',e)}}
function genericPoint(o){return point(o)||point(o?.location)||point(o?.properties)}
function statusText(o){return String(o?.status||o?.condition||o?.remarks||o?.description||o?.properties?.status||'')}
async function refreshRoads(){const f=focus();if(!f)return;try{const j=await fetchJSON(API+'highway/?limit=1800',11000),arr=rows(j).map(o=>({o,p:genericPoint(o)})).filter(x=>x.p).map(x=>({...x,d:dist(f,x.p)})).filter(x=>x.d<=Math.max(50,currentRadius())).sort((a,b)=>a.d-b.d).slice(0,12);if($('roadList'))$('roadList').innerHTML=arr.length?arr.map(x=>{const s=statusText(x.o),bad=/closed|block|partial|बन्द|अवरुद्ध|one way/i.test(s);return `<div class="item"><span class="tag ${bad?'red':'green'}">${bad?(state.lang==='en'?'Issue':'समस्या'):(state.lang==='en'?'Reported':'रिपोर्ट')}</span><b>${esc(x.o.title||x.o.name||x.o.road_name||'Road')}</b><small>${x.d.toFixed(1)} km • ${esc(s||'DoR/BIPAD record')}</small><small>${state.lang==='en'?'Source':'स्रोत'}: Department of Roads via BIPAD</small></div>`}).join(''):`<div class="item"><small>${state.lang==='en'?'No geolocated DoR/BIPAD road record found in this radius.':'यो दूरीभित्र स्थानसहितको DoR/BIPAD सडक रेकर्ड भेटिएन।'}</small></div>`;state.lastRoad=new Date()}catch(e){console.warn('roads pro',e)}}
function dateNP(d){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function stamp(o){return o?.incidentOn||o?.incident_on||o?.createdOn||o?.created_on||o?.created_at||o?.date||o?.modifiedOn||null}
function floodObj(o){return /flood|flash flood|बाढी|डुबान/i.test(JSON.stringify(o||{}))}
function isToday(o){const s=stamp(o);if(!s)return false;const d=new Date(s);return !Number.isNaN(d.getTime())&&dateNP(d)===dateNP(new Date())}
async function refreshImpact(){try{const [ir,lr]=await Promise.all([fetchJSON(API+'incident/?limit=1000',12000),fetchJSON(API+'loss-people/?limit=1800',12000)]),inc=rows(ir).filter(o=>floodObj(o)&&isToday(o)),ids=new Set(inc.map(o=>String(o.id??o.pk)));let dead=0,inj=0,miss=0,matched=0;for(const o of rows(lr)){const rid=String(o.incident?.id??o.incident??o.incident_id??o.incidentId??''),txt=JSON.stringify(o).toLowerCase();if(!(ids.has(rid)||floodObj(o)))continue;if(stamp(o)&&!isToday(o))continue;const c=Math.max(1,Math.round(+(o.count??o.number??o.total??1)||1));if(/dead|death|deceased|मृत/.test(txt)){dead+=c;matched++}else if(/injured|घाइते/.test(txt)){inj+=c;matched++}else if(/missing|बेपत्ता/.test(txt)){miss+=c;matched++}}if($('incidentV'))$('incidentV').textContent=inc.length;if($('deadV'))$('deadV').textContent=matched||inc.length?dead:'—';if($('injuredV'))$('injuredV').textContent=matched||inc.length?inj:'—';if($('missingV'))$('missingV').textContent=matched||inc.length?miss:'—';if($('impactNote'))$('impactNote').textContent=state.lang==='en'?'Confirmed values currently returned by BIPAD incident/loss feeds for today. Source reporting can arrive later than the event.':'आजको BIPAD incident/loss feed ले अहिले पुष्टि गरेर फर्काएको संख्या। स्रोतमा रिपोर्ट ढिलो आए app मा पनि ढिलो आउन सक्छ।';state.lastImpact=new Date()}catch(e){console.warn('impact pro',e)}}
async function loadDistrictNames(){try{const u='https://raw.githubusercontent.com/l3lackcurtains/nepali-geo-pro-max/117fd0f3d2dabae3bd86bfe9e4c57098ffe56669/src/geo/districts.geo.ts',t=await (await fetch(u)).text(),m='export const NEPAL_DISTRICTS_GEO',p=t.indexOf(m),s=t.indexOf('{',p),e=t.lastIndexOf('};'),j=JSON.parse(t.slice(s,e+1));for(const f of j.features||[]){const p=f.properties||{};if(p.nameNe&&p.nameEn)state.districtNames.set(String(p.nameNe),String(p.nameEn))}}catch{}}
function hookAlerts(){const b=$('alertsBtn');if(b)b.addEventListener('click',async()=>{state.alerts=true;localStorage.setItem('floodsafe-pro-alerts','1');try{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission()}catch{};sound()});const s=$('soundBtn');if(s)s.addEventListener('click',sound)}
function tickAges(){if($('stationAge')&&state.lastStation)$('stationAge').textContent=(state.lang==='en'?'checked ':'चेक ')+ageText(state.lastStation);if($('todayWeatherAge')&&state.lastWeather)$('todayWeatherAge').textContent=(state.lang==='en'?'checked ':'चेक ')+ageText(state.lastWeather)}
async function start(){injectCSS();injectUI();await loadDistrictNames();mo.observe(document.body,{subtree:true,childList:true,characterData:true});setLang(state.lang);hookAlerts();await Promise.allSettled([refreshStations(),refreshTodayWeather(),refreshRoads(),refreshImpact()]);setInterval(refreshStations,POLL_STATION);setInterval(refreshRoads,POLL_ROAD);setInterval(refreshImpact,POLL_IMPACT);setInterval(refreshTodayWeather,POLL_WEATHER);setInterval(()=>{tickAges();const f=focus();if(f)renderUpstream()},1000);window.addEventListener('storage',e=>{if(e.key==='floodsafe-focus'){refreshTodayWeather();refreshRoads();renderStations();renderUpstream()}});document.getElementById('gpsBtn')?.addEventListener('click',()=>setTimeout(()=>{refreshTodayWeather();refreshRoads();renderStations();renderUpstream()},1800));document.getElementById('centerBtn')?.addEventListener('click',()=>setTimeout(()=>{refreshTodayWeather();refreshRoads();renderStations();renderUpstream()},500));document.getElementById('radius')?.addEventListener('change',()=>{renderStations();renderUpstream();refreshRoads()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
