import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,db=createClient(U,K,{auth:{persistSession:false}});
const CORS={"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"content-type, apikey, authorization","access-control-allow-methods":"GET,OPTIONS","cache-control":"no-store, max-age=0"};
const ARCHIVE=24*60*60*1000,FUTURE=5*60*1000,CACHE=15000,ALLOWED=["RONB Post","Radio Nepal","News24 Nepal"];
type Item={title:string,url:string,published_at:string,source:string};
const clean=(s:any)=>String(s??"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g," ").trim();
const titleKey=(s:any)=>String(s??"").normalize('NFKC').toLocaleLowerCase('ne-NP').replace(/\s+/g,' ').trim();
function iso(x:any){if(!x)return null;let s=String(x).trim();if(/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d$/.test(s))s+="Z";const d=new Date(s);return Number.isFinite(+d)?d.toISOString():null}
async function fetchText(url:string,ms=4500){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:"no-store",redirect:"follow",signal:c.signal,headers:{"user-agent":"Mozilla/5.0 (compatible; FloodSafeNepal-News/9.0)",accept:"application/json,text/html;q=0.9,*/*;q=0.8"}});if(!r.ok)throw new Error(`${r.status}`);return await r.text()}finally{clearTimeout(to)}}
function add(out:Item[],title:any,url:any,t:any,source:string){const z=iso(t),tt=clean(title),u=String(url||"").trim();if(z&&tt.length>=8&&/^https?:\/\//.test(u))out.push({title:tt,url:u,published_at:z,source})}
async function wp(url:string,source:string){const j=JSON.parse(await fetchText(url));if(!Array.isArray(j))throw Error("WP response not array");const out:Item[]=[];for(const p of j){const title=typeof p?.title==='object'?p.title.rendered:p?.title;add(out,title,p?.link,p?.date_gmt||p?.date,source)}return out}
async function ronb(){return wp("https://www.ronbpost.com/wp-json/wp/v2/posts?per_page=40&_fields=date_gmt,date,modified_gmt,modified,link,title","RONB Post")}
async function radio(){const settled=await Promise.allSettled([wp("https://radionepalonline.com/wp-json/wp/v2/posts?per_page=40&_fields=date_gmt,date,modified_gmt,modified,link,title","Radio Nepal"),wp("https://radionepalonline.com/en/wp-json/wp/v2/posts?per_page=40&_fields=date_gmt,date,modified_gmt,modified,link,title","Radio Nepal")]);const out:Item[]=[];for(const x of settled)if(x.status==='fulfilled')out.push(...x.value);if(!out.length)throw Error("Radio Nepal feeds unavailable");return out}
function absoluteNews24(href:string){try{return new URL(href,"https://www.news24nepal.com/").href.replace(/\/$/,"")}catch{return null}}
function detailLinks(h:string){const out:string[]=[];for(const m of h.matchAll(/href=["']([^"']+)["']/gi)){const raw=m[1];if(!/\/(?:detail|news|mukhya)\//i.test(raw)&&!/\/detail\/\d+/i.test(raw))continue;const u=absoluteNews24(raw);if(!u||!u.startsWith("https://www.news24nepal.com/"))continue;if(!out.includes(u))out.push(u);if(out.length>=12)break}return out}
function news24Time(h:string){for(const p of[/property=["']article:published_time["'][^>]*content=["']([^"']+)/i,/name=["']date["'][^>]*content=["']([^"']+)/i,/"datePublished"\s*:\s*"([^"]+)/i,/<time[^>]+datetime=["']([^"']+)/i]){const m=h.match(p),z=m&&iso(m[1]);if(z)return z}return null}
function news24Title(h:string){return clean((h.match(/<meta\s+property=["']og:title["']\s+content=["']([^"']+)/i)||h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||"")}
async function news24(){const home=await fetchText("https://www.news24nepal.com/?option=com_content&view=frontpage",5000),links=detailLinks(home);if(!links.length)throw Error("News24 detail links missing");const pages=await Promise.allSettled(links.slice(0,10).map(async u=>({u,h:await fetchText(u,4500)})));const out:Item[]=[];for(const p of pages)if(p.status==='fulfilled'){const t=news24Time(p.value.h);if(t)add(out,news24Title(p.value.h),p.value.u,t,"News24 Nepal")}return out}
function current(items:Item[]){const n=Date.now();return items.filter(x=>{const t=+new Date(x.published_at),a=n-t;return Number.isFinite(t)&&a>=-FUTURE&&a<ARCHIVE})}
function dedupe(items:Item[]){const out:Item[]=[],seenUrl=new Set<string>(),seenTitle=new Set<string>();for(const x of items.sort((a,b)=>+new Date(b.published_at)-+new Date(a.published_at))){const u=x.url.split('#')[0],k=titleKey(x.title);if(!k||seenUrl.has(u)||seenTitle.has(k))continue;seenUrl.add(u);seenTitle.add(k);out.push(x)}return out.slice(0,100)}
async function refresh(prev:any){const fns:any=[["RONB Post",ronb],["Radio Nepal",radio],["News24 Nepal",news24]],settled=await Promise.all(fns.map(async([source,fn]:any)=>{try{return{source,ok:true,items:current(await fn())}}catch(e){const keep=current(Array.isArray(prev?.items)?prev.items.filter((x:any)=>x?.source===source):[]);return{source,ok:false,items:keep,error:String(e).slice(0,180)}}}));const sources:any={},all:Item[]=[];for(const x of settled){const newest=x.items.map((i:Item)=>i.published_at).sort().at(-1)||null;sources[x.source]={ok:x.ok,items:x.items.length,newest,...(x.error?{error:x.error}:{})};all.push(...x.items)}const payload={generated_at:new Date().toISOString(),latest_window_minutes:10,archive_window_minutes:1440,allowed_sources:ALLOWED,sources,items:dedupe(all)};await db.from('floodsafe_news_cache').upsert({id:1,payload,checked_at:new Date().toISOString()},{onConflict:'id'});return payload}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});try{const {data}=await db.from('floodsafe_news_cache').select('payload,checked_at').eq('id',1).maybeSingle();const force=new URL(req.url).searchParams.get('force')==='1',age=data?.checked_at?Date.now()-+new Date(data.checked_at):Infinity,payload=(force||!data?.payload||Object.keys(data.payload||{}).length===0||age>CACHE)?await refresh(data?.payload||{}):data.payload;return new Response(JSON.stringify(payload),{headers:CORS})}catch(e){return new Response(JSON.stringify({status:'error',error:String(e),allowed_sources:ALLOWED,items:[]}),{status:500,headers:CORS})}});

