(()=>{
'use strict';
const $=id=>document.getElementById(id),RIVER_API=/bipadportal\.gov\.np\/api\/v1\/(river|river-stations)/i;
let ctx=null,audioEnabled=localStorage.getItem('fs23-audio-enabled')==='1',baseline=null,timer=null,riverFeed=[],lastFocus='';

function css(){if($('fs23-hotfix-css'))return;const s=document.createElement('style');s.id='fs23-hotfix-css';s.textContent=`
.leaflet-top.leaflet-left{top:auto!important;bottom:58px!important;left:8px!important}.leaflet-control-zoom{margin:0!important;box-shadow:0 6px 18px #0008!important}
.fs23roadTools,.fs23AlertGate{margin-top:8px;border:1px solid #604238;border-radius:10px;padding:8px 9px;background:#15100e;color:#d7c8c0;font-size:10px;line-height:1.45}.fs23roadTools b,.fs23AlertGate b{color:#fff}.fs23roadBtns{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.fs23roadBtns button{border:1px solid #765044;background:#261713;color:#fff;border-radius:9px;padding:8px 9px;font-weight:850;cursor:pointer}.fs23roadBtns button:first-child{background:#3b5f2a;border-color:#72a653}.fs23impactFallback{color:#f5d37a!important;font-weight:700}.fs23soundOn{background:#176b4d!important;border-color:#54dca8!important}.fs23AlertGate.high{border-color:#e79a35;color:#ffe0ac}.fs23AlertGate.very{border-color:#ff5570;color:#ffd7de;background:#2c1116}
@media(max-width:900px){.leaflet-top.leaflet-left{bottom:62px!important}.mapBadge{max-width:58%!important}.mapBtns{max-width:42%!important}.mapTop{align-items:flex-start!important}}
`;document.head.appendChild(s)}
const rows=j=>Array.isArray(j)?j:(j?.results||j?.data||j?.objects||[]);
const coord=o=>{const c=o?.point?.coordinates||o?.location?.coordinates||o?.centroid?.coordinates||o?.geometry?.coordinates;return Array.isArray(c)&&c.length>=2&&Number.isFinite(+c[0])&&Number.isFinite(+c[1])?[+c[1],+c[0]]:null};
function km(a,b){if(!a||!b)return Infinity;const R=6371,p=Math.PI/180,d1=(b[0]-a[0])*p,d2=(b[1]-a[1])*p,x=Math.sin(d1/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function val(o,ks){for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null}
const title=o=>String(val(o,['title','name','station_name','river_name','location_name'])||val(o?.station||{},['name','station_name'])||'DHM river station');
const status=o=>String(val(o,['status','steady','trend','state','warning_status','alert_status'])||'').trim().toUpperCase();
const n=v=>Number.isFinite(+v)?+v:null,th=v=>{const x=n(v);return x!==null&&x>0?x:null};
function stage(o){const wl=n(val(o,['waterLevel','water_level','level','waterlevel'])),w=th(val(o,['warningLevel','warning_level','warning'])),d=th(val(o,['dangerLevel','danger_level','danger'])),st=status(o),below=/BELOW\s+(WARNING|DANGER)|NORMAL|SAFE/.test(st);if(!below&&((d!==null&&wl!==null&&wl>=d)||/ABOVE\s+DANGER|DANGER\s+LEVEL\s+EXCEEDED|^DANGER$|RED\s+ALERT|VERY\s+HIGH/.test(st)))return'very';if(!below&&((w!==null&&wl!==null&&wl>=w)||/ABOVE\s+WARNING|WARNING\s+LEVEL\s+EXCEEDED|ORANGE\s+ALERT|HIGH\s+ALERT/.test(st)))return'high';return'none'}
const when=o=>val(o,['waterLevelOn','measuredOn','modifiedOn','createdOn','recordedDate','date']);
function fresh(o,h=6){const t=+new Date(when(o)||0);return Number.isFinite(t)&&Date.now()-t>=-3600e3&&Date.now()-t<=h*3600e3}
function focus(){try{const f=window.__fs?.getFocus?.();return Array.isArray(f)&&f.length===2?f:null}catch{return null}}
const focusKey=()=>{const f=focus();return f?f.map(x=>(+x).toFixed(4)).join(','):''};

function capture(){if(window.__fs23FloodCapture)return;window.__fs23FloodCapture=true;const native=window.fetch.bind(window);window.fetch=async(...args)=>{const r=await native(...args);try{const u=String(args[0]?.url||args[0]||'');if(RIVER_API.test(u)){const a=rows(await r.clone().json());if(a.length)merge(a)}}catch{}return r}}
function merge(a){const m=new Map();[...riverFeed,...a].forEach(o=>{const c=coord(o),k=title(o).toLowerCase()+'|'+(c?c.map(v=>v.toFixed(4)).join(','):'');m.set(k,o)});riverFeed=[...m.values()].slice(-1400)}
async function seed(){try{for(const u of ['river-stations/?limit=650','river/?limit=650']){const r=await fetch('https://bipadportal.gov.np/api/v1/'+u,{cache:'no-store'});if(r.ok)merge(rows(await r.clone().json()))}}catch{}}

const norm=s=>String(s||'').toLowerCase().replace(/[()\[\],./_-]+/g,' ').replace(/\b(river|khola|nadi|station|gauge|at|the|near|bridge)\b/g,' ').replace(/\s+/g,' ').trim();
const toks=s=>norm(s).split(' ').filter(x=>x.length>=3);
function sameRiver(a,b){const A=toks(a),B=toks(b);return A.some(x=>B.some(y=>x===y||(x.length>=5&&y.length>=5&&(x.includes(y)||y.includes(x)))))}
function parseKm(s){const m=String(s||'').match(/([0-9]+(?:\.[0-9]+)?)\s*(?:किमि|km)/i);return m?+m[1]:Infinity}
function waterways(){return [...document.querySelectorAll('#waterwayList .item')].map(el=>{const meta=[...el.querySelectorAll('small')].map(x=>x.textContent||'').join(' '),type=/\briver\b/i.test(meta)?'river':/\bstream\b/i.test(meta)?'stream':/\bcanal\b/i.test(meta)?'canal':'waterway';return{name:el.querySelector('b')?.textContent?.trim()||'',d:parseKm(meta),type}}).filter(x=>Number.isFinite(x.d)).sort((a,b)=>a.d-b.d)}
function corridor(sev,type){if(type==='river')return sev==='very'?1.6:.9;if(type==='stream')return sev==='very'?.85:.45;if(type==='canal')return sev==='very'?.65:.35;return sev==='very'?1.2:.7}
function sourceLimit(sev,matched){return matched?(sev==='very'?50:30):(sev==='very'?5:3)}
function risks(){const f=focus();if(!f)return[];const ws=waterways(),nearest=ws[0]||null,out=[],seen=new Set();for(const o of riverFeed){const c=coord(o),sev=stage(o);if(!c||sev==='none'||!fresh(o))continue;const sd=km(f,c);let matched=null;for(const w of ws)if(w.name&&sameRiver(title(o),w.name)&&(!matched||w.d<matched.d))matched=w;
 let wd=Infinity,wname='',wtype='gauge',matchedName=false,ok=false;
 if(matched||nearest){const w=matched||nearest;wd=w.d;wname=w.name;wtype=w.type;matchedName=!!matched;ok=wd<=corridor(sev,w.type)&&sd<=sourceLimit(sev,matchedName)}
 else{const fallback=sev==='very'?1.5:.75;wd=sd;wname='DHM gauge fallback';ok=sd<=fallback}
 if(!ok)continue;const key=norm(title(o))+'|'+sev;if(seen.has(key))continue;seen.add(key);out.push({key,sev,title:title(o),waterDist:wd,sourceDist:sd,matched:matchedName,waterName:wname,waterType:wtype})}
 return out.sort((a,b)=>(a.sev==='very'?0:1)-(b.sev==='very'?0:1)||a.waterDist-b.waterDist)}

async function audio(){try{if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')await ctx.resume();return ctx.state==='running'}catch{return false}}
async function chime(){if(!await audio()){try{navigator.vibrate?.([110,70,150])}catch{}return false}const t=ctx.currentTime,m=ctx.createGain();m.gain.setValueAtTime(.0001,t);m.gain.exponentialRampToValueAtTime(.15,t+.025);m.gain.exponentialRampToValueAtTime(.0001,t+1.35);m.connect(ctx.destination);[[0,660,.22],[.28,880,.22],[.62,740,.34]].forEach(([dt,f,d])=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.0001,t+dt);g.gain.exponentialRampToValueAtTime(.42,t+dt+.018);g.gain.exponentialRampToValueAtTime(.0001,t+dt+d);o.connect(g);g.connect(m);o.start(t+dt);o.stop(t+dt+d+.04)});try{navigator.vibrate?.([90,55,135])}catch{}return true}
function history(){try{return JSON.parse(localStorage.getItem('fs23-risk-history')||'{}')}catch{return{}}}
const canSound=k=>{const h=history();return !h[k]||Date.now()-h[k]>30*60*1000};
function remember(k){const h=history();h[k]=Date.now();for(const x in h)if(Date.now()-h[x]>86400e3)delete h[x];localStorage.setItem('fs23-risk-history',JSON.stringify(h))}
async function notify(r){try{if(Notification.permission!=='granted')return;const tt=r.sev==='very'?'🔴 VERY HIGH बाढी ALERT':'⚠️ HIGH बाढी ALERT',body='तपाईं स्थानीय नदी/खोला safety buffer भित्र हुनुहुन्छ • '+r.waterDist.toFixed(1)+' km • '+r.title,reg=await navigator.serviceWorker?.ready;if(reg)reg.showNotification(tt,{body,icon:'./icon.svg',badge:'./icon.svg',tag:'fs23-'+r.key,renotify:false});else new Notification(tt,{body,icon:'./icon.svg',tag:'fs23-'+r.key})}catch{}}
async function scan(force=false){const fk=focusKey();if(fk!==lastFocus){lastFocus=fk;baseline=null}const rr=risks(),now=new Map(rr.map(r=>[r.key,r]));gate(rr);if(baseline===null){baseline=force?new Map():now;if(!force)return}const freshR=rr.filter(r=>!baseline.has(r.key));if(audioEnabled&&freshR.length){const r=freshR[0];if(canSound(r.key)){await chime();remember(r.key);await notify(r)}}baseline=now}
function gate(rr=risks()){let el=$('fs23AlertGate');if(!el){const a=document.querySelector('.hero .actions');if(!a)return;el=document.createElement('div');el.id='fs23AlertGate';el.className='fs23AlertGate';a.insertAdjacentElement('afterend',el)}el.className='fs23AlertGate';if(!focus()){el.innerHTML='🔕 आवाज <b>GPS/स्थान छानेपछि</b> मात्र जाँच हुन्छ।';return}const r=rr[0];if(!r){el.innerHTML='🔕 आवाज केवल <b>HIGH ⚠️ / VERY HIGH 🔴 स्थानीय बाढी जोखिम</b> मा मात्र बज्छ। सडक, सामान्य/बढ्दो नदी वा टाढाको चेतावनीले आवाज बज्दैन।';return}el.classList.add(r.sev==='very'?'very':'high');el.innerHTML=(r.sev==='very'?'🔴 <b>VERY HIGH ALERT</b>':'⚠️ <b>HIGH ALERT</b>')+' • नदी/खोला safety distance '+r.waterDist.toFixed(1)+' km • DHM source '+r.sourceDist.toFixed(1)+' km'+(r.waterType==='gauge'?' • OSM geometry fallback':'');const rv=$('riskV');if(rv){rv.textContent=r.sev==='very'?'VERY HIGH ALERT':'HIGH ALERT';rv.className=r.sev==='very'?'bad':'warn'}}
function soundHooks(){const test=$('soundBtn'),en=$('alertsBtn');if(test&&!test.dataset.fsRisk){test.dataset.fsRisk='1';test.onclick=async function(){const ok=await chime();this.textContent=ok?'🔊 ध्वनि चल्यो':'⚠️ आवाज अनुमति चाहियो';setTimeout(()=>this.textContent='♪ ध्वनि परीक्षण',1600)}}if(en&&!en.dataset.fsRisk){en.dataset.fsRisk='1';en.onclick=async function(){audioEnabled=true;localStorage.setItem('fs23-audio-enabled','1');await audio();try{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission()}catch{}this.classList.add('fs23soundOn');this.textContent='🔔 HIGH/VERY HIGH सूचना सक्रिय';baseline=new Map();await scan(true)}}if(en&&audioEnabled){en.classList.add('fs23soundOn');en.textContent='🔔 HIGH/VERY HIGH सूचना सक्रिय'}if(!timer)timer=setInterval(()=>scan(false),5000)}

function impact(){const d=$('deadV'),i=$('injuredV'),m=$('missingV'),ev=$('incidentV'),note=$('impactNote');if(!d||!i||!m||!ev||!note)return;const blank=x=>!x||x==='—'||x==='-'||x==='0',empty=blank(d.textContent.trim())&&blank(i.textContent.trim())&&blank(m.textContent.trim())&&(ev.textContent.trim()==='0'||blank(ev.textContent.trim()));if(empty){d.textContent='९५';i.textContent='—';m.textContent='—';ev.textContent='—';note.classList.add('fs23impactFallback');note.innerHTML='BIPAD को आजको aggregated loss total अहिले sync भएको छैन। नेपाल प्रहरीले २०८३-०५-१०, १९:१४ सम्म रसुवा बाढीमा <b>९५ मृत्यु</b> पुष्टि गरेको छ। <a href="https://www.nepalpolice.gov.np/news/10245/" target="_blank" rel="noopener" style="color:#9fe6c4">नेपाल प्रहरी स्रोत</a>'}}
function google(){const f=focus();if(!f)return alert('पहिले नक्सामा स्थान छान्नुहोस्।');window.open('https://www.google.com/maps/@?api=1&map_action=map&center='+encodeURIComponent(f[0]+','+f[1])+'&zoom=14&basemap=roadmap','_blank','noopener')}
function waze(){const f=focus();if(!f)return alert('पहिले नक्सामा स्थान छान्नुहोस्।');window.open('https://www.waze.com/live-map/directions?to=ll.'+encodeURIComponent(f[0]+','+f[1]),'_blank','noopener')}
function roads(){const list=$('roadList');if(!list||$('fs23roadTools'))return;const b=document.createElement('div');b.id='fs23roadTools';b.className='fs23roadTools';b.innerHTML='<b>🛣 थप सडक जाँच</b><small>In-app सडक status DoR/BIPAD बाट refresh हुन्छ।</small><div class="fs23roadBtns"><button id="fsGoogleRoad">Google Maps</button><button id="fsWazeRoad">Waze Live Map</button></div><small>Google/Waze बाह्य route/traffic स्रोत हुन्; सरकारी चेतावनी होइन।</small>';list.insertAdjacentElement('afterend',b);$('fsGoogleRoad').onclick=google;$('fsWazeRoad').onclick=waze}
function roadText(){const l=$('roadList');if(!l)return;if(/रेकर्ड भेटिएन/.test(l.innerText||'')){const x=l.querySelector('.item small');if(x)x.textContent='छानिएको दूरीभित्र DoR/BIPAD को बन्द/आंशिक सडक record भेटिएन। तल Google Maps/Waze बाट live route context जाँच गर्न सक्नुहुन्छ।'}}
function boot(){css();capture();soundHooks();roads();impact();roadText();gate();seed().then(()=>setTimeout(()=>scan(false),700));setInterval(()=>{soundHooks();impact();roadText();gate()},5000);new MutationObserver(()=>{clearTimeout(window.__fsHotMut);window.__fsHotMut=setTimeout(()=>{impact();roadText();gate();scan(false)},450)}).observe(document.body,{subtree:true,childList:true,characterData:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,350));else setTimeout(boot,350);
})();
