(()=>{
'use strict';
const API='https://bipadportal.gov.np/api/v1/';
const STATION_POLL=15000, WEATHER_POLL=60000;
const state={lang:localStorage.getItem('fs22-lang')||'ne',stations:[],prev:new Map(),lastStations:null,lastWeather:null,impactLayer:null,focus:null,weatherTimer:null,stationTimer:null};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const txt=(ne,en)=>state.lang==='en'?en:ne;
const num=v=>{const n=parseFloat(v);return Number.isFinite(n)?n:null};
const km=(a,b)=>{const R=6371,p=Math.PI/180,d1=(b[0]-a[0])*p,d2=(b[1]-a[1])*p,s=Math.sin(d1/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(s))};
const impact={updated:'2026-08-26T19:14:00+05:45',deaths:95,source:'Nepal Police',districts:[['Rasuwa',1,28.11,85.30],['Nuwakot',11,27.92,85.16],['Dhading',18,27.87,84.90],['Chitwan',33,27.53,84.35],['Gorkha',16,28.00,84.63],['Tanahun',5,27.94,84.23],['Nawalparasi East',11,27.65,84.02]]};
const snowStations=[
 {n:'Beding',id:'10005602',e:3704},{n:'DanpheLek',id:'10005565',e:null},{n:'Hurikot',id:'10005557',e:2684},{n:'Kyangjing',id:'10005556',e:3850},{n:'Panchamukhi',id:'10005613',e:3933},{n:'Pangboche',id:'10005606',e:4002},{n:'Tashi Gaun',id:'10005579',e:2100},{n:'Tilicho',id:'10005638',e:4919},{n:'Tsho Rolpa Lake',id:'10000131',e:4557}
];
const staticMap={
 'बाढी सुरक्षा नेपाल':'FloodSafe Nepal','नेपाल समय':'Nepal time','अन्तिम लाइभ अपडेट':'Last live update','अहिलेको मौसम':'Current weather','तपाईंको क्षेत्र पहिले':'Your area first','मेरो वरिपरि बाढीको अवस्था':'Flood situation around me','मेरो स्थान प्रयोग':'Use my location','नक्साको बीच छान्नुहोस्':'Use map centre','स्थानीय जोखिम':'Local risk','नजिकका नदी स्टेशन':'Nearby river stations','सडक समस्या':'Road issues','वर्षा स्टेशन':'Rain stations','वरिपरिका खोला / नदी':'Nearby streams / rivers','नजिकको सडक अवस्था':'Nearby road condition','आजको बाढी प्रभाव':'Today flood impact','मृतक':'Deaths','घाइते':'Injured','बेपत्ता':'Missing','बाढी घटना':'Flood incidents','अहिलेको जानकारी':'Current information','७७ जिल्ला स्थिति':'77 district status','बाढी चेतावनी ध्वनि':'Flood alerts','सूचना सक्रिय गर्नुहोस्':'Enable alerts','ध्वनि परीक्षण':'Test sound','नेपाल बाढी नक्सा':'Nepal flood map','उपग्रह':'Satellite','सडक':'Road','NASA वर्षा':'NASA rain','लाइभ':'Live'};
function translateStatic(){document.documentElement.lang=state.lang==='en'?'en':'ne';document.querySelectorAll('[data-fs22-ne]').forEach(el=>{el.textContent=state.lang==='en'?el.dataset.fs22En:el.dataset.fs22Ne});document.querySelectorAll('h1,h2,h3,button,label,.box small,.stat small').forEach(el=>{const raw=el.dataset.fs22Orig||el.textContent.trim();if(!el.dataset.fs22Orig)el.dataset.fs22Orig=raw;if(state.lang==='en'&&staticMap[raw])el.textContent=staticMap[raw];else if(state.lang==='ne')el.textContent=raw});document.querySelectorAll('.fs22Lang').forEach(b=>b.classList.toggle('on',b.dataset.lang===state.lang));renderStations();renderMountains();renderImpactCard();}
function css(){const s=document.createElement('style');s.textContent=`
.fs22bar{display:flex;gap:6px;align-items:center;margin:10px 0 0}.fs22Lang{border:1px solid #4c718e;background:#071b30;color:#fff;border-radius:9px;padding:7px 10px;font-weight:900;cursor:pointer}.fs22Lang.on{background:#dc143c;border-color:#ff6b83}.fs22panel{margin-top:9px;padding:11px;background:#0a2139;border:1px solid #315777;border-radius:14px}.fs22head{display:flex;justify-content:space-between;align-items:center;gap:8px}.fs22head h3{margin:0;font-size:14px}.fs22badge{font-size:9px;padding:4px 7px;border-radius:99px;background:#17415e;color:#d9effd;font-weight:850}.fs22badge.live{background:#15543e;color:#b8f5dc}.fs22badge.red{background:#7b2033;color:#ffd5dd}.fs22grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.fs22cell{background:#071b30;border:1px solid #294b68;border-radius:10px;padding:8px}.fs22cell small{font-size:9px;color:#9fb2c3}.fs22cell b{display:block;font-size:13px;margin-top:3px}.fs22station{background:#071b30;border:1px solid #294b68;border-radius:10px;padding:8px;margin-top:6px}.fs22stationTop{display:flex;justify-content:space-between;gap:8px}.fs22stage{font-size:8px;border-radius:99px;padding:4px 6px;font-weight:900;white-space:nowrap}.fs22stage.normal{background:#15543e;color:#b8f5dc}.fs22stage.rising{background:#655119;color:#ffe7a0}.fs22stage.warning{background:#76461b;color:#ffe1b6}.fs22stage.danger{background:#7b2033;color:#ffd5dd}.fs22meter{height:6px;margin-top:6px;border-radius:99px;background:#102e49;overflow:hidden}.fs22meter span{display:block;height:100%;background:linear-gradient(90deg,#2dd58b,#f7c64b,#ff9f43,#ff3f5d)}.fs22note{font-size:9.5px;line-height:1.45;color:#aebfcd;margin-top:7px}.fs22mount{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin-top:8px}.fs22impact{border-left:4px solid #dc143c}.fs22tap{position:absolute;z-index:1001;left:50%;top:72px;transform:translateX(-50%);background:#071b30e8;border:1px solid #f7c64b;color:#fff;border-radius:10px;padding:7px 10px;font-size:10px;font-weight:850;pointer-events:none}.fs22pulse{animation:fs22pulse 1.6s infinite}@keyframes fs22pulse{50%{stroke-width:5;fill-opacity:.28}}@media(max-width:900px){.fs22grid{grid-template-columns:repeat(2,1fr)}.fs22mount{grid-template-columns:1fr}.fs22tap{top:64px;max-width:70%;text-align:center}}
`;document.head.appendChild(s)}
function inject(){const brand=document.querySelector('.brand');if(brand&&!$('fs22bar')){const d=document.createElement('div');d.id='fs22bar';d.className='fs22bar';d.innerHTML='<button class="fs22Lang" data-lang="ne">नेपाली</button><button class="fs22Lang" data-lang="en">English</button><span class="fs22badge live">V22 LIVE</span>';brand.insertAdjacentElement('afterend',d);d.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;localStorage.setItem('fs22-lang',state.lang);translateStatic();refreshWeather();});}
const weather=document.querySelector('.weather');if(weather&&!$('fs22weather')){const p=document.createElement('section');p.id='fs22weather';p.className='fs22panel';p.innerHTML='<div class="fs22head"><h3 data-fs22-ne="आजको विस्तृत मौसम" data-fs22-en="Detailed weather today">आजको विस्तृत मौसम</h3><span class="fs22badge" id="fs22wxage">—</span></div><div class="fs22grid"><div class="fs22cell"><small data-fs22-ne="अधिकतम" data-fs22-en="High">अधिकतम</small><b id="fs22max">—</b></div><div class="fs22cell"><small data-fs22-ne="न्यूनतम" data-fs22-en="Low">न्यूनतम</small><b id="fs22min">—</b></div><div class="fs22cell"><small data-fs22-ne="वर्षा सम्भावना" data-fs22-en="Rain chance">वर्षा सम्भावना</small><b id="fs22prob">—</b></div><div class="fs22cell"><small data-fs22-ne="आर्द्रता" data-fs22-en="Humidity">आर्द्रता</small><b id="fs22hum">—</b></div><div class="fs22cell"><small data-fs22-ne="बादल" data-fs22-en="Cloud">बादल</small><b id="fs22cloud">—</b></div><div class="fs22cell"><small data-fs22-ne="महसुस तापक्रम" data-fs22-en="Feels like">महसुस तापक्रम</small><b id="fs22feel">—</b></div></div><div class="fs22note" id="fs22wxnote">GPS वा नक्सामा क्लिक गरेर स्थान छान्नुहोस्।</div>';weather.insertAdjacentElement('afterend',p)}
const stats=document.querySelector('.stats');if(stats&&!$('fs22stations')){const p=document.createElement('section');p.id='fs22stations';p.className='fs22panel';p.innerHTML='<div class="fs22head"><h3 data-fs22-ne="⚡ नदी स्टेशन लाइभ" data-fs22-en="⚡ Live river stations">⚡ नदी स्टेशन लाइभ</h3><span class="fs22badge live" id="fs22stationAge">—</span></div><div class="fs22grid"><div class="fs22cell"><small data-fs22-ne="स्टेशन" data-fs22-en="Stations">स्टेशन</small><b id="fs22stationCount">—</b></div><div class="fs22cell"><small data-fs22-ne="चेतावनी/खतरा" data-fs22-en="Warning/danger">चेतावनी/खतरा</small><b id="fs22warnCount">—</b></div><div class="fs22cell"><small data-fs22-ne="बढ्दो" data-fs22-en="Rising">बढ्दो</small><b id="fs22riseCount">—</b></div></div><div id="fs22stationList"></div><div class="fs22note" data-fs22-ne="आधिकारिक warning/danger सीमा DHM/BIPAD बाट। Rising/early-watch app ले पछिल्लो reading तुलना गरेर देखाउँछ; official warning होइन।" data-fs22-en="Official warning/danger thresholds come from DHM/BIPAD. Rising/early-watch is an app trend from recent readings, not an official warning.">आधिकारिक warning/danger सीमा DHM/BIPAD बाट। Rising/early-watch app ले पछिल्लो reading तुलना गरेर देखाउँछ; official warning होइन।</div>';stats.insertAdjacentElement('afterend',p)}
const impactPanel=[...document.querySelectorAll('.panel')].find(x=>/आजको बाढी प्रभाव|Today/.test(x.querySelector('h3')?.textContent||''));if(impactPanel&&!$('fs22impact')){const p=document.createElement('section');p.id='fs22impact';p.className='fs22panel fs22impact';impactPanel.insertAdjacentElement('afterend',p)}
const districtPanel=[...document.querySelectorAll('.panel')].find(x=>/७७ जिल्ला|77 district/.test(x.querySelector('h3')?.textContent||''));if(districtPanel&&!$('fs22mountain')){const p=document.createElement('section');p.id='fs22mountain';p.className='fs22panel';p.innerHTML='<div class="fs22head"><h3 data-fs22-ne="🏔 हिमाल • हिमनदी • उच्च उचाइ" data-fs22-en="🏔 Mountains • glaciers • high altitude">🏔 हिमाल • हिमनदी • उच्च उचाइ</h3><span class="fs22badge">DHM</span></div><div class="fs22note" data-fs22-ne="DHM को Snow, Glacier & Glacial Lake Monitoring Network का स्टेशन। Sensor update स्रोतको cadence अनुसार आउँछ; screen मा check age हरेक सेकेन्ड बदलिन्छ।" data-fs22-en="Stations from DHM Snow, Glacier & Glacial Lake Monitoring Network. Sensor values update at the source cadence; the on-screen check age updates every second.">DHM को Snow, Glacier & Glacial Lake Monitoring Network का स्टेशन। Sensor update स्रोतको cadence अनुसार आउँछ; screen मा check age हरेक सेकेन्ड बदलिन्छ।</div><div class="fs22mount" id="fs22mountList"></div>';districtPanel.insertAdjacentElement('afterend',p)}
const alertPanel=[...document.querySelectorAll('.panel')].find(x=>/बाढी चेतावनी ध्वनि|Flood alert/.test(x.querySelector('h3')?.textContent||''));if(alertPanel){const p=alertPanel.querySelector('p');if(p)p.textContent='नजिकको आधिकारिक चेतावनी वा बढ्दो नदी जोखिम भेटिँदा सूचना र चिनिने नरम ध्वनि आउँछ।';}
const mapWrap=document.querySelector('.mapWrap');if(mapWrap&&!$('fs22tap')){const d=document.createElement('div');d.id='fs22tap';d.className='fs22tap';d.textContent='📍 नक्सामा क्लिक गरेर आफ्नो स्थान छान्नुहोस्';mapWrap.appendChild(d)}
}
function currentFocus(){try{return window.__fs&&window.__fs.getFocus?window.__fs.getFocus():state.focus}catch{return state.focus}}
async function jget(url,ms=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,headers:{accept:'application/json'}});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
function rows(j){return Array.isArray(j)?j:(j&&j.results)||[]}
function stationPoint(o){const p=o.point||o.provided_point||o.corrected_point;if(p&&Array.isArray(p.coordinates))return[+p.coordinates[1],+p.coordinates[0]];return null}
function stage(o){const wl=num(o.waterLevel),warn=num(o.warningLevel),danger=num(o.dangerLevel),steady=String(o.steady||'').toUpperCase(),id=String(o.id||o.stationSeriesId||o.title),prev=state.prev.get(id),delta=wl!==null&&prev!==undefined?wl-prev:0;if(wl!==null)state.prev.set(id,wl);if(danger!==null&&wl!==null&&wl>=danger)return{key:'danger',label:txt('खतरा','Danger'),delta};if(warn!==null&&wl!==null&&wl>=warn)return{key:'warning',label:txt('चेतावनी','Warning'),delta};if(steady.includes('RISING')||delta>=0.03||(warn!==null&&wl!==null&&wl>=warn*.8))return{key:'rising',label:txt('प्रारम्भिक सतर्कता','Early watch'),delta};return{key:'normal',label:txt('सामान्य','Normal'),delta}}
function age(d){if(!d)return'—';const x=new Date(d);if(Number.isNaN(x.getTime()))return String(d);const s=Math.max(0,Math.round((Date.now()-x.getTime())/1000));if(s<60)return s+'s';if(s<3600)return Math.round(s/60)+'m';return Math.round(s/3600)+'h'}
function renderStations(){const f=currentFocus();state.focus=f;let arr=state.stations.map(o=>{const p=stationPoint(o),st=stage(o);return{o,p,st,d:f&&p?km(f,p):99999}}).filter(x=>x.p);if(f)arr.sort((a,b)=>a.d-b.d);else arr.sort((a,b)=>({danger:0,warning:1,rising:2,normal:3}[a.st.key]-({danger:0,warning:1,rising:2,normal:3}[b.st.key])));const visible=f?arr.filter(x=>x.d<=100).slice(0,10):arr.filter(x=>x.st.key!=='normal').slice(0,10);$('fs22stationCount')&&($('fs22stationCount').textContent=state.stations.length);$('fs22warnCount')&&($('fs22warnCount').textContent=arr.filter(x=>x.st.key==='danger'||x.st.key==='warning').length);$('fs22riseCount')&&($('fs22riseCount').textContent=arr.filter(x=>x.st.key==='rising').length);if($('fs22stationAge'))$('fs22stationAge').textContent=state.lastStations?age(state.lastStations):'—';if($('fs22stationList'))$('fs22stationList').innerHTML=visible.length?visible.map(x=>{const o=x.o,wl=num(o.waterLevel),w=num(o.warningLevel),dg=num(o.dangerLevel),pct=w&&wl!==null?Math.min(100,Math.max(4,wl/(dg||w*1.2)*100)):15;return '<div class="fs22station"><div class="fs22stationTop"><b>'+esc(o.title||o.station_name||'River station')+'</b><span class="fs22stage '+x.st.key+'">'+esc(x.st.label)+'</span></div><small>'+esc(o.basin||'')+(f?' • '+x.d.toFixed(1)+' km':'')+'</small><div class="fs22meter"><span style="width:'+pct+'%"></span></div><small>'+txt('पानी','Water')+': '+(wl??'—')+' m • '+txt('चेतावनी','Warning')+': '+(w??'—')+' • '+txt('खतरा','Danger')+': '+(dg??'—')+'</small><small>'+txt('मापन','Measured')+': '+esc(o.waterLevelOn||'—')+' • '+esc(o.steady||'—')+'</small></div>'}).join(''):'<div class="fs22note">'+txt('स्थान वरिपरि देखाउन नक्सामा क्लिक गर्नुहोस्।','Click the map to see nearby stations.')+'</div>';checkEarlyAlert(arr,f)}
function checkEarlyAlert(arr,f){if(!f)return;const radius=25;const risky=arr.filter(x=>x.d<=radius&&['danger','warning','rising'].includes(x.st.key));const key=risky.map(x=>(x.o.id||x.o.title)+'|'+x.st.key).sort().join(',');const old=sessionStorage.getItem('fs22-risk-key')||'';sessionStorage.setItem('fs22-risk-key',key);if(key&&old&&key!==old){const btn=$('alertsBtn');if(btn&&btn.classList.contains('on')){$('soundBtn')?.click();try{if(Notification.permission==='granted')new Notification(txt('बाढी सुरक्षा चेतावनी','Flood safety alert'),{body:txt('तपाईं नजिकको नदी स्टेशनमा पानी बढ्दो/चेतावनी अवस्था भेटियो।','A nearby river station is rising or at warning level.'),icon:'./icon.svg'})}catch{}}}}
async function refreshStations(){try{const j=await jget(API+'river-stations/?limit=650',12000);state.stations=rows(j);state.lastStations=new Date();renderStations()}catch(e){console.warn('station refresh',e)}}
async function refreshWeather(){const f=currentFocus();state.focus=f;if(!f){if($('fs22wxnote'))$('fs22wxnote').textContent=txt('GPS वा नक्सामा क्लिक गरेर स्थान छान्नुहोस्।','Use GPS or click the map to select a location.');return}try{const u='https://api.open-meteo.com/v1/forecast?latitude='+f[0]+'&longitude='+f[1]+'&current=temperature_2m,apparent_temperature,relative_humidity_2m,cloud_cover,precipitation&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FKathmandu&forecast_days=1';const j=await jget(u,9000),c=j.current||{},d=j.daily||{};$('fs22max').textContent=(d.temperature_2m_max?.[0]??'—')+'°';$('fs22min').textContent=(d.temperature_2m_min?.[0]??'—')+'°';$('fs22prob').textContent=(d.precipitation_probability_max?.[0]??'—')+'%';$('fs22hum').textContent=(c.relative_humidity_2m??'—')+'%';$('fs22cloud').textContent=(c.cloud_cover??'—')+'%';$('fs22feel').textContent=(c.apparent_temperature??'—')+'°';state.lastWeather=new Date();$('fs22wxage').textContent=txt('अहिले','now');$('fs22wxnote').textContent=txt('स्थानअनुसार मौसम मोडेल; नदी चेतावनीको स्रोत DHM/BIPAD नै हो।','Location weather model; river warnings still come from DHM/BIPAD.')}catch{$('fs22wxnote').textContent=txt('मौसम डेटा अहिले उपलब्ध छैन।','Weather data is temporarily unavailable.')}}
function renderImpactCard(){if(!$('fs22impact'))return;const rows=impact.districts.map(d=>'<div class="fs22station"><div class="fs22stationTop"><b>'+esc(d[0])+'</b><span class="fs22stage danger">'+d[1]+' '+txt('मृत्यु','deaths')+'</span></div></div>').join('');$('fs22impact').innerHTML='<div class="fs22head"><h3>'+txt('🚨 रसुवा बाढी — आधिकारिक प्रभाव','🚨 Rasuwa flood — official impact')+'</h3><span class="fs22badge red">Nepal Police</span></div><div class="fs22grid"><div class="fs22cell"><small>'+txt('पुष्टि मृत्यु','Confirmed deaths')+'</small><b>95</b></div><div class="fs22cell"><small>'+txt('प्रभावित जिल्ला','Affected districts')+'</small><b>7</b></div><div class="fs22cell"><small>'+txt('अपडेट','Updated')+'</small><b>19:14</b></div></div><div class="fs22note">'+txt('नेपाल प्रहरीको २०८३-०५-१०, १९:१४ सम्मको आधिकारिक प्रेस अपडेट। BIPAD incident feed ढिलो भए पनि यो छुट्टै स्रोत भनेर देखाइएको छ।','Official Nepal Police press update as of 19:14 on 2083-05-10. This is shown separately when the BIPAD incident feed is delayed.')+'</div>'+rows;drawImpact()}
function drawImpact(){const m=window.__fs&&window.__fs.map;if(!m||!window.L)return;if(state.impactLayer){m.removeLayer(state.impactLayer);state.impactLayer=null}state.impactLayer=L.layerGroup();impact.districts.forEach(d=>L.circleMarker([d[2],d[3]],{radius:9+d[1]/6,color:'#fff',weight:1.5,fillColor:'#dc143c',fillOpacity:.65,className:'fs22pulse'}).bindPopup('<b>'+esc(d[0])+'</b><br>'+d[1]+' '+txt('पुष्टि मृत्यु','confirmed deaths')+'<br>Nepal Police • 19:14').addTo(state.impactLayer));state.impactLayer.addTo(m)}
function renderMountains(){if(!$('fs22mountList'))return;$('fs22mountList').innerHTML=snowStations.map(s=>'<div class="fs22station"><div class="fs22stationTop"><b>'+esc(s.n)+'</b><span class="fs22stage normal">DHM</span></div><small>'+txt('स्टेशन','Station')+' '+esc(s.id)+(s.e?' • '+s.e+' m':'')+'</small><small>'+txt('Snow/Glacier monitoring network','Snow/Glacier monitoring network')+'</small></div>').join('')}
function mapHook(){const tryHook=()=>{const fs=window.__fs;if(!fs||!fs.map||!fs.setFocus)return false;fs.map.off('click.fs22');fs.map.on('click',e=>{state.focus=[e.latlng.lat,e.latlng.lng];fs.setFocus(state.focus,'map');$('fs22tap')&&($('fs22tap').style.display='none');setTimeout(()=>{refreshWeather();renderStations();drawImpact()},80)});drawImpact();return true};let n=0,t=setInterval(()=>{if(tryHook()||++n>40)clearInterval(t)},250)}
function timers(){setInterval(()=>{if(state.lastStations&&$('fs22stationAge'))$('fs22stationAge').textContent=age(state.lastStations);if(state.lastWeather&&$('fs22wxage'))$('fs22wxage').textContent=age(state.lastWeather)},1000);state.stationTimer=setInterval(refreshStations,STATION_POLL);state.weatherTimer=setInterval(refreshWeather,WEATHER_POLL)}
function boot(){css();inject();translateStatic();mapHook();refreshStations();renderMountains();renderImpactCard();timers();setTimeout(()=>{const f=currentFocus();if(f){state.focus=f;refreshWeather()}},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();
